{
 "title": "【Advanced】rocketmq5 instance monitoring",
 "tags": [
  "scene:middleware",
  "addon:name:cloud-rocketmq5",
  "env:Cloud",
  "dashboard:name:rocketmq-instance",
  "env:type:Cloud",
  "rocketmq 5.0",
  "prometheus",
  "addon:version:0.0.5"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "InstanceID",
    "label": "InstanceID",
    "query": "label_values(rocketmq_messages_in_total,instance_id)"
   },
   {
    "name": "Topic",
    "label": "Topic",
    "query": "label_values(rocketmq_messages_in_total{instance_id=\"$InstanceID\"}, topic)"
   },
   {
    "name": "ConsumerGroup",
    "query": {
     "query": "label_values(rocketmq_messages_out_total{instance_id=\"$InstanceID\", topic=~\"$Topic\"},consumer_group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topic Related Indicators (Topic : $Topic)",
   "type": "table",
   "description": "The data version requirements of the Send Success Rate and Send RT indicators are:rocketmq-client v5.0.0 and above.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rocketmq_messages_in_total{instance_id=\"$InstanceID\",topic=~\"$Topic\",aggregation=\"delta\"}) by (topic)",
     "legendFormat": "Amount of messages produced"
    },
    {
     "expr": "sum(rocketmq_message_size_sum{aggregation=\"delta\",instance_id=\"$InstanceID\",topic=~\"$Topic\"}) by (topic)/sum(rocketmq_message_size_count{aggregation=\"delta\",instance_id=\"$InstanceID\",topic=~\"$Topic\"}) by (topic)",
     "legendFormat": "Message size"
    },
    {
     "expr": "sum(rate(rocketmq_send_cost_time_count{invocation_status=\"success\", instance_id=\"$InstanceID\",topic=~\"$Topic\"}[2m])) by (topic)/sum(rate(rocketmq_send_cost_time_count{invocation_status=~\"success|failure\", instance_id=\"$InstanceID\",topic=~\"$Topic\"}[2m])) by (topic)",
     "legendFormat": "Send success rate"
    },
    {
     "expr": "sum(irate(rocketmq_send_cost_time_sum{instance_id=\"$InstanceID\",topic=~\"$Topic\",invocation_status=\"success\"}[2m])) by (topic)/sum(irate(rocketmq_send_cost_time_count{instance_id=\"$InstanceID\",topic=~\"$Topic\",invocation_status=\"success\"}[2m])) by (topic)",
     "legendFormat": "Send RT"
    }
   ]
  },
  {
   "title": "Consumption Scenario Indicators (Topic : $Topic)",
   "type": "table",
   "description": "The data version requirements of the Message Processing Time and Message Processing Success Rate indicators are:rocketmq-client v5.0.0 and above.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rocketmq_messages_out_total{instance_id=\"$InstanceID\",aggregation=\"delta\",topic=~\"$Topic\"}) by(consumer_group) ",
     "legendFormat": "Amount of messages consumed"
    },
    {
     "expr": "sum({__name__=~\"rocketmq_consumer_ready_messages|rocketmq_consumer_inflight_messages\",instance_id=\"$InstanceID\",topic=~\"$Topic\"}) by (consumer_group)",
     "legendFormat": "Accumulation"
    },
    {
     "expr": "max(rocketmq_consumer_lag_latency{instance_id=\"$InstanceID\",topic=~\"$Topic\"}) by (consumer_group)"
    },
    {
     "expr": "sum(rate(rocketmq_process_time_sum{instance_id=\"$InstanceID\",topic=~\"$Topic\"}[2m])) by(consumer_group) / sum(rate(rocketmq_process_time_count{instance_id=\"$InstanceID\",topic=~\"$Topic\"}[2m])) by(consumer_group)"
    },
    {
     "expr": "sum(rate(rocketmq_process_time_count{invocation_status=\"success\",instance_id=\"$InstanceID\",topic=~\"$Topic\"}[2m])) by(consumer_group) / sum(rate(rocketmq_process_time_count{invocation_status=~\"success|failure\",instance_id=\"$InstanceID\",topic=~\"$Topic\"}[2m])) by(consumer_group)",
     "legendFormat": "Message processing success rate"
    }
   ]
  },
  {
   "title": "Message Rate Sent by Producers to Servers (messages/minute)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocketmq_messages_in_total{instance_id=\"$InstanceID\",aggregation=\"delta\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message Rate Sent by Servers to Consumers (messages/minute)",
   "type": "timeseries",
   "description": "Including messages being processed by consumers, successfully processed, and failed to be processed",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocketmq_messages_out_total{instance_id=\"$InstanceID\",aggregation=\"delta\"}) by(consumer_group) ",
     "legendFormat": "{{consumer_group}}"
    }
   ]
  },
  {
   "title": "Message Accumulation Volume (messages)",
   "type": "timeseries",
   "description": "The accumulation volume indicates the amount of all messages that have not been successfully consumed, including messages being processed and ready messages.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"rocketmq_consumer_ready_messages|rocketmq_consumer_inflight_messages\",instance_id=\"$InstanceID\"}) by (consumer_group)",
     "legendFormat": "{{consumer_group}}"
    }
   ]
  },
  {
   "title": "Message Processing Time",
   "type": "timeseries",
   "description": "The average message processing time distribution of PushConsumer within two minutes, including successful and failed processing.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(rocketmq_process_time_sum{instance_id=\"$InstanceID\"}[2m])) by(consumer_group) / sum(rate(rocketmq_process_time_count{instance_id=\"$InstanceID\"}[2m])) by(consumer_group)",
     "legendFormat": "{{consumer_group}}"
    }
   ]
  },
  { "title": "Producer (Topic: $Topic)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Average Message Size (bytes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(rocketmq_message_size_sum{aggregation=\"delta\",instance_id=\"$InstanceID\",topic=~\"$Topic\"}[$__range]))/sum(sum_over_time(rocketmq_message_size_count{aggregation=\"delta\",instance_id=\"$InstanceID\",topic=~\"$Topic\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Messages Produced Per Minute (messages/minute)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocketmq_messages_in_total{aggregation=\"delta\",instance_id=\"$InstanceID\",topic=~\"$Topic\"})",
     "legendFormat": "Amount of messages produced (messages/minute)"
    }
   ]
  },
  {
   "title": "Message Type Proportion ($Topic)",
   "type": "piechart",
   "description": "normal: normal message\nfifo: sequential message\ntransaction: transaction message\ndelay: delayed/scheduled message",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(rocketmq_messages_in_total{aggregation=\"delta\",instance_id=\"$InstanceID\",topic=~\"$Topic\"}[$__range])) by (message_type)",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Production Call Success Rate ($Topic)",
   "type": "timeseries",
   "description": "Current indicator version requirements: rocketmq-client v5.0 and above",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(rocketmq_send_cost_time_count{instance_id=\"$InstanceID\",topic=~\"$Topic\",invocation_status=\"success\"}[2m]))/\nsum(irate(rocketmq_send_cost_time_count{instance_id=\"$InstanceID\",topic=~\"$Topic\",invocation_status=~\"success|failure\"}[2m])) ",
     "legendFormat": "Success rate"
    }
   ]
  },
  {
   "title": "Message Production Call Success Time (Topic: $Topic)",
   "type": "timeseries",
   "description": "Current indicator version requirements: rocketmq-client v5.0 and above",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(irate(rocketmq_send_cost_time_sum{invocation_status=\"success\",instance_id=\"$InstanceID\",topic=~\"$Topic\"}[2m]))/sum(irate(rocketmq_send_cost_time_count{invocation_status=\"success\",instance_id=\"$InstanceID\",topic=~\"$Topic\"}[2m]))",
     "legendFormat": "Average value"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(irate(rocketmq_send_cost_time_bucket{invocation_status=\"success\",instance_id=\"$InstanceID\",topic=~\"$Topic\"}[2m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(irate(rocketmq_send_cost_time_bucket{invocation_status=\"success\",instance_id=\"$InstanceID\",topic=~\"$Topic\"}[2m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Consumers (Topic: $Topic | ConsumerGroup: $ConsumerGroup)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }
  },
  {
   "title": "Ready message queue time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rocketmq_consumer_queueing_latency{instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"})"
    }
   ]
  },
  {
   "title": "Ready message volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocketmq_consumer_ready_messages{instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"})"
    }
   ]
  },
  {
   "title": "Message processing delay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(rocketmq_consumer_lag_latency{instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"})"
    }
   ]
  },
  {
   "title": "Processing message volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocketmq_consumer_inflight_messages{instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"})"
    }
   ]
  },
  {
   "title": "Consumer message volume per minute (Topic: $Topic | ConsumerGroup: $ConsumerGroup)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocketmq_messages_out_total{aggregation=\"delta\",instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"})",
     "legendFormat": "Amount of messages consumed (messages/minute)"
    }
   ]
  },
  {
   "title": "Consumption delay (Topic: $Topic | ConsumerGroup: $ConsumerGroup)",
   "type": "timeseries",
   "description": "Message accumulation, please first check whether the client's message processing time and processing success rate have changed",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(rocketmq_consumer_queueing_latency{instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"})",
     "legendFormat": "Ready message queue time"
    },
    {
     "expr": "max(rocketmq_consumer_lag_latency{instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"})",
     "legendFormat": "Message processing lag time"
    }
   ]
  },
  {
   "title": "Consumption accumulation (Topic: $Topic | ConsumerGroup: $ConsumerGroup)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"rocketmq_consumer_ready_messages|rocketmq_consumer_inflight_messages\",instance_id=\"$InstanceID\",consumer_group=~\"$ConsumerGroup\",topic=~\"$Topic\"})",
     "legendFormat": "Accumulation (ready + processing)"
    },
    {
     "expr": "sum(rocketmq_consumer_ready_messages{instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(rocketmq_consumer_inflight_messages{instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"})",
     "legendFormat": "Processing"
    }
   ]
  },
  {
   "title": "PushConsumer message processing time (Topic: $Topic | ConsumerGroup: $ConsumerGroup)",
   "type": "timeseries",
   "description": "Current indicator version requirements: rocketmq-client v5.0 and above",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(irate(rocketmq_process_time_sum{instance_id=\"$InstanceID\",topic=~\"$Topic\", consumer_group=~\"$ConsumerGroup\"}[2m]))/sum(irate(rocketmq_process_time_count{instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"}[2m]))",
     "legendFormat": "Average value"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(irate(rocketmq_process_time_bucket{instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"}[2m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(irate(rocketmq_process_time_bucket{instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"}[2m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "PushConsumer message processing success rate (Topic: $Topic | ConsumerGroup: $ConsumerGroup)",
   "type": "timeseries",
   "description": "Current indicator version requirements: rocketmq-client v5.0 and above",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(rocketmq_process_time_count{invocation_status=\"success\",instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"}[2m])) /sum(irate(rocketmq_process_time_count{invocation_status=~\"success|failure\",instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"}[2m])) ",
     "legendFormat": "Success rate"
    }
   ]
  },
  {
   "title": "The number of messages in the PushConsumer local buffer queue (Topic: $Topic | ConsumerGroup: $ConsumerGroup)",
   "type": "timeseries",
   "description": "Current indicator version requirements: rocketmq-client v5.0 and above",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocketmq_consumer_cached_messages{instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"})",
     "legendFormat": "Amount of messages (messages)"
    }
   ]
  },
  {
   "title": "The number of messages that become dead letters per minute (Topic: $Topic | ConsumerGroup: $ConsumerGroup)",
   "type": "timeseries",
   "description": "Becoming a dead letter means that the maximum number of re-delivery times per minute reaches the number of messages that are no longer delivered. \nMessages that are no longer delivered will be saved to the specified Topic or discarded according to the settings. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocketmq_send_to_dlq_messages_total{aggregation=\"delta\",instance_id=\"$InstanceID\",topic=~\"$Topic\",consumer_group=~\"$ConsumerGroup\"})",
     "legendFormat": "Amount of messages transferred to dead messages (messages/minute)"
    }
   ]
  }
 ]
}