{
 "title": "ACK Cluster Overview Non_Prod",
 "tags": [
  "Kubernetes",
  "Cluster",
  "scene:container",
  "addon:name:cs-default",
  "addon:version:0.0.11",
  "env:CS",
  "env:type:ManagedKubernetes",
  "env:profile:Default",
  "dashboard:name:k8s-overview"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource ", "query": "prometheus" },
   { "name": "clusterUid", "query": "5328-18c04c" },
   {
    "name": "env",
    "label": "Select Env",
    "query": "ALL : nprd , Dev : dev, Uat : uat, Sit : sit"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)-3" }
   ]
  },
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)" }
   ]
  },
  {
   "title": "PVC Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "count(node_volume_capacity_bytes_available_counter )",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Node Request Memory Average Percent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kube_pod_container_resource_requests_memory_bytes)by (node)/sum(kube_node_status_capacity_memory_bytes)by(node))"
    }
   ]
  },
  {
   "title": "Node Request CPU Average Percent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kube_pod_container_resource_requests_cpu_cores)by (node)/sum(kube_node_status_capacity_cpu_cores)by(node))"
    }
   ]
  },
  {
   "title": "API Server Success Request Percent",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb=~\"GET|LIST\"}[5m]))/sum(irate(apiserver_request_total{verb=~\"GET|LIST\"}[5m]))",
     "legendFormat": "APIServer"
    }
   ]
  },
  {
   "title": "Node Memory Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(label_replace(topk(10, 1-(node_memory_MemAvailable_bytes{} / node_memory_MemTotal_bytes{})), \"node_ip\", \"$1\", \"instance\", \"(.*):(.*)\"))by(node_ip)",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node Disk Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(1-node_filesystem_free_bytes{mountpoint=\"/\"}/node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"},\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node Network In (Top 10)",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(max(irate(node_network_receive_bytes_total{}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node Network Out (Top 10)",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(max(irate(node_network_transmit_bytes_total{}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node Sockets Count(Top 10)",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(max(node_sockstat_TCP_alloc) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  { "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Namespace Overview",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count(kube_pod_info{}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{}) by(namespace)"
    },
    {
     "expr": "count(kube_pod_container_info{}) by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info{}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{}) by(namespace)",
     "legendFormat": "secret"
    },
    {
     "expr": "count(kube_deployment_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_job_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_cronjob_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_pod_status_ready{condition=\"false\"}==1) by(namespace) - (count(kube_pod_status_phase{phase=\"Succeeded\"}==1) by(namespace) or vector(0)) or count(kube_pod_status_ready{condition=\"false\"}==1) by(namespace)"
    },
    {
     "expr": "count(kube_deployment_status_replicas_ready{}<kube_deployment_spec_replicas{}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_status_replicas_ready{}<kube_statefulset_replicas{}) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_status_number_unavailable{}>0)by(namespace)"
    },
    {
     "expr": "count(kube_job_status_failed{} == 1) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_persistentvolumeclaim_info{}) by (namespace)"
    }
   ]
  },
  {
   "title": "PVC Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "label_replace(node_volume_capacity_bytes_total_counter{node!=\"\"}, \"Source\", \"$1\", \"server\", \"(.*)\")\n* on(namespace, pvc) group_left(pv)\ngroup by (namespace, pv, pvc) (\n label_replace (\n kube_persistentvolumeclaim_status_phase > 0,\n \"pvc\", \"$1\", \"persistentvolumeclaim\", \"(.*)\"\n )\n * on(namespace, persistentvolumeclaim) group_left(pv)\n label_replace(\n label_replace(\n group(kube_resource_relationship{target_kind=\"PersistentVolume\"} > 0) by (namespace, target_name, name),\n \"pv\", \"$1\", \"target_name\", \"(.*)\"\n ),\n \"persistentvolumeclaim\", \"$1\", \"name\", \"(.*)\"\n )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_volume_capacity_bytes_used{node!=\"\"}"
    },
    {
     "expr": "group by (pv, pvc, namespace) (\n label_replace (\n kube_persistentvolumeclaim_status_phase > 0,\n \"pvc\", \"$1\", \"persistentvolumeclaim\", \"(.*)\"\n )\n * on(namespace, persistentvolumeclaim) group_left(pv)\n label_replace(\n label_replace(\n group(kube_resource_relationship{target_kind=\"PersistentVolume\"} > 0) by (namespace, target_name, name),\n \"pv\", \"$1\", \"target_name\", \"(.*)\"\n ),\n \"persistentvolumeclaim\", \"$1\", \"name\", \"(.*)\"\n )\n)\n* on(pv) group_left(type, Source)\nlabel_replace(\n label_replace(\n group by (pv, bucket_name, backend_storage) (node_volume_posix_read_total_counter),\n \"Source\", \"$1\", \"bucket_name\", \"(.*)\"\n ),\n \"type\", \"$1\", \"backend_storage\", \"(.*)\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (namespace, pvc) (node_volume_capacity_bytes_available{node!=\"\"})\n or\ncount by (namespace, pvc) (\n node_volume_capacity_bytes_available_counter * on(pv) group_left(namespace, pvc)\n group by (namespace, pv, pvc) (\n label_replace (\n kube_persistentvolumeclaim_status_phase > 0,\n \"pvc\", \"$1\", \"persistentvolumeclaim\", \"(.*)\"\n )\n * on(namespace, persistentvolumeclaim) group_left(pv)\n label_replace(\n label_replace(\n group(kube_resource_relationship{target_kind=\"PersistentVolume\"} > 0) by (namespace, target_name, name),\n \"pv\", \"$1\", \"target_name\", \"(.*)\"\n ),\n \"persistentvolumeclaim\", \"$1\", \"name\", \"(.*)\"\n )\n )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Usage(Top10)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum (container_memory_working_set_bytes{container !=\"\",container!=\"POD\"}) by (container))",
     "legendFormat": "WorkingSet：[Container]:{{ container }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage/Limit(Top10)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10,((max(container_memory_working_set_bytes{container!=\"\",container!=\"POD\"}) by(pod,container,namespace) / max(kube_pod_container_resource_limits_memory_bytes{container!=\"\"}) by(pod,container,namespace))) <= 100 or on() vector(0))",
     "legendFormat": "WorkingSet：[Container]:{{ container }}"
    }
   ]
  },
  {
   "title": "Container CPU Usage(Top10)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\"}[2m])) by (container))",
     "legendFormat": "Usage [Container]:{{ container}}"
    }
   ]
  },
  {
   "title": "Container Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_network_receive_bytes_total{image!=\"\",name=~\"^K8S_.*\"}[2m])) by (pod))",
     "legendFormat": "Receive: [Pod]:{{pod}}"
    },
    {
     "expr": "-topk(10, sum(irate(container_network_transmit_bytes_total{image!=\"\",name=~\"^K8S_.*\"}[2m])) by (pod))",
     "legendFormat": "Transmit: [Pod]:{{pod}}"
    }
   ]
  },
  {
   "title": "Container File System Usage(Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "topk(10, sum by (container) (container_fs_usage_bytes{container!=\"\"}))",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{container}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Container File System Inode Usage(Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "topk(10, sum by (container) (container_fs_inodes_used{container!=\"\"}))",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{container}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Container Memory Usage/Limit (Top 10)",
   "type": "table",
   "description": "请确认Pod Yaml中设置了resources.limits",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10,((max(container_memory_working_set_bytes{container!=\"\",container!=\"POD\"}) by(pod,container,namespace) / max(kube_pod_container_resource_limits_memory_bytes{container!=\"\"}) by(pod,container,namespace))) <= 100 or on() vector(0))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[1m])) by (container,pod,namespace)or on() vector(0))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Container Socket Count(Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(container_sockets{container!=\"\"}) by (container,pod,namespace)or on() vector(0))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "count(avg_over_time(kube_pod_info{created_by_kind!~\"<none>|Job\",node!~\"\"}[$__range])) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",node!~\"\"}[$__range]))by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node!~\"\"}[$__range])) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node!~\"\"}[$__range])) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (avg_over_time(container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node!~\"\"}[$__range])) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container!~\"\",node!~\"\"}[$__range]))by (node) / sum(avg_over_time(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node!~\"\"}[$__range]))by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (avg_over_time(container_memory_working_set_bytes{container!~\"\",node!~\"\"}[$__range]))by (node) / sum(avg_over_time(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node!~\"\"}[$__range]))by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (avg_over_time(container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node!~\"\"}[$__range]))by (node) / sum (avg_over_time(container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node!~\"\"}[$__range]))by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node!~\"\"}[$__range]))by (node) / sum(avg_over_time(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node!~\"\"}[$__range]))by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node!~\"\"}[$__range]))by (node) / sum(avg_over_time(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node!~\"\"}[$__range]))by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node!~\"\"}[$__range]))by (node) / sum(avg_over_time(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node!~\"\"}[$__range]))by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node!~\"\"}[$__range]))by (node) / sum(avg_over_time (kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node!~\"\"}[$__range]))by (node)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}