{
 "title": "ALB instance-Dashbord",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_LoadBalancerQPS|AliyunAlb_LoadBalancerHealthyHostCount\"}, regionId)"
    }
   },
   {
    "name": "loadBalancername",
    "label": "loadBalancerName",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_LoadBalancerQPS|AliyunAlb_LoadBalancerHealthyHostCount\", regionId=~\"$regionId\"},loadBalancerName)"
    }
   },
   {
    "name": "listenerProtocol",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_ListenerQPS|AliyunAlb_ListenerHealthyHostCount\",regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"},listenerProtocol)"
    }
   },
   {
    "name": "listenerPort",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_ListenerQPS|AliyunAlb_ListenerHealthyHostCount\",regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\"},listenerPort)"
    }
   },
   {
    "name": "ruleId",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_RuleQPS|AliyunAlb_RuleHealthyHostCount\",regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"},ruleId)"
    }
   },
   {
    "name": "serverGroupId",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_ServerGroupQPS|AliyunAlb_ServerGroupHealthyHostCount\",regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"},serverGroupId)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Over view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total instances ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cloud_monitor_instance_info{product=\"alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance list",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "group (cloud_monitor_instance_info{product=~\"alb\"}) by(id,loadBalancerName,resourceGroupName)",
     "legendFormat": "__auto"
    },
    {
     "expr": "group (cloud_monitor_instance_tag{product=~\"alb\",key=~\"AppCode\"}) by(id,value)",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceil(avg(AliyunAlb_LoadBalancerActiveConnection{}) by(id)) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceil(avg(AliyunAlb_LoadBalancerHTTPCode5XX{}) by(id))",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceil(avg(AliyunAlb_ServerGroupHTTPCodeUpstream5XX{}) by(id)) ",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic (bits/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerOutBits{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Load balancing instance outbound bandwidth"
      },
      {
       "expr": "AliyunAlb_LoadBalancerInBits{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Load balancing instance inbound bandwidth"
      }
     ]
    },
    {
     "title": "Health Check (pcs)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerHealthyHostCount{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of healthy servers in the load balancing instance"
      },
      {
       "expr": "AliyunAlb_ListenerUnHealthyHostCount{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of unhealthy servers in the load balancing instance"
      }
     ]
    },
    {
     "title": "HTTP Status Code (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerHTTPCodeUpstream2XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of 2XX load balancing instances per second"
      },
      {
       "expr": "AliyunAlb_LoadBalancerHTTPCodeUpstream3XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of 3XX load balancing instances per second"
      },
      {
       "expr": "AliyunAlb_LoadBalancerHTTPCodeUpstream4XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of 4XX load balancing instances per second"
      },
      {
       "expr": "AliyunAlb_LoadBalancerHTTPCodeUpstream5XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of 5XX load balancing instances per second"
      }
     ]
    },
    {
     "title": "HTTP5XX Status Code (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerHTTPCode500{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of 500 load balancing instances per second"
      },
      {
       "expr": "AliyunAlb_LoadBalancerHTTPCode502{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of 502 load balancing instances per second"
      },
      {
       "expr": "AliyunAlb_LoadBalancerHTTPCode503{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of 503 load balancing instances per second"
      },
      {
       "expr": "AliyunAlb_LoadBalancerHTTPCode504{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of 504 load balancing instances per second"
      }
     ]
    },
    {
     "title": "Backend HTTP Status Code (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerHTTPCodeUpstream2XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of 2XX load balancing instances per second backend"
      },
      {
       "expr": "AliyunAlb_LoadBalancerHTTPCodeUpstream3XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of 3XX load balancing instances per second backend"
      },
      {
       "expr": "AliyunAlb_LoadBalancerHTTPCodeUpstream4XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of 4XX load balancing instances per second backend"
      },
      {
       "expr": "AliyunAlb_LoadBalancerHTTPCodeUpstream5XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of 5XX load balancing instances per second backend"
      }
     ]
    },
    {
     "title": "Number of Custom Reponses (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerHTTPFixedResponse{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of custom responses per second in the load balancing instance"
      }
     ]
    },
    {
     "title": "Number of Redirects (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerHTTPRedirect{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Load Number of redirects per second for the load balancing instance"
      }
     ]
    },
    {
     "title": "Number of Requests (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 53 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerQPS{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of requests per second for the load balancing instance"
      }
     ]
    },
    {
     "title": "Number of Non-sticky Requests (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 53 },
     "targets": [
      {
       "expr": "AliyunAlb_RuleNonStickyRequest{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of non-sticky requests per second for the load balancing instance"
      }
     ]
    },
    {
     "title": "Backend Response Time (milliseconds)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerUpstreamResponseTime{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Backend response time for the load balancing instance"
      }
     ]
    },
    {
     "title": "Number of Active Connections (pcs)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 62 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerActiveConnection{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of active connections for the load balancing instance"
      }
     ]
    },
    {
     "title": "Number of Dropped Connections (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 62 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerRejectedConnection{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of dropped connections per second for the load balancing instance"
      }
     ]
    },
    {
     "title": " New connections (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerNewConnection{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of new connections per second for the load balancing instance"
      }
     ]
    },
    {
     "title": "TLS handshake failed connections (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 71 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerClientTLSNegotiationError{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of TLS handshake failures per second for the load balancing instance"
      }
     ]
    },
    {
     "title": "Backend connection failures (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 71 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerUpstreamConnectionError{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of failed connections per second for the backend of the load balancing instance"
      }
     ]
    },
    {
     "title": "Backend TLS handshake failures (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "AliyunAlb_LoadBalancerUpstreamTLSNegotiationError{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\"}",
       "legendFormat": "Number of TLS handshake failures per second for the backend of the load balancing instance"
      }
     ]
    }
   ]
  },
  {
   "title": "Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic (bits/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerOutBits{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Monitor outgoing bandwidth"
      },
      {
       "expr": "AliyunAlb_ListenerInBits{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Monitor incoming bandwidth"
      }
     ]
    },
    {
     "title": "Health checks (number)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 90 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerHealthyHostCount{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Number of healthy servers monitored"
      },
      {
       "expr": "AliyunAlb_ListenerUnHealthyHostCount{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Number of unhealthy servers monitored"
      }
     ]
    },
    {
     "title": "HTTP status code (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 90 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerHTTPCode2XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Number of 2XX monitored per second"
      },
      {
       "expr": "AliyunAlb_ListenerHTTPCode3XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Number of 3XX monitored per second"
      },
      {
       "expr": "AliyunAlb_ListenerHTTPCode4XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Number of 4XX monitored per second"
      },
      {
       "expr": "AliyunAlb_ListenerHTTPCode5XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Number of 5XX monitored per second"
      }
     ]
    },
    {
     "title": "HTTP5XX status code (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerHTTPCode500{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Number of 500 monitored per second"
      },
      {
       "expr": "AliyunAlb_ListenerHTTPCode502{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Number of 502 monitored per second"
      },
      {
       "expr": "AliyunAlb_ListenerHTTPCode503{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": " Listening for 503s per second"
      },
      {
       "expr": "AliyunAlb_ListenerHTTPCode504{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for 504s per second"
      }
     ]
    },
    {
     "title": "Backend HTTP status code (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 99 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerHTTPCodeUpstream2XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for 2XXs per second on the backend"
      },
      {
       "expr": "AliyunAlb_ListenerHTTPCodeUpstream3XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for 3XXs per second on the backend"
      },
      {
       "expr": "AliyunAlb_ListenerHTTPCodeUpstream4XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for 4XXs per second on the backend"
      },
      {
       "expr": "AliyunAlb_ListenerHTTPCodeUpstream5XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for 5XXs per second on the backend"
      }
     ]
    },
    {
     "title": "Custom reponses (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 99 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerHTTPFixedResponse{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for custom repons per second"
      }
     ]
    },
    {
     "title": "Redirects (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerHTTPFixedRedirect{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for redirects per second"
      }
     ]
    },
    {
     "title": "Requests (Count/s) ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 108 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerQPS{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for requests per second"
      }
     ]
    },
    {
     "title": "Number of non-sticky requests (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 108 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerNonStickyRequest{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for non-sticky requests per second"
      }
     ]
    },
    {
     "title": "Backend response time (milliseconds)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 117 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerUpstreamResponseTime{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for backend response time"
      }
     ]
    },
    {
     "title": "Number of active connections (counts)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 117 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerActiveConnection{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for active connections"
      }
     ]
    },
    {
     "title": "Number of dropped connections (count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 117 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerRejectedConnection{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for dropped connections per second"
      }
     ]
    },
    {
     "title": "Number of new connections (count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 126 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerNewConnection{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for new connections per second"
      }
     ]
    },
    {
     "title": "Number of TLS handshake failures (count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 126 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerClientTLSNegotiationError{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for TLS handshake failed connections per second"
      }
     ]
    },
    {
     "title": "Number of backend connection failures (count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 126 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerUpstreamConnectionError{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for backend connection failures per second"
      }
     ]
    },
    {
     "title": "Number of backend TLS handshake failures (count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "AliyunAlb_ListenerUpstreamTLSNegotiationError{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "legendFormat": "Listening for TLS handshake failed connections per second"
      }
     ]
    }
   ]
  },
  {
   "title": "Forwarding rules",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health check (counts)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 253 },
     "targets": [
      {
       "expr": "AliyunAlb_RuleHealthyHostCount{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",ruleId=~\"$ruleId\"}",
       "legendFormat": "Number of servers with healthy forwarding rules"
      },
      {
       "expr": "AliyunAlb_RuleUnHealthyHostCount{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",ruleId=~\"$ruleId\"}",
       "legendFormat": "Number of servers with unhealthy forwarding rules"
      }
     ]
    },
    {
     "title": "Backend HTTP status code (count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 253 },
     "targets": [
      {
       "expr": "AliyunAlb_RuleHTTPCodeUpstream2XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",ruleId=~\"$ruleId\"}",
       "legendFormat": "Number of 2XXs per second on the backend for forwarding rules"
      },
      {
       "expr": "AliyunAlb_RuleHTTPCodeUpstream3XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",ruleId=~\"$ruleId\"}",
       "legendFormat": "Number of servers with unhealthy forwarding rules ,3XX"
      },
      {
       "expr": "AliyunAlb_RuleHTTPCodeUpstream4XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",ruleId=~\"$ruleId\"}",
       "legendFormat": "4XX forwarding rule backend per second"
      },
      {
       "expr": "AliyunAlb_RuleHTTPCodeUpstream5XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",ruleId=~\"$ruleId\"}",
       "legendFormat": "5XX forwarding rule backend per second"
      }
     ]
    },
    {
     "title": "Number of requests (count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 253 },
     "targets": [
      {
       "expr": "AliyunAlb_RuleQPS{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",ruleId=~\"$ruleId\"}",
       "legendFormat": "forwarding rule requests per second"
      }
     ]
    },
    {
     "title": "Number of non-sticky requests (count/s) s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 262 },
     "targets": [
      {
       "expr": "AliyunAlb_RuleNonStickyRequest{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",ruleId=~\"$ruleId\"}",
       "legendFormat": "forwarding rule non-sticky requests per second"
      }
     ]
    },
    {
     "title": "Backend response time (milliseconds)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 262 },
     "targets": [
      {
       "expr": "AliyunAlb_RuleUpstreamResponseTime{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",ruleId=~\"$ruleId\"}",
       "legendFormat": "forwarding rule backend response time"
      }
     ]
    },
    {
     "title": "Backend connection failures (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 262 },
     "targets": [
      {
       "expr": "AliyunAlb_RuleUpstreamConnectionError{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",ruleId=~\"$ruleId\"}",
       "legendFormat": "forwarding rule backend connection failures per second"
      }
     ]
    },
    {
     "title": "Backend TLS handshake failures (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 271 },
     "targets": [
      {
       "expr": "AliyunAlb_RuleUpstreamTLSNegotiationError{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",ruleId=~\"$ruleId\"}",
       "legendFormat": "forwarding rule backend TLS handshake failures per second"
      }
     ]
    }
   ]
  },
  {
   "title": "Server groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health checks (pcs)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "AliyunAlb_ServerGroupHealthyHostCount{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",serverGroupId=~\"$serverGroupId\"}",
       "legendFormat": "healthy servers in the server group"
      },
      {
       "expr": "AliyunAlb_ServerGroupUnHealthyHostCount{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",serverGroupId=~\"$serverGroupId\"}",
       "legendFormat": "unhealthy servers in the server group"
      }
     ]
    },
    {
     "title": "Backend HTTP status codes (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "AliyunAlb_ServerGroupHTTPCodeUpstream2XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",serverGroupId=~\"$serverGroupId\"}",
       "legendFormat": "2XX server group backend per second"
      },
      {
       "expr": "AliyunAlb_ServerGroupHTTPCodeUpstream3XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",serverGroupId=~\"$serverGroupId\"}",
       "legendFormat": "3XX server group backend per second"
      },
      {
       "expr": "AliyunAlb_ServerGroupHTTPCodeUpstream4XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",serverGroupId=~\"$serverGroupId\"}",
       "legendFormat": "4XX server group backend per second"
      },
      {
       "expr": "AliyunAlb_ServerGroupHTTPCodeUpstream5XX{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",serverGroupId=~\"$serverGroupId\"}",
       "legendFormat": "5XX server group backend per second"
      }
     ]
    },
    {
     "title": "Number of requests (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "targets": [
      {
       "expr": "AliyunAlb_ServerGroupQPS{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",serverGroupId=~\"$serverGroupId\"}",
       "legendFormat": "server group requests per second"
      }
     ]
    },
    {
     "title": "Number of non-sticky requests (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "AliyunAlb_ServerGroupNonStickyRequest{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",serverGroupId=~\"$serverGroupId\"}",
       "legendFormat": "server group non-sticky requests per second"
      }
     ]
    },
    {
     "title": "Backend response time (milliseconds)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
     "targets": [
      {
       "expr": "AliyunAlb_ServerGroupUpstreamResponseTime{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",serverGroupId=~\"$serverGroupId\"}",
       "legendFormat": "server group backend response time"
      }
     ]
    },
    {
     "title": "Backend connection failures (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
     "targets": [
      {
       "expr": "AliyunAlb_ServerGroupUpstreamConnectionError{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",serverGroupId=~\"$serverGroupId\"}",
       "legendFormat": "server group backend connection failures per second"
      }
     ]
    },
    {
     "title": "Backend TLS handshake failures (Count/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "AliyunAlb_ServerGroupUpstreamTLSNegotiationError{regionId=~\"$regionId\",loadBalancerName=~\"$loadBalancername\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\",serverGroupId=~\"$serverGroupId\"}",
       "legendFormat": "server group backend TLS handshake failures per second"
      }
     ]
    }
   ]
  }
 ]
}