{
 "title": "ALB",
 "tags": [
  "cmee",
  "alb",
  "scene:middleware",
  "addon:name:cloud-alb",
  "addon:version:0.0.3",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:cmee-alb-overview"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "regionId", "query": "cn-hongkong" },
   {
    "name": "NameSpace",
    "label": "ProjectName",
    "query": "Jarvis : ns-hkg-agent-system, ODS : ns-hkg-ods-system,ATAS : ns-gft-atas-system,DCS : ns-hkg-dcs-system,"
   },
   {
    "name": "Service",
    "label": "AppName",
    "query": {
     "query": "label_values(arms_app_requests_count_raw{namespace=\"$NameSpace\"},app)"
    }
   },
   {
    "name": "loadBalancerId",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_LoadBalancerQPS|AliyunAlb_LoadBalancerHealthyHostCount\", regionId=~\"$regionId\"},loadBalancerId)"
    }
   },
   {
    "name": "listenerProtocol",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_ListenerQPS|AliyunAlb_ListenerHealthyHostCount\",regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\"},listenerProtocol)"
    }
   },
   {
    "name": "listenerPort",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_ListenerQPS|AliyunAlb_ListenerHealthyHostCount\",regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\",listenerProtocol=~\"$listenerProtocol\"},listenerPort)"
    }
   },
   {
    "name": "ruleId",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_RuleQPS|AliyunAlb_RuleHealthyHostCount\",regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"},ruleId)"
    }
   },
   {
    "name": "serverGroupId",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_ServerGroupQPS|AliyunAlb_ServerGroupHealthyHostCount\",regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"},serverGroupId)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   { "name": "asm_gateway_name", "label": "asm_gateway_name", "query": "istio-ingressgateway" },
   {
    "name": "Pid",
    "label": "pid",
    "query": {
     "query": "label_values(arms_app_requests_count_ign_destid_endpoint_parent_ppid_prpc{service=\"$Service\"},pid)"
    }
   },
   {
    "name": "ASMSVC",
    "label": "asmavc",
    "query": {
     "query": "label_values(arms_app_requests_count_raw{namespace=\"$NameSpace\", service=\"$Service\"},app)"
    }
   },
   {
    "name": "incallKind",
    "label": "incallKind",
    "query": "http|rpc|consumer|custom_entry|server"
   },
   {
    "name": "outcallKind",
    "label": "outcallKind",
    "query": "rpc_client|http_client|db|sql|nosql|cache|producer|client"
   },
   {
    "name": "fullIncallKinds",
    "label": "fullIncallKinds",
    "query": "http|rpc|consumer|custom_entry|schedule|server"
   },
   {
    "name": "PromInstanceId",
    "label": "promInstanceId",
    "query": {
     "query": "label_values(AliyunAlb_ListenerQPS{loadBalancerId=\"$loadBalancerId\"},promInstanceId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ALB-->APIGW",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round(avg_over_time(AliyunAlb_ListenerQPS{regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\"}[5m]))+1",
     "legendFormat": "alb-QPS"
    },
    {
     "expr": "round(avg_over_time(AliyunAlb_ListenerUpstreamResponseTime{loadBalancerId=~\"$loadBalancerId\"}[5m]))",
     "legendFormat": "Alb-Resp"
    },
    {
     "expr": "round(avg_over_time(AliyunCnapigateway_EnvoyClusterQps{promInstanceId=\"$PromInstanceId\"}[5m]))+1",
     "legendFormat": "apigw-qps"
    },
    {
     "expr": "round(avg_over_time(AliyunCnapigateway_EnvoyDownstreamSuccessRate{promInstanceId=~\"$PromInstanceId\"}[5m]))",
     "legendFormat": "apigwRate"
    },
    {
     "expr": "\r\nsum(AliyunAlb_LoadBalancerHTTPCodeUpstream2XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"})\r\n/\r\nsum(\r\n AliyunAlb_LoadBalancerHTTPCodeUpstream2XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream3XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream4XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream5XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\n)\r\n",
     "legendFormat": "alb-rate"
    },
    {
     "expr": "round(avg_over_time(AliyunCnapigateway_EnvoyApiRtAvg{promInstanceId=~\"$PromInstanceId\"}[5m]))",
     "legendFormat": "gw-resp"
    }
   ]
  },
  {
   "title": "ALB QPS (Count/s)",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "AliyunAlb_LoadBalancerQPS{regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "ALB-HTTP 4xx & 5xx Status Code (Count/s)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "AliyunAlb_LoadBalancerHTTPCodeUpstream4XX{regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\"}",
     "legendFormat": "Http-4XX"
    },
    {
     "expr": "AliyunAlb_LoadBalancerHTTPCodeUpstream5XX{regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\"}",
     "legendFormat": "Http-5XX"
    }
   ]
  },
  {
   "title": "ALB Backend Response Time (milliseconds)",
   "type": "timeseries",
   "description": "负载均衡实例后端应答时间(ms)",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "AliyunAlb_LoadBalancerUpstreamResponseTime{loadBalancerId=~\"$loadBalancerId\"}",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "APIGW Operation QPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "AliyunCnapigateway_EnvoyOperationQps{apiOperation=~\"$ASMSVC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GW ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "AliyunCnapigateway_EnvoyDownstreamSuccessRate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average latency of gateway operation requests",
   "type": "timeseries",
   "description": "网关Operation请求平均时延",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "AliyunCnapigateway_EnvoyOperationRtAvg{apiOperation=~\"$ASMSVC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ASM-->ACK",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=~\"source\",app=~\"$ASMSVC\"}[5m])))",
     "legendFormat": "Asm QPS"
    },
    {
     "expr": "(sum(irate(istio_request_duration_milliseconds_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[5m])) by (source_app, source_workload_namespace, le) / 1000) or sum(irate(istio_request_duration_seconds_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[5m])) by (source_app, source_workload_namespace, le)",
     "legendFormat": "asm resp"
    },
    {
     "expr": "sum_over_time(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\",response_code=~\"2..\"}[5m])/sum_over_time(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\"}[5m])",
     "legendFormat": "asm rate"
    },
    {
     "expr": "sum(irate(apiserver_request_total{subresource !~ \".*/healthz$|/livez$|/readyz$\"}[5m]))",
     "legendFormat": "ack qps"
    },
    {
     "expr": "avg (sum by (verb) (irate(apiserver_request_duration_seconds_bucket{verb!~\"WATCH|CONNECT\",resource!=\"\",subresource!~\".*/healthz$|/livez$|/readyz$\"}[5m])))",
     "legendFormat": "ack resp"
    },
    {
     "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb!~\"GET|LIST|WATCH|CONNECT\"}[5m]))/sum(irate(apiserver_request_total{verb!~\"GET|LIST|WATCH|CONNECT\"}[5m]))",
     "legendFormat": "ack rate"
    }
   ]
  },
  {
   "title": "ASM-QPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (destination_app)(rate(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",destination_app=~\"$ASMSVC\"}[$__range]))",
     "legendFormat": "{{ASMSVC}}"
    }
   ]
  },
  {
   "title": "ASM-http",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum by (response_code)(rate(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",destination_app=~\"$ASMSVC\"}[$__range]))",
     "legendFormat": "{{ASMSVC}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (callType) (arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc_rpc{namespace=\"$NameSpace\",callKind=~\"$incallKind\"})/sum by (callType) (arms_app_requests_count_ign_destid_endpoint_ppid_prpc_rpc{namespace=\"$NameSpace\",callKind=~\"$incallKind\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{service=~\"$Service\",rpc!~\".*/liveness$\",}[50m])) or vector(0)",
     "legendFormat": "app qps"
    },
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_seconds_raw{service=\"$Service\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",source=\"apm\",}[$__range]))/sum(sum_over_time_lorc(arms_app_requests_count_raw{service=\"$Service\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",source=\"apm\"}[$__range])) or vector(0)",
     "legendFormat": "app duration"
    },
    {
     "expr": "sum by()(sum_over_time(arms_requests_by_status_count_raw{source=\"apm\",status=~\"2..\",app=\"$Service\",rpc!~\".*/liveness$\"}[30m]))/sum by()(sum_over_time(arms_requests_by_status_count_raw{source=\"apm\",app=\"$Service\",rpc!~\".*/liveness$\"}[30m]))",
     "legendFormat": "app rate"
    }
   ]
  },
  {
   "title": "APP RPS/5min",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{service=~\"$Service\",service!=\"\",rpc!~\".*/liveness$\",}[5m])) or vector(0)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "4xx/5xx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "sum by(status) (sum_over_time_lorc(arms_requests_by_status_count_raw{source=\"apm\",status=~\"4..|5..\",app=\"$Service\"}[$__range])) or vector(0)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "repeat": "Service",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(sum_over_time_lorc(arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc_rpc{pid=\"$Pid\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",source=\"apm\", }[$__range]))/sum(sum_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc_rpc{pid=\"$Pid\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",source=\"apm\", }[$__range]))) or vector(0)",
     "legendFormat": "Time"
    }
   ]
  }
 ]
}