{
 "title": "Alibaba Cloud Opensearch-Instance Details",
 "tags": [
  "dashboard:name:opensearch-detail",
  "env:Cloud",
  "scene:big-data",
  "addon:name:cloud-opensearch",
  "env:type:Cloud",
  "addon:version:0.0.2",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "appName",
    "label": "appName",
    "query": {
     "query": "label_values(AliyunOpensearch_ComputeCostbyApp{}, appName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Single query computing consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_ComputeCostbyApp{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Computing resource utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_ComputeResourceRatiobyApp{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Computing resources",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_ComputeResourcebyApp{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Computing resources daily peak",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_DailyPeakComputeResourcebyApp{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Total number of documents",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_DocCountbyApp{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Storage capacity utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_DocSizeRatiobyApp{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Storage capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_DocSizebyApp{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Query time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_LatencybyApp{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Query flow limit QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_LossQPSbyApp{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Query QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_QPSbyApp{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Number of task execution failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_TaskRunningFailsbyApp{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Application schedule processing delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_app_realtime_trigger_latency{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Application real-time processing delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_app_realtime_write_latency{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Application real-time read-in documents per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_app_rt_read_tps{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Application real-time write-out documents per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_app_rt_write_tps{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Application schedule triggers the main table documents per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_app_slave_trigger_tps{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  },
  {
   "title": "Application real-time push speed limit QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunOpensearch_app_write_rate_limit_qps{appName=~\"$appName\"}",
     "legendFormat": "{{appName}}/{{appId}}"
    }
   ]
  }
 ]
}