{
 "title": "Alibaba Cloud Kafka Message Queue Service - Instance Details Dashboard",
 "tags": [
  "scene:middleware",
  "env:Cloud",
  "env:type:Cloud",
  "addon:name:cloud-kafka-cmee",
  "prometheus",
  "dashboard:name:aliKafka-detail",
  "addon:version:0.0.4"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instanceId",
    "label": "InstanceId",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"aliKafka\",series=\"v2\"}, instanceId)"
    }
   },
   {
    "name": "instanceName",
    "label": "InstanceName",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{instanceId=~\"$instanceId\",series=\"v2\"}, instanceName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instance list",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "cloud_monitor_instance_info{service=\"aliKafka\",series=\"v2\",instanceId=~\"$instanceId\",instanceName=~\"$instanceName\"}"
    }
   ]
  },
  {
   "title": "Total consumption rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_group_message_num_output{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{consumerGroup}}"
    }
   ]
  },
  {
   "title": "Consumption rate (Topic level)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_group_message_num_output_onetopic{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{consumerGroup}}/{{topic}}"
    }
   ]
  },
  {
   "title": "Instance disk usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_instance_disk_capacity{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Actual inflow of instance business",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_instance_message_input{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of instance message production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_instance_message_num_input{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of instance message consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_instance_message_num_output{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Actual outflow of instance business",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_instance_message_output{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of instance message sending",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_instance_reqs_input{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of instance message consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_instance_reqs_output{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Message accumulation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_message_accumulation{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{consumerGroup}}"
    }
   ]
  },
  {
   "title": "Number of messages that ConsumerGroup has not consumed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_message_accumulation_onetopic{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{consumerGroup}}/{{topic}}"
    }
   ]
  },
  {
   "title": "Topic message production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_topic_message_input{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{topic}}"
    }
   ]
  },
  {
   "title": "Number of topic message production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_topic_message_num_input{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{topic}}"
    }
   ]
  },
  {
   "title": "Number of topic message consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_topic_message_num_output{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{topic}}"
    }
   ]
  },
  {
   "title": "Topic message consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_topic_message_output{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{topic}}"
    }
   ]
  },
  {
   "title": "Number of topic message sending",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_topic_reqs_input{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{topic}}"
    }
   ]
  },
  {
   "title": "Number of topic message consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_topic_reqs_output{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{topic}}"
    }
   ]
  }
 ]
}