{
 "title": "Alibaba Cloud Kafka V3 Message Queue Service - Instance Details",
 "tags": [
  "dashboard:name:kafkaV3-detail",
  "scene:middleware",
  "env:Cloud",
  "env:type:Cloud",
  "addon:name:cloud-kafka-cmee",
  "prometheus",
  "addon:version:0.0.4"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instanceId",
    "label": "InstanceId",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"aliKafka\",series=\"v3\"}, instanceId)"
    }
   },
   {
    "name": "instanceName",
    "label": "InstanceName",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{instanceId=~\"$instanceId\" ,series=\"v3\"}, instanceName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instance list",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "cloud_monitor_instance_info{service=\"aliKafka\",series=\"v3\",instanceId=~\"$instanceId\",instanceName=~\"$instanceName\"}"
    }
   ]
  },
  {
   "title": "V3 instance cluster inflow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_ClusterMessageInputV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Consumption rate (Partition level)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_GroupMessageNumOutputOnetopicOnepartitionV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{consumerGroup}}/{{topic}}/{{partition}}"
    }
   ]
  },
  {
   "title": "Consumption rate (Topic level)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_GroupMessageNumOutputOnetopicV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{consumerGroup}}/{{topic}}"
    }
   ]
  },
  {
   "title": "Total consumption rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_GroupMessageNumOutputV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{consumerGroup}}"
    }
   ]
  },
  {
   "title": "Storage size used by V3 instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_InstanceDiskLogSizeV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "V3 instance public network read bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_InstanceInternetRxRateV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Topic message production per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_TopicMessageInputV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{topic}}"
    }
   ]
  },
  {
   "title": "Instance message production per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_InstanceMessageInputV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Instance message production per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_InstanceMessageNumInputV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "V3 instance public network write bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_InstanceInternetTxRateV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Instance message consumption per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_InstanceMessageOutputV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Instance message sending per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_InstanceReqsInputV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Instance message consumption per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_InstanceReqsOutputV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Consumer group unconsumed messages for a topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_MessageAccumulationOnetopicV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{consumerGroup}}/{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer group unconsumed messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_MessageAccumulationV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{consumerGroup}}"
    }
   ]
  },
  {
   "title": "Topic message consumption per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_TopicMessageOutputV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{topic}}"
    }
   ]
  },
  {
   "title": "Topic message production per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_TopicMessageNumInputV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{topic}}"
    }
   ]
  },
  {
   "title": "Topic message consumption per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_TopicReqsOutputV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{topic}}"
    }
   ]
  },
  {
   "title": "Topic message sending per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAlikafka_TopicReqsInputV3{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{topic}}"
    }
   ]
  }
 ]
}