{
 "title": "AliCloud Rabbitmq Overview - NonProd",
 "tags": [
  "RabbitMQ",
  "MQ",
  "scene:middleware",
  "addon:name:cloud-rabbitmq",
  "addon:version:0.0.1",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:rabbitmq-dashboard"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Select Env", "query": "nprd,dev,uat" },
   {
    "name": "InstanceName",
    "label": "InstanceName",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"amqp\", regionId=\"$region\"},instanceName)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "region",
    "label": "area",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"amqp\"}, regionId)"
    }
   },
   {
    "name": "InstanceID",
    "label": "InstanceID",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"amqp\", regionId=\"$region\", instanceName=\"$InstanceName\"},instanceId)"
    }
   },
   {
    "name": "VirtualHost",
    "label": "VirtualHost",
    "query": {
     "query": "label_values(rabbitmq_connections{instanceId=\"$InstanceID\"},vHost)"
    }
   },
   {
    "name": "ExchangeName",
    "label": "ExchangeName",
    "query": {
     "query": "label_values(rabbitmq_exchange_messages_published_in_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"},exchangeName)"
    }
   },
   {
    "name": "QueueName",
    "label": "QueueName",
    "query": {
     "query": "label_values(rabbitmq_queue_messages_published_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"},queueName)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Overview (Vhost : $VirtualHost)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ready messages ($VirtualHost)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum({__name__=~\"rabbitmq_queue_accumulation|rabbitmq_queue_messages_ready\",instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"})"
      }
     ]
    },
    {
     "title": "Current connections ($VirtualHost)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_connections{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"})"
      }
     ]
    },
    {
     "title": "Current channels ($VirtualHost)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_channels{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"})"
      }
     ]
    },
    {
     "title": "Current consumers（$VirtualHost）",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_consumers{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"})"
      }
     ]
    },
    {
     "title": "Queue overview (message rate in bars/second)",
     "type": "table",
     "description": "Message processing time = server response time - server message delivery time.\n",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum({__name__=~\"rabbitmq_queue_accumulation|rabbitmq_queue_messages_ready\",instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}) by (vHost,queueName)",
       "legendFormat": "Ready messages"
      },
      {
       "expr": "sum({__name__=~\"rabbitmq_queue_unacked_deliver_messages|rabbitmq_queue_unacked_get_messages\",instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}) by (vHost,queueName)",
       "legendFormat": "Unacked messages"
      },
      {
       "expr": "sum(rabbitmq_queue_messages_timing{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}) by (vHost,queueName)",
       "legendFormat": "The number of messages in the timer"
      },
      {
       "expr": "sum(rate(rabbitmq_queue_messages_published_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}[1m])) by (vHost,queueName)",
       "legendFormat": "Incoming message rate"
      },
      {
       "expr": "sum(rate({__name__=~\"rabbitmq_queue_deliver_total|rabbitmq_queue_get_total\",instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}[1m])) by (vHost,queueName)",
       "legendFormat": "Deliver/get message rate"
      },
      {
       "expr": "sum(rate(rabbitmq_queue_ack_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}[1m])) by (vHost,queueName)",
       "legendFormat": "Ack message rate"
      },
      {
       "expr": "sum(rabbitmq_queue_consumers{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}) by (vHost,queueName)",
       "legendFormat": "Number of consumers"
      },
      {
       "expr": "avg({__name__=~\"rabbitmq_consumer_acked_proccess_time_avg|rabbitmq_consumer_unacked_proccess_time_avg\",instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}) by (vHost,queueName)",
       "legendFormat": "process time"
      }
     ]
    },
    {
     "title": "Exchange overview (message rate Unit: bar/second)",
     "type": "table",
     "description": "Click the column name to sort in ascending or descending order according to the current column value",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_exchange_messages_published_in_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",exchangeName=~\"$ExchangeName\"}[1m])) by (vHost,exchangeName)",
       "legendFormat": "message rate in (messages/s)"
      },
      {
       "expr": "sum(rate(rabbitmq_exchange_messages_published_out_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",exchangeName=~\"$ExchangeName\"}[1m])) by (vHost,exchangeName)",
       "legendFormat": "message rate out (messages/s)"
      }
     ]
    },
    {
     "title": "Ready messages top 20 queues($VirtualHost)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20,sum({__name__=~\"rabbitmq_queue_accumulation|rabbitmq_queue_messages_ready\",instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}) by (queueName))",
       "legendFormat": "{{queueName}}"
      }
     ]
    },
    {
     "title": "Message processing time (server response time - server message delivery time) top 20 queues($VirtualHost)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(20,avg({__name__=~\"rabbitmq_consumer_acked_proccess_time_avg|rabbitmq_consumer_unacked_proccess_time_avg\",instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}) by (queueName))",
       "legendFormat": "{{queueName}}"
      }
     ]
    },
    {
     "title": "Queue publish message rate top 20 queues ($VirtualHost)",
     "type": "timeseries",
     "description": "Total number of messages published to queues",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20,sum(rate(rabbitmq_queue_messages_published_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (queueName))",
       "legendFormat": "{{queueName}}"
      }
     ]
    },
    {
     "title": "Deliver and get message rate top 20 queues ($VirtualHost)",
     "type": "timeseries",
     "description": "Total number of messages deliver and get from queues",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20,sum(rate({__name__=~\"rabbitmq_queue_deliver_total|rabbitmq_queue_get_total\",instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (queueName))",
       "legendFormat": "{{queueName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ins Total (ALL)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cloud_monitor_instance_info{product=~\"amqp\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "group(cloud_monitor_instance_info{product=~\"amqp\"}) by(id,instanceName,instanceType,status,resourceGroupName)",
     "legendFormat": "__auto"
    },
    {
     "expr": "group(cloud_monitor_instance_tag{product=~\"amqp\",key=~\"AppCode\"}) by(id,value)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(AliyunAmqp_instance_InstanceConnections{})by(id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(AliyunAmqp_instance_InstanceConsumers{})by(id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(AliyunAmqp_instance_InstanceChannelsNew{})by(id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ins Total (Stoped)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cloud_monitor_instance_info{product=~\"amqp\",status!~\"SERVING\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exchanges (Vhost:$VirtualHost , Exchange : $ExchangeName)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exchange messages published in (Exchagne:$ExchangeName)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_exchange_messages_published_in_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",exchangeName=~\"$ExchangeName\"}[1m])) "
      }
     ]
    },
    {
     "title": "Exchange messages published out (Exchange:$ExchangeName)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_exchange_messages_published_out_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",exchangeName=~\"$ExchangeName\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Queues (Vhost:$VirtualHost , Queue : $QueueName)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue messages (Queue:$QueueName)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum({__name__=~\"rabbitmq_queue_accumulation|rabbitmq_queue_messages_ready\",instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"})",
       "legendFormat": "ready"
      },
      {
       "expr": "sum(rabbitmq_queue_unacked_deliver_messages{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"})",
       "legendFormat": "deliver unacked"
      },
      {
       "expr": "sum(rabbitmq_queue_unacked_get_messages{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"})",
       "legendFormat": "get unacked"
      },
      {
       "expr": "sum(rabbitmq_queue_messages_timing{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"})",
       "legendFormat": "Timing"
      }
     ]
    },
    {
     "title": "Message processing time (server response time - server message delivery time) (Queue:$QueueName)",
     "type": "timeseries",
     "description": "Message processing time = server response time - server message delivery time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "avg({__name__=~\"rabbitmq_consumer_acked_proccess_time_avg|rabbitmq_consumer_unacked_proccess_time_avg\",instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"})",
       "legendFormat": "Processing time"
      }
     ]
    },
    {
     "title": "Queue APIs rate(Queue:$QueueName)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_queue_messages_published_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}[1m])) ",
       "legendFormat": "publish"
      },
      {
       "expr": "sum(rate(rabbitmq_queue_deliver_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}[1m])) ",
       "legendFormat": "deliver"
      },
      {
       "expr": "sum(rate(rabbitmq_queue_get_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}[1m])) ",
       "legendFormat": "get"
      },
      {
       "expr": "sum(rate(rabbitmq_queue_ack_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}[1m])) ",
       "legendFormat": "ack"
      },
      {
       "expr": "sum(rate(rabbitmq_queue_uack_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}[1m])) ",
       "legendFormat": " unack"
      },
      {
       "expr": "sum(rate(rabbitmq_queue_recover_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}[1m])) ",
       "legendFormat": "recover"
      },
      {
       "expr": "sum(rate(rabbitmq_queue_reject_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}[1m])) ",
       "legendFormat": "reject"
      },
      {
       "expr": "sum(rate(rabbitmq_queue_other_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}[1m]))",
       "legendFormat": "other"
      }
     ]
    },
    {
     "title": "Queue consumers (Queue:$QueueName)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_consumers{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\",queueName=~\"$QueueName\"}) ",
       "legendFormat": "consumer count"
      }
     ]
    }
   ]
  },
  {
   "title": "VirtualHost (Vhost : $VirtualHost)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate per API ($VirtualHost)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_connections_opened_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (vHost)",
       "legendFormat": "open connection"
      },
      {
       "expr": "sum(rate(rabbitmq_connections_closed_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (vHost)",
       "legendFormat": "close connection"
      },
      {
       "expr": "sum(rate(rabbitmq_channels_opened_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (vHost)",
       "legendFormat": "open channel"
      },
      {
       "expr": "sum(rate(rabbitmq_channels_closed_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (vHost)",
       "legendFormat": "close channel"
      },
      {
       "expr": "sum(rate(rabbitmq_queues_declared_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (vHost)",
       "legendFormat": "declare queue"
      },
      {
       "expr": "sum(rate(rabbitmq_queues_deleted_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (vHost)",
       "legendFormat": "delete queue"
      },
      {
       "expr": "sum(rate(rabbitmq_exchange_declared_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (vHost)",
       "legendFormat": "declare exchange"
      },
      {
       "expr": "sum(rate(rabbitmq_exchange_deleted_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (vHost)",
       "legendFormat": "delete exchange"
      },
      {
       "expr": "sum(rate(rabbitmq_exchange_bind_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (vHost)",
       "legendFormat": "bind exchange"
      },
      {
       "expr": "sum(rate(rabbitmq_exchange_unbind_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (vHost)",
       "legendFormat": "unbind exchange"
      },
      {
       "expr": "sum(rate(rabbitmq_queue_bind_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (vHost)",
       "legendFormat": "bind queue"
      },
      {
       "expr": "sum(rate(rabbitmq_queue_unbind_total{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}[1m])) by (vHost)",
       "legendFormat": "unbind queue"
      }
     ]
    },
    {
     "title": "VirtualHost channels ($VirtualHost)",
     "type": "timeseries",
     "description": "Channels currently open.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rabbitmq_channels{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}) by (vHost)",
       "legendFormat": "{{vHost}}"
      }
     ]
    },
    {
     "title": "VirtualHost connections ($VirtualHost)",
     "type": "timeseries",
     "description": "Connections currently open.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rabbitmq_connections{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}) by (vHost)",
       "legendFormat": "{{vHost}}"
      }
     ]
    },
    {
     "title": "Channels per Connection ($VirtualHost)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "topk(20,sum(rabbitmq_connection_channels{instanceId=\"$InstanceID\",vHost=~\"$VirtualHost\"}) by (remoteAddress))",
       "legendFormat": "{{remoteAddress}}"
      }
     ]
    }
   ]
  }
 ]
}