{
 "title": "AliCloud ECS Overview - NonProd Copy",
 "description": "This dashboard provides a concise overview of the workloads of all ECS instances in the NonProd environment on Alibaba Cloud, enabling quick identification of ECS instances that have been running with long-term low utilization.",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "label": "Region",
    "query": {
     "query": "label_values(AliyunEcs_CPUUtilization{regionId!=\"--\"}, regionId)"
    }
   },
   {
    "name": "instanceName",
    "label": "InstanceName",
    "query": {
     "query": "label_values(AliyunEcs_CPUUtilization{regionId=~\"$regionId\"},instanceName)"
    }
   },
   {
    "name": "nodeIp",
    "label": "NodeIP",
    "query": {
     "query": "label_values(AliyunEcs_CPUUtilization{regionId=~\"$regionId\",instanceName=~\"$instanceName\"}, nodeIp)"
    }
   },
   {
    "name": "instanceId",
    "label": "InstanceID",
    "query": {
     "query": "label_values(AliyunEcs_CPUUtilization{regionId=~\"$regionId\",instanceName=~\"$instanceName\",nodeIp=~\"$nodeIp\"}, instanceId)"
    }
   },
   {
    "name": "tagKey",
    "label": "TagKey",
    "query": {
     "query": "label_values(cloud_monitor_instance_tag{regionId=~\"$regionId\",product=\"ecs\" },key)"
    }
   },
   {
    "name": "tagValue",
    "label": "TagValue",
    "query": {
     "query": "query_result(cloud_monitor_instance_tag{key=~\"o11y.aliyun.dev/$tagKey\",regionId=~\"$regionId\",product=\"ecs\"}>0)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "Env",
    "label": "Env",
    "query": {
     "query": "label_values(AliyunEcs_CPUUtilization{unique_cluster_account!=\"--\"},unique_cluster_account)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total ECS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cloud_monitor_instance_info{service=\"ecs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ECS Average CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_CPUUtilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"})"
    }
   ]
  },
  {
   "title": "ECS Average Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_memory_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"})"
    }
   ]
  },
  {
   "title": "ECS Diskusage Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_diskusage_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"})"
    }
   ]
  },
  {
   "title": "ECS instance Detail",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_cpu_total{})by(nodeIp,instanceId,instanceName,unique_cluster_account)"
    },
    {
     "expr": "avg(AliyunEcs_memory_usedutilization{})by(nodeIp,instanceId,instanceName,unique_cluster_account)"
    },
    {
     "expr": "avg(AliyunEcs_net_tcpconnection{state=\"ESTABLISHED\"})by(nodeIp,instanceId,instanceName,unique_cluster_account)"
    },
    {
     "expr": "max(AliyunEcs_IntranetInRate{})by(nodeIp,instanceId,instanceName,unique_cluster_account)/1024"
    },
    {
     "expr": "max(AliyunEcs_IntranetOutRate{})by(nodeIp,instanceId,instanceName,unique_cluster_account)/1024"
    },
    {
     "expr": "avg(AliyunEcs_VPC_PublicIP_InternetOutRate_Percent{})by(nodeIp,instanceId,instanceName,unique_cluster_account) or vector(0)"
    },
    {
     "expr": "max by(instanceId, app_name) (label_replace(cloud_monitor_instance_tag{product=\"ecs\", key=\"AppCode\"}>0, \"app_name\", \"$1\", \"value\", \"(.+)\"))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "AliyunEcs_CPUUtilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}"
      }
     ]
    },
    {
     "title": "Current CPU Idle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "AliyunEcs_cpu_idle{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "AliyunEcs_memory_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}"
      }
     ]
    },
    {
     "title": "Current Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "AliyunEcs_memory_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "targets": [
      {
       "expr": "AliyunEcs_diskusage_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}"
      }
     ]
    },
    {
     "title": "Current Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "targets": [
      {
       "expr": "AliyunEcs_diskusage_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Read Bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskReadBPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Write Bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskWriteBPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Read IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskReadIOPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskWriteIOPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Intranet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Intranet In Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "AliyunEcs_IntranetInRate{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}/1024/1024",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Current Intranet Out Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "AliyunEcs_IntranetOutRate{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}/1024/1024",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  }
 ]
}