{
 "title": "AliCloud ECS Overview - NonProd",
 "description": "This dashboard provides a concise overview of the workloads of all ECS instances in the NonProd environment on Alibaba Cloud, enabling quick identification of ECS instances that have been running with long-term low utilization.",
 "tags": [ "ecs" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "tagKey",
    "label": "TagKey",
    "query": {
     "query": "label_values(cloud_monitor_instance_tag{regionId=~\"$regionId\",product=\"ecs\" },key)"
    }
   },
   {
    "name": "tagValue",
    "label": "TagValue",
    "query": {
     "query": "label_values(cloud_monitor_instance_tag{service=\"ecs\", key=\"$tagKey\"},value)"
    }
   },
   {
    "name": "regionId",
    "label": "Region",
    "query": {
     "query": "label_values(AliyunEcs_CPUUtilization{regionId!=\"--\"}, regionId)"
    }
   },
   {
    "name": "instanceName",
    "label": "InstanceName",
    "query": {
     "query": "label_values(AliyunEcs_CPUUtilization{regionId=~\"$regionId\", instanceId=\"$instanceId\"},instanceName)"
    }
   },
   {
    "name": "instanceId",
    "label": "InstanceID",
    "query": {
     "query": "label_values(cloud_monitor_instance_tag{service=\"ecs\", value=\"$tagValue\"},id)"
    }
   },
   {
    "name": "nodeIp",
    "label": "NodeIP",
    "query": {
     "query": "label_values(AliyunEcs_CPUUtilization{instanceName=~\"$instanceName\"},nodeIp)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total ECS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cloud_monitor_instance_info{service=\"ecs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dev Env Total ECS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cloud_monitor_instance_info{service=\"ecs\",promInstanceId=\"rw-b2336b29445cb338f8201822a7b7\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dev Env Total ECS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cloud_monitor_instance_info{service=\"ecs\",promInstanceId=\"rw-83f8a21d40da8b5c4dffe50b6ac5\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ECS Overall CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_CPUUtilization{})"
    }
   ]
  },
  {
   "title": "ECS Overall Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_memory_usedutilization{})"
    }
   ]
  },
  {
   "title": "ECS Overall Diskusage Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_diskusage_utilization{})"
    }
   ]
  },
  {
   "title": "ECS instance Detail",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_CPUUtilization{})by(id,nodeIp,instanceName)"
    },
    {
     "expr": "avg(AliyunEcs_memory_usedutilization{})by(id,nodeIp,instanceName)"
    },
    {
     "expr": "avg(AliyunEcs_net_tcpconnection{state=\"ESTABLISHED\"})by(id,nodeIp,instanceName)"
    },
    {
     "expr": "max(AliyunEcs_IntranetInRate{})by(id,nodeIp,instanceName)/1024"
    },
    {
     "expr": "max(AliyunEcs_IntranetOutRate{})by(id,nodeIp,instanceName)/1024"
    },
    {
     "expr": "avg(AliyunEcs_VPC_PublicIP_InternetOutRate_Percent{})by(id,nodeIp,instanceName)"
    },
    {
     "expr": "group(cloud_monitor_instance_info{product=~\"ecs\"})by(id,nodeIp,instanceName,status,instanceType,resourceGroupName)",
     "legendFormat": "__auto"
    },
    {
     "expr": "group(cloud_monitor_instance_tag{product=\"ecs\", key=~\"AppCode\"})by(id,value)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Utilization Heatmap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "AliyunEcs_CPUUtilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\"}",
     "legendFormat": "{{instanceName}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "AliyunEcs_memory_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\"}"
      }
     ]
    },
    {
     "title": "Current Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "AliyunEcs_memory_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "AliyunEcs_diskusage_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\"}"
      }
     ]
    },
    {
     "title": "Current Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "AliyunEcs_diskusage_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Read Bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskReadBPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Write Bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskWriteBPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Read IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskReadIOPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskWriteIOPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Intranet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Intranet In Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "AliyunEcs_IntranetInRate{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}/1024/1024",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Current Intranet Out Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "AliyunEcs_IntranetOutRate{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}/1024/1024",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  }
 ]
}