{
 "title": "API Gateway - InstanceDashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instanceName",
    "label": "instanceName",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"cnapigateway\"},instanceName)"
    }
   },
   {
    "name": "instanceId",
    "label": "InstanceId",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"cnapigateway\", instanceName=~\"$instanceName\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instances Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cloud_monitor_instance_info{product=\"cnapigateway\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "group(cloud_monitor_instance_info{product=\"cnapigateway\"}) by (id,status,instanceName)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(ceil(AliyunCnapigateway_EnvoyApiQps{}))by(id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(AliyunCnapigateway_EnvoyCpuUsageRate{})by(id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(AliyunCnapigateway_EnvoyMemoryUsageRate{})by(id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(AliyunCnapigateway_EnvoyDownstreamSuccessRate{})by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average latency of gateway API requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyApiRtAvg{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{apiName}}/{{apiEnv}}/{{apiVersion}}"
    }
   ]
  },
  {
   "title": "Success rate of gateway API requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyApiSuccessRate{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{apiName}}/{{apiEnv}}/{{apiVersion}}"
    }
   ]
  },
  {
   "title": "Gateway API QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyApiQps{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{apiName}}/{{apiEnv}}/{{apiVersion}}"
    }
   ]
  },
  {
   "title": "Number of connections destroyed per second by gateway clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClientDestroyConnection{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of SSL handshake failures per second by gateway clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClientDestroySSL{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of currently active connections of gateway clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClientActiveConnection{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of SSL handshakes per second by gateway clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClientNewSSL{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of SSL handshakes reused per second by gateway clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClientReuseSSL{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of new connections per second by gateway clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClientNewConnection{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average latency of gateway service requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClusterRtAvg{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Success rate of gateway service requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClusterSuccessRate{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Gateway service QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClusterQps{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "QPS (client)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyDownstreamQps{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average latency of requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyDownstreamRtAvg{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Gateway CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyCpuUsageRate{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Disk Read load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyFsReadBytes{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Disk Write load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 53 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyFsWriteBytes{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Success rate of requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyDownstreamSuccessRate{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Memory load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyMemoryUsageRate{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Gateway network inbound IO load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 62 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyNetworkInBytes{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Gateway memory load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 62 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyMemoryUsage{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Gateway Operation QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 62 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyOperationQps{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{apiName}}/{{apiEnv}}/{{apiVersion}}/{{apiOperation}}"
    }
   ]
  },
  {
   "title": "Average latency of gateway operation requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyOperationRtAvg{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{apiName}}/{{apiEnv}}/{{apiVersion}}/{{apiOperation}}"
    }
   ]
  },
  {
   "title": "Gateway network outbound IO load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 71 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyNetworkOutBytes{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of gateway plugin crashes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 71 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyPluginCrash{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{pluginName}}"
    }
   ]
  },
  {
   "title": "Number of API gateway flow limiting requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 80 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyRateLimitRequests{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Success rate of gateway operation requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyOperationSuccessRate{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{apiName}}/{{apiEnv}}/{{apiVersion}}/{{apiOperation}}"
    }
   ]
  },
  {
   "title": "Gateway routing QPS(2xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 80 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyRouteQps2XX{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{route}}"
    }
   ]
  },
  {
   "title": "Gateway routing QPS(4xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 89 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyRouteQps4XX{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{route}}"
    }
   ]
  },
  {
   "title": "Gateway routing QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 89 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyRouteQps{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{route}}"
    }
   ]
  },
  {
   "title": "Average latency of gateway routing requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyRouteRtAvg{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{route}}"
    }
   ]
  },
  {
   "title": "Success rate of gateway routing requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyRouteSuccessRate{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{route}}"
    }
   ]
  },
  {
   "title": "Gateway routing QPS(5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 98 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyRouteQps5XX{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{route}}"
    }
   ]
  },
  {
   "title": "Number of connections destroyed per second of gateway service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 98 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamDestroyConnection{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of current healthy nodes of gateway service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 107 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamEndpoints{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Number of current active connections of gateway service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 107 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamActiveConnection{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Gateway QPS(upstream)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 107 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamQps{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average latency of backend service requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamRtAvg{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of new connections per second of gateway service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 116 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamNewConnection{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Success rate of backend service requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamSuccessRate{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  }
 ]
}