{
 "title": "Application Over View Copy",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Env", "query": "dev,uat" },
   { "name": "datasource", "label": "AppEnv", "query": "prometheus" },
   { "name": "datasource_ack", "label": "ACK", "query": "prometheus" },
   {
    "name": "NameSpace",
    "label": "NameSpace",
    "query": {
     "query": "label_values(arms_agent_info{namespace!~\"(?i).*arms.*\"},namespace)"
    }
   },
   {
    "name": "service",
    "label": "Services",
    "query": {
     "query": "label_values(arms_tag_host_entity{namespace=\"$NameSpace\",app!~\"(?i).*alicloud.*\"},app)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(arms_app_requests_count_raw{service=\"$service\"},host)"
    }
   },
   {
    "name": "incallKind",
    "label": "incallKind",
    "query": "http|rpc|consumer|custom_entry|server"
   },
   {
    "name": "outcallKind",
    "label": "outcallKind",
    "query": "rpc_client|http_client|db|sql|nosql|cache|producer|client"
   },
   {
    "name": "fullIncallKinds",
    "label": "fullIncallKinds",
    "query": "http|rpc|consumer|custom_entry|schedule|server"
   },
   {
    "name": "pid",
    "label": "pid",
    "query": {
     "query": "label_values(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{service=\"$service\"},pid)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$NameSpace\"},pod)"
    }
   },
   {
    "name": "Container",
    "label": "Microservice (Container Name)",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$NameSpace\"},container)"
    }
   },
   {
    "name": "origin_prometheus",
    "label": "K8S",
    "query": {
     "query": "label_values(kube_node_info,unique_cluster_name)"
    }
   },
   {
    "name": "Node",
    "label": "Nodes",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Instances (Real-Time)",
   "type": "stat",
   "description": "Take the last number of instances that are not 0 points.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (hostname) (max_over_time_lorc(arms_tag_host_entity{namespace=~\"$NameSpace\",app=~\"$service\" }[10m]))) or vector(0)"
    }
   ]
  },
  {
   "title": "Totol Request Num (Selected Time Period)",
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{app=\"$service\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",rpc!~\".*/health/.*\",source=\"apm\",}[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request Volume (Selected Time Period)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_requests_by_status_count_raw{namespace=~\"$NameSpace\",app=~\"$service\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\"}[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time consumption (selected period)",
   "type": "stat",
   "description": "Except liveness",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_seconds_raw{app=\"$service\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",source=\"apm\",rpc!~\".*/health/.*\"}[$__range]))/sum(sum_over_time_lorc(arms_app_requests_count_raw{app=\"$service\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",source=\"apm\",rpc!~\".*/health/.*\"}[$__range])) or vector(0)",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Cumulative Errors (Selected Time Period)",
   "type": "stat",
   "description": "Except liveness",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_error_count_raw{app=\"$service\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",source=\"apm\",}[$__range])) or vector(0)",
     "legendFormat": "Current"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Number of requests",
   "type": "timeseries",
   "description": "Except liveness",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service)(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",namespace=\"$NameSpace\",source=\"apm\"}[1h]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (service) (arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc_rpc{namespace=~\"$NameSpace\",host=~\"$host\",callKind=~\"$incallKind\"})/sum by (service) (arms_app_requests_count_ign_destid_endpoint_ppid_prpc_rpc{namespace=~\"$NameSpace\",host=~\"$host\",callKind=~\"$incallKind\"})",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "HTTP-status code statistics",
   "type": "timeseries",
   "description": "Except liveness",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(app,status) (sum_over_time_lorc(arms_requests_by_status_count_raw{namespace=~\"$NameSpace\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",rpc!~\".*/health.*\",rpc!~ \".*__all__$\",source=\"apm\"}[$__range]))",
     "legendFormat": "{{app}}: http-{{status}}"
    }
   ]
  },
  {
   "title": "Num Error",
   "type": "timeseries",
   "description": "Except liveness",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(app)(sum_over_time(arms_app_requests_error_count_raw{namespace=~\"$NameSpace\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!=\"GET /health/liveness\",source=\"apm\",}[$__range])) or vector (0)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Provided Service Ranking of Requests ",
   "type": "table",
   "description": "Except liveness",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "topk(5,sum by (rpc,callType,callKind,pid) (sum_over_time_lorc(arms_requests_by_status_count_raw{namespace=~\"$NameSpace\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",rpc!~\".*/liveness$\",rpc!~\".*/health.*\",source=\"apm\", }[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provided Service Ranking of Average Duration (Top5)",
   "type": "table",
   "description": "Except liveness",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "topk(5,sum by (rpc,pid,callType,callKind) (sum_over_time_lorc(arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc{namespace=~\"$NameSpace\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",rpc!~\".*/liveness$\",rpc!~\".*/health.*\",source=\"apm\"}[$__range]))/sum by (rpc,pid,callType,callKind) (sum_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{namespace=~\"$NameSpace\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",rpc !~\".*/liveness$\",rpc!~\".*/health.*\",source=\"apm\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summary of Interface Indicators (Selected Time Periods)",
   "type": "table",
   "description": "Displays the interface indicators of service in the selected time period.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (rpc) (sum_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{app=\"$service\",callKind=~\"$fullIncallKinds\"}[$__range]))"
    },
    {
     "expr": "sum by (rpc) (sum_over_time_lorc(arms_app_requests_error_count_ign_destid_endpoint_ppid_prpc{app=\"$service\",callKind=~\"$fullIncallKinds\"}[$__range]))"
    },
    {
     "expr": "sum by (rpc) (sum_over_time_lorc(arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc{app=\"$service\",callKind=~\"$fullIncallKinds\"}[$__range]))/sum by (rpc) (sum_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{app=\"$service\",callKind=~\"$fullIncallKinds\"}[$__range]))"
    },
    {
     "expr": "sum by (rpc) (sum_over_time_lorc(arms_exception_requests_count_raw{app=\"$service\"}[$__range])) or on (rpc) group by (rpc) (max_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{app=\"$service\",callKind=~\"$fullIncallKinds\"}[$__range]))-1"
    },
    {
     "expr": "max by (rpc) (max_over_time_lorc(arms_http_requests_latency_seconds{app=\"$service\",quantile=\"0.75\"}[$__range])) or on (rpc) group by (rpc) (max_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{app=\"$service\",callKind=~\"$fullIncallKinds\"}[$__range]))-1"
    },
    {
     "expr": "max by (rpc) (max_over_time_lorc(arms_http_requests_latency_seconds{app=\"$service\",quantile=\"0.9\"}[$__range])) or on (rpc) group by (rpc) (max_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{app=\"$service\",callKind=~\"$fullIncallKinds\"}[$__range]))-1"
    },
    {
     "expr": "max by (rpc) (max_over_time_lorc(arms_http_requests_latency_seconds{app=\"$service\",quantile=\"0.99\"}[$__range])) or on (rpc) group by (rpc) (max_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{app=\"$service\",callKind=~\"$fullIncallKinds\"}[$__range]))-1"
    }
   ]
  },
  { "title": "Application dependency service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Application Dependent Service Requests/Per Minute",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by (workloadName) (sum_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc_rpc{namespace=~\"$NameSpace\",callKind=~\"$outcallKind\",workloadName!=\"\"}[1m]))",
     "legendFormat": "{{workloadName}}"
    }
   ]
  },
  {
   "title": "Average response time per minute for application-dependent services",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (workloadName) (sum_over_time_lorc(arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc_rpc{namespace=~\"$NameSpace\",callKind=~\"$outcallKind\",workloadName!=\"\"}[1m]))/sum by (workloadName) (sum_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc_rpc{namespace=~\"$NameSpace\",callKind=~\"$outcallKind\", workloadName!=\"\"}[1m]))",
     "legendFormat": "{{workloadName}}"
    }
   ]
  },
  { "title": "Application service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Application to provide service requests/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by (workloadName) (sum_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc_rpc{app=\"$service\",callKind=~\"$incallKind\"}[1m]))",
     "legendFormat": "{{workloadName}} "
    }
   ]
  },
  {
   "title": "Average response time per minute for application provision services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (callType) (sum_over_time_lorc(arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc_rpc{app=\"$service\",callKind=~\"$incallKind\"}[1m]))/sum by (callType) (sum_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc_rpc{app=\"$service\",callKind=~\"$incallKind\"}[1m]))",
     "legendFormat": "{{callType}} Entry"
    }
   ]
  },
  {
   "title": "JVM monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC times/min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum(sum_over_time_lorc(arms_jvm_gc_delta{app=\"$service\",host=~\"$host\",gen=\"old\"}[1m]))",
       "legendFormat": "FullGC times-instantaneous value"
      },
      {
       "expr": "sum(max_over_time_lorc(arms_jvm_gc_total{app=\"$service\",host=~\"$host\",gen=\"old\"}[1m]))",
       "legendFormat": "FullGC Times-Cumulative Value"
      },
      {
       "expr": "sum(sum_over_time_lorc(arms_jvm_gc_delta{app=\"$service\",host=~\"$host\",gen=\"young\"}[1m]))",
       "legendFormat": "Number of YoungGC-Instantaneous Value"
      },
      {
       "expr": "sum(max_over_time_lorc(arms_jvm_gc_total{app=\"$service\",host=~\"$host\",gen=\"young\"}[1m]))",
       "legendFormat": "Number of YoungGC-Cumulative Value"
      }
     ]
    },
    {
     "title": "GC time consuming/minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(sum_over_time_lorc(arms_jvm_gc_seconds_delta{app=\"$service\",host=~\"$host\",gen=\"young\"}[1m]))",
       "legendFormat": "YoungGC Time Consumption-Instantaneous Value"
      },
      {
       "expr": "max(max_over_time_lorc(arms_jvm_gc_seconds_total{app=\"$service\",host=~\"$host\",gen=\"young\"}[1m]))",
       "legendFormat": "YoungGC Time-Cumulative Value"
      },
      {
       "expr": "sum(sum_over_time_lorc(arms_jvm_gc_seconds_delta{app=\"$service\",host=~\"$host\",gen=\"old\"}[1m]))",
       "legendFormat": "FullGC Time-Instantaneous Value"
      },
      {
       "expr": "max(max_over_time_lorc(arms_jvm_gc_seconds_total{app=\"$service\",host=~\"$host\",gen=\"old\"}[1m]))",
       "legendFormat": "FullGC Time-Cumulative Value"
      }
     ]
    },
    {
     "title": "Heap Memory Details/Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "max by (id) (max_over_time_lorc(arms_jvm_mem_used_bytes{app=\"$service\",host=~\"$host\",area=\"heap\"}[1m]))/1024/1024",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Meta space/minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "max(max_over_time_lorc(arms_jvm_mem_used_bytes{app=\"$service\",host=~\"$host\",area=\"nonheap\",id=\"metaspace\"}[1m]))/1024/1024",
       "legendFormat": "Meta space"
      }
     ]
    },
    {
     "title": "Non-heap memory/min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "max(max_over_time_lorc(arms_jvm_mem_committed_bytes{app=\"$service\",host=~\"$host\",area=\"nonheap\"}[1m]))/1024/1024",
       "legendFormat": "Number of bytes submitted"
      },
      {
       "expr": "max(max_over_time_lorc(arms_jvm_mem_init_bytes{app=\"$service\",host=~\"$host\",area=\"nonheap\"}[1m]))/1024/1024",
       "legendFormat": "Initial number of bytes"
      },
      {
       "expr": "max(max_over_time_lorc(arms_jvm_mem_max_bytes{app=\"$service\",host=~\"$host\",area=\"nonheap\"}[1m]))/1024/1024",
       "legendFormat": "Maximum number of bytes"
      }
     ]
    },
    {
     "title": "Direct buffer/minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "max(max_over_time_lorc(arms_jvm_buffer_pool_total_bytes{app=\"$service\",host=~\"$host\",id=\"direct\"}[1m]))/1024/1024",
       "legendFormat": "Total DirectBuffer size"
      },
      {
       "expr": "max(max_over_time_lorc(arms_jvm_buffer_pool_used_bytes{app=\"$service\",host=~\"$host\",id=\"direct\"}[1m]))",
       "legendFormat": "DirectBuffer usage size"
      }
     ]
    },
    {
     "title": "Number of JVM threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "sum by (state) (arms_jvm_threads_count{app=\"$service\",host=~\"$host\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  { "title": "Threads monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Number of threads",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(app)(arms_tag_host_entity{namespace=~\"$NameSpace\",app!~\"\"})",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Pod monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Container Resource Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (container))"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container)",
     "legendFormat": "Total Cores Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "sum (container_memory_rss{container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "Average Memory%(RSS)"
    },
    {
     "expr": "sum (container_memory_rss{container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "Total Memory Usage (RSS) "
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"})"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "avg(container_fs_usage_bytes{container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "sum(group by(pod,container)(kube_pod_container_info{namespace=~\"$NameSpace\"})) by (container)"
    },
    {
     "expr": "avg(container_fs_limit_bytes{container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    }
   ]
  },
  {
   "title": "Pod Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "group by (container,pod,namespace) (kube_pod_container_info{namespace!~\"kube-system|twistlock|istio-system|ack-onepilot|arms-prom|\",container!~\".*job.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (container,pod,namespace)(kube_pod_container_status_restarts_total{namespace!~\"kube-system|twistlock|istio-system|ack-onepilot|arms-prom|\",container!~\".*job.*\"})",
     "legendFormat": "Restarts"
    },
    {
     "expr": "sum by (container,pod,namespace)(kube_pod_container_resource_requests_cpu_cores{namespace!~\"kube-system|twistlock|istio-system|ack-onepilot|arms-prom|\",container!~\".*job.*\"})",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "sum by (container,pod,namespace)(kube_pod_container_resource_requests_memory_bytes{namespace!~\"kube-system|twistlock|istio-system|ack-onepilot|arms-prom|\",container!~\".*job.*\"})",
     "legendFormat": "Memory Request"
    },
    {
     "expr": "max by (container,pod,namespace)(kube_pod_container_status_running{namespace!~\"kube-system|twistlock|istio-system|ack-onepilot|arms-prom|\",container!~\".*job.*\"})"
    },
    {
     "expr": "sum by (container,pod,namespace)(kube_pod_container_resource_limits{resource=\"cpu\",namespace!~\"kube-system|twistlock|istio-system|ack-onepilot|arms-prom\",container!~\".*job.*\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "sum by (container,pod,namespace)(kube_pod_container_resource_limits{resource=\"memory\",namespace!~\"kube-system|twistlock|istio-system|ack-onepilot|arms-prom|\",container!~\".*job.*\"})",
     "legendFormat": "Memory Limit"
    }
   ]
  }
 ]
}