{
 "title": "Block Storage-Instance Details Dashboard",
 "tags": [
  "scene:big-data",
  "addon:name:cloud-ebs",
  "addon:version:0.0.2",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:disk-detail"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "disk_id",
    "label": "disk_id",
    "query": {
     "query": "label_values(AliyunDisk_DiskIOPSRead,instanceId)"
    }
   },
   {
    "name": "pair_rep_id",
    "label": "pair_rep_id",
    "query": {
     "query": "label_values(AliyunDisk_async_pair_replication_data_pending,id)"
    }
   },
   {
    "name": "pair_group_id",
    "label": "pair_group_id",
    "query": {
     "query": "label_values(AliyunDisk_async_pair_group_replication_latency,id)"
    }
   },
   {
    "name": "dbsc_id",
    "query": {
     "query": "label_values(AliyunDisk_dbsc_free_storage_capacity,id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cloud disk read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_DiskIOPSRead{id=~\"$disk_id\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Cloud disk write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_DiskIOPSWrite{id=~\"$disk_id\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Cloud disk read BPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_DiskReadBytes{id=~\"$disk_id\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Cloud disk write BPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_DiskWriteBytes{id=~\"$disk_id\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  }
 ]
}