{
 "title": "BlockStorage-Instance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "disk_id",
    "label": "disk_id",
    "query": {
     "query": "label_values(AliyunDisk_DiskIOPSRead{}, id)"
    }
   },
   {
    "name": "pair_rep_id",
    "label": "pair_rep_id",
    "query": {
     "query": "label_values(AliyunDisk_async_pair_replication_data_pending,id)"
    }
   },
   {
    "name": "pair_group_id",
    "label": "pair_group_id",
    "query": {
     "query": "label_values(AliyunDisk_async_pair_group_replication_latency,id)"
    }
   },
   {
    "name": "dbsc_id",
    "query": {
     "query": "label_values(AliyunDisk_dbsc_free_storage_capacity,id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cloud disk read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_DiskIOPSRead{id=~\"$disk_id\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Cloud disk write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_DiskIOPSWrite{id=~\"$disk_id\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Cloud disk write BPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_DiskWriteBytes{id=~\"$disk_id\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Cloud disk read BPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_DiskReadBytes{id=~\"$disk_id\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Asynchronous replication data volume to be replicated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Mib" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_async_pair_replication_data_pending{id=~\"$pair_rep_id\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Asynchronous replication RPO delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_async_pair_replication_latency{id=~\"$pair_rep_id\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Asynchronous replication consistency group data volume to be replicated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_async_pair_group_replication_data_pending{id=~\"$pair_group_id\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Asynchronous replication consistency group RPO delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_async_pair_group_replication_latency{id=~\"$pair_group_id\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Dedicated block storage cluster remaining storage capacity monitoring",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "GiB" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_dbsc_free_storage_capacity",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Dedicated block storage cluster capacity monitoring",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "GiB" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunDisk_dbsc_storage_capacity",
     "legendFormat": "{{instanceId}}"
    }
   ]
  }
 ]
}