{
 "title": "Cloud ASM Istio Gateway Status",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "IstioGateway",
  "ASM",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "evn", "label": "Selecte Env", "query": "dev,dev,sit" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{namespace=\"istio-system\"}, namespace)"
   },
   {
    "name": "deployment",
    "label": "ASM_Gateway_Name",
    "query": "query_result(sum(istio_requests_total{reporter=\"source\",source_workload_namespace='$namespace'}) by (source_app))"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~'$namespace',pod=~\"$deployment-[^-]+-[^-]+$\"} ,pod_name)"
   },
   {
    "name": "podOne",
    "label": "podOne",
    "query": "query_result(kube_pod_info{namespace=~'$namespace',pod =~\"$Pod\",pod=~\"$deployment-[^-]+-[^-]+$\"} >0)"
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "IstioGateway", "type": "text", "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 }, "options": { "content": "# $deployment" } },
  {
   "title": "Pod Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(container_memory_working_set_bytes{pod_name=~\"$Pod\",namespace=\"$namespace\"}) by(pod_name))"
    }
   ]
  },
  {
   "title": "spec_replicas",
   "type": "stat",
   "description": "Number of resource definition copies",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(kube_deployment_spec_replicas{deployment=\"$deployment\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod Mem Used",
   "type": "stat",
   "description": "Current memory working set (working set) usage",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod_name=~\"$Pod\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod memory limit ",
   "type": "stat",
   "description": "The default value is 0 if there is no quota.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_spec_memory_limit_bytes{image!=\"\",pod_name=~\"$Pod\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "description": "Pod memory usage details. Current memory working set (working set) usage, resource-memory resource usage, limit-allocated memory resource quota,",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits_memory_bytes{pod_name=\"$podOne\",namespace=\"$namespace\"})>0",
     "legendFormat": "limit"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{pod_name=\"$podOne\",namespace=\"$namespace\"})>0",
     "legendFormat": "request"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod_name=~\"$Pod\",namespace=\"$namespace\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "description": "Details of pod cpu usage, total amount of pod CPU usage, request-number of cores used by CPU, limit-amount of CPU resources allocated",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits_cpu_cores{pod_name=\"$podOne\",namespace=\"$namespace\"})>0",
     "legendFormat": "limit"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{pod_name=\"$podOne\",namespace=\"$namespace\"})>0",
     "legendFormat": "request"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod_name=~\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "description": "Container Network Received Data Volume-Container Network Transmitted Data Volume",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",pod_name=~\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod_name)",
     "legendFormat": "Received {{pod_name}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",pod_name=~\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod_name)",
     "legendFormat": "Sent {{pod_name}}"
    }
   ]
  }
 ]
}