{
 "title": "Cloud Firewall - Details Dashboard",
 "tags": [
  "dashboard:name:cfw-detail",
  "scene:middleware",
  "env:Cloud",
  "addon:name:cloud-cfw",
  "env:type:Cloud",
  "addon:version:0.0.1",
  "prometheus"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of ACL interceptions at a single IP granularity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetAclBlockByIp{}",
     "legendFormat": "{{userId}}/{{assetIp}}"
    }
   ]
  },
  {
   "title": "Number of ACL interceptions at a single region granularity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetAclBlockByRegion{}",
     "legendFormat": "{{userId}}/{{regionId}}"
    }
   ]
  },
  {
   "title": "Number of ACL interceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetAclBlockByUser{}",
     "legendFormat": "{{userId}}"
    }
   ]
  },
  {
   "title": "Percentage of ACL interceptions at a single IP granularity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetAclBlockPerByIp{}",
     "legendFormat": "{{userId}}/{{assetIp}}"
    }
   ]
  },
  {
   "title": "Percentage of ACL interceptions at a single region granularity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetAclBlockPerByRegion{}",
     "legendFormat": "{{userId}}/{{regionId}}"
    }
   ]
  },
  {
   "title": "Percentage of ACL interceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetAclBlockPerByUser{}",
     "legendFormat": "{{userId}}"
    }
   ]
  },
  {
   "title": "Number of IPS interceptions at a single IP granularity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetIpsBlockByIp{}",
     "legendFormat": "{{userId}}/{{assetIp}}"
    }
   ]
  },
  {
   "title": "Number of IPS interceptions at a single region granularity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetIpsBlockByRegion{}",
     "legendFormat": "{{userId}}/{{regionId}}"
    }
   ]
  },
  {
   "title": "Number of IPS interceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetIpsBlockByUser{}",
     "legendFormat": "{{userId}}"
    }
   ]
  },
  {
   "title": "Percentage of IPS interceptions at a single IP granularity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetIpsBlockPerByIp{}",
     "legendFormat": "{{userId}}/{{assetIp}}"
    }
   ]
  },
  {
   "title": "Percentage of IPS interceptions at a single region granularity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetIpsBlockPerByRegion{}",
     "legendFormat": "{{userId}}/{{regionId}}"
    }
   ]
  },
  {
   "title": "Percentage of IPS interceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetIpsBlockPerByUser{}",
     "legendFormat": "{{userId}}"
    }
   ]
  },
  {
   "title": "Number of new connections at a single IP granularity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetNewConnByIp{}",
     "legendFormat": "{{userId}}/{{assetIp}}"
    }
   ]
  },
  {
   "title": "Number of new connections at a single region granularity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetNewConnByRegion{}",
     "legendFormat": "{{userId}}/{{regionId}}"
    }
   ]
  },
  {
   "title": "Number of new connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetNewConnByUser{}",
     "legendFormat": "{{userId}}"
    }
   ]
  },
  {
   "title": "Percentage of new connections at a single IP granularity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetNewConnPerByIp{}",
     "legendFormat": "{{userId}}/{{assetIp}}"
    }
   ]
  },
  {
   "title": "Percentage of new connections at a single region granularity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetNewConnPerByRegion{}",
     "legendFormat": "{{userId}}/{{assetIp}}"
    }
   ]
  },
  {
   "title": "Percentage of new connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_InternetNewConnPerByUser{}",
     "legendFormat": "{{userId}}"
    }
   ]
  }
 ]
}