{
 "title": "Cloud-native API Gateway - Instance Details Dashboard",
 "tags": [
  "scene:middleware",
  "addon:name:cloud-cnapigateway",
  "addon:version:0.0.2",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:cnapigateway-detail"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instanceName",
    "label": "instanceName",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"cnapigateway\"},instanceName)"
    }
   },
   {
    "name": "instanceId",
    "label": "InstanceId",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"cnapigateway\", instanceName=~\"$instanceName\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Success rate of gateway API requests",
   "type": "timeseries",
   "description": "网关API请求成功率",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyApiSuccessRate{id=~\"$instanceId\"}",
     "legendFormat": "{{apiName}}/{{apiEnv}}/{{apiVersion}}"
    }
   ]
  },
  {
   "title": "Success rate of requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyDownstreamSuccessRate{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average latency of gateway API requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyApiRtAvg{id=~\"$instanceId\"}",
     "legendFormat": "{{apiName}}/{{apiEnv}}/{{apiVersion}}"
    }
   ]
  },
  {
   "title": "Success rate of gateway service requests",
   "type": "timeseries",
   "description": "网关服务请求成功率 Unit:%",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "AliyunCnapigateway_EnvoyClusterSuccessRate{id=\"$instanceId\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Gateway API QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyApiQps{id=~\"$instanceId\"}",
     "legendFormat": "{{apiName}}/{{apiEnv}}/{{apiVersion}}"
    }
   ]
  },
  {
   "title": "Number of connections destroyed per second by gateway clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClientDestroyConnection{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of SSL handshake failures per second by gateway clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClientDestroySSL{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of currently active connections of gateway clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClientActiveConnection{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of SSL handshakes per second by gateway clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClientNewSSL{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of SSL handshakes reused per second by gateway clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClientReuseSSL{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of new connections per second by gateway clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClientNewConnection{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average latency of gateway service requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClusterRtAvg{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Average latency of requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyDownstreamRtAvg{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Gateway service QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyClusterQps{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "QPS (client)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyDownstreamQps{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Disk Write load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyFsWriteBytes{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Gateway CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyCpuUsageRate{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Disk Read load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyFsReadBytes{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Gateway network inbound IO load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyNetworkInBytes{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Gateway memory load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyMemoryUsage{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Memory load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyMemoryUsageRate{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average latency of gateway operation requests",
   "type": "timeseries",
   "description": "网关Operation请求平均时延",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyOperationRtAvg{id=~\"$instanceId\"}",
     "legendFormat": "{{apiName}}/{{apiEnv}}/{{apiVersion}}/{{apiOperation}}"
    }
   ]
  },
  {
   "title": "Gateway network outbound IO load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyNetworkOutBytes{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Gateway Operation QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyOperationQps{id=~\"$instanceId\"}",
     "legendFormat": "{{apiName}}/{{apiEnv}}/{{apiVersion}}/{{apiOperation}}"
    }
   ]
  },
  {
   "title": "Number of API gateway flow limiting requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyRateLimitRequests{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Success rate of gateway operation requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyOperationSuccessRate{id=~\"$instanceId\"}",
     "legendFormat": "{{apiName}}/{{apiEnv}}/{{apiVersion}}/{{apiOperation}}"
    }
   ]
  },
  {
   "title": "Number of gateway plugin crashes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyPluginCrash{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{pluginName}}"
    }
   ]
  },
  {
   "title": "Success rate of gateway routing requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyRouteSuccessRate{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}/{{route}}"
    }
   ]
  },
  {
   "title": "Gateway routing QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyRouteQps{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}/{{route}}"
    }
   ]
  },
  {
   "title": "Gateway routing QPS(2xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 81 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyRouteQps2XX{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}/{{route}}"
    }
   ]
  },
  {
   "title": "Number of current healthy nodes of gateway service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamEndpoints{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Gateway routing QPS(5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 90 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyRouteQps5XX{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}/{{route}}"
    }
   ]
  },
  {
   "title": "Average latency of gateway routing requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyRouteRtAvg{id=~\"$instanceId\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Average latency of backend service requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamRtAvg{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of current active connections of gateway service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 99 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamActiveConnection{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of connections destroyed per second of gateway service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 99 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamDestroyConnection{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Success rate of backend service requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamSuccessRate{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of new connections per second of gateway service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 108 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamNewConnection{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Gateway QPS(upstream)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 108 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCnapigateway_EnvoyUpstreamQps{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  }
 ]
}