{
 "title": "Cloud Firewall-NAT-Details Dashboard",
 "tags": [
  "scene:middleware",
  "env:Cloud",
  "addon:name:cloud-cfw",
  "env:type:Cloud",
  "addon:version:0.0.1",
  "dashboard:name:cfw-nat-detail",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of ACL interceptions at the granularity of a single NAT firewall instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_NatAclBlockByInstanceId{}",
     "legendFormat": "{{userId}}/{{cloudInstanceId}}"
    }
   ]
  },
  {
   "title": "Number of ACL interceptions at the granularity of a single region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_NatAclBlockByRegion{}",
     "legendFormat": "{{userId}}/{{regionId}}"
    }
   ]
  },
  {
   "title": "Number of ACL interceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "cacheDurationSeconds": 300, "expr": "AliyunCfw_NatAclBlockByUser{}", "legendFormat": "{{userId}}" }
   ]
  },
  {
   "title": "Percentage of ACL interceptions at the granularity of a single NAT firewall instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_NatAclBlockPerByInstanceId{}",
     "legendFormat": "{{userId}}/{{cloudInstanceId}}"
    }
   ]
  },
  {
   "title": "Percentage of ACL interceptions at the granularity of a single region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_NatAclBlockPerByRegion{}",
     "legendFormat": "{{userId}}/{{regionId}}"
    }
   ]
  },
  {
   "title": "Percentage of ACL interceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_NatAclBlockPerByUser{}",
     "legendFormat": "{{userId}}"
    }
   ]
  },
  {
   "title": "Number of new connections at the granularity of a single NAT firewall instance.",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_NatNewConnByInstanceId{}",
     "legendFormat": "{{userId}}/{{cloudInstanceId}}"
    }
   ]
  },
  {
   "title": "Number of new connections at the granularity of a single region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    { "cacheDurationSeconds": 300, "expr": "AliyunCfw_NatNewConnByRegion{}", "legendFormat": "{{userId}}/{{regionId}}" }
   ]
  },
  {
   "title": "Number of new connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    { "cacheDurationSeconds": 300, "expr": "AliyunCfw_NatNewConnByUser{}", "legendFormat": "{{userId}}" }
   ]
  },
  {
   "title": "Percentage of new connections at the granularity of a single NAT firewall instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_NatNewConnPerByInstanceId{}",
     "legendFormat": "{{userId}}/{{cloudInstanceId}}"
    }
   ]
  },
  {
   "title": "Percentage of new connections at the granularity of a single region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_NatNewConnPerByRegion{}",
     "legendFormat": "{{userId}}/{{regionId}}"
    }
   ]
  },
  {
   "title": "Percentage of new connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_NatNewConnPerByUser{}",
     "legendFormat": "{{userId}}"
    }
   ]
  }
 ]
}