{
 "title": "CloudFlow Prod",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Functionflow_ExecutionsFailed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AliyunFunctionflow_ExecutionsFailed{} or vector(0)",
     "legendFormat": "{{flowName}}"
    }
   ]
  },
  {
   "title": "Functionflow_ExecutionExecTimeMs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "AliyunFunctionflow_ExecutionExecTimeMs",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Functionflow_ExecutionsStarted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "AliyunFunctionflow_ExecutionsStarted",
     "legendFormat": "{{flowName}}"
    }
   ]
  },
  {
   "title": "Functionflow_ExecutionsSucceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "AliyunFunctionflow_ExecutionsSucceeded",
     "legendFormat": "{{flowName}}"
    }
   ]
  }
 ]
}