{
 "title": "Cloud ASM Istio Tcp Gateway",
 "tags": [
  "integration",
  "ASM",
  "prometheus",
  "tcpgateway"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "asm_gateway_name",
    "label": "ASM_Gateway_Name",
    "query": "query_result(sum(istio_requests_total{reporter=\"source\",source_workload_namespace=\"istio-system\"}) by (source_app))"
   }
  ]
 },
 "panels": [
  {
   "title": "istio_tcp_connections_closed_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (istio)(rate(istio_tcp_connections_closed_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\",}[5m]))"
    }
   ]
  },
  {
   "title": "istio_tcp_connections_opened_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (istio)(rate(istio_tcp_connections_opened_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\",}[5m]))"
    }
   ]
  },
  {
   "title": "Bytes Received from Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"source\",source_app=\"$asm_gateway_name\", source_workload_namespace=\"istio-system\"}[1m])) by (source_workload, source_workload_namespace), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}} "
    }
   ]
  },
  {
   "title": "Bytes Sent to Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_sent_bytes_total{reporter=\"source\", source_app=\"$asm_gateway_name\", source_workload_namespace=\"istio-system\"}[1m])) by (source_workload, source_workload_namespace), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}} "
    }
   ]
  }
 ]
}