{
 "title": "Cloud database MongoDB version - Sharded cluster - Instance details dashboard",
 "tags": [
  "scene:database",
  "dashboard:name:mongodb_sharding-detail",
  "addon:name:cloud-mongodb_sharding",
  "env:Cloud",
  "Group Observation",
  "env:type:Cloud",
  "Instance Observation",
  "prometheus",
  "addon:version:0.0.5"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instanceId",
    "label": "InstanceId",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"mongodb_sharding\"}, id)"
    }
   },
   {
    "name": "instanceName",
    "label": "InstanceName",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"mongodb_sharding\"}, instanceName)"
    }
   },
   {
    "name": "groupId",
    "label": "Application Group ID",
    "query": {
     "query": "label_values(AliyunMongodb_sharding_GroupShardingCPUUtilization{},groupId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Application group dimension observation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Application group CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_GroupShardingCPUUtilization{groupId=~\"$groupId\"}",
     "legendFormat": "{{groupId}}"
    }
   ]
  },
  {
   "title": "Application group memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_GroupShardingMemoryUtilization{groupId=~\"$groupId\"}",
     "legendFormat": "{{groupId}}"
    }
   ]
  },
  {
   "title": "Application group connection usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_GroupShardingConnectionUtilization{groupId=~\"$groupId\"}",
     "legendFormat": "{{groupId}}"
    }
   ]
  },
  {
   "title": "Application group IOPS usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_GroupShardingIOPSUtilization{groupId=~\"$groupId\"}",
     "legendFormat": "{{groupId}}"
    }
   ]
  },
  {
   "title": "Application group disk usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_GroupShardingDiskUtilization{groupId=~\"$groupId\"}",
     "legendFormat": "{{groupId}}"
    }
   ]
  },
  { "title": "Instance dimension observation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Instance list",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "cloud_monitor_instance_info{service=\"mongodb_sharding\",instanceId=~\"$instanceId\",instanceName=~\"$instanceName\"}"
    }
   ]
  },
  {
   "title": "Connection usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingConnectionAmount{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Connection usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingConnectionUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingCPUUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Original disk configuration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingDataDiskAmountOriginal{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingDiskUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Data disk space occupied",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingDataDiskAmount{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Occupied disk space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingInstanceDiskAmount{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Network inbound traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingIntranetIn{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "IOPS usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingIOPSUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Disk space occupied by logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingLogDiskAmount{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingMemoryUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Network outbound traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingIntranetOut{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Command operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 65 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingOpCommand{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Delete operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 65 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingOpDelete{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 65 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingNumberRequests{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Insert operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 74 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingOpInsert{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Query operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 74 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingOpQuery{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Getmore operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 74 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingOpGetmore{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Oplog retention time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 83 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingOplogTimeInterval{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 83 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingQPS{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Update operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 83 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingOpUpdate{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  },
  {
   "title": "Replication delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 92 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_sharding_ShardingReplicationLag{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{subinstanceId}}/{{role}}"
    }
   ]
  }
 ]
}