{
 "title": "Cloud ASM Istio Http Gateway",
 "tags": [
  "integration",
  "ASM",
  "prometheus",
  "httpgateway"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "asm_gateway_name",
    "label": "ASM_Gateway_Name",
    "query": {
     "query": "query_result(sum(istio_requests_total{reporter=\"source\",source_workload_namespace=\"istio-system\"}) by (source_app))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (istio)(rate(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\"}[5m]))",
     "legendFormat": "5min"
    },
    {
     "expr": "sum by (istio)(rate(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\"}[1m]))",
     "legendFormat": "1min"
    },
    {
     "expr": "sum by (istio)(rate(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\"}[30s]))",
     "legendFormat": "30s"
    }
   ]
  },
  {
   "title": "Response Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (response_code)(rate(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\"}[5m]))",
     "legendFormat": "response_code={{response_code}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-sysytem\",source_app=\"$asm_gateway_name\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_app}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app, source_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app, source_workload_namespace, le))",
     "legendFormat": "{{source_app}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app, source_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app, source_workload_namespace, le))",
     "legendFormat": "{{source_app}}.{{source_workload_namespace}} P95 "
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app, source_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app, source_workload_namespace, le))",
     "legendFormat": "{{source_app}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app, source_workload_namespace, le))",
     "legendFormat": "{{ source_app }}.{{ source_workload_namespace }} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app, source_workload_namespace, le))",
     "legendFormat": "{{ source_app }}.{{ source_workload_namespace }} P90 "
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app, source_workload_namespace, le))",
     "legendFormat": "{{ source_app }}.{{ source_workload_namespace }} P95 "
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app, source_workload_namespace, le))",
     "legendFormat": "{{ source_app }}.{{ source_workload_namespace }} P99 "
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app,source_workload_namespace,le))",
     "legendFormat": "{{source_app}}.{{source_workload_namespace}}P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app,source_workload_namespace,le))",
     "legendFormat": "{{ source_app }}.{{ source_workload_namespace }} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app,source_workload_namespace,le))",
     "legendFormat": "{{ source_app }}.{{ source_workload_namespace }} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[1m])) by (source_app,source_workload_namespace,le))",
     "legendFormat": "{{ source_app}}.{{ source_workload_namespace }} P99 "
    }
   ]
  }
 ]
}