{
 "title": "Cloud Firewall-VPC-Details Dashboard",
 "tags": [
  "scene:middleware",
  "env:Cloud",
  "addon:name:cloud-cfw",
  "env:type:Cloud",
  "addon:version:0.0.1",
  "dashboard:name:cfw-vpc-detail",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of ACL interceptions at the granularity of a single VPC firewall instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "cacheDurationSeconds": 300, "expr": "AliyunCfw_VpcAclBlockByCen{}", "legendFormat": "{{userId}}/{{firewallId}}" }
   ]
  },
  {
   "title": "Number of ACL interceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "cacheDurationSeconds": 300, "expr": "AliyunCfw_VpcAclBlockByUser{}", "legendFormat": "{{userId}}" }
   ]
  },
  {
   "title": "Number of ACL interceptions at the granularity of source-destination VPC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_VpcAclBlockByVpcPeer{}",
     "legendFormat": "{{userId}}/{{vpcIdPeer}}"
    }
   ]
  },
  {
   "title": "Percentage of ACL interceptions at the granularity of a single VPC firewall instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_VpcAclBlockPerByCen{}",
     "legendFormat": "{{userId}}/{{firewallId}}"
    }
   ]
  },
  {
   "title": "Percentage of ACL interceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_VpcAclBlockPerByUser{}",
     "legendFormat": "{{userId}}"
    }
   ]
  },
  {
   "title": "Percentage of ACL interceptions at the granularity of source-destination VPC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_VpcAclBlockPerByVpcPeer{}",
     "legendFormat": "{{userId}}/{{vpcIdPeer}}"
    }
   ]
  },
  {
   "title": "Number of IPS interceptions at the granularity of a single VPC firewall instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    { "cacheDurationSeconds": 300, "expr": "AliyunCfw_VpcIpsBlockByCen{}", "legendFormat": "{{userId}}/{{firewallId}}" }
   ]
  },
  {
   "title": "Number of IPS interceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    { "cacheDurationSeconds": 300, "expr": "AliyunCfw_VpcIpsBlockByUser{}", "legendFormat": "{{userId}}" }
   ]
  },
  {
   "title": "Number of IPS interceptions at the granularity of source-destination VPC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_VpcIpsBlockByVpcPeer{}",
     "legendFormat": "{{userId}}/{{vpcIdPeer}}"
    }
   ]
  },
  {
   "title": "Percentage of IPS interceptions at the granularity of source-destination VPC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_VpcIpsBlockPerByCen{}",
     "legendFormat": "{{userId}}/{{firewallId}}"
    }
   ]
  },
  {
   "title": "Percentage of IPS interceptions at the granularity of single VPC firewall instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_VpcIpsBlockPerByUser{}",
     "legendFormat": "{{userId}}"
    }
   ]
  },
  {
   "title": "Percentage of IPS interceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_VpcIpsBlockPerByVpcPeer{}",
     "legendFormat": "{{userId}}/{{vpcIdPeer}}"
    }
   ]
  },
  {
   "title": "Percentage of IPS interceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "cacheDurationSeconds": 300, "expr": "AliyunCfw_VpcNewConnByCen{}", "legendFormat": "{{userId}}/{{firewallId}}" }
   ]
  },
  {
   "title": "Percentage of IPS interceptions at the granularity of source-destination VPC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    { "cacheDurationSeconds": 300, "expr": "AliyunCfw_VpcNewConnByUser{}", "legendFormat": "{{userId}}" }
   ]
  },
  {
   "title": "Number of new connections at the granularity of a single VPC firewall instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_VpcNewConnByVpcPeer{}",
     "legendFormat": "{{userId}}/{{vpcIdPeer}}"
    }
   ]
  },
  {
   "title": "Number of new connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "cacheDurationSeconds": 300, "expr": "AliyunCfw_VpcNewConnPerByCen{}", "legendFormat": "{{userId}}/{{firewallId}}" }
   ]
  },
  {
   "title": "Number of new connections at the granularity of source-destination VPC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_VpcNewConnPerByUser{}",
     "legendFormat": "{{userId}}"
    }
   ]
  },
  {
   "title": "Percentage of new connections at the granularity of single VPC firewall instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunCfw_VpcNewConnPerByVpcPeer{}",
     "legendFormat": "{{userId}}/{{vpcIdPeer}}"
    }
   ]
  }
 ]
}