{
 "title": "CMS-NAS",
 "description": "NAS",
 "tags": [
  "dashboard:name:cms-nas",
  "nas",
  "addon:name:cloud-nas",
  "scene:middleware",
  "cmee",
  "env:Cloud",
  "env:type:Cloud",
  "addon:version:0.0.2",
  "prometheus"
 ],
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "query": "label_values(AliyunNas_AlignedSize, regionId)"
   },
   {
    "name": "description",
    "query": "label_values(AliyunNas_AlignedSize{regionId=~\"$regionId\"}, description)"
   },
   {
    "name": "fileSystemId",
    "query": "label_values(AliyunNas_AlignedSize{regionId=~\"$regionId\" ,description=~\"$description\"},fileSystemId)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "IOPS Read",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "AliyunNas_IopsRead{description=~\"$description\",fileSystemId=~\"$fileSystemId\"}",
     "legendFormat": "{{fileSystemId}}/{{description}}"
    }
   ]
  },
  {
   "title": "IOPS Write",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "AliyunNas_IopsWrite{description=~\"$description\",fileSystemId=~\"$fileSystemId\"}",
     "legendFormat": "{{fileSystemId}}/{{description}}"
    }
   ]
  },
  {
   "title": "Latency Read",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "AliyunNas_LatencyRead{description=~\"$description\",fileSystemId=~\"$fileSystemId\"}",
     "legendFormat": "{{fileSystemId}}/{{description}}"
    }
   ]
  },
  {
   "title": "Latency Write",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "AliyunNas_LatencyWrite{description=~\"$description\",fileSystemId=~\"$fileSystemId\"}",
     "legendFormat": "{{fileSystemId}}/{{description}}"
    }
   ]
  },
  {
   "title": "Throughput Read",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "AliyunNas_ThruputRead{description=~\"$description\",fileSystemId=~\"$fileSystemId\"}",
     "legendFormat": "{{fileSystemId}}/{{description}}"
    }
   ]
  },
  {
   "title": "Throughput Write",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "AliyunNas_ThruputWrite{description=~\"$description\",fileSystemId=~\"$fileSystemId\"}",
     "legendFormat": "{{fileSystemId}}/{{description}}"
    }
   ]
  },
  {
   "title": "General NAS Data Volume",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "AliyunNas_AlignedSize{description=~\"$description\",fileSystemId=~\"$fileSystemId\"}",
     "legendFormat": "{{fileSystemId}}/{{description}}"
    }
   ]
  },
  {
   "title": "Low-Frequency Media Data Volume",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "AliyunNas_SecondaryAlignedSize{description=~\"$description\",fileSystemId=~\"$fileSystemId\"}",
     "legendFormat": "{{fileSystemId}}/{{description}}"
    }
   ]
  },
  {
   "title": "Low-Frequency Media Read Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "AliyunNas_OfflineReadQuantity{description=~\"$description\",fileSystemId=~\"$fileSystemId\"}",
     "legendFormat": "{{fileSystemId}}/{{description}}"
    }
   ]
  },
  {
   "title": "Low-Frequency Media Write Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNas_OfflineWriteQuantity{description=~\"$description\",fileSystemId=~\"$fileSystemId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{fileSystemId}}/{{description}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of Files",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "AliyunNas_FileCount{description=~\"$description\",fileSystemId=~\"$fileSystemId\"}",
     "legendFormat": "{{fileSystemId}}/{{description}}"
    }
   ]
  },
  {
   "title": "Metadata QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "AliyunNas_QpsMeta{description=~\"$description\",fileSystemId=~\"$fileSystemId\"}",
     "legendFormat": "{{fileSystemId}}/{{description}}"
    }
   ]
  }
 ]
}