{
 "title": "CS Cost Node Pool",
 "tags": [ "prometheus" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Selecte Env", "query": "nprod,uat,dev,sit" },
   { "name": "datasource_ack", "label": "datasource", "query": "prometheus" },
   {
    "name": "cost_measure",
    "label": "Actual/original bill",
    "query": "pretax_amount : pretax_amount,pretax_gross_amount : pretax_gross_amount"
   },
   {
    "name": "NodePoolId",
    "label": "Node Pool ID(NodePoolID)",
    "query": {
     "query": "query_result( sum(count_over_time($cost_measure{}[2d])) by (node_pool_id) )"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node spent yesterday",
   "type": "stat",
   "description": "This is original billing price without discount of this NodePool.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "abs(sum(max($cost_measure{node_pool_id=~\"$NodePoolId\", product_code=\"ecs\"}) by (product_code, instance_id))) "
    }
   ]
  },
  {
   "title": "Node Pool Node Spending Day Ring Ratio",
   "type": "stat",
   "description": "if there is \"No data\", please wait for at least two days's data.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "abs((sum(max($cost_measure{node_pool_id=~\"$NodePoolId\", product_code=\"ecs\"} offset 1d) by (product_code, instance_id)) - abs(sum(max($cost_measure{node_pool_id=~\"$NodePoolId\", product_code=\"ecs\"} offset 2d) by (product_code, instance_id))))) / abs(sum(max($cost_measure{node_pool_id=~\"$NodePoolId\", product_code=\"ecs\"} offset 2d) by (product_code, instance_id)))"
    }
   ]
  },
  {
   "title": "Unit price per core of the cluster",
   "type": "graph",
   "description": "The \"Pod Cost Per Core\" is estimated by compute resource of the cluster. Which is calculated by:\n \nΣ(Pod Request/Node Capacity)*EachNodePrice / Node Price\n\nWarning:\n1. This is a estimate data by compute resource.\n2. If there is \"No Data\", please wait for at least one hour.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "$/Core*Hour" }
   ],
   "targets": [
    {
     "expr": "((sum(sum(node_current_price / on (node) group_left max(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"})by(node)) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})) / sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})) * 3600",
     "legendFormat": "Unit nuclear hour price per hour"
    }
   ]
  },
  {
   "title": "Node pool node spend as a percentage of total cluster cost",
   "type": "stat",
   "description": "This billing data is related to the cluster. This is original compute resource billing price without discount.\n\nCost Ratio = This NodePool Cost / This Cluster Cost",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "abs(sum(max($cost_measure{node_pool_id=~\"$NodePoolId\", product_code=\"ecs\"}) by (product_code, instance_id))) \n/ \nabs(sum(max($cost_measure{}) by (product_code, instance_id))) "
    }
   ]
  },
  {
   "title": "Node Unit Core Time Price-Overall Cluster",
   "type": "stat",
   "description": "The \"Pod Cost Per Core\" is estimated by compute resource of this cluster. Which is calculated by:\n \nΣ(Pod Request/Node Capacity)*EachNodePrice / Node Price\n\nWarning:\n1. This is a estimate data by compute resource.\n2. If there is \"No Data\", please wait for at least one hour.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "$/ Core*Hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(sum(node_current_price / on (node) group_left max(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"})by(node)) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})) / sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})) * 3600",
     "legendFormat": "$Namespace"
    }
   ]
  },
  {
   "title": "Node Pool Cost Change Trend",
   "type": "graph",
   "description": "This billing data is related to the cluster. This is original compute resource billing price without discount.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "$/ day" } },
   "yaxes": [
    { "format": "$/ day" }
   ],
   "targets": [
    {
     "expr": "abs(sum(max($cost_measure{node_pool_id=~\"$NodePoolId\", product_code=\"ecs\"}) by (product_code, instance_id)))",
     "legendFormat": "[Node Pool ID]: $NodePoolId"
    }
   ]
  },
  {
   "title": "Trend of node pool node cost as a percentage of total cluster cost",
   "type": "graph",
   "description": "This billing data is related to the cluster. This is original compute resource billing price without discount.\n\nCost Ratio = This NodePool Cost / This Cluster Cost\n\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "abs(sum(max($cost_measure{node_pool_id=~\"$NodePoolId\", product_code=\"ecs\"}) by (product_code, instance_id))) \n/ \nabs(sum(max($cost_measure{}) by (product_code, instance_id))) ",
     "legendFormat": "[Node Pool ID]: $NodePoolId"
    }
   ]
  },
  {
   "title": "Change Trend of Number of Node Instances with Different Billing Policies",
   "type": "graph",
   "description": "This billing data is related to the cluster. This is original compute resource billing price without discount.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(node_current_price{chargeType != \"\"}) by (chargeType)",
     "legendFormat": "{{chargeType}}"
    }
   ]
  },
  {
   "title": "Cost Trend of Node Instances with Different Payment Policies-Original Price Billing Cost",
   "type": "graph",
   "description": "This billing data is related to the cluster. This is original compute resource billing price without discount.\n\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "$/ Hour" }
   ],
   "targets": [
    {
     "expr": "sum(node_current_price{chargeType != \"\"}) by (chargeType) * 3600",
     "legendFormat": "{{chargeType}}"
    }
   ]
  },
  {
   "title": "Forecast nodes are all pay-as-you-go expenses.",
   "type": "stat",
   "description": "Estimated Cost for Pay-As-You-Go Policy Node\n\nThis billing data is related to the cluster. This is original compute resource billing price without discount.\n\nThis cost is without discount.\n\nThis is a forecasting increase cost when your cluster all replace to PayAsYouGo charge type.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "$/ Hour" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(node_payAsYouGo_price) - sum(node_current_price{})) * 3600) > 0",
     "legendFormat": "Excess:"
    },
    {
     "expr": "((sum(node_payAsYouGo_price) - sum(node_current_price{})) * 3600) <= 0",
     "legendFormat": "Savings:"
    }
   ]
  },
  {
   "title": "Forecast nodes are all annual and monthly expenses.",
   "type": "stat",
   "description": "Forecast nodes are all annual and monthly expenses.\nThis billing data is related to the cluster. This is original compute resource billing price without discount.\n\nThis cost is without discount.\n\nThis is a forecasting increase cost when your cluster all replace to PayByPeriod (one year) charge type.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "$/ Hour" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(node_payByPeriod_price) - sum(node_current_price{})) * 3600) > 0",
     "legendFormat": "超额："
    },
    {
     "expr": "((sum(node_payByPeriod_price) - sum(node_current_price{})) * 3600) <= 0",
     "legendFormat": "节省："
    }
   ]
  },
  {
   "title": "Forecast nodes are all Spot Spending",
   "type": "stat",
   "description": "Forecast nodes are all Spot Spending\n\nThis billing data is related to the cluster. This is original compute resource billing price without discount.\n\nThis cost is without discount.\n\nThis is a forecasting increase cost when your cluster all replace to Spot charge type.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "$/ Hour" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(node_spot_price) - sum(node_current_price{})) * 3600) > 0",
     "legendFormat": "超额："
    },
    {
     "expr": "((sum(node_spot_price) - sum(node_current_price{})) * 3600) <= 0",
     "legendFormat": "节省："
    }
   ]
  },
  {
   "title": "Overall node payment policy statistics-original price bill cost",
   "type": "piechart",
   "description": "Different Charge Type's cost distribution of this cluster, count by dashboard time range.",
   "gridPos": { "h": 10, "w": 4, "x": 9, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_current_price{chargeType != \"\"}) by (chargeType) * 3600",
     "legendFormat": "{{chargeType}}"
    }
   ]
  },
  {
   "title": "Statistics on the number of instances with different payment policies for the overall cluster node",
   "type": "piechart",
   "description": "Different Charge Type's cost distribution of this cluster, count by dashboard time range.",
   "gridPos": { "h": 10, "w": 4, "x": 13, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_current_price{chargeType != \"\"}) by (chargeType)",
     "legendFormat": "{{chargeType}}"
    }
   ]
  },
  {
   "title": "Hourly cost/payment policy statistics of the node-original price bill cost",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "$/ day" } },
   "yaxes": [
    { "format": "$/ day" }
   ],
   "targets": [
    {
     "expr": "sum(node_current_price{chargeType != \"\"}) by (chargeType, node) * 3600",
     "legendFormat": "[node] :{{ node}}-[billing policy] :{{ chargeType}}"
    }
   ]
  },
  {
   "title": "Forecast nodes are all pay-as-you-go expenses.",
   "type": "stat",
   "description": "Estimated cost savings for pay-as-you-go strategy nodes\n\nThis billing data is related to the cluster. This is original compute resource billing price without discount.\n\nThis cost is without discount.\n\nThis is a forecasting increase cost rate when your cluster all replace to PayAsYouGo charge type.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(node_payAsYouGo_price) - sum(node_current_price)) / sum(node_current_price)) > 0",
     "legendFormat": "Excess:"
    },
    {
     "expr": "((sum(node_payAsYouGo_price) - sum(node_current_price)) / sum(node_current_price)) <= 0",
     "legendFormat": "Savings:"
    }
   ]
  },
  {
   "title": "Forecast nodes are all annual and monthly expenses.",
   "type": "stat",
   "description": "Forecast nodes are all annual and monthly expenses.\n\nThis billing data is related to the cluster. This is original compute resource billing price without discount.\n\nThis cost is without discount.\n\nThis is a forecasting increase cost rate when your cluster all replace to PayByPeriod (one year) charge type.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(node_payByPeriod_price) - sum(node_current_price{})) / sum(node_current_price)) > 0",
     "legendFormat": "Excess:"
    },
    {
     "expr": "((sum(node_payByPeriod_price) - sum(node_current_price{})) / sum(node_current_price)) <= 0",
     "legendFormat": "Savings:"
    }
   ]
  },
  {
   "title": "Forecast nodes are all Spot Spending",
   "type": "stat",
   "description": "Forecast nodes are all Spot Spending\n\nThis billing data is related to the cluster. This is original compute resource billing price without discount.\n\nThis cost is without discount.\n\nThis is a forecasting increase cost rate when your cluster all replace to Spot charge type.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(node_spot_price) - sum(node_current_price{})) / sum(node_current_price{})) > 0",
     "legendFormat": "Excess:"
    },
    {
     "expr": "((sum(node_spot_price) - sum(node_current_price{})) / sum(node_current_price{})) <= 0",
     "legendFormat": "Savings:"
    }
   ]
  },
  {
   "title": "Estimated cost of different payment policies for daily node pool nodes-original bill cost",
   "type": "graph",
   "description": "This billing data is related to the cluster. This is original compute resource billing price without discount.\n\nThis cost is without discount.\n\nThis is a forecasting cost when your cluster all replace to PayAsYouGo / PayByPeriod (one year) / Spot charge type.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "$/ day" } },
   "yaxes": [
    { "format": "$/ day" }
   ],
   "targets": [
    {
     "expr": "sum(node_current_price{chargeType != \"\"}) * 3600",
     "legendFormat": "Current expenses"
    },
    {
     "expr": "sum(node_payAsYouGo_price) * 3600",
     "legendFormat": "Estimated as Pay-As-You-Go strategy (PayAsYouGo)"
    },
    {
     "expr": "sum(node_payByPeriod_price) * 3600",
     "legendFormat": "Estimated as package year and package month strategy (PayByPeriod)"
    },
    {
     "expr": "sum(node_spot_price) * 3600",
     "legendFormat": "Estimated as Preemptive Instance Policy (Spot)"
    }
   ]
  }
 ]
}