{
 "title": "CS Cost Namespace",
 "tags": [ "prometheus" ],
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace (Namespace)",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "cost_allocation_method",
    "label": "cost allocation model",
    "query": "CPU模型 : 1, 内存模型 : 0, CPU-内存混合模型（推荐权重） : -10000, CPU-内存混合模型（自定义权重） : -1"
   },
   { "name": "CPUWeight", "label": "CPU Weight Setting (%)", "query": "100" },
   {
    "name": "cost_measure",
    "label": "Actual/original bill",
    "query": "优惠后实际账单成本 : pretax_amount,原价账单成本 : pretax_gross_amount"
   }
  ]
 },
 "panels": [
  {
   "title": "Current CPU Weight",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "scalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"})+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"})))\n",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Current Memory Weight",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "scalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"})+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"})))",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "CPU resource usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum (rate (container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[1m])) by (node) * on(node) max(kube_node_labels{}) by (node))",
     "legendFormat": "CPU Resource Usage (Usage):"
    },
    {
     "expr": "sum(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}) by (node) * on(node) max(kube_node_labels{}) by (node))",
     "legendFormat": "CPU resource request:"
    },
    {
     "expr": "sum(sum(machine_cpu_cores) by (node) * on(node) max(kube_node_labels{}) by (node))",
     "legendFormat": "Total CPU resources (Capacity):"
    },
    {
     "expr": "sum(sum (rate (container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[2m])) by (node) * on(node) max(kube_node_labels{}) by (node))\n\n/\n\nsum(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}) by (node) * on(node) max(kube_node_labels{}) by (node))",
     "legendFormat": "CPU resource usage (Usage / Request):"
    }
   ]
  },
  {
   "title": "Memory resource usage",
   "type": "stat",
   "description": "This metric is memory working set, which is cluster scheduler relay on.\n",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "GiB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(container_memory_working_set_bytes{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}) by (node) * on(node) max(kube_node_labels{}) by (node)) / 1024 / 1024 / 1024",
     "legendFormat": "Memory resource usage:"
    },
    {
     "expr": "sum(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}) by (node) * on(node) max(kube_node_labels{}) by (node)) / 1024 / 1024 / 1024",
     "legendFormat": "Memory resource request (Request):"
    },
    {
     "expr": "sum(sum(machine_memory_bytes) by (node) * on(node) max(kube_node_labels{}) by (node)) / 1024 / 1024 / 1024",
     "legendFormat": "Total memory resource capacity (Capacity):"
    },
    {
     "expr": "sum(sum(container_memory_working_set_bytes{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}) by (node) * on(node) max(kube_node_labels{}) by (node))\n\n/ \n\nsum(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}) by (node) * on(node) max(kube_node_labels{}) by (node))",
     "legendFormat": "Memory Resource Utilization (Usage / Request):"
    }
   ]
  },
  {
   "title": "GPU Resource Usage",
   "type": "stat",
   "description": "This metric is GPU Memory with ACK GPU-Exporter V2, which is cluster scheduler relay on.\n",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum(floor(max_over_time(DCGM_CUSTOM_PROCESS_MEM_USED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,NamespaceName))",
     "legendFormat": "GPU memory resource usage (Usage):"
    },
    {
     "expr": "sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,NamespaceName))",
     "legendFormat": "GPU memory resource allocation (Usage):"
    },
    {
     "expr": "sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,NamespaceName) \n/ on(NodeName, NamespaceName) sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s]))) by (NodeName,NamespaceName) \n* on(NodeName) group_left \nsum(sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (gpu, NodeName)) by (NodeName))",
     "legendFormat": "Total GPU memory resource capacity (Capacity):"
    },
    {
     "expr": "sum(sum(floor(max_over_time(DCGM_CUSTOM_PROCESS_MEM_USED{}[29s]))) by (NodeName,NamespaceName) \n/ on(NodeName) group_left \nsum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s]))) by (NodeName,NamespaceName) )",
     "legendFormat": "GPU memory resource utilization (Pod Used / Pod Allocated):"
    }
   ]
  },
  {
   "title": "Namespace Real-time Cost Estimation",
   "type": "stat",
   "description": "The \"Namespace Cost\" is estimated by compute resource. Which is calculated by:\n\nΣ(Pod Request/Node Capacity)*EachNodePrice\n\nWarning:\n1. This is a estimate data by compute resource.\n2. If there is \"No Data\", please wait for at least one hour.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\n\n#由于某些namespace可能没有配cpu或内存request，保证结果展示全量的namespace\nmax(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 \n\n#cpu分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"cpu\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by (namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n* \n\n#cpu权重\nscalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#内存分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"memory\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n#内存权重\n*\nscalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#ECI成本\n+ on(namespace) group_left\nsum(max(label_replace(pod_current_price, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\")) by (exported_pod, namespace) or max(kube_namespace_labels{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n# GPU节点\n+ on(namespace) group_left\nsum(max(node_current_price) by (node) * on (node) group_right label_replace(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName)) by (NodeName, NamespaceName), \"node\", \"$1\", \"NodeName\", \"(.*)\"), \"namespace\", \"$1\", \"NamespaceName\", \"(.*)\") * on(node) group_left kube_node_labels{label_aliyun_accelerator_nvidia_name!=\"\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n)",
     "legendFormat": "Total cost (original bill cost):"
    }
   ]
  },
  {
   "title": "Namespace Cost Allocation-$cost_measure",
   "type": "stat",
   "description": "The \"Namespace Cost\" is estimated by compute resource. Which is calculated by:\n\nΣ(Pod Request/Node Capacity)*EachNodePrice\n\nWarning:\n1. This is a estimate data by compute resource.\n2. If there is \"No Data\", please wait for at least one hour.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\n\n#由于某些namespace可能没有配cpu或内存request，保证结果展示全量的namespace\nmax(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 \n\n#cpu分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"cpu\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by (namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n* \n\n#cpu权重\nscalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#内存分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"memory\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n#内存权重\n*\nscalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#ECI成本\n+ on(namespace) group_left\nsum(max(label_replace(pod_current_price, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\")) by (exported_pod, namespace) or max(kube_namespace_labels{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n# GPU节点\n+ on(namespace) group_left\nsum(max(node_current_price) by (node) * on (node) group_right label_replace(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName)) by (NodeName, NamespaceName), \"node\", \"$1\", \"NodeName\", \"(.*)\"), \"namespace\", \"$1\", \"NamespaceName\", \"(.*)\") * on(node) group_left kube_node_labels{label_aliyun_accelerator_nvidia_name!=\"\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n)\n/\nscalar(\n sum(node_current_price or pod_current_price) * ($__interval_ms/1000)\n)\n*\nscalar(abs(sum(max(sum($cost_measure)) by (product_code, instance_id)) ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Price per core-hour",
   "type": "graph",
   "description": "The \"Pod Cost Per Core\" is estimated by compute resource. Which is calculated by:\n \nΣ(Pod Request/Node Capacity)*EachNodePrice / Node Price\n\nWarning:\n1. This is a estimate data by compute resource.\n2. If there is \"No Data\", please wait for at least one hour.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "$/Core*Hour" }
   ],
   "targets": [
    {
     "expr": "sum(\n((sum(sum(node_current_price{chargeType!=\"IDC\"} / on (node) group_left max(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node)) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"})) / sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"})) * 3600\nor\nsum(pod_current_price{exported_namespace=~\"$Namespace\"}) / sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}) * 3600\n)",
     "legendFormat": "ECS/ECI"
    },
    {
     "expr": "((sum(sum(node_current_price{chargeType=\"IDC\"} / on (node) group_left max(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node)) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"})) / sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"})) * 3600",
     "legendFormat": "IDC"
    }
   ]
  },
  {
   "title": "CPU/Memory Resource Usage Trend",
   "type": "graph",
   "description": "CPU Usage / CPU Request.\n\nIf this Utilization is too low, may be your app is idle.\n\nIf this Utilization > 100%, your app is oversold.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum (rate (container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[2m])) / (sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) )) > 0 or vector(0)",
     "legendFormat": "CPU Utilization (Usage / Request)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}) / sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) ",
     "legendFormat": "Memory Utilization (Usage / Request)"
    }
   ]
  },
  {
   "title": "CPU resource request/usage trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[1m])) ",
     "legendFormat": "CPUUsage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"})",
     "legendFormat": "CPURequest"
    }
   ]
  },
  {
   "title": "Memory resource request/usage trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "GiB" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}) / 1024 / 1024 / 1024",
     "legendFormat": "MemoryUsage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}) / 1024 / 1024 / 1024",
     "legendFormat": "MemoryRequest"
    }
   ]
  },
  {
   "title": "GPU memory resource request/usage trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(floor(max_over_time(DCGM_CUSTOM_PROCESS_MEM_USED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,NamespaceName)",
     "legendFormat": "GPUMemoryUsed"
    },
    {
     "expr": "sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,NamespaceName)",
     "legendFormat": "GPUMemoryAllocated"
    }
   ]
  },
  {
   "title": "Namespace Estimated Cost Trend-Original Bill Cost",
   "type": "graph",
   "description": "The \"Namespace Cost Trend\" is estimated by compute resource. Which is calculated by:\n \nΣ(Pod Request/Node Capacity)*EachNodePrice\n\nWarning:\n1. This is a estimate data by compute resource.\n2. If there is \"No Data\", please wait for at least 10 minutes.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "$/Day" } },
   "targets": [
    {
     "expr": "sum(\n\n#由于某些namespace可能没有配cpu或内存request，保证结果展示全量的namespace\nmax(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 \n\n#cpu分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"cpu\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by (namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n* \n\n#cpu权重\nscalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#内存分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"memory\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n#内存权重\n*\nscalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#ECI成本\n+ on(namespace) group_left\nsum(max(label_replace(pod_current_price, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\")) by (exported_pod, namespace) or max(kube_namespace_labels{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n# GPU节点\n+ on(namespace) group_left\nsum(max(node_current_price) by (node) * on (node) group_right label_replace(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName)) by (NodeName, NamespaceName), \"node\", \"$1\", \"NodeName\", \"(.*)\"), \"namespace\", \"$1\", \"NamespaceName\", \"(.*)\") * on(node) group_left kube_node_labels{label_aliyun_accelerator_nvidia_name!=\"\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Trend in the proportion of cluster total costs attributable to this namespace",
   "type": "graph",
   "description": "The \"Namespace Cost Trend\" is estimated by compute resource. Which is calculated by:\n\nΣ(Pod Request/Node Capacity)*EachNodePrice / ALL Node Cost\n\nWarning:\n1. This is a estimate data by compute resource.\n2. If there is \"No Data\", please wait for at least 10 minutes.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n\n#由于某些namespace可能没有配cpu或内存request，保证结果展示全量的namespace\nmax(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 \n\n#cpu分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"cpu\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by (namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n* \n\n#cpu权重\nscalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#内存分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"memory\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n#内存权重\n*\nscalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#ECI成本\n+ on(namespace) group_left\nsum(max(label_replace(pod_current_price, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\")) by (exported_pod, namespace) or max(kube_namespace_labels{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n# GPU节点\n+ on(namespace) group_left\nsum(max(node_current_price) by (node) * on (node) group_right label_replace(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName)) by (NodeName, NamespaceName), \"node\", \"$1\", \"NodeName\", \"(.*)\"), \"namespace\", \"$1\", \"NamespaceName\", \"(.*)\") * on(node) group_left kube_node_labels{label_aliyun_accelerator_nvidia_name!=\"\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n)\n\n/\n\nsum(\nsum(node_current_price) by (pod, namespace) * ($__interval_ms/1000)\n\nor\nsum(max(pod_current_price{}) by (exported_pod, exported_namespace)) * ($__interval_ms/1000)\n)\n",
     "legendFormat": "[Namespace]: $Namespace"
    }
   ]
  },
  {
   "title": "Pod resource request volume ranking",
   "type": "table",
   "description": "Sorted by CPU Request.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(max(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) > 0",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(max(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) > 0",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(label_replace(label_replace(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s]))) by (NodeName,PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\"), \"node\", \"$1\", \"NodeName\", \"(.*)\")) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Resource Usage Ranking-Sorted by CPU Usage",
   "type": "table",
   "description": "Sorted by CPU Usage.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(max(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[2m])) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(max(container_memory_working_set_bytes{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(max(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[1m])) by (pod, container)) by (pod) / sum(max(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} > 0) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(max(container_memory_working_set_bytes{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}) by (pod, container)) by (pod) / sum(max(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} > 0) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(\n \nlabel_replace(label_replace(sum(floor(max_over_time(DCGM_CUSTOM_PROCESS_MEM_USED{}[29s]))) by (NodeName,PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\"), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n* on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) \n\n/ on(node) group_left \n\nlabel_replace(sum(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s])) by (NodeName), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n) by (node, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod resource idle ranking",
   "type": "table",
   "description": "Sort by WasteRate.\nWasteRate = 1 - CPUUtilization\n\nCPUUtilization = CPUUsage / CPURequest\n\nMemroyUtilization = MemoryUsage / MemroyRequest",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(max(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[2m])) by (pod, container)) by (pod) / sum(max(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} > 0) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(max(container_memory_working_set_bytes{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}) by (pod, container)) by (pod) / sum(max(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} > 0) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(\n \nlabel_replace(label_replace(sum(floor(max_over_time(DCGM_CUSTOM_PROCESS_MEM_USED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\"), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n* on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) \n\n/ on(node) group_left \n\nlabel_replace(sum(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s])) by (NodeName), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "1 \n\n- \n## 1. CPU 利用率\n(\n sum(max(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[1m])) by (pod, container)) by (pod) / sum(max(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} > 0) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) \n > 0\n or max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) * 0\n)\n\n- \n\n## 2. GPU显存利用率\n\n(\n sum(label_replace(label_replace(sum(floor(max_over_time(DCGM_CUSTOM_PROCESS_MEM_USED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\"), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n* on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) \n/ on(node) group_left \nlabel_replace(sum(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s])) by (NodeName), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n) by (pod) > 0\n or max(kube_pod_labels{namespace=~\"$Namespace\"}) by (pod) * 0\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}