{
 "title": "CS Cost Application",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "env", "label": "Selecte Env", "query": "uat,dev,sit" },
   { "name": "datasource_ack", "label": "ACK", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Namespace (Namespace)",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "ControllerType",
    "label": "Workload type",
    "query": "Deployment : Deployment, StatefulSet : StatefulSet, DaemonSet : DaemonSet, Job : Job"
   },
   {
    "name": "ControllerName",
    "label": "Workload Name",
    "query": {
     "query": "label_values({__name__=~\"kube_(pod|replicaset)_owner\", job=\"_kube-state-metrics\", namespace=~\"$Namespace\", owner_kind=~\"$ControllerType\"}, owner_name)"
    }
   },
   {
    "name": "LabelSelector",
    "label": "Label Pair Filter (LabelSelector)"
   },
   {
    "name": "LabelKey",
    "label": "LabelKey",
    "query": {
     "query": "query_result(label_replace(label_replace(vector(1), \"key_value\", \"$LabelSelector\", \"$LabelSelector\", \".*\"), \"key_value\", \"label_$1\", \"key_value\", \"(.*)[=|:]+(.*)\")) "
    }
   },
   {
    "name": "LabelValue",
    "label": "LabelValue",
    "query": {
     "query": "query_result(label_replace(label_replace(vector(1), \"key_value\", \"$LabelSelector\", \"$LabelSelector\", \".*\"), \"key_value\", \"$2\", \"key_value\", \"(.*)[=|:]+(.*)\")) "
    }
   },
   {
    "name": "FormatKeyValue",
    "label": "FormatKeyValue",
    "query": {
     "query": "query_result(label_replace(vector(1), \"key_value\", \"$LabelKey=~\\\"$LabelValue\\\"\", \"$LabelKey\", \".*\"))"
    }
   },
   {
    "name": "cost_allocation_method",
    "label": "cost allocation model",
    "query": "CPU模型 : 1, 内存模型 : 0, CPU-内存混合模型（推荐权重） : -10000, CPU-内存混合模型（自定义权重） : -1"
   },
   { "name": "CPUWeight", "label": "CPU Weight Setting (%)", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "Application Cost Dashboard Usage-Current Filter Criteria: Namespace: ($Namespace) WorkloadType: ($ControllerType) WorkloadName: ($ControllerName) LabelKey: ($LabelKey) LabelValue: ($LabelValue)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "## App View of Cost Analysis.\ncost and resource analysis of pods, selected by Namespace and pod's LabelSelector. \nversion: v1.0.4. [Help Doc](https://help.aliyun.com/document_detail/215497.html) \n\nThis cost is without discount.\n\n##### How to config LabelSelector: \nLabelSelector is for pod's metadata label key-value. \nformat support: \n```app=ack-cost-exporter``` \n```app:ack-cost-exporter``` \n\n \nif your pod label key have: ```/```、```.```、```-```, you need transport it to ```_```, and input should delete all ```\"``` \ne.g. \npod label: \n```\"sparkoperator.k8s.io/submission-id\":\"db08a66a-c0b7-4d32-8013-02ac4f8eff4c\"``` \nyou can input LabelSelector: \n```sparkoperator_k8s_io_submission_id:db08a66a-c0b7-4d32-8013-02ac4f8eff4c``` "
     }
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Current CPU Weight",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "scalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"})+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"})))\n",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Current Memory Weight",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "scalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"})+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"})))",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Application Cost",
   "type": "stat",
   "description": "Cost applied by the selected time range of the market\n\nWhich is calculate by Σ(Pod Request/Node Capacity)*EachNodePrice\n\nWarning:\n\nThis is a estimate data by compute resource.\nIf there is \"No Data\", please wait for at least one hour's data.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\n\n(\n#cpu分摊成本\nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"cpu\"}) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right max_over_time(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}[$__interval])) by (pod) * on(pod) group_right max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod) or max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * 0) by (pod) \n* \n#cpu权重\nscalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"})+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"})))\n\n+ \n\n#内存分摊成本\nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"memory\"}) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right max_over_time(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}[$__interval])) by (pod) * on(pod) group_right max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod) or max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * 0) by (pod) \n*\n#内存权重\nscalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"})+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"})))\n\n+ \n\n#ECI成本\nsum(sum(label_replace(label_replace(max_over_time(pod_current_price{exported_namespace=~\"$Namespace\"}[$__interval]), \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"), \"pod\", \"$1\", \"exported_pod\", \"(.*)\")) by (pod) * on(pod) group_right max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod) or max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * 0 ) by (pod) \n\n+\n\n# GPU节点\nsum(max(node_current_price) by (node) * on (node) group_right label_replace(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName)) by (NodeName, PodName), \"node\", \"$1\", \"NodeName\", \"(.*)\"), \"pod\", \"$1\", \"PodName\", \"(.*)\") * on(node) group_left kube_node_labels{label_aliyun_accelerator_nvidia_name!=\"\"} * on(pod) group_right max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) or max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * 0 ) by (pod)\n\n)\n\n* on(pod) group_left max(sum_over_time(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\"}[3599s:15s])) by(pod) * 15\n\n* on(pod) group_left max(\n label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval])) by (replicaset) \n or \n max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n ) by (pod))"
    }
   ]
  },
  {
   "title": "Apply current number of copies",
   "type": "stat",
   "description": "Max / Min Pod Num in this time range.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(kube_pod_info{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} ) by (pod) * on(pod) group_right max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application accounts for the entire cluster/namespace resource utilization",
   "type": "stat",
   "description": "Cluster Ratio (Resource Ratio of Cluster) = CPU request of pods / CPU request of cluster.\n\nNamespace Ratio (Resource Ratio of Namespace) = CPU request of pods / CPU request of selected namespace.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod) * on(pod) group_right max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n) / sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})",
     "legendFormat": "Percentable cluster:"
    },
    {
     "expr": "sum(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod) * on(pod) group_right max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n) / sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"})",
     "legendFormat": "Namespace occupied:"
    }
   ]
  },
  {
   "title": "Hourly cost of the node",
   "type": "bargauge",
   "description": "Price of each CPU Core of pods.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\nmax(node_current_price) by (node) * on(node)\n\nmax((sum(max_over_time(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}[$__interval])) by (pod, node)\n\n * on(pod) group_left sum(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left sum(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod)\n * on(pod) group_left max(\n label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval]) ) by(replicaset)\n or \n max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n ) by (pod)\n \n / on(pod) group_left sum(max_over_time(kube_pod_container_resource_requests_cpu_cores[$__interval])) by (pod))\n) by (node)\n\n* 3600",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Application running time/total number of core-time resources consumed",
   "type": "stat",
   "description": "Uptime is pods's total runtime (hours).\nCore*Hours is pods's total CPU core*hours.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "# sum(max(max_over_time(kube_pod_info[$__interval])) by(pod) * on(pod) group_right max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval]) * on (pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod)\nsum(max(sum_over_time(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}[3599s:15s])) by(pod) * 15 / 3600\n* on(pod) group_left max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on (pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod)\n* on(pod) group_left max(\n label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval]) ) by(replicaset)\n or \n max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n ) by (pod))",
     "legendFormat": "Cumulative application running time (hours):"
    },
    {
     "expr": "sum(sum(max_over_time(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}[$__interval])) by (pod) * on(pod) group_right \nmax(sum_over_time(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\"}[3599s:15s])) by(pod) * 15 / 3600\n* on(pod) group_left max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on (pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod)\n* on(pod) group_left max(\n label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval]) ) by(replicaset)\n or \n max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n ) by (pod))",
     "legendFormat": "When the application consumes total cores (Core * Hour):"
    }
   ]
  },
  {
   "title": "Computing Resource Utilization",
   "type": "stat",
   "description": "CPU / Memory Utilization of pods.\nUsage / Request.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(rate (container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[2m])) by (pod) * on(pod) group_right max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)) \n/ \nsum(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} ) by (pod) * on(pod) group_right max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod))",
     "legendFormat": "CPU："
    },
    {
     "expr": "sum(sum(container_memory_working_set_bytes{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}) by (pod) * on(pod) group_right max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)) \n/ \nsum(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} ) by (pod) * on(pod) group_right max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod))",
     "legendFormat": "Memory："
    },
    {
     "expr": "sum(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (gpu, NodeName)) by (NodeName)) by (PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\") * on(pod) group_right max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod))",
     "legendFormat": "GPU Memory："
    }
   ]
  },
  {
   "title": "Pod Dimension Business Cost Analysis",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum( rate (container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[2m])) by (pod, node) / on (pod) group_left sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} ) by (pod) * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) \n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod) > 0",
     "legendFormat": "CPU_Util"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}) by (pod, node) / on(pod) group_left sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} ) by (pod) * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) \n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod) > 0",
     "legendFormat": "MEM_Util"
    },
    {
     "expr": "\nsum(max(node_current_price) by (node) / on (node) group_left max(max_over_time(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}[$__interval]))by(node) * on(node) group_right max_over_time(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}[$__interval])) by (pod)\n\n * on(pod) group_right sum(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left sum(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod)\n * on(pod) group_left max(\n label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval]) ) by(replicaset)\n or \n max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n ) by (pod)\n \n / on(pod) sum(max_over_time(kube_pod_container_resource_requests_cpu_cores[$__interval])) by (pod) * ($__interval_ms/1000) > 0"
    },
    {
     "expr": "# sum(max(max_over_time(kube_pod_info[$__interval])) by(pod,node) * on(pod) group_left max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod,node) \n# * on (pod) group_left sum(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod)\n# * on(pod) group_left max(\n# label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval]) ) by(replicaset)\n# or \n# max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n# ) by (pod) > 0\nmax(max_over_time(kube_pod_info{node!=\"\"}[$__interval])) by(pod,node) * on(pod) group_left \nmax(sum_over_time(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}[3599s:15s])) by(pod) * 15 / 3600\n* on(pod) group_left max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on (pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod)\n* on(pod) group_left max(\n label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval]) ) by(replicaset)\n or \n max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n ) by (pod)",
     "legendFormat": "Core*Hour"
    },
    {
     "expr": "sum(\n \nlabel_replace(label_replace(sum(floor(max_over_time(DCGM_CUSTOM_PROCESS_MEM_USED{}[29s]))) by (NodeName,PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\"), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n* on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) \n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n\n/ on(node) group_left \n\nlabel_replace(sum(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s])) by (NodeName), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n) by (node, pod)",
     "legendFormat": "GPU_Used_Utilization"
    },
    {
     "expr": "sum(\n \nlabel_replace(label_replace(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s]))) by (NodeName,PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\"), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n* on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) \n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n\n/ on(node) group_left \n\nlabel_replace(sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n) by (node, pod)",
     "legendFormat": "GPU_Alloc_Utilization"
    },
    {
     "expr": "(\n#cpu分摊成本\nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"cpu\"}) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right max_over_time(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}[$__interval])) by (pod) * on(pod) group_right max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod) or max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * 0) by (pod) \n* \n#cpu权重\nscalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"})+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"})))\n\n+ \n\n#内存分摊成本\nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"memory\"}) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right max_over_time(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}[$__interval])) by (pod) * on(pod) group_right max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod) or max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * 0) by (pod) \n*\n#内存权重\nscalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"})+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"})))\n\n+ \n\n#ECI成本\nsum(sum(label_replace(label_replace(max_over_time(pod_current_price{exported_namespace=~\"$Namespace\"}[$__interval]), \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"), \"pod\", \"$1\", \"exported_pod\", \"(.*)\")) by (pod) * on(pod) group_right max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod) or max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * 0 ) by (pod) \n\n+\n\n# GPU节点\nsum(max(node_current_price) by (node) * on (node) group_right label_replace(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName)) by (NodeName, PodName), \"node\", \"$1\", \"NodeName\", \"(.*)\"), \"pod\", \"$1\", \"PodName\", \"(.*)\") * on(node) group_left kube_node_labels{label_aliyun_accelerator_nvidia_name!=\"\"} * on(pod) group_right max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) or max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * 0 ) by (pod)\n\n)\n\n* on(pod) group_left max(sum_over_time(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\"}[3599s:15s])) by(pod) * 15\n\n* on(pod) group_left max(\n label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval])) by (replicaset) \n or \n max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n ) by (pod)"
    }
   ]
  },
  {
   "title": "Apply estimated spending trends",
   "type": "graph",
   "description": "Cost (Cost Per Hour) is the total cost of pods per hour.\nCost Per Core * Hour is the Price of each CPU Core.\n \n\nWhich is calculate by Σ(Pod Request/Node Capacity)*EachNodePrice\n\nWarning:\n\nThis is a estimate data by compute resource.\nIf there is \"No Data\", please wait for at least one hour's data.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n\n(\n#cpu分摊成本\nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"cpu\"}) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right max_over_time(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}[$__interval])) by (pod) * on(pod) group_right max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod) or max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * 0) by (pod) \n* \n#cpu权重\nscalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"})+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"})))\n\n+ \n\n#内存分摊成本\nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"memory\"}) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right max_over_time(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}[$__interval])) by (pod) * on(pod) group_right max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod) or max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * 0) by (pod) \n*\n#内存权重\nscalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"})+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"})))\n\n+ \n\n#ECI成本\nsum(sum(label_replace(label_replace(max_over_time(pod_current_price{exported_namespace=~\"$Namespace\"}[$__interval]), \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"), \"pod\", \"$1\", \"exported_pod\", \"(.*)\")) by (pod) * on(pod) group_right max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod) or max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * 0 ) by (pod) \n\n+\n\n# GPU节点\nsum(max(node_current_price) by (node) * on (node) group_right label_replace(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName)) by (NodeName, PodName), \"node\", \"$1\", \"NodeName\", \"(.*)\"), \"pod\", \"$1\", \"PodName\", \"(.*)\") * on(node) group_left kube_node_labels{label_aliyun_accelerator_nvidia_name!=\"\"} * on(pod) group_right max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) or max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * 0 ) by (pod)\n\n)\n\n* on(pod) group_left max(sum_over_time(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\"}[3599s:15s])) by(pod) * 15\n\n* on(pod) group_left max(\n label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval])) by (replicaset) \n or \n max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n ) by (pod))",
     "legendFormat": "Estimated Cost (Per Hour)"
    },
    {
     "expr": "avg(\n\nsum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"})by(node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod)\n\n * on(pod) group_right max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n \n / on(pod) sum(kube_pod_container_resource_requests_cpu_cores) by (pod)\n \n \n) * 3600",
     "legendFormat": "Unit price per core hour (Cost Per Core * Hour)"
    }
   ]
  },
  {
   "title": "Application Pod Scale Trend",
   "type": "graph",
   "description": "Trend of up pods's count.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum(kube_pod_info{namespace=~\"$Namespace\"})by(pod) * on(pod) group_right max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue})by(pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n)",
     "legendFormat": "Number of Pods"
    }
   ]
  },
  {
   "title": "CPU Requests & Usage Trends",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", namespace=~\"$Namespace\", resource=\"cpu\"}) by(pod) * on(pod) group_right max(kube_pod_labels{$FormatKeyValue}) by(pod) * on (pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod) )\n\n# sum(sum(max_over_time(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", namespace=~\"$Namespace\", resource=\"cpu\"}[$__interval])) by(pod) * on(pod) group_right sum(max_over_time(kube_pod_labels{$FormatKeyValue}[$__interval])) by(pod) * on (pod) group_left sum(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod)\n# * on(pod) group_left max(\n# label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval]) ) by(replicaset)\n# or \n# max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n# ) by (pod))",
     "legendFormat": "CPU resource requests (Core)"
    },
    {
     "expr": "sum(sum(rate (container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[1m])) by(pod) * on(pod) group_right max(kube_pod_labels{$FormatKeyValue}) by(pod) * on (pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod))",
     "legendFormat": "CPU Usage (Core)"
    }
   ]
  },
  {
   "title": "Memory Requests & Usage Trends",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", namespace=~\"$Namespace\",resource=\"memory\"}) by(pod) * on(pod) group_right max(kube_pod_labels{$FormatKeyValue}) by(pod) * on (pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) \n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n ) / 1024 / 1024 / 1024",
     "legendFormat": "Memory resource requests"
    },
    {
     "expr": "sum(sum(container_memory_working_set_bytes{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"})by(pod) * on(pod) group_right max(kube_pod_labels{$FormatKeyValue}) by(pod) * on (pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n ) / 1024 / 1024 / 1024",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "GPU memory requests & usage trends",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum( label_replace(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s]))) by (PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\") * on(pod) group_right max(kube_pod_labels{$FormatKeyValue}) by(pod) * on (pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n ) ",
     "legendFormat": "GPU memory resource requests (Allocated)"
    },
    {
     "expr": "sum( label_replace(sum(floor(max_over_time(DCGM_CUSTOM_PROCESS_MEM_USED{NamespaceName=~\"$Namespace\"}[29s]))) by (PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\") * on(pod) group_right max(kube_pod_labels{$FormatKeyValue}) by(pod) * on (pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n* on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n ) ",
     "legendFormat": "GPU memory resource usage (Allocated)"
    }
   ]
  },
  {
   "title": "Forecast nodes are all pay-as-you-go expenses.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\n (sum(node_payAsYouGo_price) by (node) - sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n)\n* 3600 > 0",
     "legendFormat": "Excess:"
    },
    {
     "expr": "sum(\n (sum(node_payAsYouGo_price) by (node) - sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n)\n* 3600 <= 0",
     "legendFormat": "Savings:"
    }
   ]
  },
  {
   "title": "Forecast nodes are all annual and monthly expenses.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\n (sum(node_payByPeriod_price) by (node) - sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n)\n* 3600 > 0",
     "legendFormat": "Excess:"
    },
    {
     "expr": "sum(\n (sum(node_payByPeriod_price) by (node) - sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n)\n* 3600 <= 0",
     "legendFormat": "Savings:"
    }
   ]
  },
  {
   "title": "Forecast nodes are all Spot Spending",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\n (sum(node_spot_price) by (node) - sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n)\n* 3600 > 0",
     "legendFormat": "Excess:"
    },
    {
     "expr": "sum(\n (sum(node_spot_price) by (node) - sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n)\n* 3600 <= 0",
     "legendFormat": "Savings:"
    }
   ]
  },
  {
   "title": "Payment policy statistics of the node where the application resides",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(node_current_price) by (node, chargeType) * on(node) group_left\n\nmax((sum(max_over_time(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}[$__interval])) by (pod, node)\n\n * on(pod) group_left sum(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left sum(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod)\n * on(pod) group_left max(\n label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval]) ) by(replicaset)\n or \n max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n ) by (pod)\n \n / on(pod) group_left sum(max_over_time(kube_pod_container_resource_requests_cpu_cores[$__interval])) by (pod))\n) by (node)\n) by (chargeType)\n* 3600",
     "legendFormat": "{{chargeType}}"
    }
   ]
  },
  {
   "title": "Hourly cost/payment policy statistics of the node where the application resides",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "$/ Hour" } },
   "targets": [
    {
     "expr": "sum(max(node_current_price) by (node, chargeType) * on(node) group_left\n\nmax((sum(max_over_time(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}[$__interval])) by (pod, node)\n\n * on(pod) group_left sum(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left sum(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod)\n * on(pod) group_left max(\n label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval]) ) by(replicaset)\n or \n max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n ) by (pod)\n \n / on(pod) group_left sum(max_over_time(kube_pod_container_resource_requests_cpu_cores[$__interval])) by (pod))\n) by (node)\n) by (chargeType)\n* 3600",
     "legendFormat": "[node] :{{ node}}-[billing policy] :{{ chargeType}}"
    }
   ]
  },
  {
   "title": "Forecast nodes are all pay-as-you-go expenses.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n sum(\n (sum(node_payAsYouGo_price) by (node) - sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n) \n\n/\n\nsum(\n (sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n)\n) > 0",
     "legendFormat": "Excess:"
    },
    {
     "expr": "(\n sum(\n (sum(node_payAsYouGo_price) by (node) - sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n) \n\n/\n\nsum(\n (sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n)\n) <= 0",
     "legendFormat": "Savings:"
    }
   ]
  },
  {
   "title": "Forecast nodes are all annual and monthly expenses.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n sum(\n (sum(node_payByPeriod_price) by (node) - sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n) \n\n/\n\nsum(\n (sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n)\n) > 0",
     "legendFormat": "Excess:"
    },
    {
     "expr": "(\n sum(\n (sum(node_payByPeriod_price) by (node) - sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n) \n\n/\n\nsum(\n (sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n)\n) <= 0",
     "legendFormat": "Savings:"
    }
   ]
  },
  {
   "title": "Forecast nodes are all Spot Spending",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n sum(\n (sum(node_spot_price) by (node) - sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n) \n\n/\n\nsum(\n (sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n)\n) > 0",
     "legendFormat": "Excess:"
    },
    {
     "expr": "(\n sum(\n (sum(node_spot_price) by (node) - sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n) \n\n/\n\nsum(\n (sum(node_current_price{}) by (node)) * on(node)\n\nsum((sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\",namespace=~\"$Namespace\"}) by (pod, node)\n\n * on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n \n / on(node) group_left sum(kube_node_status_capacity_cpu_cores{job=\"_kube-state-metrics\"}) by (node))\n) by (node)\n)\n) <= 0",
     "legendFormat": "Savings:"
    }
   ]
  },
  {
   "title": "Pod resource request volume ranking",
   "type": "table",
   "description": "Sorted by CPU Request.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(max(max_over_time(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}[$__interval])) by (pod, container)) by (pod) * on(pod) max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod)\n* on(pod) group_left max(\n label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval]) ) by(replicaset)\n or \n max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n ) by (pod)\n > 0",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "# sum(max(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n# * on(pod) group_left max(\n# label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval]) ) by(replicaset)\n# or \n# max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n# ) by (pod)\n# > 0\nsum(max(max_over_time(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"}[$__interval])) by (pod, container)) by (pod) * on(pod) max(max_over_time(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}[$__interval])) by (pod) * on(pod) group_left max(max_over_time(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}[$__interval])) by (pod)\n* on(pod) group_left max(\n label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval]) ) by(replicaset)\n or \n max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n ) by (pod)\n > 0",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(label_replace(label_replace(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s]))) by (NodeName,PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\"), \"node\", \"$1\", \"NodeName\", \"(.*)\")) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n* on(pod) group_left max(\n label_replace(max_over_time(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}[$__interval]), \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left max(max_over_time(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}[$__interval]) ) by(replicaset)\n or \n max_over_time(kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}[$__interval])\n ) by (pod)\n > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Resource Usage Ranking-Sorted by CPU Usage",
   "type": "table",
   "description": "Sorted by CPU Usage.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum(max(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[2m])) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(max(container_memory_working_set_bytes{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(max(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[2m])) by (pod, container)) by (pod) / sum(max(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} > 0) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(max(container_memory_working_set_bytes{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}) by (pod, container)) by (pod) / sum(max(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} > 0) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(\n \nlabel_replace(label_replace(sum(floor(max_over_time(DCGM_CUSTOM_PROCESS_MEM_USED{}[29s]))) by (NodeName,PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\"), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n* on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) \n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)\n\n/ on(node) group_left \n\nlabel_replace(sum(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s])) by (NodeName), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n) by (node, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod resource idle ranking",
   "type": "table",
   "description": "Sort by WasteRate.\nWasteRate = 1 - CPUUtilization\n\nCPUUtilization = CPUUsage / CPURequest\n\nMemroyUtilization = MemoryUsage / MemroyRequest",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(max(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[2m])) by (pod, container)) by (pod) / sum(max(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} > 0) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(max(container_memory_working_set_bytes{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}) by (pod, container)) by (pod) / sum(max(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} > 0) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(\n \nlabel_replace(label_replace(sum(floor(max_over_time(DCGM_CUSTOM_PROCESS_MEM_USED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\"), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n* on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) \n\n/ on(node) group_left \n\nlabel_replace(sum(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s])) by (NodeName), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n) by (pod)\n * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "(\n1 \n\n- \n## 1. CPU 利用率\n(\n sum(max(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", namespace!=\"\",container !=\"\",container!=\"POD\"}[2m])) by (pod, container)) by (pod) / sum(max(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\", namespace=~\"$Namespace\"} > 0) by (pod, container)) by (pod) * on(pod) max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * on(pod) group_left max(kube_pod_status_phase{namespace=~\"$Namespace\", phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) \n > 0\n or max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * 0\n)\n\n- \n\n## 2. GPU显存利用率\n\n(\n sum(label_replace(label_replace(sum(floor(max_over_time(DCGM_CUSTOM_PROCESS_MEM_USED{NamespaceName=~\"$Namespace\"}[29s]))) by (NodeName,PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\"), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n* on(pod) group_left max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) \n/ on(node) group_left \nlabel_replace(sum(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{NamespaceName=~\"$Namespace\"}[29s])) by (NodeName), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n) by (pod) > 0\n or max(kube_pod_labels{namespace=~\"$Namespace\", $FormatKeyValue}) by (pod) * 0\n)\n) * on(pod) group_left max(\n label_replace(kube_pod_info{job=\"_kube-state-metrics\", created_by_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"created_by_name\", \"(.+)\") * on(replicaset) group_left() max(kube_replicaset_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\",owner_name=~\"$ControllerName\"}) by (replicaset) \n or \n kube_pod_owner{job=\"_kube-state-metrics\", owner_kind=~\"$ControllerType\", owner_name=~\"$ControllerName\"}\n ) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}