{
 "title": "CS Cost Overview",
 "tags": [ "prometheus" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cost_measure",
    "label": "Actual/original bill",
    "query": "优惠后实际账单成本 : pretax_amount,原价账单成本 : pretax_gross_amount"
   },
   {
    "name": "cost_allocation_method",
    "label": "cost allocation model",
    "query": "CPU模型 : 1, 内存模型 : 0, CPU-内存混合模型（推荐权重） : -10000, CPU-内存混合模型（自定义权重） : -1"
   },
   { "name": "CPUWeight", "label": "CPU Weight Setting (%)", "query": "100" }
  ]
 },
 "panels": [
  { "title": "Cluster Cost Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current CPU Weight",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "scalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"})+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"})))",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Current Memory Weight",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "scalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"})+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"})))",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Yesterday's Cluster Cost- $cost_measure",
   "type": "stat",
   "description": "Yesterday's cluster cost-${cost_measure:text}",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "abs(sum(max($cost_measure) by (product_code, instance_id)) )"
    }
   ]
  },
  {
   "title": "Cost ratio- $cost_measure",
   "type": "stat",
   "description": "If “No data” is displayed, please wait at least two days for the data to accumulate before checking again.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "abs((sum(max($cost_measure offset 1d) by (product_code, instance_id)) - sum(max($cost_measure offset 2d) by (product_code, instance_id)))) / abs(sum(max($cost_measure offset 2d) by (product_code, instance_id)))"
    }
   ]
  },
  {
   "title": "Forecast Cost Tomorrow- $cost_measure",
   "type": "stat",
   "description": "Tomorrow's predicted spend-${cost_measure:text}",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "abs(sum(max($cost_measure) by (product_code, instance_id)) ) * abs(sum(max($cost_measure offset 1d) by (product_code, instance_id))) / abs(sum(max($cost_measure offset 2d) by (product_code, instance_id)))"
    }
   ]
  },
  {
   "title": "Cluster Cost & Cluster Capacity Trend Chart",
   "type": "graph",
   "description": "The cost data are daily T+1 data (i.e., settled one day later).\n\nThe capacity data are collected in real time on an hourly basis.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "$" }
   ],
   "targets": [
    {
     "expr": "sum(machine_cpu_cores) ",
     "legendFormat": "Total Cluster Capacity (CPU Core)"
    },
    {
     "expr": "abs(sum(max($cost_measure) by (product_code, instance_id)) )",
     "legendFormat": "Total Cluster Cost"
    }
   ]
  },
  {
   "title": "This week's cumulative expenses- $cost_measure",
   "type": "stat",
   "description": "This week’s total spend-${cost_measure:text}",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "abs(sum(max($cost_measure) by (product_code, instance_id)))"
    }
   ]
  },
  {
   "title": "Cumulative Expenses for the Month- $cost_measure",
   "type": "stat",
   "description": "Monthly Cumulative Spending-${cost_measure:text}",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "abs(sum(max($cost_measure) by (product_code, instance_id)))"
    }
   ]
  },
  {
   "title": "Total Forecast Spend This Month- $cost_measure",
   "type": "stat",
   "description": "Total predicted expenses for this month-${cost_measure:text}",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "abs(sum(max($cost_measure) by (product_code, instance_id))) * (30 * 24 * 60 * 60 ) / ($__range_s) "
    }
   ]
  },
  {
   "title": "Real-time cost estimation (namespace)",
   "type": "piechart",
   "description": "“Namespace cost” is estimated based on recent compute resource consumption and represents the undiscounted, original billing price.\n\nThe calculation formula is:\nΣ(Pod resource requests/Node total capacity) × Node unit price",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "#由于某些namespace可能没有配cpu或内存request，保证结果展示全量的namespace\nmax(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 \n\n#cpu分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"cpu\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"} * on(pod) group_left max(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n* \n\n#cpu权重\nscalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#内存分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"memory\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"} * on(pod) group_left max(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n#内存权重\n*\nscalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#ECI成本\n+ on(namespace) group_left\nsum(max(label_replace(pod_current_price, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\")) by (exported_pod, namespace) or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n# GPU节点\n+ on(namespace) group_left\nsum(max(node_current_price) by (node) * on (node) group_right label_replace(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName)) by (NodeName, NamespaceName), \"node\", \"$1\", \"NodeName\", \"(.*)\"), \"namespace\", \"$1\", \"NamespaceName\", \"(.*)\") * on(node) group_left kube_node_labels{label_aliyun_accelerator_nvidia_name!=\"\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(node_current_price or pod_current_price) * ($__interval_ms/1000) \n\n- \n\nsum(\n#由于某些namespace可能没有配cpu或内存request，保证结果展示全量的namespace\nmax(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 \n\n#cpu分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"cpu\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n* \n\n#cpu权重\nscalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#内存分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"memory\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n#内存权重\n*\nscalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#ECI成本\n+ on(namespace) group_left\nsum(max(label_replace(pod_current_price, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\")) by (exported_pod, namespace) or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n# GPU节点\n+ on(namespace) group_left\nsum(max(node_current_price) by (node) * on (node) group_right label_replace(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName)) by (NodeName, NamespaceName), \"node\", \"$1\", \"NodeName\", \"(.*)\"), \"namespace\", \"$1\", \"NamespaceName\", \"(.*)\") * on(node) group_left kube_node_labels{label_aliyun_accelerator_nvidia_name!=\"\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n)",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Charges (namespace)-$cost_measure",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "(\n \n#由于某些namespace可能没有配cpu或内存request，保证结果展示全量的namespace\nmax(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 \n\n#cpu分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"cpu\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"} * on(pod) group_left max(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n* \n\n#cpu权重\nscalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#内存分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"memory\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"} * on(pod) group_left max(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n#内存权重\n*\nscalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#ECI成本\n+ on(namespace) group_left\nsum(max(label_replace(pod_current_price, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\")) by (exported_pod, namespace) or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n# GPU节点\n+ on(namespace) group_left\nsum(max(node_current_price) by (node) * on (node) group_right label_replace(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName)) by (NodeName, NamespaceName), \"node\", \"$1\", \"NodeName\", \"(.*)\"), \"namespace\", \"$1\", \"NamespaceName\", \"(.*)\") * on(node) group_left kube_node_labels{label_aliyun_accelerator_nvidia_name!=\"\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n)\n/\nscalar(sum(node_current_price or pod_current_price)* ($__interval_ms/1000)) \n*\nscalar(abs(sum(max(sum($cost_measure)) by (product_code, instance_id)) ))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(\nsum(node_current_price or pod_current_price) * ($__interval_ms/1000) \n- \nsum(\n\n#由于某些namespace可能没有配cpu或内存request，保证结果展示全量的namespace\nmax(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 \n\n#cpu分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"cpu\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"} * on(pod) group_left max(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n* \n\n#cpu权重\nscalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#内存分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"memory\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"} * on(pod) group_left max(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n#内存权重\n*\nscalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#ECI成本\n+ on(namespace) group_left\nsum(max(label_replace(pod_current_price, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\")) by (exported_pod, namespace) or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n# GPU节点\n+ on(namespace) group_left\nsum(max(node_current_price) by (node) * on (node) group_right label_replace(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName)) by (NodeName, NamespaceName), \"node\", \"$1\", \"NodeName\", \"(.*)\"), \"namespace\", \"$1\", \"NamespaceName\", \"(.*)\") * on(node) group_left kube_node_labels{label_aliyun_accelerator_nvidia_name!=\"\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n\n))\n/\nscalar(\n sum(node_current_price or pod_current_price) * ($__interval_ms/1000)\n)\n*\nscalar(abs(sum(max(sum($cost_measure)) by (product_code, instance_id)) )) > 0 or vector(0)\n",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Stability & Efficiency Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Stability/Performance Risks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "(count(\n((count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace)) +\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace)) +\n(count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace)) +\n(count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace)) \n== 4)\n* \n(max(kube_pod_status_phase{job=\"_kube-state-metrics\", phase=\"Running\"})by(pod,namespace) > 0)\n)or vector(0))",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Number of BestEffort Pods:",
     "method": "GET"
    },
    {
     "expr": "count(max(kube_pod_status_phase{job=\"_kube-state-metrics\", phase=\"Running\"})by(pod,namespace) > 0)\n-\n(count(\n((count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace)) +\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace)) +\n(count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace)) +\n(count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace)) \n== 4)\n* \n(max(kube_pod_status_phase{job=\"_kube-state-metrics\", phase=\"Running\"})by(pod,namespace) > 0)\n)or vector(0))\n-\n(count(\nsum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace) == sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace)\nand\nsum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace) == sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace)\n* \n(max(kube_pod_status_phase{job=\"_kube-state-metrics\", phase=\"Running\"})by(pod,namespace) > 0)\n)or vector(0))",
     "legendFormat": "Number of Burstable Pods:"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage Overview",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( rate (container_cpu_usage_seconds_total{ namespace!=\"\",container!=\"\",container!=\"POD\"}[2m]))",
     "legendFormat": "Cluster CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\",resource=\"cpu\"})",
     "legendFormat": "Cluster CPU request"
    },
    {
     "expr": "sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\",node!~\"virtual.*\"})",
     "legendFormat": "Total CPU cores in the cluster"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage Overview",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace!=\"\",container!=\"\",container!=\"POD\"})/1024/1024",
     "legendFormat": "Cluster memory usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\",resource=\"memory\"})/1024/1024",
     "legendFormat": "Cluster memory request"
    },
    {
     "expr": "sum(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\",node!~\"virtual.*\"})/1024/1024",
     "legendFormat": "Total cluster memory"
    }
   ]
  },
  {
   "title": "Cluster Pod Resource Utilization Analysis",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum( rate (container_cpu_usage_seconds_total{ namespace!=\"\",container!=\"\",container!=\"POD\"}[2m])) by (pod, namespace) / on (pod, namespace) group_right sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"} ) by (pod,namespace) * on(pod,namespace) group_right max(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod,node,namespace) >0",
     "legendFormat": "CPU_Util"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace!=\"\",container!=\"\",container!=\"POD\"}) by (pod, namespace) / on(pod, namespace) group_right sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"} ) by (pod, namespace) * on(pod,namespace) group_right max(kube_pod_status_phase{phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod,namespace,node) > 0",
     "legendFormat": "MEM_Util"
    },
    {
     "expr": "max(kube_pod_info) by(pod, node,namespace) * on (pod) group_left max(kube_pod_status_phase{ phase=~\"Running\", job=\"_kube-state-metrics\"}) by (pod) > 0",
     "legendFormat": "Core*Hour"
    },
    {
     "expr": "sum(\n \nlabel_replace(label_replace(sum(floor(max_over_time(DCGM_CUSTOM_PROCESS_MEM_USED{}[29s]))) by (NodeName,PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\"), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n/ on(node) group_left \n\nlabel_replace(sum(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s])) by (NodeName), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n) by (node, pod)",
     "legendFormat": "GPU_Used_Utilization"
    },
    {
     "expr": "sum(\n \nlabel_replace(label_replace(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s]))) by (NodeName,PodName), \"pod\", \"$1\", \"PodName\", \"(.*)\"), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n/ on(node) group_left \n\nlabel_replace(sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName), \"node\", \"$1\", \"NodeName\", \"(.*)\") \n\n) by (node, pod)",
     "legendFormat": "GPU_Alloc_Utilization"
    }
   ]
  },
  {
   "title": "Burstable Pod-Resource Usage Analysis",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "# 筛选逻辑：找出以下所有pod，使用or聚合，可以得到所有burstable和besteffort的pod，但besteffort没有这些设置值，所有不会展示。\n# 1、未设置cpu requests\n# 2、未设置mem requests\n# 3、未设置cpu limits\n# 4、未设置mem limits\n# 5、设置了cpu requests和limits，但二者不相等\n# 6、设置了mem requests和limits，但二者不相等\n\nsum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace) * 1000\n* \n(((count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\n# 如果有对应的设置值，这里一定会大于1.\nor\n(count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\nsum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace) != sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace)\nor\nsum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace) != sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace)) * 0 + 1)\n* \n(max(kube_pod_status_phase{job=\"_kube-state-metrics\", phase=\"Running\"})by(pod,namespace) > 0)\n# max(kube_pod_status_phase)必须加括号，因为request or limit可能设置为0，这里需要限制仅仅是kube_pod_status_phase > 0。\n",
     "legendFormat": "CPU_Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace) /1024/1024\n* \n(((count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\n(count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\nsum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace) != sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace)\nor\nsum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace) != sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace)) * 0 + 1)\n* \n(max(kube_pod_status_phase{job=\"_kube-state-metrics\", phase=\"Running\"})by(pod,namespace) > 0)\n# max(kube_pod_status_phase)必须加括号，因为request or limit可能设置为0，这里需要限制仅仅是kube_pod_status_phase > 0。\n\n",
     "legendFormat": "MEM_Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace) * 1000\n* \n(((count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\n(count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\nsum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace) != sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace)\nor\nsum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace) != sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace)) * 0 + 1)\n* \n(max(kube_pod_status_phase{job=\"_kube-state-metrics\", phase=\"Running\"})by(pod,namespace) > 0)\n# max(kube_pod_status_phase)必须加括号，因为request or limit可能设置为0，这里需要限制仅仅是kube_pod_status_phase > 0。\n\n",
     "legendFormat": "CPU_Limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace) /1024/1024\n* \n(((count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\n(count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"}) by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace)) == 1\nor\nsum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace) != sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace)\nor\nsum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace) != sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace)) * 0 + 1)\n* \n(max(kube_pod_status_phase{job=\"_kube-state-metrics\", phase=\"Running\"})by(pod,namespace) > 0)\n# max(kube_pod_status_phase)必须加括号，因为request or limit可能设置为0，这里需要限制仅仅是kube_pod_status_phase > 0。\n\n",
     "legendFormat": "MEM_Limits"
    },
    {
     "expr": "# 这里单独一个query做node维度展示，是因为kube_pod_status_phase{}不存在node label，因此最后一句max(kube_pod_status_phase)需要使用group by聚合，语法要求只能去掉max(kube_pod_status_phase)>0外面的括号.\n\n# 解决方式是外层再加一个kube_pod_container_resource_requests，用于去除best effort pod的展示。\n\n(sum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace,node) +1)\n*\n(((count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"}) by(pod,namespace,node)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace,node)) == 1\nor\n(count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"}) by(pod,namespace,node)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace,node)) == 1\nor\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"}) by(pod,namespace,node)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace,node)) == 1\nor\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"}) by(pod,namespace,node)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"}) by(pod,namespace,node)) == 1\nor\nsum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace,node) != sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace,node)\nor\nsum(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace,node) != sum(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace,node)) * 0 + 1)\n* \non(pod,namespace) group_left max(kube_pod_status_phase{job=\"_kube-state-metrics\", phase=\"Running\"})by(pod,namespace) > 0\n",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "Best Effort Pod-Resource Usage Analysis",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum( rate (container_cpu_usage_seconds_total{ namespace!=\"\",container!=\"\",container!=\"POD\"}[2m])) by (pod, namespace) * 1000 \n* \n((count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace)) +\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace)) +\n(count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace)) +\n(count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace)) \n== 4)/4\n* \n(max(kube_pod_status_phase{job=\"_kube-state-metrics\", phase=\"Running\"})by(pod,namespace) > 0)\n",
     "legendFormat": "CPU_Util"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace!=\"\",container!=\"\",container!=\"POD\"}) by (pod, namespace,node) /1024/1024 *\n((count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace,node)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace,node)) +\n(count(kube_pod_container_resource_limits{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace,node)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace,node)) +\n(count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"cpu\"})by(pod,namespace,node)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace,node)) +\n(count(kube_pod_container_resource_requests{job=\"_kube-state-metrics\", resource=\"memory\"})by(pod,namespace,node)+2 or max(kube_pod_info{job=\"_kube-state-metrics\"})by(pod,namespace,node)) \n== 4)/4\n* on(pod,namespace) group_left max(kube_pod_status_phase{job=\"_kube-state-metrics\", phase=\"Running\"})by(pod,namespace) > 0\n",
     "legendFormat": "MEM_Util"
    }
   ]
  },
  { "title": "Cluster Cost Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Cloud product cost analysis- $cost_measure",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "abs(sum(max($cost_measure) by (product_code, instance_id)) by (product_code))",
     "legendFormat": "{{product_code}}"
    }
   ]
  },
  {
   "title": "Actual Spending Trend (Cloud Product Dimension)-$cost_measure",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "$" }
   ],
   "targets": [
    {
     "expr": "abs(sum(max($cost_measure) by (product_code, instance_id)) by (product_code))",
     "legendFormat": "{{product_code}}"
    }
   ]
  },
  {
   "title": "Actual spending trend (cluster dimension)-$cost_measure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "yaxes": [
    { "format": "$" }
   ],
   "targets": [
    {
     "expr": "abs(sum(max($cost_measure) by (product_code, instance_id)))",
     "legendFormat": "Total Cluster Cost"
    }
   ]
  },
  {
   "title": "Actual Spending Trend (Node Pool Dimension)-$cost_measure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "$" }
   ],
   "targets": [
    {
     "expr": "abs(sum(max($cost_measure{node_pool_id=\"\", product_code=\"ecs\"}) by (product_code, instance_id)))",
     "legendFormat": "default_node_pool"
    },
    {
     "expr": "abs(sum(max($cost_measure{node_pool_id!=\"\",product_code=\"ecs\"}) by (product_code, instance_id, node_pool_id)) by (node_pool_id))",
     "legendFormat": "{{node_pool_id}}"
    },
    {
     "expr": "abs(sum(max($cost_measure{product_code=\"eci\"}) by (product_code, instance_id)))",
     "legendFormat": "virtual_kubelet"
    }
   ]
  },
  {
   "title": "Cost Estimation Analysis (Namespace Dimension)-Original Bill Cost",
   "type": "graph",
   "description": "“Namespace cost” is estimated based on recent compute resource consumption and represents the undiscounted, original billing price.\n\nThe calculation formula is:\nΣ(Pod resource requests/Node total capacity) × Node unit price",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "$" }
   ],
   "targets": [
    {
     "expr": "#由于某些namespace可能没有配cpu或内存request，保证结果展示全量的namespace\nmax(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 \n\n#cpu分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"cpu\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n* \n\n#cpu权重\nscalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#内存分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"memory\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n#内存权重\n*\nscalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#ECI成本\n+ on(namespace) group_left\nsum(max(label_replace(pod_current_price, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\")) by (exported_pod, namespace) or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n# GPU节点\n+ on(namespace) group_left\nsum(max(node_current_price) by (node) * on (node) group_right label_replace(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName)) by (NodeName, NamespaceName), \"node\", \"$1\", \"NodeName\", \"(.*)\"), \"namespace\", \"$1\", \"NamespaceName\", \"(.*)\") * on(node) group_left kube_node_labels{label_aliyun_accelerator_nvidia_name!=\"\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(node_current_price or pod_current_price) * ($__interval_ms/1000) \n\n- \n\nsum(\n#由于某些namespace可能没有配cpu或内存request，保证结果展示全量的namespace\nmax(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 \n\n#cpu分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"cpu\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n* \n\n#cpu权重\nscalar((vector($cost_allocation_method) == 1) or\n(vector($cost_allocation_method) == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*($CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#内存分摊成本\n+ on(namespace) group_left \nsum(sum(max(node_current_price) by (node) / on (node) group_left max(kube_node_status_capacity{job=\"_kube-state-metrics\", resource=\"memory\"}) by (node)) by (node) * on(node) max(kube_node_labels{label_aliyun_accelerator_nvidia_name=\"\"}) by (node) * on(node) group_right kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n#内存权重\n*\nscalar((vector($cost_allocation_method) + 1 == 1) or\n(vector($cost_allocation_method) - 1 == 0) or\n(vector($cost_allocation_method) == -1)*vector(-1)*(1-$CPUWeight/100) or\n(sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node)))/(sum(kube_pod_container_resource_requests_cpu_cores{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"cpu\"}) by (node))+sum(kube_pod_container_resource_requests_memory_bytes{job=\"_kube-state-metrics\"})/sum(max(kube_node_status_capacity{job=\"_kube-state-metrics\",resource=\"memory\"}) by (node))))\n\n#ECI成本\n+ on(namespace) group_left\nsum(max(label_replace(pod_current_price, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\")) by (exported_pod, namespace) or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n\n# GPU节点\n+ on(namespace) group_left\nsum(max(node_current_price) by (node) * on (node) group_right label_replace(label_replace(sum(sum(floor(max_over_time(DCGM_CUSTOM_CONTAINER_MEM_ALLOCATED{}[29s]))) by (NodeName,NamespaceName,AllocateMode,PodName) / on(NodeName) group_left sum(max_over_time(DCGM_CUSTOM_DEV_FB_TOTAL{}[29s])) by (NodeName)) by (NodeName, NamespaceName), \"node\", \"$1\", \"NodeName\", \"(.*)\"), \"namespace\", \"$1\", \"NamespaceName\", \"(.*)\") * on(node) group_left kube_node_labels{label_aliyun_accelerator_nvidia_name!=\"\"} or max(kube_namespace_labels{job=\"_kube-state-metrics\"}) by(namespace) * 0 ) by (namespace) * ($__interval_ms/1000)\n)",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Request & Utilization Trend Chart of Cluster Computing Resources",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) / sum(machine_cpu_cores) ",
     "legendFormat": "Resource Request Rate RequestUtilization"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\"}[1m])) / sum(machine_cpu_cores) ",
     "legendFormat": "Resource Usage UsageUtilization"
    }
   ]
  },
  {
   "title": "Billing details of the cluster-cloud product dimension",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "abs(max(pretax_gross_amount) by (product_code, instance_id, billing_date, subscription_type))",
     "legendFormat": "Original Cost (without discount)"
    },
    {
     "expr": "count(max($cost_measure) by (product_code, instance_id, billing_date, subscription_type)) by (product_code, billing_date)",
     "legendFormat": "InstanceCount"
    },
    {
     "expr": "abs(max(pretax_amount) by (product_code, instance_id, billing_date, subscription_type))",
     "legendFormat": "Discounted Cost"
    }
   ]
  },
  {
   "title": "Billing details of the cluster-Instance dimension",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "abs(max(pretax_gross_amount) by (product_code, instance_id, billing_date, subscription_type))",
     "legendFormat": "Original Cost (without discount)"
    },
    {
     "expr": "abs(max(pretax_amount) by (product_code, instance_id, billing_date, subscription_type))",
     "legendFormat": "Discounted Cost"
    }
   ]
  }
 ]
}