{
 "title": "Demo Logical Architecture Overview--ADO",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "regionId", "query": "cn-hongkong" },
   { "name": "env", "label": "Selecte Env", "query": "dev,uat" },
   {
    "name": "NameSpace",
    "label": "ProjectName",
    "query": "Jarvis : ns-hkg-agent-system, ODS : ns-hkg-ods-system,ATAS : ns-gft-atas-system,DCS : ns-hkg-dcs-system,"
   },
   {
    "name": "Service",
    "label": "AppName",
    "query": {
     "query": "label_values(arms_app_requests_count_raw{namespace=\"$NameSpace\"},app)"
    }
   },
   {
    "name": "loadBalancerId",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_LoadBalancerQPS|AliyunAlb_LoadBalancerHealthyHostCount\", regionId=~\"$regionId\"},loadBalancerId)"
    }
   },
   {
    "name": "listenerProtocol",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_ListenerQPS|AliyunAlb_ListenerHealthyHostCount\",regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\"},listenerProtocol)"
    }
   },
   {
    "name": "listenerPort",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_ListenerQPS|AliyunAlb_ListenerHealthyHostCount\",regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\",listenerProtocol=~\"$listenerProtocol\"},listenerPort)"
    }
   },
   {
    "name": "ruleId",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_RuleQPS|AliyunAlb_RuleHealthyHostCount\",regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"},ruleId)"
    }
   },
   {
    "name": "serverGroupId",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_ServerGroupQPS|AliyunAlb_ServerGroupHealthyHostCount\",regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"},serverGroupId)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   { "name": "asm_gateway_name", "label": "asm_gateway_name", "query": "istio-ingressgateway" },
   {
    "name": "Pid",
    "label": "pid",
    "query": {
     "query": "label_values(arms_app_requests_count_ign_destid_endpoint_parent_ppid_prpc{service=\"$Service\"},pid)"
    }
   },
   {
    "name": "ASMSVC",
    "label": "asmsvc",
    "query": {
     "query": "label_values(arms_app_requests_count_raw{namespace=\"$NameSpace\", service=\"$Service\"},app)"
    }
   },
   {
    "name": "GWSVC",
    "label": "asmavc",
    "query": {
     "query": "label_values(arms_app_requests_count_raw{namespace=\"$NameSpace\", service=\"$Service\"},app)"
    }
   },
   {
    "name": "incallKind",
    "label": "incallKind",
    "query": "http|rpc|consumer|custom_entry|server"
   },
   {
    "name": "outcallKind",
    "label": "outcallKind",
    "query": "rpc_client|http_client|db|sql|nosql|cache|producer|client"
   },
   {
    "name": "fullIncallKinds",
    "label": "fullIncallKinds",
    "query": "http|rpc|consumer|custom_entry|schedule|server"
   },
   {
    "name": "PromInstanceId",
    "label": "promInstanceId",
    "query": {
     "query": "label_values(AliyunAlb_ListenerQPS{loadBalancerId=\"$loadBalancerId\"},promInstanceId)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "canvas",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round(avg_over_time(AliyunAlb_ListenerQPS{regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\"}[$__range]))",
     "legendFormat": "alb-QPS"
    },
    {
     "expr": "round(avg_over_time(AliyunAlb_ListenerUpstreamResponseTime{loadBalancerId=~\"$loadBalancerId\"}[5m]))",
     "legendFormat": "Alb-Resp"
    },
    {
     "expr": "round(avg_over_time(AliyunCnapigateway_EnvoyApiQps{apiName=~\"hk-ado-jarvis\"}[$__range]))",
     "legendFormat": "apigw-qps"
    },
    {
     "expr": "round(avg_over_time(AliyunCnapigateway_EnvoyDownstreamSuccessRate{promInstanceId=~\"$PromInstanceId\"}[5m]))",
     "legendFormat": "apigwRate"
    },
    {
     "expr": "\r\nround(sum(AliyunAlb_LoadBalancerHTTPCodeUpstream2XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"})\r\n/\r\nsum(\r\n AliyunAlb_LoadBalancerHTTPCodeUpstream2XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream3XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream4XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream5XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\n))\r\n",
     "legendFormat": "alb-rate"
    },
    {
     "expr": "round(avg_over_time(AliyunCnapigateway_EnvoyApiRtAvg{promInstanceId=~\"$PromInstanceId\"}[5m]))",
     "legendFormat": "gw-resp"
    },
    {
     "expr": "round(sum by (istio)(rate(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\"}[$__range])))",
     "legendFormat": "Asm QPS"
    },
    {
     "expr": "(sum(irate(istio_request_duration_milliseconds_bucket_delta{reporter=\"source\",source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[5m])) by (source_app, source_workload_namespace, le) / 1000) or sum(irate(istio_request_duration_seconds_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[5m])) by (source_app, source_workload_namespace, le)",
     "legendFormat": "asm resp"
    },
    {
     "expr": "sum_over_time(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\",response_code=~\"2..\"}[5m])/sum_over_time(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\"}[5m])",
     "legendFormat": "asm rate"
    },
    {
     "expr": "round(sum(irate(apiserver_request_total{subresource !~ \".*/healthz$|/livez$|/readyz$\"}[5m])))",
     "legendFormat": "ack qps"
    },
    {
     "expr": "avg (sum by (verb) (irate(apiserver_request_duration_seconds_bucket{verb!~\"WATCH|CONNECT\",resource!=\"\",subresource!~\".*/healthz$|/livez$|/readyz$\"}[5m])))",
     "legendFormat": "ack resp"
    },
    {
     "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb!~\"GET|LIST|WATCH|CONNECT\"}[5m]))/sum(irate(apiserver_request_total{verb!~\"GET|LIST|WATCH|CONNECT\"}[5m]))",
     "legendFormat": "ack rate"
    },
    {
     "expr": "round(sum(avg_over_time_lorc(arms_app_requests_count_raw{service=~\"hk-ado-jarvis-chatbot-service-prd\",rpc!~\".*/liveness$\",}[$__range]))) or vector(0)",
     "legendFormat": "chatbot qps"
    },
    {
     "expr": "round(sum(avg_over_time_lorc(arms_app_requests_count_raw{service=~\"hk-ado-jarvis-generic-service-prd\",rpc!~\".*/liveness$\",}[$__range]))) or vector(0)",
     "legendFormat": "generic qps"
    },
    {
     "expr": "round(sum(avg_over_time(arms_app_requests_count_raw{destId=\"svc-hk-ado-jarvis-ai-service.ns-hkg-agent-system\",rpc!~\".*/liveness$\",}[$__range]))) or vector(0)",
     "legendFormat": "ai qps"
    },
    {
     "expr": "sum(sum_over_time(arms_requests_by_status_count_raw{source=\"apm\",status=~\"2..\",app=\"hk-ado-jarvis-generic-service-prd\",rpc!~\".*/liveness$\"}[$__range]) or vector(1))/sum(sum_over_time(arms_requests_by_status_count_raw{source=\"apm\",app=\"hk-ado-jarvis-generic-service-prd\",rpc!~\".*/liveness$\"}[$__range]) or vector(1)) ",
     "legendFormat": "genrice rate"
    },
    {
     "expr": "sum(sum_over_time(arms_requests_by_status_count_raw{source=\"apm\",status=~\"2..\",app=\"hk-ado-jarvis-chatbot-service-prd\",rpc!~\".*/liveness$\"}[$__range]) or vector(1))/sum(sum_over_time(arms_requests_by_status_count_raw{source=\"apm\",app=\"hk-ado-jarvis-chatbot-service-prd\",rpc!~\".*/liveness$\"}[$__range]) or vector(1)) ",
     "legendFormat": "chtbot rate"
    },
    {
     "expr": "sum(sum_over_time(arms_requests_by_status_count_raw{source=\"apm\",status=~\"2..\",app=\"hk-ado-jarvis-ai-service-prod\",rpc!~\".*/liveness$\"}[$__range]) or vector(1))/sum(sum_over_time(arms_requests_by_status_count_raw{source=\"apm\",app=\"hk-ado-jarvis-ai-service-prod\",rpc!~\".*/liveness$\"}[$__range]) or vector(1)) ",
     "legendFormat": "ai rate"
    },
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_seconds_raw{service=\"hk-ado-jarvis-ai-service-prod\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",source=\"apm\",}[$__range]))/sum(sum_over_time_lorc(arms_app_requests_count_raw{service=\"hk-ado-jarvis-ai-service-prod\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",source=\"apm\"}[$__range])) or vector(0)",
     "legendFormat": "ai resp"
    },
    {
     "expr": "\r\nround(\r\n (\r\n sum(sum_over_time_lorc(arms_app_requests_seconds_raw{\r\n service=\"hk-ado-jarvis-chatbot-service-prd\",\r\n serverIp=~\".*\",\r\n callKind=~\"http|rpc|custom_entry|server\",\r\n rpc!~\".*/liveness$\",\r\n source=\"apm\",\r\n }[$__range]))\r\n /\r\n sum(sum_over_time_lorc(arms_app_requests_count_raw{\r\n service=\"hk-ado-jarvis-chatbot-service-prd\",\r\n serverIp=~\".*\",\r\n callKind=~\"http|rpc|custom_entry|server\",\r\n rpc!~\".*/liveness$\",\r\n source=\"apm\",\r\n }[$__range]))\r\n or vector(1)\r\n ) * 10\r\n) / 10\r\n",
     "legendFormat": "chatbot resp"
    },
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_seconds_raw{service=\"hk-ado-jarvis-generic-service-prd\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",source=\"apm\",}[$__range]))/sum(sum_over_time_lorc(arms_app_requests_count_raw{service=\"hk-ado-jarvis-generic-service-prd\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",source=\"apm\"}[$__range])) or vector(0)",
     "legendFormat": " generic resp"
    },
    {
     "expr": "count(max by(container_id)(kube_pod_container_info{namespace=\"ns-hkg-agent-system\",pod=~\"^dep-hk-ado-jarvis-chatbot-service.*\"}))",
     "legendFormat": "chatbot pod"
    },
    {
     "expr": "count(max by(container_id)(kube_pod_container_info{namespace=\"ns-hkg-agent-system\",pod=~\"^dep-hk-ado-jarvis-ai-service.*\"}))",
     "legendFormat": "ai pod"
    },
    {
     "expr": "count(max by(container_id)(kube_pod_container_info{namespace=\"ns-hkg-agent-system\",pod=~\"^dep-hk-ado-jarvis-generic-service.*\"}))",
     "legendFormat": "generic pod"
    },
    {
     "expr": "topk(1,sum by (container,pod)(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"ns-hkg-agent-system\",pod=~\"^dep-hk-ado-jarvis-ai-service.*\"}))",
     "legendFormat": "ai cpu"
    },
    {
     "expr": "topk(1,sum by (container,pod)(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"ns-hkg-agent-system\",pod=~\"^dep-hk-ado-jarvis-chatbot-service.*\"}))",
     "legendFormat": "chatbot cpu"
    },
    {
     "expr": "topk(1,sum by (container,pod)(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"ns-hkg-agent-system\",pod=~\"^dep-hk-ado-jarvis-generic-service.*\"}))",
     "legendFormat": "generic cpu"
    },
    {
     "expr": "topk(1,sum by (container,pod)(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"ns-hkg-agent-system\",pod=~\"^dep-hk-ado-jarvis-generic-service.*\"}))",
     "legendFormat": "generic mem"
    },
    {
     "expr": "topk(1,sum by (container,pod)(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"ns-hkg-agent-system\",pod=~\"^dep-hk-ado-jarvis-chatbot-service.*\"}))",
     "legendFormat": "chatbot mem"
    },
    {
     "expr": "topk(1,sum by (container,pod)(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"ns-hkg-agent-system\",pod=~\"^dep-hk-ado-jarvis-ai-service.*\"}))",
     "legendFormat": "ai mem"
    }
   ]
  },
  {
   "title": "ALB Req (Count/5m)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(AliyunAlb_LoadBalancerQPS{regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\"}[5m])",
     "legendFormat": "alb qps"
    }
   ]
  },
  {
   "title": "ALB Suc rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(AliyunAlb_LoadBalancerHTTPCodeUpstream2XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"})\r\n/\r\nsum(\r\n AliyunAlb_LoadBalancerHTTPCodeUpstream2XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream3XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream4XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream5XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\n)\r\n",
     "legendFormat": "alb rate"
    }
   ]
  },
  {
   "title": "ALB Backend Resp",
   "type": "timeseries",
   "description": "负载均衡实例后端应答时间(ms)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "AliyunAlb_LoadBalancerUpstreamResponseTime{loadBalancerId=~\"$loadBalancerId\"}",
     "legendFormat": "Alb resp"
    }
   ]
  },
  {
   "title": "GW Req (Count/5m)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "AliyunCnapigateway_EnvoyApiQps{apiName=~\"$GWSVC\"}",
     "legendFormat": "gw qps"
    }
   ]
  },
  {
   "title": "GW Suc rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(AliyunCnapigateway_EnvoyDownstreamSuccessRate,0.01)",
     "legendFormat": "{{instanceName}}"
    }
   ]
  },
  {
   "title": "GW Resp",
   "type": "timeseries",
   "description": "网关Operation请求平均时延",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "AliyunCnapigateway_EnvoyApiRtAvg{apiName=~\"$GWSVC\"}",
     "legendFormat": "gw resp"
    }
   ]
  },
  {
   "title": "ASM Req (Count/5m)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (istio)(rate(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\"}[5m]))",
     "legendFormat": "asm qps"
    }
   ]
  },
  {
   "title": "ASM Suc Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(istio_requests_total{destination_app=\"$ASMSVC\",response_code=~\"2..\"}[5m]))/sum(sum_over_time(istio_requests_total{destination_app=\"$ASMSVC\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ASM Resp",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (callType) (arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc_rpc{namespace=\"$NameSpace\",callKind=~\"$incallKind\"})/sum by (callType) (arms_app_requests_count_ign_destid_endpoint_ppid_prpc_rpc{namespace=\"$NameSpace\",callKind=~\"$incallKind\"})",
     "legendFormat": "Asm resp"
    }
   ]
  },
  {
   "title": "APP Req (Count/5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(service)(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",namespace=\"$NameSpace\",source=\"apm\"}[5m])) -1",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "App Suc Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(app)(sum_over_time_lorc(arms_requests_by_status_count_raw {source=\"apm\",status=~\"2..\",namespace=\"$NameSpace\"}[5m]))/sum by(app)(sum_over_time_lorc(arms_requests_by_status_count_raw {source=\"apm\",namespace=\"$NameSpace\"}[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "App Resp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (service) (arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc_rpc{callKind=~\"$incallKind\",rpc!~\".*/liveness$\",namespace=\"$NameSpace\"})/sum by (service) (arms_app_requests_count_ign_destid_endpoint_ppid_prpc_rpc{callKind=~\"$incallKind\",rpc!~\".*/liveness$\",namespace=\"$NameSpace\"})",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}