{
 "title": "DTS",
 "tags": [
  "dts",
  "scene:database",
  "cmee",
  "addon:name:cloud-dts",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:dts-overview",
  "addon:version:0.0.3",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instanceName",
    "query": "label_values({__name__=~\"AliyunDts_SynchronizationLatency|AliyunDts_MigrationLatency|AliyunDts_ChangeTrackingLatency\"},instanceName)"
   },
   {
    "name": "instanceId",
    "query": "label_values({__name__=~\"AliyunDts_SynchronizationLatency|AliyunDts_MigrationLatency|AliyunDts_ChangeTrackingLatency\"},instanceId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Migration delay (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "AliyunDts_MigrationLatency{instanceName=~\"$instanceName\",instanceId=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Synchronization delay (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "AliyunDts_SynchronizationLatency{instanceName=~\"$instanceName\",instanceId=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Subscription delay (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "AliyunDts_ChangeTrackingLatency{instanceName=~\"$instanceName\",instanceId=~\"$instanceId\"}",
     "legendFormat": "{{instanceId}}"
    }
   ]
  }
 ]
}