{
 "title": "ECS Public Network Monitor",
 "tags": [
  "CloudMonitor",
  "scene:host",
  "ECS",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:cmee-ecs-network-dashboard",
  "Network",
  "addon:name:cloud-ecs",
  "prometheus",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(AliyunEcs_VPC_PublicIP_InternetInRate, regionId)"
    }
   },
   {
    "name": "rmgroup",
    "label": "Resource Group",
    "query": {
     "query": "label_values(AliyunEcs_VPC_PublicIP_InternetInRate, resourceGroupName)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "ECS public network inbound bandwidth total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(AliyunEcs_VPC_PublicIP_InternetInRate{regionId=~\"$region\",resourceGroupName=~\"$rmgroup\"})"
    }
   ]
  },
  {
   "title": "ECS public network outbound bandwidth total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(AliyunEcs_VPC_PublicIP_InternetOutRate{regionId=~\"$region\",resourceGroupName=~\"$rmgroup\"})"
    }
   ]
  },
  {
   "title": "ECS public network bandwidth top",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "AliyunEcs_VPC_PublicIP_InternetInRate{regionId=~\"$region\",resourceGroupName=~\"$rmgroup\"}/1024/1024"
    },
    {
     "expr": "AliyunEcs_VPC_PublicIP_InternetOutRate{regionId=~\"$region\",resourceGroupName=~\"$rmgroup\"}/1024/1024"
    },
    {
     "expr": "AliyunEcs_VPC_PublicIP_InternetOutRate_Percent{regionId=~\"$region\",resourceGroupName=~\"$rmgroup\"}"
    }
   ]
  },
  {
   "title": "ECS public network inbound bandwidth top 5",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(5,AliyunEcs_VPC_PublicIP_InternetInRate{regionId=~\"$region\",resourceGroupName=~\"$rmgroup\"})",
     "legendFormat": "{{hostName}}#{{ip}}#{{instanceName}}"
    }
   ]
  },
  {
   "title": "ECS public network outbound bandwidth top 5",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(5,AliyunEcs_VPC_PublicIP_InternetOutRate{regionId=~\"$region\",resourceGroupName=~\"$rmgroup\"})",
     "legendFormat": "{{hostName}}#{{ip}}#{{instanceName}}"
    }
   ]
  },
  {
   "title": "ECS public network outbound bandwidth utilization top 5",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5,AliyunEcs_VPC_PublicIP_InternetOutRate_Percent{regionId=~\"$region\",resourceGroupName=~\"$rmgroup\"})",
     "legendFormat": "{{hostName}}#{{ip}}#{{instanceName}}"
    }
   ]
  }
 ]
}