{
 "title": "ECS resource regional distribution template",
 "tags": [
  "scene:host",
  "cmee",
  "ecs",
  "env:Cloud",
  "env:type:Cloud",
  "addon:name:cloud-ecs",
  "prometheus",
  "dashboard:name:cmee-ecs-resource-distribution",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(AliyunEcs_cpu_cores,regionId)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Basic indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total number of ECS instances in $region",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (regionId) (AliyunEcs_CPUUtilization{regionId=~\"$region\"})",
     "legendFormat": "{{regionId}}"
    }
   ]
  },
  {
   "title": "Total number of CPU cores of ECS instances in $region",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ncount" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (regionId) (AliyunEcs_cpu_cores{regionId=~\"$region\"})",
     "legendFormat": "{{regionId}}"
    }
   ]
  },
  {
   "title": "Percentage of memory used in $region",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pcount" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (regionId) (AliyunEcs_memory_usedutilization{regionId=~\"$region\"})",
     "legendFormat": "{{regionId}}"
    }
   ]
  },
  {
   "title": "Total memory space of ECS instances in $region",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decount" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (regionId) (AliyunEcs_memory_totalspace{regionId=~\"$region\"})",
     "legendFormat": "{{regionId}}"
    }
   ]
  },
  {
   "title": "Percentage of disk space remaining available in $region",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pcount" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (regionId) (AliyunEcs_diskusage_free{regionId=~\"$region\"}) / sum by (regionId) (AliyunEcs_diskusage_total{regionId=~\"$region\"}) * 100",
     "legendFormat": "{{regionId}}"
    }
   ]
  },
  {
   "title": "Total disk space of ECS instances in $region",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decount" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (regionId) (AliyunEcs_diskusage_total{regionId=~\"$region\"})",
     "legendFormat": "{{regionId}}"
    }
   ]
  },
  { "title": "TCP connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total number of TCP connections of ECS instances in $region",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "repeat": "region",
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "sum by (regionId,state) (AliyunEcs_net_tcpconnection{regionId=~\"$region\"})",
     "legendFormat": "{{regionId}}/{{state}}"
    }
   ]
  }
 ]
}