{
 "title": "ECS instance details",
 "tags": [
  "scene:host",
  "cmee",
  "ecs",
  "env:Cloud",
  "env:type:Cloud",
  "addon:version:0.0.1",
  "addon:name:cloud-ecs",
  "prometheus",
  "dashboard:name:cmee-ecs-instance-info",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "label": "Region",
    "query": "label_values(AliyunEcs_CPUUtilization{regionId!=\"--\"}, regionId)"
   },
   {
    "name": "instanceName",
    "label": "InstanceName",
    "query": "label_values(AliyunEcs_CPUUtilization{regionId=~\"$regionId\"},instanceName)"
   },
   {
    "name": "nodeIp",
    "label": "NodeIP",
    "query": "label_values(AliyunEcs_CPUUtilization{regionId=~\"$regionId\",instanceName=~\"$instanceName\"}, nodeIp)"
   },
   {
    "name": "instanceId",
    "label": "InstanceID",
    "query": "label_values(AliyunEcs_CPUUtilization{regionId=~\"$regionId\",instanceName=~\"$instanceName\",nodeIp=~\"$nodeIp\"}, instanceId)"
   },
   {
    "name": "tagKey",
    "label": "TagKey",
    "query": "label_values(cloud_monitor_instance_tag{regionId=~\"$regionId\",product=\"ecs\" },key)"
   },
   {
    "name": "tagValue",
    "label": "TagValue",
    "query": "query_result(cloud_monitor_instance_tag{key=~\"o11y.aliyun.dev/$tagKey\",regionId=~\"$regionId\",product=\"ecs\"}>0)"
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ECS Average CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_CPUUtilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"})"
    }
   ]
  },
  {
   "title": "ECS CPU Total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_cpu_total{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}) "
    }
   ]
  },
  {
   "title": "ECS Average Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_memory_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"})"
    }
   ]
  },
  {
   "title": "ECS Diskusage Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_diskusage_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"})"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AliyunEcs_load_1m{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
     "legendFormat": "{{hostName}}/{{instanceName}}#1m"
    },
    {
     "expr": "AliyunEcs_load_5m{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
     "legendFormat": "{{hostName}}/{{instanceName}}#5m"
    },
    {
     "expr": "AliyunEcs_load_15m{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
     "legendFormat": "{{hostName}}/{{instanceName}}#15m"
    }
   ]
  },
  {
   "title": "Net Tcp Connection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "yaxes": [
    { "format": "count" }
   ],
   "targets": [
    {
     "expr": "AliyunEcs_net_tcpconnection{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
     "legendFormat": "{{hostName}}/{{instanceName}}#{{state}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "AliyunEcs_CPUUtilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}"
      }
     ]
    },
    {
     "title": "Current CPU Idle",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "AliyunEcs_cpu_idle{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "AliyunEcs_memory_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}"
      }
     ]
    },
    {
     "title": "Current Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "AliyunEcs_memory_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "AliyunEcs_diskusage_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}"
      }
     ]
    },
    {
     "title": "Current Disk Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "AliyunEcs_diskusage_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Read Bps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskReadBPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Write Bps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskWriteBPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Read IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskReadIOPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Write IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskWriteIOPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Internet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Internet In Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "AliyunEcs_InternetInRate{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Current Internet Out Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "AliyunEcs_InternetOutRate{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Intranet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Intranet In Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "AliyunEcs_IntranetInRate{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Current Intranet Out Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "AliyunEcs_IntranetOutRate{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Power Readings Power Draw",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "AliyunEcs_instance_gpu_power_readings_power_draw{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Decoder Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_decoder_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Encoder Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_encoder_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_gpu_temperature{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Used Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_gpu_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Memory Free Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_memory_freespace{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Memory Free Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_memory_freeutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Memory Used Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_memory_usedspace{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Memory Used Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_memory_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  }
 ]
}