{
 "title": "ECS instance details",
 "tags": [ "ecs" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "label": "Region",
    "query": {
     "query": "label_values(AliyunEcs_CPUUtilization{regionId!=\"--\"}, regionId)"
    }
   },
   {
    "name": "instanceName",
    "label": "InstanceName",
    "query": {
     "query": "label_values(AliyunEcs_CPUUtilization{regionId=~\"$regionId\"},instanceName)"
    }
   },
   {
    "name": "nodeIp",
    "label": "NodeIP",
    "query": {
     "query": "label_values(AliyunEcs_CPUUtilization{regionId=~\"$regionId\",instanceName=~\"$instanceName\"}, nodeIp)"
    }
   },
   {
    "name": "instanceId",
    "label": "InstanceID",
    "query": {
     "query": "label_values(AliyunEcs_CPUUtilization{regionId=~\"$regionId\",instanceName=~\"$instanceName\",nodeIp=~\"$nodeIp\"}, instanceId)"
    }
   },
   {
    "name": "tagKey",
    "label": "TagKey",
    "query": {
     "query": "label_values(cloud_monitor_instance_tag{regionId=~\"$regionId\",product=\"ecs\" },key)"
    }
   },
   {
    "name": "tagValue",
    "label": "TagValue",
    "query": {
     "query": "query_result(cloud_monitor_instance_tag{key=~\"o11y.aliyun.dev/$tagKey\",regionId=~\"$regionId\",product=\"ecs\"}>0)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "Env",
    "label": "Env",
    "query": {
     "query": "label_values(AliyunEcs_CPUUtilization{unique_cluster_account!=\"--\"},unique_cluster_account)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total ECS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cloud_monitor_instance_info{service=\"ecs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ECS Average CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_CPUUtilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"})"
    }
   ]
  },
  {
   "title": "ECS CPU Total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_cpu_total{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}) "
    }
   ]
  },
  {
   "title": "ECS Average Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_memory_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"})"
    }
   ]
  },
  {
   "title": "ECS Diskusage Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_diskusage_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"})"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "AliyunEcs_load_1m{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
     "legendFormat": "{{hostName}}/{{instanceName}}#1m"
    },
    {
     "expr": "AliyunEcs_load_5m{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
     "legendFormat": "{{hostName}}/{{instanceName}}#5m"
    },
    {
     "expr": "AliyunEcs_load_15m{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
     "legendFormat": "{{hostName}}/{{instanceName}}#15m"
    }
   ]
  },
  {
   "title": "Net Tcp Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "AliyunEcs_net_tcpconnection{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
     "legendFormat": "{{hostName}}/{{instanceName}}#{{state}}"
    }
   ]
  },
  {
   "title": "ECS instance Detail",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(AliyunEcs_cpu_total{})by(nodeIp,instanceId,instanceName,unique_cluster_account)"
    },
    {
     "expr": "avg(AliyunEcs_memory_usedutilization{})by(nodeIp,instanceId,instanceName,unique_cluster_account)"
    },
    {
     "expr": "avg(AliyunEcs_net_tcpconnection{state=\"ESTABLISHED\"})by(nodeIp,instanceId,instanceName,unique_cluster_account)"
    },
    {
     "expr": "max(AliyunEcs_IntranetInRate{})by(nodeIp,instanceId,instanceName,unique_cluster_account)/1024"
    },
    {
     "expr": "max(AliyunEcs_IntranetOutRate{})by(nodeIp,instanceId,instanceName,unique_cluster_account)/1024"
    },
    {
     "expr": "avg(AliyunEcs_VPC_PublicIP_InternetOutRate_Percent{})by(nodeIp,instanceId,instanceName,unique_cluster_account) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "AliyunEcs_CPUUtilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}"
      }
     ]
    },
    {
     "title": "Current CPU Idle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "AliyunEcs_cpu_idle{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "AliyunEcs_memory_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}"
      }
     ]
    },
    {
     "title": "Current Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "AliyunEcs_memory_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "targets": [
      {
       "expr": "AliyunEcs_diskusage_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}"
      }
     ]
    },
    {
     "title": "Current Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "targets": [
      {
       "expr": "AliyunEcs_diskusage_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Read Bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskReadBPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Write Bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskWriteBPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Read IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskReadIOPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Disk Write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "AliyunEcs_DiskWriteIOPS{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Internet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Internet In Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "AliyunEcs_InternetInRate{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Current Internet Out Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "AliyunEcs_InternetOutRate{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Intranet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Intranet In Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "AliyunEcs_IntranetInRate{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}/1024/1024",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "Current Intranet Out Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "AliyunEcs_IntranetOutRate{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}/1024/1024",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Power Readings Power Draw",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "AliyunEcs_instance_gpu_power_readings_power_draw{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Decoder Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_decoder_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Encoder Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_encoder_utilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_gpu_temperature{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Used Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_gpu_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Memory Free Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_memory_freespace{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Memory Free Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_memory_freeutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Memory Used Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_memory_usedspace{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    },
    {
     "title": "GPU Memory Used Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "AliyunEcs_gpu_memory_usedutilization{instanceId=~\"$instanceId\",nodeIp=~\"$nodeIp\",${tagKey}=~\"$tagValue\"}",
       "legendFormat": "{{hostName}}/{{instanceName}}"
      }
     ]
    }
   ]
  }
 ]
}