{
 "title": "ECS instance utilization sorting disk",
 "tags": [
  "scene:host",
  "cmee",
  "ecs",
  "env:Cloud",
  "env:type:Cloud",
  "addon:name:cloud-ecs",
  "dashboard:name:cmee-ecs-instance-utilization",
  "prometheus",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(AliyunEcs_cpu_total,regionId)"
    }
   },
   {
    "name": "instanceId",
    "query": {
     "query": "label_values(AliyunEcs_cpu_total,instanceId)"
    }
   },
   { "name": "TopByRegion", "label": "Top by region", "query": "3,5,10,20,30,50" },
   { "name": "topall", "label": "TOP", "query": "3,5,10,20,30,50" },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Top by region-$TopByRegion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Datasource" },
  {
   "title": "Top${TopByRegion} of $region/CPU utilization",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "repeat": "region",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($TopByRegion,AliyunEcs_cpu_total{regionId=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Top${TopByRegion} of $region/Memory utilization",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "repeat": "region",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($TopByRegion,AliyunEcs_memory_usedutilization{regionId=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Top${TopByRegion} of $region/Disk utilization",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "repeat": "region",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($TopByRegion,AliyunEcs_diskusage_utilization{regionId=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Top${TopByRegion} of $region/Number of connections",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "repeat": "region",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk($TopByRegion,AliyunEcs_net_tcpconnection{regionId=~\"$region\",state=\"ESTABLISHED\"})"
    }
   ]
  },
  {
   "title": "Top${TopByRegion} of specified region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Top$topall of $region/CPU utilization",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($topall,AliyunEcs_cpu_total{regionId=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Top$topall of $region/Memory utilization",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($topall,AliyunEcs_memory_usedutilization{regionId=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Top$topall of $region/Disk utilization",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($topall,AliyunEcs_diskusage_utilization{regionId=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Top${topall} of $region/Number of connections",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk($topall,AliyunEcs_net_tcpconnection{regionId=~\"$region\",state=\"ESTABLISHED\"})"
    }
   ]
  },
  { "title": "All instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Top${topall} of $region/ECS instance resource usage",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "AliyunEcs_cpu_total{regionId=~\"$region\"} "
    },
    {
     "expr": "AliyunEcs_memory_usedutilization{regionId=~\"$region\"}"
    },
    {
     "expr": "AliyunEcs_net_tcpconnection{regionId=~\"$region\",state=\"ESTABLISHED\"}"
    },
    {
     "expr": "max(AliyunEcs_diskusage_utilization{regionId=~\"$region\"}) by (regionId,instanceName,instanceId)"
    }
   ]
  }
 ]
}