{
 "title": "Elasticsearch cluster monitoring template",
 "tags": [
  "cmee",
  "elasticsearch",
  "env:Cloud",
  "scene:big-data",
  "env:type:Cloud",
  "addon:name:cloud-es",
  "addon:version:0.0.3",
  "dashboard:name:cmee-es-overview",
  "prometheus",
  "es"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "query": {
     "query": "label_values(AliyunElasticsearch_NodeCPUUtilization,regionId)"
    }
   },
   {
    "name": "description",
    "query": {
     "query": "label_values(AliyunElasticsearch_NodeCPUUtilization{regionId=~\"$regionId\"},description)"
    }
   },
   {
    "name": "clusterId",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(AliyunElasticsearch_NodeCPUUtilization{regionId=\"$regionId\",description=~\"$description\"},clusterId)"
    }
   },
   {
    "name": "nodeIP",
    "label": "Node IP",
    "query": {
     "query": "label_values(AliyunElasticsearch_NodeCPUUtilization{regionId=~\"$regionId\",clusterId=~\"$clusterId\"},nodeIP)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Elasticsrarch-cluster status",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "AliyunElasticsearch_ClusterStatus{regionId=~\"$regionId\",clusterId=~\"$clusterId\"}"
    },
    {
     "expr": "AliyunElasticsearch_ClusterAutoSnapshotLatestStatus{regionId=~\"$regionId\",clusterId=~\"$clusterId\"}"
    }
   ]
  },
  {
   "title": "Elasticsrarch-cluster write QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "AliyunElasticsearch_ClusterIndexQPS{regionId=~\"$regionId\",clusterId=~\"$clusterId\"}",
     "legendFormat": "{{description}}/{{clusterId}}"
    }
   ]
  },
  {
   "title": "Elasticsrarch-cluster query QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "AliyunElasticsearch_ClusterQueryQPS{regionId=~\"$regionId\",clusterId=~\"$clusterId\"}",
     "legendFormat": "{{description}}/{{clusterId}}"
    }
   ]
  },
  {
   "title": "Elasticsrarch-node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "AliyunElasticsearch_NodeCPUUtilization{regionId=~\"$regionId\",clusterId=~\"$clusterId\",nodeIP=~\"$nodeIP\"}",
     "legendFormat": "{{description}}/{{clusterId}}/{{nodeIP}}"
    }
   ]
  },
  {
   "title": "Elasticsrarch-node Load_1m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "AliyunElasticsearch_NodeLoad_1m{regionId=~\"$regionId\",clusterId=~\"$clusterId\",nodeIP=~\"$nodeIP\"}",
     "legendFormat": "{{description}}/{{clusterId}}/{{nodeIP}}"
    }
   ]
  },
  {
   "title": "Elasticsrarch-node disk usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "AliyunElasticsearch_NodeDiskUtilization{regionId=~\"$regionId\",clusterId=~\"$clusterId\",nodeIP=~\"$nodeIP\"}",
     "legendFormat": "{{description}}/{{clusterId}}/{{nodeIP}}"
    }
   ]
  },
  {
   "title": "Elasticsrarch-node HeapMemory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "AliyunElasticsearch_NodeHeapMemoryUtilization{regionId=~\"$regionId\",clusterId=~\"$clusterId\",nodeIP=~\"$nodeIP\"}",
     "legendFormat": "{{description}}/{{clusterId}}/{{nodeIP}}"
    }
   ]
  },
  {
   "title": "Elasticsrarch-node network outflow packet",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "AliyunElasticsearch_NodeStatsNetworkoutPackages{regionId=~\"$regionId\",clusterId=~\"$clusterId\",nodeIP=~\"$nodeIP\"}",
     "legendFormat": "{{description}}/{{clusterId}}/{{nodeIP}}"
    }
   ]
  },
  {
   "title": "Elasticsrarch-Exception times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Counts" } },
   "targets": [
    {
     "expr": "AliyunElasticsearch_NodeStatsExceptionLogCount{regionId=~\"$regionId\",clusterId=~\"$clusterId\",nodeIP=~\"$nodeIP\"}",
     "legendFormat": "{{description}}/{{clusterId}}/{{nodeIP}}"
    }
   ]
  },
  {
   "title": "Elasticsrarch-FullGc times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Counts" } },
   "targets": [
    {
     "expr": "AliyunElasticsearch_NodeStatsFullGcCollectionCount{regionId=~\"$regionId\",clusterId=~\"$clusterId\",nodeIP=~\"$nodeIP\"}",
     "legendFormat": "{{description}}/{{clusterId}}/{{nodeIP}}"
    }
   ]
  }
 ]
}