{
 "title": "Envoy Cluster",
 "description": "Envoy proxy monitoring Dashboard with service level templates.",
 "tags": [
  "addon:name:cloud-ingressenvoy",
  "scene:middleware",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:envoy-cluster",
  "addon:version:0.0.2",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instanceid",
    "label": "InstanceId",
    "query": "label_values(envoy_server_live, kubeone_ali_appinstance_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(envoy_cluster_upstream_cx_active{kubeone_ali_appinstance_name='$instanceid-envoy'}, cluster_name)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(envoy_cluster_upstream_cx_active{kubeone_ali_appinstance_name='$instanceid-envoy', cluster_name=~\".*$service.*\"}, cluster_name)"
   },
   {
    "name": "version",
    "label": "version",
    "query": "label_values(envoy_cluster_upstream_cx_active{kubeone_ali_appinstance_name='$instanceid-envoy', cluster_name=~\".*$service.*\"}, cluster_name)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Service PV ",
   "type": "stat",
   "description": "($service) pv",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_cluster_upstream_rq_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound_${port}_${version}_${service}\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Connect Fail Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_cluster_upstream_cx_connect_fail{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound_${port}_${version}_${service}\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Service Endpoint",
   "type": "stat",
   "description": "($service) pv",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(sum(envoy_cluster_membership_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound_${port}_${version}_${service}\"}) by (pod_name))\n"
    }
   ]
  },
  {
   "title": "Total bytes sent",
   "type": "stat",
   "description": "Total bytes sent",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_cluster_upstream_cx_tx_bytes_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound_${port}_${version}_${service}\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total bytes received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_cluster_upstream_cx_rx_bytes_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound_${port}_${version}_${service}\"}[$__range]))"
    }
   ]
  },
  { "title": "UpStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Upstream QPS",
   "type": "graph",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(rate(envoy_cluster_upstream_rq_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$service\"}[2m])) by (cluster_name), \"service_name\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")",
     "legendFormat": "QPS_{{version}}"
    }
   ]
  },
  {
   "title": "Error Request Per Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(rate(envoy_cluster_upstream_rq{ envoy_clusterid=\"${instanceid}\",cluster_name=~\"outbound_${port}_${version}_${service}\"}[2m])) by (response_code_class, cluster_name), \"service_name\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")",
     "legendFormat": "{{response_code_class}}_{{version}}"
    }
   ]
  },
  {
   "title": "Upstream Total Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(envoy_cluster_upstream_cx_active{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound_${port}_${version}_${service}\"}) by (cluster_name), \"service_name\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")",
     "legendFormat": "Connections_{{ version }}"
    }
   ]
  },
  {
   "title": "RT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound_${port}_${version}_${service}\"}[2m])) by (cluster_name) / sum(rate(envoy_cluster_upstream_rq_time_count{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound_${port}_${version}_${service}\"}[2m])) by (cluster_name)",
     "legendFormat": "RT(avg)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound_${port}_${version}_${service}\"}[2m])) by (le, cluster_name))",
     "legendFormat": "RT(p99)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(envoy_cluster_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound_${port}_${version}_${service}\"}[2m])) by (le, cluster_name))",
     "legendFormat": "RT(p90)"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound_${port}_${version}_${service}\"}[2m]))",
     "legendFormat": "Bytes Sent"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound_${port}_${version}_${service}\"}[2m]))",
     "legendFormat": "Bytes Received"
    }
   ]
  },
  {
   "title": "Retry Per Seconds",
   "type": "graph",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(rate(envoy_cluster_upstream_rq_retry{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$service\"}[2m])) by (cluster_name), \"service_name\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")",
     "legendFormat": "Retry Per Seconds :{{version}}"
    }
   ]
  },
  {
   "title": "Connect Fail Per Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(rate(envoy_cluster_upstream_cx_connect_fail{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$service\"}[2m])) by (cluster_name), \"service_name\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")",
     "legendFormat": "Connect Fail Per Seconds :{{version}}"
    }
   ]
  },
  {
   "title": "Connect RT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(rate(envoy_cluster_upstream_cx_connect_ms_sum{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$service\"}[2m])) / sum(rate(envoy_cluster_upstream_cx_connect_ms_count{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$service\"}[2m])) , \"service_name\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")",
     "legendFormat": "Connect RT(avg)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\",cluster_name=~\"outbound_${port}_${version}_${service}\"}[2m])) by (le))",
     "legendFormat": "RT(P99)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\",cluster_name=~\"outbound_${port}_${version}_${service}\"}[2m])) by (le))",
     "legendFormat": "RT(P90)"
    }
   ]
  }
 ]
}