{
 "title": "Envoy Top",
 "tags": [
  "addon:name:cloud-ingressenvoy",
  "scene:middleware",
  "env:Cloud",
  "env:type:Cloud",
  "addon:version:0.0.2",
  "prometheus",
  "dashboard:name:envoy-top"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instanceid",
    "query": {
     "query": "label_values(aliyun_ingress_envoy_request_count,envoy_clusterid)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Instance: ${instanceid} ", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Requests TOP10",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(label_replace(topk(10, sum(delta(envoy_cluster_upstream_rq_total{envoy_clusterid=\"$instanceid\", cluster_name=~\"outbound_([0-9]+)_(.*)_(.*)$\"}[$__range])) by (cluster_name)), \"service_name\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")"
    }
   ]
  },
  {
   "title": "Service RT TOP10",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(avg(delta(envoy_cluster_upstream_rq_time_sum{envoy_clusterid=\"$instanceid\", cluster_name=~\"outbound_([0-9]+)_(.*)_(.*)$\"}[$__range])) by (cluster_name) / avg(delta(envoy_cluster_upstream_rq_time_count{envoy_clusterid=\"$instanceid\", cluster_name=~\"outbound_([0-9]+)_(.*)_(.*)$\"}[$__range])) by (cluster_name), \"service_name\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")"
    },
    {}
   ]
  },
  {
   "title": "Service Failure Requests TOP10",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(topk(10, sum(delta(envoy_cluster_upstream_rq{response_code_class=~\"(4|5)xx\", envoy_clusterid=\"$instanceid\", cluster_name=~\"outbound_([0-9]+)_(.*)_(.*)$\"}[$__range])) by (cluster_name)), \"service_name\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")"
    }
   ]
  },
  {
   "title": "Service Endpoints TOP10",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(topk(10, avg(avg(envoy_cluster_membership_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound_([0-9]+)_(.*)_(.*)$\", cluster_name!~\".*waf-proxy.static\"}) by(pod_name, cluster_name)) by (cluster_name)), \"service_name\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")"
    }
   ]
  }
 ]
}