{
 "title": "Envoy Instance",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "addon:name:cloud-ingressenvoy",
  "scene:middleware",
  "env:Cloud",
  "env:type:Cloud",
  "addon:version:0.0.2",
  "prometheus",
  "dashboard:name:envoy-instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instanceid",
    "query": "label_values(aliyun_ingress_envoy_request_count,envoy_clusterid)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Instance: ${instanceid} ", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(container_memory_working_set_bytes{pod_name=~\"$instanceid.*\"}) by(pod_name))"
    }
   ]
  },
  {
   "title": "Pod Mem Used",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod_name=~\"$instanceid-envoy.*\"}) / sum(kube_pod_container_resource_limits_memory_bytes{pod_name=~\"$instanceid-envoy.*\"}) "
    }
   ]
  },
  {
   "title": "Pod CPU Usage Secs",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (sum(irate(container_cpu_usage_seconds_total{namespace=\"wakanda\", pod_name=~\"$instanceid-envoy.*\"}[2m])) / sum(max(kube_pod_container_resource_limits_cpu_cores{namespace=\"wakanda\", pod_name=~\"$instanceid-envoy.*\"})by (pod_name) ) )"
    }
   ]
  },
  {
   "title": "restarts_total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum ( (kube_pod_container_status_restarts_total{ pod_name=~\"$instanceid-envoy.*\"} ))"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod_name=~\"$instanceid-envoy.*\"}) / sum(kube_pod_container_resource_limits_memory_bytes{pod_name=~\"$instanceid-envoy.*\"}) ",
     "legendFormat": "Memory(avg)"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "100 * (sum(irate(container_cpu_usage_seconds_total{namespace=\"wakanda\", pod_name=~\"$instanceid-envoy.*\"}[1m])) / sum(max(kube_pod_container_resource_limits_cpu_cores{namespace=\"wakanda\", pod_name=~\"$instanceid-envoy.*\"})by (pod_name) ) )",
     "legendFormat": "CPU(avg)"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",pod_name=~\"$instanceid-envoy.*\"}[1m]))",
     "legendFormat": "Received {{pod_name}}"
    },
    {
     "expr": "-sum (rate (container_network_transmit_bytes_total{image!=\"\",pod_name=~\"$instanceid-envoy.*\"}[1m]))",
     "legendFormat": "Sent {{pod_name}}"
    }
   ]
  },
  {
   "title": "fs writes/reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "- sum (rate (container_fs_writes_bytes_total{image!=\"\",pod_name=~\"$instanceid-envoy.*\"}[1m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum (rate (container_fs_reads_bytes_total{image!=\"\",pod_name=~\"$instanceid-envoy.*\"}[1m])) ",
     "legendFormat": "read "
    }
   ]
  }
 ]
}