{
 "title": "Envoy Route",
 "description": "Envoy proxy monitoring Dashboard with service level templates.",
 "tags": [
  "addon:name:cloud-ingressenvoy",
  "scene:middleware",
  "env:Cloud",
  "env:type:Cloud",
  "addon:version:0.0.2",
  "prometheus",
  "dashboard:name:envoy-route"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instanceid",
    "label": "InstanceId",
    "query": {
     "query": "label_values(envoy_server_live, kubeone_ali_appinstance_name)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": "label_values(envoy_vhost_route_upstream_rq{kubeone_ali_appinstance_name='$instanceid-envoy'}, route)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Route PV ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_vhost_route_upstream_rq{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", route=\"${route}\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Timdout Request",
   "type": "stat",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_vhost_route_upstream_rq_timeout{envoy_clusterid=\"${instanceid}\", route=\"${route}\"}[$__range]))by (response_code_class)"
    }
   ]
  },
  {
   "title": "Upstream QPS",
   "type": "piechart",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_vhost_route_upstream_rq{envoy_clusterid=\"${instanceid}\", route=\"${route}\"}[$__range]))by (response_code_class)",
     "legendFormat": "{{ response_code_class}}"
    }
   ]
  },
  { "title": "UpStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Upstream QPS",
   "type": "graph",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_vhost_route_upstream_rq_total{envoy_clusterid=\"${instanceid}\", route=\"${route}\"}[2m]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Upstream Response Code Class Per Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_vhost_route_upstream_rq{envoy_clusterid=\"${instanceid}\", route=\"${route}\"}[2m]))by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "Failed Request Per Seconds",
   "type": "graph",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_vhost_route_upstream_rq_timeout{envoy_clusterid=\"${instanceid}\", route=\"${route}\"}[2m]))",
     "legendFormat": "Timedout Request Per Seconds"
    },
    {
     "expr": "sum(rate(envoy_vhost_route_upstream_rq_retry_success{envoy_clusterid=\"${instanceid}\", route=\"${route}\"}[2m]))",
     "legendFormat": "Retry Success Request Per Seconds"
    }
   ]
  },
  {
   "title": "RT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_vhost_route_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", route=\"${route}\"}[2m])) by (le))",
     "legendFormat": "RT(p99)"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_vhost_route_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", route=\"${route}\"}[2m])) by (le))",
     "legendFormat": "RT(p90)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_vhost_route_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", route=\"${route}\"}[2m])) by (le))",
     "legendFormat": "RT(p50)"
    }
   ]
  }
 ]
}