{
 "title": "Envoy General",
 "tags": [
  "addon:name:cloud-ingressenvoy",
  "scene:middleware",
  "dashboard:name:envoy-general",
  "env:Cloud",
  "env:type:Cloud",
  "addon:version:0.0.2",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instanceid",
    "query": "label_values(aliyun_ingress_envoy_request_count,envoy_clusterid)"
   },
   { "name": "compareTime", "label": "compareTime", "query": "1d,1w,1h" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Instance: ${instanceid} ", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PV",
   "type": "stat",
   "description": "The total number of requests for the selected time range\n",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_http_rq_total{envoy_clusterid=\"$instanceid\"}[$__range]))",
     "legendFormat": "current"
    },
    {
     "expr": "sum(delta(envoy_http_rq_total{envoy_clusterid=\"$instanceid\"}[$__range] offset $compareTime))",
     "legendFormat": "Compare "
    }
   ]
  },
  {
   "title": "Ingress traffic",
   "type": "stat",
   "description": "All bytes received in the range",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_http_downstream_cx_rx_bytes_total{envoy_clusterid=\"$instanceid\"}[$__range]))",
     "legendFormat": "current"
    },
    {
     "expr": "sum(delta(envoy_http_downstream_cx_rx_bytes_total{envoy_clusterid=\"$instanceid\"}[$__range] offset $compareTime))",
     "legendFormat": "compare"
    }
   ]
  },
  {
   "title": "Egress traffic",
   "type": "stat",
   "description": "All bytes sent in the range",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_http_downstream_cx_tx_bytes_total{envoy_clusterid=\"$instanceid\"}[$__range]))",
     "legendFormat": "current"
    },
    {
     "expr": "sum(delta(envoy_http_downstream_cx_tx_bytes_total{envoy_clusterid=\"$instanceid\"}[$__range] offset $compareTime))",
     "legendFormat": "compare"
    }
   ]
  },
  {
   "title": "Response code distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_http_downstream_rq{envoy_clusterid=\"$instanceid\"}[$__range])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "Request distribution Per Instance",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(delta(envoy_http_downstream_rq{envoy_clusterid=\"$instanceid\"}[$__range])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Request success rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_http_downstream_rq{response_code_class=~\"[4-5].*\",envoy_clusterid=\"$instanceid\"}[$__range])) / sum(delta(envoy_http_downstream_rq{envoy_clusterid=\"$instanceid\"}[$__range])) ",
     "legendFormat": "current"
    },
    {
     "expr": "sum(delta(envoy_http_downstream_rq{response_code_class=~\"[4-5].*\",envoy_clusterid=\"$instanceid\"}[$__range] offset $compareTime)) / sum(delta(envoy_http_downstream_rq{envoy_clusterid=\"$instanceid\"}[$__range] offset $compareTime)) ",
     "legendFormat": "compare"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(delta(envoy_http_downstream_rq{response_code_class=~\"4.*\",envoy_clusterid=\"$instanceid\"}[$__range])) by (response_code_class)",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(delta(envoy_http_downstream_rq{response_code_class=~\"5.*\",envoy_clusterid=\"$instanceid\"}[$__range])) by (response_code_class)",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time_sum{envoy_clusterid=\"$instanceid\"}[2m])) / sum(rate(envoy_http_downstream_rq_time_count{envoy_clusterid=\"$instanceid\"}[2m]))",
     "legendFormat": "current"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time_sum{envoy_clusterid=\"$instanceid\"}[2m] offset $compareTime)) / sum(rate(envoy_http_downstream_rq_time_count{envoy_clusterid=\"$instanceid\"}[2m] offset $compareTime))",
     "legendFormat": "compare"
    }
   ]
  },
  {
   "title": "P50 latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_clusterid=\"$instanceid\"}[2m])) by (le, service))",
     "legendFormat": "current"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_clusterid=\"$instanceid\"}[2m] offset $compareTime)) by (le, service))",
     "legendFormat": "compare"
    }
   ]
  },
  {
   "title": "P95 latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_clusterid=\"$instanceid\"}[2m])) by (le, service))",
     "legendFormat": "current"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_clusterid=\"$instanceid\"}[2m] offset $compareTime)) by (le, service))",
     "legendFormat": "compare"
    }
   ]
  },
  {
   "title": "P99 latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_clusterid=\"$instanceid\"}[2m])) by (le, service))",
     "legendFormat": "current"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_clusterid=\"$instanceid\"}[2m] offset $compareTime)) by (le, service))",
     "legendFormat": "compare"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq{envoy_clusterid=\"$instanceid\"}[2m]))",
     "legendFormat": "QPS"
    },
    {
     "expr": "sum(irate(envoy_http_downstream_rq{envoy_clusterid=\"$instanceid\"}[2m] offset $compareTime))",
     "legendFormat": "QPS($compareTime offset)"
    }
   ]
  },
  {
   "title": "Failure Requests Per Seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq{response_code_class=~\"[4-5].*\",envoy_clusterid=\"$instanceid\"}[2m])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time_sum{envoy_clusterid=\"$instanceid\"}[2m])) / sum(rate(envoy_http_downstream_rq_time_count{envoy_clusterid=\"$instanceid\"}[2m]))",
     "legendFormat": "RT(avg)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_clusterid=\"$instanceid\"}[2m])) by (le, service))",
     "legendFormat": "RT(p95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_clusterid=\"$instanceid\"}[2m])) by (le, service))",
     "legendFormat": "RT(p99)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_clusterid=\"$instanceid\"}[2m])) by (le, service))",
     "legendFormat": "RT(p50)"
    }
   ]
  }
 ]
}