{
 "title": "Envoy Global",
 "description": "Envoy proxy monitoring Dashboard with service level templates.",
 "tags": [
  "addon:name:cloud-ingressenvoy",
  "scene:middleware",
  "dashboard:name:envoy-global",
  "env:Cloud",
  "env:type:Cloud",
  "addon:version:0.0.2",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instanceid",
    "query": "label_values(aliyun_ingress_envoy_request_count,envoy_clusterid)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Instance: ${instanceid} ", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Gateway Base Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Request Per Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_rq_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\"}[2m])) by (kubeone_ali_appinstance_name)",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Connections Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_listener_downstream_cx_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\"}[2m]))",
     "legendFormat": "Connection Per Seconds"
    },
    {
     "expr": "sum(envoy_http_downstream_cx_active{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\"})",
     "legendFormat": "Active Connections"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time_sum{envoy_clusterid=\"$instanceid\"}[2m])) / sum(rate(envoy_http_downstream_rq_time_count{envoy_clusterid=\"$instanceid\"}[2m]))",
     "legendFormat": "Downstream RT(avg)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_clusterid=\"$instanceid\"}[2m])) by (le, service))",
     "legendFormat": "Downstream RT(P95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_clusterid=\"$instanceid\"}[2m])) by (le, service))",
     "legendFormat": "Downstream RT(P99)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_clusterid=\"$instanceid\"}[2m])) by (le, service))",
     "legendFormat": "Downstream RT(P50)"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(label_replace(sum(rate(envoy_cluster_upstream_rq{response_code_class=\"2xx\",pod_name=~\"$instanceid-envoy.*\"}[2m])) by (kubeone_ali_appinstance_name) / sum(rate(envoy_cluster_upstream_rq{pod_name=~\"$instanceid-envoy.*\"}[2m])) by (kubeone_ali_appinstance_name), \"gateway_name\", \"$1\", \"kubeone_ali_appinstance_name\", \"gw-(.*)-envoy\")) by (gateway_name) ",
     "legendFormat": "Upstream Success Rate"
    },
    {
     "expr": "avg(label_replace(sum(rate(envoy_http_downstream_rq{response_code_class=\"2xx\",pod_name=~\"$instanceid-envoy.*\"}[2m])) by (kubeone_ali_appinstance_name) / sum(rate(envoy_http_downstream_rq{pod_name=~\"$instanceid-envoy.*\"}[2m])) by (kubeone_ali_appinstance_name), \"gateway_name\", \"$1\", \"kubeone_ali_appinstance_name\", \"gw-(.*)-envoy\")) by (gateway_name) ",
     "legendFormat": "Downstream Success Rate"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_cx_rx_bytes_total{envoy_clusterid=~\"${instanceid}\"}[1m])) by (envoy_cluster_id)",
     "legendFormat": "Bytes Received"
    },
    {
     "expr": "sum(irate(envoy_http_downstream_cx_tx_bytes_total{envoy_clusterid=~\"${instanceid}\"}[1m])) by (envoy_cluster_id)",
     "legendFormat": "Bytes Sent"
    }
   ]
  },
  {
   "title": "TLS Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_listener_ssl_handshake{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\"}[1m]))",
     "legendFormat": "SSL HandShake Count Per Seconds"
    },
    {
     "expr": "sum(rate(envoy_listener_ssl_session_reused{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\"}[1m]))",
     "legendFormat": "SSL Reuse Count Per Second"
    }
   ]
  },
  { "title": "Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Upstream RPS",
   "type": "graph",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\"}[2m]))",
     "legendFormat": "Upstream QPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{ kubeone_ali_appinstance_name=~\"${instanceid}-envoy\"}[2m])) by (response_code_class)",
     "legendFormat": "{{ response_code_class }}"
    }
   ]
  },
  {
   "title": "Upstream CPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\"}[2m]))",
     "legendFormat": "Upstream Connection Per Second"
    },
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\"})",
     "legendFormat": "Upstream Active Connection"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\"}[2m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\"}[2m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\"}[2m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Service Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Service",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(envoy_cluster_upstream_cx_active{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound.*\"}) by ( cluster_name), \"destination\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")"
    },
    {
     "expr": "label_replace(label_replace(avg(envoy_cluster_membership_healthy{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound.*\"}) by (cluster_name) / avg(envoy_cluster_membership_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound.*\"}) by (cluster_name), \"destination\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")"
    },
    {
     "expr": "label_replace(label_replace(sum(irate(envoy_cluster_upstream_rq_time_count{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound.*\"}[1m])) by (cluster_name), \"destination\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")"
    },
    {
     "expr": "label_replace(label_replace(histogram_quantile(0.50, sum(rate(envoy_cluster_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound.*\"}[1m])) by (le, cluster_name)), \"destination\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")"
    },
    {
     "expr": "label_replace(label_replace(histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound.*\"}[1m])) by (le, cluster_name)), \"destination\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")"
    },
    {
     "expr": "label_replace(label_replace(sum(rate(envoy_cluster_upstream_rq{response_code_class=\"2xx\",kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound.*\"}[1m])) by (cluster_name) / sum(rate(envoy_cluster_upstream_rq{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\"outbound.*\"}[1m])) by (cluster_name), \"destination\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")"
    }
   ]
  },
  { "title": "Gateway Extra Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Compressed Traffic Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_compressor_text_optimized_gzip_total_uncompressed_bytes{envoy_clusterid=~\"${instanceid}\"}[2m])) ",
     "legendFormat": "NotCompressed Data"
    },
    {
     "expr": "sum(irate(envoy_http_compressor_text_optimized_gzip_total_compressed_bytes{envoy_clusterid=~\"${instanceid}\"}[2m]))",
     "legendFormat": "Compressed Data"
    }
   ]
  },
  {
   "title": "Compressed Request Info",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_compressor_text_optimized_gzip_compressed{envoy_clusterid=~\"${instanceid}\"}[2m])) ",
     "legendFormat": "Gzip Compressed Request Per Seconds"
    },
    {
     "expr": "sum(irate(envoy_http_compressor_text_optimized_gzip_not_compressed{envoy_clusterid=~\"${instanceid}\"}[2m])) ",
     "legendFormat": "Gzip NotCompressed Requests Per Seconds"
    }
   ]
  },
  {
   "title": "Custom Authentication",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_ext_authz_ok{envoy_clusterid=~\"${instanceid}\"}[2m]))",
     "legendFormat": "Auth Success Request Per Seconds"
    },
    {
     "expr": "sum(irate(envoy_http_ext_authz_denied{envoy_clusterid=~\"${instanceid}\"}[2m]))",
     "legendFormat": "Auth Failed Request Per Seconds"
    },
    {
     "expr": "sum(irate(envoy_http_ext_authz_disabled{envoy_clusterid=~\"${instanceid}\"}[2m]))",
     "legendFormat": "Auth Skip Request Per Seconds"
    },
    {
     "expr": "sum(irate(envoy_http_ext_authz_timeout{envoy_clusterid=~\"${instanceid}\"}[2m]))",
     "legendFormat": "Auth Timeout Request Per Second"
    }
   ]
  }
 ]
}