{
 "title": "Envoy Service Compare",
 "description": "Envoy proxy monitoring Dashboard with service level templates.",
 "tags": [
  "addon:name:cloud-ingressenvoy",
  "scene:middleware",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:envoy-service-compare",
  "addon:version:0.0.2",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instanceid",
    "label": "InstanceId",
    "query": "label_values(envoy_server_live, kubeone_ali_appinstance_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(envoy_cluster_upstream_cx_active{kubeone_ali_appinstance_name='$instanceid-envoy'}, cluster_name)"
   },
   {
    "name": "gray_service",
    "label": "Service(gray)",
    "query": "label_values(envoy_cluster_upstream_cx_active{kubeone_ali_appinstance_name='$instanceid-envoy'}, cluster_name)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Service PV ",
   "type": "stat",
   "description": "($service) pv",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_cluster_upstream_rq_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Gray Service PV",
   "type": "stat",
   "description": "$gray_service PV",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(envoy_cluster_upstream_rq_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$gray_service\"}[$__range]))"
    }
   ]
  },
  { "title": "UpStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Upstream QPS",
   "type": "graph",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$service\"}[2m]))",
     "legendFormat": "$service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$gray_service\"}[2m]))",
     "legendFormat": "$gray_service"
    }
   ]
  },
  {
   "title": "Error Request Per Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{response_code_class=~\"(4|5)xx\", envoy_clusterid=\"${instanceid}\",cluster_name=~\".*$service\"}[2m]))",
     "legendFormat": "$service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{response_code_class=~\"(4|5)xx\", envoy_clusterid=~\"${instanceid}\",cluster_name=~\".*$gray_service\"}[2m]))",
     "legendFormat": "$gray_service"
    }
   ]
  },
  {
   "title": "Upstream Total Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$service\"}) by (cluster_name)",
     "legendFormat": "$service"
    },
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$gray_service\"}) by (cluster_name)",
     "legendFormat": "$gray_service"
    }
   ]
  },
  {
   "title": "Avg RT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$service\"}[2m])) / sum(rate(envoy_cluster_upstream_rq_time_count{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$service\"}[2m]))",
     "legendFormat": "$service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$gray_service\"}[2m])) / sum(rate(envoy_cluster_upstream_rq_time_count{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$gray_service\"}[2m]))",
     "legendFormat": "$gray_service"
    }
   ]
  },
  {
   "title": "P99RT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$service\"}[2m])) by (le))",
     "legendFormat": "$service"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$gray_service\"}[2m])) by (le))",
     "legendFormat": "$gray_service"
    }
   ]
  },
  {
   "title": "P99RT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$service\"}[2m])) by (le))",
     "legendFormat": "$service"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{kubeone_ali_appinstance_name=~\"${instanceid}-envoy\", cluster_name=~\".*$gray_service\"}[2m])) by (le))",
     "legendFormat": "$gray_service"
    }
   ]
  }
 ]
}