{
 "title": "Function calculation",
 "tags": [
  "scene:ai",
  "env:Cloud",
  "env:type:Cloud",
  "addon:name:cloud-fc",
  "addon:version:0.0.3",
  "prometheus",
  "dashboard:name:cmee-fc-overview"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(AliyunFc_FunctionCost,region)"
    }
   },
   {
    "name": "serviceName",
    "query": {
     "query": "label_values(AliyunFc_FunctionCost{region=~\"$region\"},functionName)"
    }
   },
   {
    "name": "functionName",
    "query": {
     "query": "label_values(AliyunFc_FunctionCost{region=~\"$region\",serviceName=~\"$serviceName\"},functionName)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Function server error count ",
   "type": "timeseries",
   "description": "count",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunFc_FunctionServerErrors{region=~\"$region\",functionName=~\"$functionName\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{serviceName}}/{{functionName}}/{{region}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of function errors ",
   "type": "timeseries",
   "description": "count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunFc_FunctionFunctionErrors{region=~\"$region\",functionName=~\"$functionName\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{serviceName}}/{{functionName}}/{{region}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Maximum memory used by function ",
   "type": "timeseries",
   "description": "MBytes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunFc_FunctionMaxMemoryUsage{region=~\"$region\",serviceName=~\"$serviceName\",functionName=~\"$functionName\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{serviceName}}/{{functionName}}/{{region}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Function client error count ",
   "type": "timeseries",
   "description": "count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunFc_FunctionClientErrors{region=~\"$region\",serviceName=~\"$serviceName\",functionName=~\"$functionName\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{serviceName}}/{{functionName}}/{{region}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Function average execution time ",
   "type": "timeseries",
   "description": "milliseconds",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunFc_FunctionAvgDuration{region=~\"$region\",serviceName=~\"$serviceName\",functionName=~\"$functionName\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{serviceName}}/{{functionName}}/{{region}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Total number of service calls ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunFc_ServiceTotalInvocations{region=~\"$region\",serviceName=~\"$serviceName\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{serviceName}}/{{region}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of calls to a function billed ",
   "type": "timeseries",
   "description": "count",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunFc_FunctionBillableInvocations{region=~\"$region\",serviceName=~\"$serviceName\",functionName=~\"$functionName\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{serviceName}}/{{functionName}}/{{region}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Function billed requests as a percentage of total calls ",
   "type": "timeseries",
   "description": "count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunFc_FunctionBillableInvocationsRate{region=~\"$region\",serviceName=~\"$serviceName\",functionName=~\"$functionName\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{serviceName}}/{{functionName}}/{{region}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of concurrent instances of a function exceeds the maximum number of requests ",
   "type": "timeseries",
   "description": "count",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunFc_FunctionThrottles{region=~\"$region\",serviceName=~\"$serviceName\",functionName=~\"$functionName\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{serviceName}}/{{functionName}}/{{region}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of concurrent Instances of a function Exceeds the maximum number of requests to the total number of requests ",
   "type": "timeseries",
   "description": "count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunFc_FunctionThrottlesRate{region=~\"$region\",serviceName=~\"$serviceName\",functionName=~\"$functionName\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{serviceName}}/{{functionName}}/{{region}}",
     "method": "GET"
    }
   ]
  }
 ]
}