{
 "title": "High-speed channel-physical port-instance details dashboard",
 "tags": [
  "dashboard:name:port-detail",
  "scene:host",
  "env:Cloud",
  "env:type:Cloud",
  "addon:name:cloud-vbr",
  "addon:version:0.0.3",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "regionId",
    "label": "regionId",
    "query": {
     "query": "label_values(AliyunVbr_PhysicalConnectionErrorPkgCountRx,regionId)"
    }
   },
   {
    "name": "instanceId",
    "label": "InstanceId",
    "query": {
     "query": "label_values(AliyunVbr_PhysicalConnectionErrorPkgCountRx{regionId=~\"$regionId\"},id)"
    }
   },
   {
    "name": "instanceName",
    "label": "instanceName",
    "query": {
     "query": "label_values(AliyunVbr_PhysicalConnectionErrorPkgCountRx{regionId=~\"$regionId\", instanceId=~\"$instanceId\"},instanceName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of wrong packets inbound on the port",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_PhysicalConnectionErrorPkgCountRx{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of wrong packets outbound on the port",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_PhysicalConnectionErrorPkgCountTx{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Outflow rate from IDC to VPC on the port",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_PhysicalConnectionRateInFromIDCtoVpc{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Inflow rate from VPC to IDC on the port",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_PhysicalConnectionRateInFromVpctoIDC{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Physical dedicated line status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_PhysicalConnectionStatus{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Dedicated line traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_PhysicalConnectionTraffic{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  }
 ]
}