{
 "title": "High-speed channel - border router - instance details dashboard",
 "tags": [
  "scene:host",
  "env:Cloud",
  "env:type:Cloud",
  "addon:name:cloud-vbr",
  "addon:version:0.0.3",
  "prometheus",
  "dashboard:name:vbr-detail"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "regionId",
    "label": "regionId",
    "query": {
     "query": "label_values(AliyunVbr_BytesInFromIDCToVpc,regionId)"
    }
   },
   {
    "name": "instanceId",
    "label": "InstanceId",
    "query": {
     "query": "label_values(AliyunVbr_BytesInFromIDCToVpc{regionId=~\"$regionId\"},id)"
    }
   },
   {
    "name": "instanceName",
    "label": "instanceName",
    "query": {
     "query": "label_values(AliyunVbr_BytesInFromIDCToVpc{instanceId=~\"$instanceId\", regionId=~\"$regionId\"},instanceName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of bytes flowing in from IDC to VPC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_BytesInFromIDCToVpc{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of bytes flowing out from VPC to IDC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_BytesOutFromVpcToIDC{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of packets flowing in from IDC to VPC discarded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_PkgsDropInFromIDCToVpc{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of packets flowing out from VPC to IDC discarded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_PkgsDropOutFromVpcToIDC{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of packets flowing in from IDC to VPC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_PkgsInFromIDCToVpc{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of packets flowing out from VPC to IDC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_PkgsOutFromVpcToIDC{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of packets flowing in at rate limit discarded from VPC to VBR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_PkgsRateLimitDropOutFromVpcToVbr{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Inflow rate from IDC to VPC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_RateInFromIDCToVpc{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Outflow rate from VPC to IDC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_RateOutFromVpcToIDC{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "VBR health check latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_VbrHealthyCheckLatency{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "VBR health check packet loss rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunVbr_VbrHealthyCheckLossRate{id=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{regionId}}/{{instanceName}}/{{instanceId}}"
    }
   ]
  }
 ]
}