{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Env", "query": "dev,uat" },
   { "name": "datasource", "label": "AppEnv", "query": "prometheus" },
   { "name": "datasource_ack", "label": "ACK", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Application OverView", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace!~\".*arms-demo.*|.*hk-arms-demo.*|ns-hkg-alicloud-system|\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "All App PV"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hkg-agent-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "Jarvis PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-gft-atas-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "ATAS PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hkg-customer-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "ODS PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",rpc!~\".*/health/.*\",source=\"apm\",namespace=~\"ns-hkg-dcs-system\"}[$__range])) or vector(0)",
     "legendFormat": "DCS PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",rpc!~\".*/health/.*\",source=\"apm\",namespace=~\"ns-hbt-system\"}[$__range])) or vector(0)",
     "legendFormat": "HBT PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",rpc!~\".*/health/.*\",source=\"apm\",service=~\".*hk-ado-idp.*\"}[$__range])) or vector(0)",
     "legendFormat": "IDP PV"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hkg-policy-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "Policy PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\",source=\"apm\",namespace=~\"ns-hkg-shared-system\"}[$__range])) or vector(0)",
     "legendFormat": "Cashier PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hkg-pnf-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "PNF PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hkg-claims-system|ns-hkg-claims-vendor-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "Claims PV"
    }
   ]
  },
  {
   "title": "Application Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application List",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum (sum_over_time(arms_app_requests_count_raw{callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",rpc!~\".*/liveness$\",rpc!~\".*/health/.*\",}[$__range])) by(namespace,service)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(sum_over_time_lorc(arms_app_requests_error_count_ign_destid_endpoint_parent_ppid_prpc_rpc{host=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",namespace!~\"\" }[$__range])) by(namespace,service) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(sum_over_time(arms_app_requests_slow_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",source=\"apm\",namespace!~\"\" }[$__range]))by(namespace,service)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace,service) (sum_over_time_lorc(arms_app_requests_seconds_ign_parent_ppid_prpc_rpc{callType=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",destId=~\".*\",host=~\".*\",namespace!~\"\" }[$__range]))/sum by(namespace,service) (sum_over_time_lorc(arms_app_requests_count_ign_parent_ppid_prpc_rpc{callType=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",destId=~\".*\",host=~\".*\",namespace!~\"\" }[$__range]))*1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DB Req Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (endpoint) (sum_over_time(arms_db_requests_count_raw{}[$__range])) or vector(0)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "DB ERROR ",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (endpoint) (sum_over_time(arms_db_requests_error_count_raw{}[$__range])) or vector(0)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "DB-Resp-Status Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status) (sum_over_time(arms_requests_by_status_count_raw{callType=\"http\",status!~\"0|2..\"}[$__range]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "DB Response ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (endpoint) (sum_over_time(arms_db_requests_seconds_raw{}[$__range]))/sum by (endpoint) (sum_over_time(arms_db_requests_count_raw{}[$__range]))",
       "legendFormat": "{{endpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ContainerMonitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "APIServer API QPS",
     "type": "stat",
     "description": "当前集群的每秒请求数总量（包括全部读写请求）",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(apiserver_request_total[3m]))"
      }
     ]
    },
    {
     "title": "APIServer Read Suc Rate",
     "type": "stat",
     "description": "每秒的读请求成功率",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb=~\"GET|LIST\"}[3m]))/sum(irate(apiserver_request_total{verb=~\"GET|LIST\"}[3m]))"
      }
     ]
    },
    {
     "title": "APIServer Write Suc Rate",
     "type": "stat",
     "description": "每秒的修改请求的成功率",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb!~\"GET|LIST|WATCH|CONNECT\"}[3m]))/sum(irate(apiserver_request_total{verb!~\"GET|LIST|WATCH|CONNECT\"}[3m]))"
      }
     ]
    },
    {
     "title": "Write req handled by the APIServer",
     "type": "stat",
     "description": "集群内在处理的写请求总量",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " sum(apiserver_current_inflight_requests{requestKind=\"mutating\"})"
      },
      {
       "expr": " sum(apiserver_current_inflight_requests{request_kind=\"mutating\"})"
      }
     ]
    },
    {
     "title": "Read req being processed by the APIServer",
     "type": "stat",
     "description": "集群内在处理的读请求总量",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(apiserver_current_inflight_requests{requestKind=\"readOnly\"})"
      },
      {
       "expr": "sum(apiserver_current_inflight_requests{request_kind=\"readOnly\"})"
      }
     ]
    },
    {
     "title": "APIServer request throttling rate",
     "type": "stat",
     "description": "因为请求数超过请求上限，导致每秒拒绝请求的数量",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(apiserver_dropped_requests_total[3m]))"
      }
     ]
    },
    {
     "title": "Node Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 95 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(kube_node_info)" }
     ]
    },
    {
     "title": "Node Request CPU Average Percent",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 3, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(sum(kube_pod_container_resource_requests_cpu_cores)by (node)/sum(kube_node_status_capacity_cpu_cores)by(node))"
      }
     ]
    },
    {
     "title": "Namespace Overview",
     "type": "table",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 95 },
     "targets": [
      {
       "expr": "count(kube_pod_info{}) by (namespace)"
      },
      {
       "expr": "count(kube_service_info{}) by(namespace)"
      },
      {
       "expr": "count(kube_pod_container_info{}) by(namespace)"
      },
      {
       "expr": "count(kube_configmap_info{}) by(namespace)",
       "legendFormat": "configmap"
      },
      {
       "expr": "count(kube_secret_info{}) by(namespace)",
       "legendFormat": "secret"
      },
      {
       "expr": "count(kube_deployment_created{}) by (namespace)"
      },
      {
       "expr": "count(kube_statefulset_created{}) by (namespace)"
      },
      {
       "expr": "count(kube_job_created{}) by (namespace)"
      },
      {
       "expr": "count(kube_cronjob_created{}) by (namespace)"
      },
      {
       "expr": "count(kube_pod_status_ready{condition=\"false\"}==1) by(namespace) - (count(kube_pod_status_phase{phase=\"Succeeded\"}==1) by(namespace) or vector(0)) or count(kube_pod_status_ready{condition=\"false\"}==1) by(namespace)"
      },
      {
       "expr": "count(kube_deployment_status_replicas_ready{}<kube_deployment_spec_replicas{}) by (namespace)"
      },
      {
       "expr": "count(kube_statefulset_status_replicas_ready{}<kube_statefulset_replicas{}) by (namespace)"
      },
      {
       "expr": "count(kube_daemonset_status_number_unavailable{}>0)by(namespace)"
      },
      {
       "expr": "count(kube_job_status_failed{} == 1) by (namespace)"
      },
      {
       "expr": "count(kube_daemonset_created{}) by (namespace)"
      },
      {
       "expr": "count(kube_persistentvolumeclaim_info{}) by (namespace)"
      }
     ]
    },
    {
     "title": "Pod Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(kube_pod_info)" }
     ]
    },
    {
     "title": "Node Request Memory Average Percent",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 3, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(sum(kube_pod_container_resource_requests_memory_bytes)by (node)/sum(kube_node_status_capacity_memory_bytes)by(node))"
      }
     ]
    },
    {
     "title": "Node Pool Overview",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "sum (kube_node_labels) by (label_alibabacloud_com_nodepool_id)"
      },
      {
       "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_allocatable{resource=\"memory\"})by(node))by (label_alibabacloud_com_nodepool_id)"
      },
      {
       "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_memory_bytes{})by(node))by (label_alibabacloud_com_nodepool_id)"
      },
      {
       "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_allocatable{resource=\"cpu\"})by(node))by (label_alibabacloud_com_nodepool_id)"
      },
      {
       "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_cpu_cores{})by(node))by (label_alibabacloud_com_nodepool_id)"
      },
      {
       "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_spec_unschedulable==1)by(node))by (label_alibabacloud_com_nodepool_id)"
      },
      {
       "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info{})by(node))by (label_alibabacloud_com_nodepool_id)"
      },
      {
       "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests_memory_bytes{})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id)"
      },
      {
       "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests_memory_bytes{})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id) / sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_memory_bytes{})by(node))by (label_alibabacloud_com_nodepool_id)"
      },
      {
       "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests_cpu_cores{})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id) / sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_cpu_cores{})by(node))by (label_alibabacloud_com_nodepool_id)"
      },
      {
       "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests_cpu_cores{})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id)"
      }
     ]
    },
    {
     "title": "Node Memory Usage (Top 10)",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(label_replace(topk(10, 1-(node_memory_MemAvailable_bytes{} / node_memory_MemTotal_bytes{})), \"node_ip\", \"$1\", \"instance\", \"(.*):(.*)\"))by(node_ip)",
       "legendFormat": "{{node_ip}}"
      }
     ]
    },
    {
     "title": "Node CPU Usage (Top 10)",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(10, sum(label_replace(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
       "legendFormat": "{{node_ip}}"
      }
     ]
    },
    {
     "title": "Node Disk Usage (Top 10)",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(10, sum(label_replace(1-node_filesystem_free_bytes{mountpoint=\"/\"}/node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"},\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
       "legendFormat": "{{node_ip}}"
      }
     ]
    },
    {
     "title": "Node Network In (Top 10)",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10, sum(label_replace(max(irate(node_network_receive_bytes_total{}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
       "legendFormat": "{{node_ip}}"
      }
     ]
    },
    {
     "title": "Node Network Out (Top 10)",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10, sum(label_replace(max(irate(node_network_transmit_bytes_total{}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
       "legendFormat": "{{node_ip}}"
      }
     ]
    },
    {
     "title": "Node Sockets Count(Top 10)",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10, sum(label_replace(max(node_sockstat_TCP_alloc) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
       "legendFormat": "{{node_ip}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infra、CloudSvcMonitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLB",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "avg(AliyunSlb_HeathyServerCount{}) by (instanceName,vip)"
      },
      {
       "expr": "avg(AliyunSlb_TrafficRXNew{})by (instanceName,vip)"
      },
      {
       "expr": "avg(AliyunSlb_TrafficTXNew{})by (instanceName,vip)"
      },
      {
       "expr": "max(max_over_time(AliyunSlb_InstanceActiveConnection{}[3m]))by (instanceName,vip)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(max_over_time(AliyunSlb_InstanceInactiveConnection{}[3m]))by (instanceName,vip)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(max_over_time(AliyunSlb_InstanceDropConnection{}[3m]))by (instanceName,vip)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(max_over_time(AliyunSlb_InstanceMaxConnection{}[3m]))by (instanceName,vip)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(AliyunSlb_InstanceQps{})by (instanceName,vip) or vector(0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(AliyunSlb_InstanceRt{})by (instanceName,vip) or vector(0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(AliyunSlb_StatusCode2xx{})by (instanceName,vip) or vector(0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(AliyunSlb_StatusCode4xx{})by (instanceName,vip) or vector(0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(AliyunSlb_StatusCode5xx{})by (instanceName,vip) or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ECS Instance",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(AliyunEcs_cpu_total{})by(regionId,instanceId,instanceName)"
      },
      {
       "expr": "avg(AliyunEcs_memory_usedutilization{})by(regionId,instanceId,instanceName)"
      },
      {
       "expr": "avg(AliyunEcs_net_tcpconnection{state=\"ESTABLISHED\"})by(regionId,instanceId,instanceName)"
      },
      {
       "expr": "avg(AliyunEcs_VPC_PublicIP_InternetInRate{})by(regionId,instanceId,instanceName)/1024/1024"
      },
      {
       "expr": "avg(AliyunEcs_VPC_PublicIP_InternetOutRate{})by(regionId,instanceId,instanceName)/1024/1024"
      },
      {
       "expr": "avg(AliyunEcs_VPC_PublicIP_InternetOutRate_Percent{})by(regionId,instanceId,instanceName)"
      }
     ]
    },
    {
     "title": "DB",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(AliyunRds_pg_cpu_usage) by (instanceName,instanceId)"
      },
      {
       "expr": "avg(AliyunRds_pg_mem_usage{}) by (instanceName,instanceId)"
      },
      {
       "expr": "max(AliyunRds_pg_iops_usage{}) by (instanceName,instanceId)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mem Status",
     "type": "stat",
     "gridPos": { "h": 14, "w": 15, "x": 0, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(AliyunEcs_memory_usedutilization{})by(regionId,instanceId,instanceName)",
       "legendFormat": "{{instanceName}}"
      }
     ]
    },
    {
     "title": "内存状态蜂窝图",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 14, "w": 9, "x": 15, "y": 53 },
     "targets": [
      {
       "expr": "avg(AliyunEcs_memory_usedutilization{})by(regionId,instanceId,instanceName)",
       "legendFormat": "{{instanceId}}"
      }
     ]
    }
   ]
  }
 ]
}