{
 "title": "Home Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ack",
    "label": "Selecte ACK",
    "query": {
     "query": "label_values(kube_node_info,unique_cluster_name)"
    }
   },
   {
    "name": "env",
    "label": "Select Env",
    "query": "ALL : nprd , Dev : dev, Uat : uat"
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "datasource_ack", "label": "datasource_ack", "query": "prometheus" },
   { "name": "datasource_app", "label": "datasource_app", "query": "prometheus" },
   {
    "name": "ack_env",
    "label": "Select ACK Env",
    "query": "ALL : nprd , Dev : dev, Uat : uat,Sit : sit"
   }
  ]
 },
 "panels": [
  { "title": "Application OverView", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{namespace!~\"arms-demo|hk-arms-demo|\",serverIp=~\".*\",service!~\".*demo.*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "All App PV"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",service=~\".*hk-ado-jarvis.*\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "Jarvis PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hkg-customer-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "MKT PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-gft-atas-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "ATAS PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",service=~\".*hk-idp.*\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "IDP PV"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",service=~\".*hk-uw.*\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "FUW PV"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",parent=~\"hk-arbs-cms-service\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "Arbs PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\",source=\"apm\",namespace=~\"ns-hkg-dcs-system\"}[$__range])) or vector(0)",
     "legendFormat": "DCS PV"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",app=~\".*hk-cas.*\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "CAS PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hbt-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "HBT PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hkg-pnf-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "PNF PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hkg-claims-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "Claims PV"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hkg-shared-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "Cashier PV"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",namespace=~\"ns-hkg-ods-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "ODS PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\",source=\"apm\",namespace=~\"ns-hkg-nb-system\"}[$__range])) or vector(0)",
     "legendFormat": "NB PV"
    }
   ]
  },
  { "title": "Application Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "${env} Application List",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum (sum_over_time(arms_app_requests_count_raw{namespace!~\"arms-demo|hk-arms-demo|\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) by(namespace,service)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_error_count_ign_destid_endpoint_parent_ppid_prpc_rpc{host=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",namespace!~\"arms-demo|hk-arms-demo|\" }[$__range])) by(namespace,service) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum_over_time(arms_app_requests_slow_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",source=\"apm\",namespace!~\"arms-demo|hk-arms-demo|\" ,rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range]))by(namespace,service)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace,service) (sum_over_time_lorc(arms_app_requests_seconds_ign_parent_ppid_prpc_rpc{callType=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",destId=~\".*\",host=~\".*\",namespace!~\"arms-demo|hk-arms-demo|\" }[$__range]))/sum by(namespace,service) (sum_over_time_lorc(arms_app_requests_count_ign_parent_ppid_prpc_rpc{callType=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",destId=~\".*\",host=~\".*\",namespace!~\"arms-demo|hk-arms-demo|\"}[$__range]))*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Req Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (sum_over_time(arms_db_requests_count_raw{}[$__range])) or vector(0) ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "DB ERROR ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(arms_db_requests_error_count_raw{}[$__range])-1",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Resp-Status Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (sum_over_time(arms_requests_by_status_count_raw{callType=\"http\",status!~\"0|2..|3..\"}[10m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "DB Response ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (endpoint) (sum_over_time(arms_db_requests_seconds_raw{}[$__range]))/avg by (endpoint) (sum_over_time(arms_db_requests_count_raw{}[$__range]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "ACK Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "${env} Node Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by(internal_ip) (kube_node_info{}))"
    }
   ]
  },
  {
   "title": "${env} Request CPU Avge Percent Node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kube_pod_container_resource_requests_cpu_cores)by (node)/sum(kube_node_status_capacity_cpu_cores)by(node))"
    }
   ]
  },
  {
   "title": "${env} ACK Node",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(label_replace(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[$__range])) by (instance) / sum(rate(node_cpu_seconds_total[$__range])) by (instance), \"node_ip\", \"$1\", \"instance\", \"(.*):.*\")) by (node_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(1-(avg_over_time(node_memory_MemAvailable_bytes{}[$__range]) / avg_over_time(node_memory_MemTotal_bytes{}[$__range])), \"node_ip\", \"$1\", \"instance\", \"(.*):(.*)\"))by(node_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(1-avg_over_time(node_filesystem_free_bytes{mountpoint=\"/\"}[$__range])/avg_over_time(node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}[$__range]),\"node_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(node_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(max(irate(node_network_receive_bytes_total{}[$__range])) by (instance),\"node_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(node_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(max(irate(node_network_transmit_bytes_total{}[$__range])) by (instance),\"node_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(node_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(max(avg_over_time(node_sockstat_TCP_alloc{}[$__range])) by (instance),\"node_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(node_ip)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${env} Pod Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)" }
   ]
  },
  {
   "title": "${env} Request Memory Average Percent Node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kube_pod_container_resource_requests_memory_bytes)by (node)/sum(kube_node_status_capacity_memory_bytes)by(node))"
    }
   ]
  },
  {
   "title": "${env} Node Pool Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum (kube_node_labels) by (label_alibabacloud_com_nodepool_id,unique_cluster_name)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_allocatable{resource=\"memory\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_memory_bytes{})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_allocatable{resource=\"cpu\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_cpu_cores{})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_spec_unschedulable==1)by(node))by (label_alibabacloud_com_nodepool_id) -1"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info{})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests_memory_bytes{})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests_memory_bytes{})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id) / sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_memory_bytes{})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests_cpu_cores{})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id) / sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_cpu_cores{})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests_cpu_cores{})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_limits_memory_bytes{})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id) / sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_memory_bytes{})by(node))by (label_alibabacloud_com_nodepool_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_limits_cpu_cores{})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id) / sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_cpu_cores{})by(node))by (label_alibabacloud_com_nodepool_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${env} Namespace Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "count(kube_pod_info{}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{}) by(namespace)"
    },
    {
     "expr": "count(kube_pod_container_info{}) by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info{}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{}) by(namespace)",
     "legendFormat": "secret"
    },
    {
     "expr": "count(kube_deployment_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_job_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_cronjob_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_pod_status_ready{condition=\"false\"}==1) by(namespace) - (count(kube_pod_status_phase{phase=\"Succeeded\"}==1) by(namespace) or vector(0)) or count(kube_pod_status_ready{condition=\"false\"}==1) by(namespace)"
    },
    {
     "expr": "count(kube_deployment_status_replicas_ready{}<kube_deployment_spec_replicas{}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_status_replicas_ready{}<kube_statefulset_replicas{}) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_status_number_unavailable{}>0)by(namespace)"
    },
    {
     "expr": "count(kube_job_status_failed{} == 1) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_persistentvolumeclaim_info{}) by (namespace)"
    }
   ]
  },
  { "title": "ECS OverView", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "${env} ECS Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg_over_time(cloud_monitor_instance_info{product=~\"ecs\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ECS Instance (${env})",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(ceil(avg_over_time(AliyunEcs_cpu_total{}[$__range])))by(id,nodeIp,instanceName)"
    },
    {
     "expr": "avg(ceil(avg_over_time(AliyunEcs_memory_usedutilization{}[$__range])))by(id,nodeIp,instanceId,instanceName)"
    },
    {
     "expr": "avg(avg_over_time(AliyunEcs_net_tcpconnection{state=\"ESTABLISHED\"}[$__range]))by(id,nodeIp,instanceName)"
    },
    {
     "expr": "max(avg_over_time(AliyunEcs_IntranetInRate{}[$__range]))by(id,nodeIp,instanceName)"
    },
    {
     "expr": "max(avg_over_time(AliyunEcs_IntranetOutRate{}[$__range]))by(id,nodeIp,instanceName)"
    },
    {
     "expr": "avg(avg_over_time(AliyunEcs_VPC_PublicIP_InternetOutRate_Percent{}[$__range]))by(id,nodeIp,instanceName) "
    },
    {
     "expr": "group(avg_over_time(cloud_monitor_instance_info{product=~\"ecs\"}[$__range]))by(id,nodeIp,instanceName,status,instanceType)",
     "legendFormat": "__auto"
    },
    {
     "expr": "group(avg_over_time(cloud_monitor_instance_tag{product=\"ecs\", key=~\"AppCode\"}[$__range]))by(id,value)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(ceil(AliyunEcs_diskusage_utilization{status=\"Running\"}))by(id,nodeIp,instanceId,instanceName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${env} ECS Total (Stoped)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg_over_time(cloud_monitor_instance_info{product=~\"ecs\",status=\"Stopped\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB OverView",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "${env} RDS PG Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 161 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=~\"postgresql\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} RDS PG DB",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 2, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (id,instanceName) (ceil (avg_over_time(AliyunRds_pg_cpu_usage{}[$__range]))) "
      },
      {
       "expr": "avg by (id,instanceName) (ceil(avg_over_time(AliyunRds_pg_mem_usage{}[$__range]))) "
      },
      {
       "expr": "max by (id,instanceName) (ceil (avg_over_time(AliyunRds_pg_iops_usage{}[$__range])) )",
       "legendFormat": "__auto"
      },
      {
       "expr": "group (avg_over_time(cloud_monitor_instance_tag{product=\"postgresql\",key=~\"AppCode\"}[$__range])) by(id,value)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Mongodb Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 12, "y": 161 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=\"mongodb\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Mongodb",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (id,instanceName)(AliyunMongodb_replicaset_CpuUser{}) "
      },
      {
       "expr": "avg by (id,instanceName) (AliyunMongodb_replicaset_MemoryUtilization)"
      },
      {
       "expr": "max by (id,instanceName) (AliyunMongodb_replicaset_IOPSUtilization)",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (id,value) (avg_over_time(cloud_monitor_instance_tag{product=\"mongodb\",key=\"AppCode\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Polardb Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 169 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=~\"polardb\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Polar DB (PG\\ORA)",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 2, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (id,desc)(AliyunPolardb_cpu_total{}) "
      },
      {
       "expr": "avg by (id,desc) (AliyunPolardb_mem_usage{}) "
      },
      {
       "expr": "max by (id,desc) (AliyunPolardb_pg_pls_iops{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(id,dbType) (cloud_monitor_instance_info{product=\"polardb\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(id,value) (avg_over_time(cloud_monitor_instance_tag{product=~\"polardb\",key=~\"AppCode\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Redis Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 12, "y": 169 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=~\"redis\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Redis",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (id,instanceName) (AliyunRedis_CpuUsage{id!~\"\"}) "
      },
      {
       "expr": "avg by (id,instanceName) (AliyunRedis_MemoryUsage{id!~\"\"}) "
      },
      {
       "expr": "max by (id,instanceName) (AliyunRedis_ConnectionUsage{id!~\"\"}) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (id,value)(avg_over_time(cloud_monitor_instance_tag{product=\"redis\",key=\"AppCode\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (id,instanceName)(avg_over_time(cloud_monitor_instance_info{product=\"redis\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} SQLServer Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 177 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=\"sqlserver\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} SQL Server",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 2, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (id,instanceName) (avg_over_time(AliyunRds_SQLServer_CpuUsage{id!~\"\"}[$__range]))"
      },
      {
       "expr": "avg by (id,instanceName) (avg_over_time(AliyunSqlserver_SQLServer_Memory_Usage{id!~\"\"}[$__range]))"
      },
      {
       "expr": "max by (id,instanceName) (avg_over_time(AliyunRds_SQLServer_IOPS{id!~\"\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (id,instanceName)(avg_over_time(cloud_monitor_instance_info{product=\"sqlserver\",id!~\"\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (id,value)(avg_over_time(cloud_monitor_instance_tag{product=\"sqlserver\",key=\"AppCode\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} MySQL Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 12, "y": 177 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=\"mysql\",instanceId!~\"rm-3ns5070959c982868\"} [$__range])) or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} RDS MySQL DB",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "group (cloud_monitor_instance_info{product=\"mysql\"}) by(id,desc)",
       "legendFormat": "__auto"
      },
      {
       "expr": "group (cloud_monitor_instance_tag{product=\"mysql\"}) by(id,value)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id)(AliyunRds_CpuUsage{instanceId=~\".*rm-.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} DTS Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 184 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=\"dts\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} DTS List",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 2, "y": 184 },
     "targets": [
      {
       "expr": "group by (id,instanceName)(avg_over_time(cloud_monitor_instance_info{product=\"dts\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(id,value) (avg_over_time(cloud_monitor_instance_tag{product=\"dts\",key=\"AppCode\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id) (avg_over_time(AliyunDts_MigrationLatency{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id) (avg_over_time(AliyunDts_SynchronizationLatency{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id) (avg_over_time(AliyunDts_ChangeTrackingLatency{}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Middleware OverView",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "${env} APIGW Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 307 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=\"cnapigateway\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Instance list",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 2, "y": 307 },
     "targets": [
      {
       "expr": "group by (id,instanceName) (avg_over_time(AliyunCnapigateway_EnvoyApiQps{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (id,instanceName) (avg_over_time(AliyunCnapigateway_EnvoyDownstreamSuccessRate{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(id,status,instanceName) (avg_over_time(cloud_monitor_instance_info{product=~\"cnapigateway\"}[$__range]))",
       "legendFormat": "__auto"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "ALB Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 12, "y": 307 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(cloud_monitor_instance_info{product=~\"alb\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Instance list",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 307 },
     "targets": [
      {
       "expr": "group (avg_over_time(cloud_monitor_instance_info{product=~\"alb\"}[$__range])) by(id,loadBalancerName)",
       "legendFormat": "__auto"
      },
      {
       "expr": "group (avg_over_time(cloud_monitor_instance_tag{product=~\"alb\",key=~\"AppCode\"}[$__range])) by(id,value)",
       "legendFormat": "__auto"
      },
      {
       "expr": "ceil(avg(avg_over_time(AliyunAlb_LoadBalancerActiveConnection{}[$__range])) by(id)) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "ceil(avg(avg_over_time(AliyunAlb_LoadBalancerHTTPCode5XX{}[$__range])) by(id))",
       "legendFormat": "__auto"
      },
      {
       "expr": "ceil(avg(avg_over_time(AliyunAlb_ServerGroupHTTPCodeUpstream5XX{}[$__range])) by(id)) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} SLB Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 421 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(cloud_monitor_instance_info{product=~\"slb\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} SLB",
     "type": "table",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 421 },
     "targets": [
      {
       "expr": "avg(AliyunSlb_HeathyServerCount{}) by (id,vip)"
      },
      {
       "expr": "avg(AliyunSlb_TrafficRXNew{})by (id,vip)"
      },
      {
       "expr": "avg(AliyunSlb_TrafficTXNew{})by (id,vip)"
      },
      {
       "expr": "max(max_over_time(AliyunSlb_InstanceActiveConnection{}[3m]))by (id,vip)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(max_over_time(AliyunSlb_InstanceInactiveConnection{}[3m]))by (id,vip)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(max_over_time(AliyunSlb_InstanceDropConnection{}[3m]))by (id,vip)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(max_over_time(AliyunSlb_InstanceMaxConnection{}[3m]))by (id,vip)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(AliyunSlb_InstanceQps{})by (id,vip) or vector(0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(AliyunSlb_InstanceRt{})by (id,vip) or vector(0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(AliyunSlb_StatusCode2xx{})by (id,vip) or vector(0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(AliyunSlb_StatusCode4xx{})by (id,vip) or vector(0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(AliyunSlb_StatusCode5xx{})by (id,vip) or vector(0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (id,value) (cloud_monitor_instance_tag{product=\"slb\",key=\"AppCode\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} RabbitsMq Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 428 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=~\"amqp\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Rabbitmq Instances Detail",
     "type": "table",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 428 },
     "targets": [
      {
       "expr": "group(avg_over_time(cloud_monitor_instance_info{product=~\"amqp\"}[$__range])) by(id,instanceName,instanceType,status,resourceGroupName)",
       "legendFormat": "__auto"
      },
      {
       "expr": "group(avg_over_time(cloud_monitor_instance_tag{product=~\"amqp\",key=~\"AppCode\"}[$__range])) by(id,value)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(ceil(avg_over_time(AliyunAmqp_instance_InstanceConnections{}[$__range])))by(id)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(ceil(avg_over_time(AliyunAmqp_instance_InstanceConsumers{}[$__range])))by(id)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(ceil(avg_over_time(AliyunAmqp_instance_InstanceChannelsNew{}[$__range])))by(id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} RocketMq Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 436 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=~\"rocketmq5\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Rocketmq Instances Detail",
     "type": "table",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 436 },
     "targets": [
      {
       "expr": "avg by(id,instanceName) (avg_over_time(AliyunRocketmq5_InstanceStorageSize{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(id,status) (avg_over_time(cloud_monitor_instance_info{product=~\"rocketmq5\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(id,value) (avg_over_time(cloud_monitor_instance_tag{product=~\"rocketmq5\",key=~\"AppCode\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id,instanceName) (avg_over_time(AliyunRocketmq5_InstanceTpsUtilization{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id,instanceName) (avg_over_time(AliyunRocketmq5_InstanceReceiveTpsUtilization{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id,instanceName) (avg_over_time(AliyunRocketmq5_InstanceSendTpsUtilization{}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Max Computer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "${env} MaxCompute Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 342 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=\"maxcompute_common\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 2, "y": 342 },
     "targets": [
      {
       "expr": "group by(id,instanceName,status) (cloud_monitor_instance_info{product=~\"maxcompute_common\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "\r\navg by (id) (\r\n avg_over_time(AliyunMaxcompute_common_TunnelUploadTrafficBP[$__range])\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (id) (AliyunMaxcompute_common_RunningInstanceTimeout)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (id) (ceil(avg_over_time(AliyunMaxcompute_common_TunnelTotalRequestBP{}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} FCTotal",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 12, "y": 342 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(AliyunFc_FunctionAvgvCPUCores{}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 14, "y": 342 },
     "targets": [
      {
       "expr": "avg by(functionName) (avg_over_time(AliyunFc_FunctionCPUPercent{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(functionName) (avg_over_time(AliyunFc_FunctionMemoryUsagePercent{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(functionName) (ceil(sum_over_time(AliyunFc_FunctionTotalInvocations{}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage%(Avg_Over_Time)",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 343 },
     "targets": [
      {
       "expr": "avg(avg_over_time(AliyunEcs_CPUUtilization{}[$__range]))by(nodeIp)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mem Usage% {Avg_Over_Time}",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 343 },
     "targets": [
      {
       "expr": "avg(avg_over_time(AliyunEcs_memory_usedutilization{}[$__range]))by(nodeIp)",
       "legendFormat": "{{instanceId}}"
      }
     ]
    },
    {
     "title": "Disk Usage% （Now）",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 357 },
     "targets": [
      {
       "expr": "avg(AliyunEcs_diskusage_utilization{})by(nodeIp)",
       "legendFormat": "{{instanceId}}"
      }
     ]
    }
   ]
  }
 ]
}