{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ack",
    "label": "Selecte ACK",
    "query": {
     "query": "label_values(kube_node_info,unique_cluster_name)"
    }
   },
   {
    "name": "env",
    "label": "Select Env",
    "query": "ALL : nprd , Dev : dev, Uat : uat"
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "datasource_ack", "label": "datasource_ack", "query": "prometheus" },
   { "name": "datasource_app", "label": "datasource_app", "query": "prometheus" },
   {
    "name": "ack_env",
    "label": "Select ACK Env",
    "query": "ALL : nprd , Dev : dev, Uat : uat,Sit : sit"
   }
  ]
 },
 "panels": [
  { "title": "App&Resource OverView", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{namespace!~\"arms-demo|hk-arms-demo|\",serverIp=~\".*\",service!~\".*demo.*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "All App PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\",source=\"apm\",namespace=~\"ns-hkg-dcs-system\"}[$__range])) or vector(0)",
     "legendFormat": "DCS PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hkg-customer-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "MKT PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-gft-atas-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "ATAS PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",service=~\".*hk-idp.*\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "IDP PV"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",service=~\".*hk-uw.*\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "FUW PV"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",parent=~\"hk-arbs-cms-service\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "Arbs PV"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",service=~\".*hk-ado-jarvis.*\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "Jarvis PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0", "legendFormat": "Preparing" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0", "legendFormat": "Preparing" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0", "legendFormat": "Preparing" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0", "legendFormat": "Preparing" }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",app=~\".*hk-cas.*\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "CAS PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hbt-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "HBT PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hkg-pnf-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "PNF PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hkg-claims-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "Claims PV"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",namespace=~\"ns-hkg-shared-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "Cashier PV"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Except liveness/health",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(arms_app_requests_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",namespace=~\"ns-hkg-ods-system\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) or vector(0)",
     "legendFormat": "ODS PV"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0", "legendFormat": "Preparing" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0", "legendFormat": "Preparing" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0", "legendFormat": "Preparing" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0", "legendFormat": "Preparing" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0", "legendFormat": "Preparing" }
   ]
  },
  {
   "title": "${env} AliSvc Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n count by (product) (\r\n cloud_monitor_instance_info{\r\n product!~\"rds_cluster|amqp_instance|mongodb_.*|aliKafka|mysql|\"\r\n }\r\n )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${env} AliSvc Instance Total",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 7 },
   "targets": [
    {
     "expr": "label_replace(count(avg_over_time(cloud_monitor_instance_info{product!~\"dts|rds_cluster|amqp_instance|mongodb_.*|mysql|\"}[$__range])) by (product) ,\"product\",\"$1\",\"product\",\"(.*)_common\")\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${env} Ins Total (Exc dts)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\ncount(\r\n cloud_monitor_instance_info{\r\n product!~\"rds_cluster|amqp_instance|mongodb_.*|aliKafka|dts|mysql|\"\r\n }\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "${env} Application List",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "sum (sum_over_time(arms_app_requests_count_raw{namespace!~\"arms-demo|hk-arms-demo|\",callKind=~\"http|rpc|custom_entry|server\",source=\"apm\",rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range])) by(namespace,service)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(sum_over_time_lorc(arms_app_requests_error_count_ign_destid_endpoint_parent_ppid_prpc_rpc{host=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",namespace!~\"arms-demo|hk-arms-demo|\" }[$__range])) by(namespace,service) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(sum_over_time(arms_app_requests_slow_count_raw{serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",source=\"apm\",namespace!~\"arms-demo|hk-arms-demo|\" ,rpc!~\".*/actuator/health.*|.*liveness.*|.*health.*\"}[$__range]))by(namespace,service)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace,service) (sum_over_time_lorc(arms_app_requests_seconds_ign_parent_ppid_prpc_rpc{callType=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",destId=~\".*\",host=~\".*\",namespace!~\"arms-demo|hk-arms-demo|\" }[$__range]))/sum by(namespace,service) (sum_over_time_lorc(arms_app_requests_count_ign_parent_ppid_prpc_rpc{callType=~\".*\",callKind=~\"http|rpc|custom_entry|server|consumer|schedule\",destId=~\".*\",host=~\".*\",namespace!~\"arms-demo|hk-arms-demo|\"}[$__range]))*1000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "ACK Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "${ack_env} Node Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by(internal_ip) (kube_node_info{}))"
    }
   ]
  },
  {
   "title": "${ack_env} Request CPU Avge Percent Node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kube_pod_container_resource_requests_cpu_cores)by (node)/sum(kube_node_status_capacity_cpu_cores)by(node))"
    }
   ]
  },
  {
   "title": "${ack_env} ACK Node",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node_name) (label_replace(1 -sum by (node)(rate(node_cpu_seconds_total{mode=\"idle\"}[$__range]))/sum by (node)(rate(node_cpu_seconds_total[$__range])),\"node_name\", \"$1\", \"node\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(1-(avg_over_time(node_memory_MemAvailable_bytes{}[$__range]) / avg_over_time(node_memory_MemTotal_bytes{}[$__range])), \"node_name\", \"$1\", \"node\", \"(.*)\"))by(node_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(1-avg_over_time(node_filesystem_free_bytes{mountpoint=\"/\"}[$__range])/avg_over_time(node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}[$__range]),\"node_name\", \"$1\", \"node\", \"(.*)\"))by(node_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(max(irate(node_network_receive_bytes_total{}[$__range])) by (node),\"node_name\", \"$1\", \"node\", \"(.*)\"))by(node_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(max(irate(node_network_transmit_bytes_total{}[$__range])) by (node),\"node_name\", \"$1\", \"node\", \"(.*)\"))by(node_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(max(avg_over_time(node_sockstat_TCP_alloc{}[$__range])) by (node),\"node_name\", \"$1\", \"node\", \"(.*)\"))by(node_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${ack_env} Pod Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)" }
   ]
  },
  {
   "title": "${ack_env} Request Memory Average Percent Node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kube_pod_container_resource_requests_memory_bytes)by (node)/sum(kube_node_status_capacity_memory_bytes)by(node))"
    }
   ]
  },
  {
   "title": "${ack_env} Node Pool Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum (max by(label_alibabacloud_com_nodepool_id,unique_cluster_name,node)(kube_node_labels)) by (label_alibabacloud_com_nodepool_id,unique_cluster_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (label_alibabacloud_com_nodepool_id) (\r\n max by (node) (\r\n kube_node_status_allocatable{resource=\"memory\"}\r\n )\r\n *\r\n on (node)\r\n group_left(label_alibabacloud_com_nodepool_id)\r\n max by (node, label_alibabacloud_com_nodepool_id) (\r\n kube_node_labels{}\r\n )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (label_alibabacloud_com_nodepool_id) (\r\n max by (node) (\r\n kube_node_status_capacity_memory_bytes{}\r\n )\r\n *\r\n on (node)\r\n group_left(label_alibabacloud_com_nodepool_id)\r\n max by (node, label_alibabacloud_com_nodepool_id) (\r\n kube_node_labels{}\r\n )\r\n)"
    },
    {
     "expr": "sum by (label_alibabacloud_com_nodepool_id) (\r\n max by (node) (\r\n kube_node_status_allocatable{resource=\"cpu\"}\r\n )\r\n *\r\n on (node)\r\n group_left(label_alibabacloud_com_nodepool_id)\r\n max by (node, label_alibabacloud_com_nodepool_id) (\r\n kube_node_labels{}\r\n )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (label_alibabacloud_com_nodepool_id) (\r\n max by (node) (\r\n kube_node_status_capacity_cpu_cores{}\r\n )\r\n *\r\n on (node)\r\n group_left(label_alibabacloud_com_nodepool_id)\r\n max by (node, label_alibabacloud_com_nodepool_id) (\r\n kube_node_labels{}\r\n )\r\n)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_spec_unschedulable==1)by(node))by (label_alibabacloud_com_nodepool_id) -1"
    },
    {
     "expr": "sum(\r\n count by (node) (\r\n max by (namespace, pod, node) (\r\n kube_pod_info\r\n )\r\n )\r\n * on(node)\r\n group_left(label_alibabacloud_com_nodepool_id)\r\n max by (node, label_alibabacloud_com_nodepool_id)(\r\n kube_node_labels{label_alibabacloud_com_nodepool_id!=\"\"}\r\n )\r\n) by (label_alibabacloud_com_nodepool_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (label_alibabacloud_com_nodepool_id) (\r\n max by (node, label_alibabacloud_com_nodepool_id) (\r\n kube_node_labels\r\n )\r\n *\r\n on (node) group_left()\r\n sum by (node) (\r\n max by (node, pod, container) (\r\n kube_pod_container_resource_requests_memory_bytes{}\r\n )\r\n )\r\n)"
    },
    {
     "expr": "sum by (label_alibabacloud_com_nodepool_id) (\r\n max by (node, label_alibabacloud_com_nodepool_id) (\r\n kube_node_labels\r\n )\r\n *\r\n on (node) group_left()\r\n sum by (node) (\r\n max by (node, pod, container) (\r\n kube_pod_container_resource_requests_memory_bytes{}\r\n )\r\n )\r\n)/sum by (label_alibabacloud_com_nodepool_id) (\r\n max by (node) (\r\n kube_node_status_allocatable{resource=\"memory\"}\r\n )\r\n *\r\n on (node)\r\n group_left(label_alibabacloud_com_nodepool_id)\r\n max by (node, label_alibabacloud_com_nodepool_id) (\r\n kube_node_labels{}\r\n )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (label_alibabacloud_com_nodepool_id) (\r\n max by (node, label_alibabacloud_com_nodepool_id) (\r\n kube_node_labels\r\n )\r\n *\r\n on (node) group_left()\r\n sum by (node) (\r\n max by (node, pod, container) (\r\n kube_pod_container_resource_requests_cpu_cores\r\n )\r\n )\r\n) / sum by (label_alibabacloud_com_nodepool_id) (\r\n max by (node) (\r\n kube_node_status_capacity_cpu_cores{}\r\n )\r\n *\r\n on (node)\r\n group_left(label_alibabacloud_com_nodepool_id)\r\n max by (node, label_alibabacloud_com_nodepool_id) (\r\n kube_node_labels{}\r\n )\r\n)"
    },
    {
     "expr": "sum by (label_alibabacloud_com_nodepool_id) (\r\n max by (node, label_alibabacloud_com_nodepool_id) (\r\n kube_node_labels\r\n )\r\n *\r\n on (node) group_left()\r\n sum by (node) (\r\n max by (node, pod, container) (\r\n kube_pod_container_resource_requests_cpu_cores\r\n )\r\n )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ECS OverView",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "${env} ECS Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 330 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(product) (avg_over_time(cloud_monitor_instance_info{product=~\"ecs\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ECS Instance (${env})",
     "type": "table",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 330 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(ceil(AliyunEcs_cpu_total{}))by(id,nodeIp,instanceName)"
      },
      {
       "expr": "max(ceil(AliyunEcs_memory_usedutilization{}))by(id,nodeIp,instanceId,instanceName)"
      },
      {
       "expr": "avg(avg_over_time(AliyunEcs_net_tcpconnection{state=\"ESTABLISHED\"}[$__range]))by(id,nodeIp,instanceName)"
      },
      {
       "expr": "max(avg_over_time(AliyunEcs_IntranetInRate{}[$__range]))by(id,nodeIp,instanceName)"
      },
      {
       "expr": "max(avg_over_time(AliyunEcs_IntranetOutRate{}[$__range]))by(id,nodeIp,instanceName)"
      },
      {
       "expr": "avg(avg_over_time(AliyunEcs_VPC_PublicIP_InternetOutRate_Percent{}[$__range]))by(id,nodeIp,instanceName) "
      },
      {
       "expr": "group(avg_over_time(cloud_monitor_instance_info{product=~\"ecs\"}[$__range]))by(id,nodeIp,instanceName,status,instanceType)",
       "legendFormat": "__auto"
      },
      {
       "expr": "group(avg_over_time(cloud_monitor_instance_tag{product=\"ecs\", key=~\"AppCode\"}[$__range]))by(id,value)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(ceil(AliyunEcs_diskusage_utilization{status=\"Running\"}))by(id,nodeIp,instanceId,instanceName)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} ECS Total (Stoped)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 335 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=~\"ecs\",status=\"Stopped\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "DB OverView",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "${env} RDS PG Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=~\"postgresql\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} RDS PG DB",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 2, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (id,instanceName) (ceil (avg_over_time(AliyunRds_pg_cpu_usage{}[$__range]))) "
      },
      {
       "expr": "avg by (id,instanceName) (ceil(avg_over_time(AliyunRds_pg_mem_usage{}[$__range]))) "
      },
      {
       "expr": "max by (id,instanceName) (ceil (avg_over_time(AliyunRds_pg_conn_usage{}[$__range])) )",
       "legendFormat": "__auto"
      },
      {
       "expr": "group (avg_over_time(cloud_monitor_instance_tag{product=\"postgresql\",key=~\"AppCode\"}[$__range])) by(id,value)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Mongodb Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 12, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=\"mongodb\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Mongodb",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (id,instanceName)(AliyunMongodb_replicaset_CpuUser{}) "
      },
      {
       "expr": "avg by (id,instanceName) (AliyunMongodb_replicaset_MemoryUtilization)"
      },
      {
       "expr": "max by (id,instanceName) (AliyunMongodb_replicaset_ConnectionUtilization)",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (id,value) (avg_over_time(cloud_monitor_instance_tag{product=\"mongodb\",key=\"AppCode\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} SQLServer Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=\"sqlserver\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} SQL Server",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 2, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (id,instanceName) (avg_over_time(AliyunRds_SQLServer_CpuUsage{id!~\"\"}[$__range]))"
      },
      {
       "expr": "avg by (id,instanceName) (avg_over_time(AliyunSqlserver_SQLServer_Memory_Usage{id!~\"\"}[$__range]))"
      },
      {
       "expr": "avg by (id,instanceName) (ceil(avg_over_time(AliyunRds_SQLServer_TotaConn{id!~\"\"}[$__range])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (id,instanceName)(avg_over_time(cloud_monitor_instance_info{product=\"sqlserver\",id!~\"\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (id,value)(avg_over_time(cloud_monitor_instance_tag{product=\"sqlserver\",key=\"AppCode\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Redis Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 12, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=~\"redis\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Redis",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (id,instanceName) (AliyunRedis_CpuUsage{id!~\"\"}) "
      },
      {
       "expr": "avg by (id,instanceName) (AliyunRedis_MemoryUsage{id!~\"\"}) "
      },
      {
       "expr": "max by (id,instanceName) (AliyunRedis_ConnectionUsage{id!~\"\"}) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (id,value)(avg_over_time(cloud_monitor_instance_tag{product=\"redis\",key=\"AppCode\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (id,instanceName)(avg_over_time(cloud_monitor_instance_info{product=\"redis\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} PG Polardb Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 92 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=~\"polardb\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Polar DB (PG\\ORA)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 2, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (id,desc)(AliyunPolardb_cpu_total{} or AliyunPolardb_pg_cpu_total{}) "
      },
      {
       "expr": "avg by (id,desc) (AliyunPolardb_mem_usage{} or AliyunPolardb_pg_mem_usage{}) "
      },
      {
       "expr": "max by (id,desc) (AliyunPolardb_conn_usage{} or AliyunPolardb_pg_conn_usage{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(id,dbType) (cloud_monitor_instance_info{product=\"polardb\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(id,value) (avg_over_time(cloud_monitor_instance_tag{product=~\"polardb\",key=~\"AppCode\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} MySQL Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 14, "y": 92 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=\"mysql\",instanceId!~\"rm-3ns5070959c982868\"} [$__range])) or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} DTS Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 16, "y": 92 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=\"dts\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} DTS List",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 92 },
     "targets": [
      {
       "expr": "group by (id,instanceName)(avg_over_time(cloud_monitor_instance_info{product=\"dts\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(id,value) (avg_over_time(cloud_monitor_instance_tag{product=\"dts\",key=\"AppCode\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id) (avg_over_time(AliyunDts_MigrationLatency{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id) (avg_over_time(AliyunDts_SynchronizationLatency{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id) (avg_over_time(AliyunDts_ChangeTrackingLatency{}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Middleware OverView",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "${env} RocketMq Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 483 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=~\"rocketmq5\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Rocketmq Instances Detail",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 2, "y": 483 },
     "targets": [
      {
       "expr": "avg by(id,instanceName) (avg_over_time(AliyunRocketmq5_InstanceStorageSize{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(id,status) (avg_over_time(cloud_monitor_instance_info{product=~\"rocketmq5\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(id,value) (avg_over_time(cloud_monitor_instance_tag{product=~\"rocketmq5\",key=~\"AppCode\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id,instanceName) (avg_over_time(AliyunRocketmq5_InstanceTpsUtilization{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id,instanceName) (avg_over_time(AliyunRocketmq5_InstanceReceiveTpsUtilization{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id,instanceName) (avg_over_time(AliyunRocketmq5_InstanceSendTpsUtilization{}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} LB Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 14, "y": 483 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(cloud_monitor_instance_info{product=~\"slb\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} LB Instances Detail",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 483 },
     "targets": [
      {
       "expr": "avg by(id,instanceName) (avg_over_time(cloud_monitor_instance_info{product=~\"slb\"}[$__range])) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(id,value) (avg_over_time(cloud_monitor_instance_tag{product=~\"slb\",key=\"AppCode\"}[$__range])) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by(id)(AliyunAlb_ConsumedLCUs{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} RabbitsMq Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 498 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=~\"amqp\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Rabbitmq Instances Detail",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 2, "y": 498 },
     "targets": [
      {
       "expr": "group(avg_over_time(cloud_monitor_instance_info{product=~\"amqp\"}[$__range])) by(id,instanceName,instanceType,status,resourceGroupName)",
       "legendFormat": "__auto"
      },
      {
       "expr": "group(avg_over_time(cloud_monitor_instance_tag{product=~\"amqp\",key=~\"AppCode\"}[$__range])) by(id,value)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(ceil(avg_over_time(AliyunAmqp_instance_InstanceConnections{}[$__range])))by(id)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(ceil(avg_over_time(AliyunAmqp_instance_InstanceConsumers{}[$__range])))by(id)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(ceil(avg_over_time(AliyunAmqp_instance_InstanceChannelsNew{}[$__range])))by(id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} APIGW Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 14, "y": 498 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=\"cnapigateway\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} Instance list",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 498 },
     "targets": [
      {
       "expr": "avg by(id,instanceName,Value)(AliyunCnapigateway_EnvoyCpuUsageRate{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (id,instanceName) (avg_over_time(AliyunCnapigateway_EnvoyDownstreamSuccessRate{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(id,status,instanceName) (avg_over_time(cloud_monitor_instance_info{product=~\"cnapigateway\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by(instanceName)(group by (apiName,instanceName)(AliyunCnapigateway_EnvoyApiQps{}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Max Computer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "${env} MaxCompute Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 447 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(cloud_monitor_instance_info{product=\"maxcompute_common\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 2, "y": 447 },
     "targets": [
      {
       "expr": "group by(id,instanceName,status) (cloud_monitor_instance_info{product=~\"maxcompute_common\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "\r\navg by (id) (\r\n avg_over_time(AliyunMaxcompute_common_TunnelUploadTrafficBP[$__range])\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (id) (AliyunMaxcompute_common_RunningInstanceTimeout)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (id) (ceil(avg_over_time(AliyunMaxcompute_common_TunnelTotalRequestBP{}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${env} FCTotal",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 12, "y": 447 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(avg_over_time(AliyunFc_FunctionAvgvCPUCores{}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 447 },
     "targets": [
      {
       "expr": "avg by(functionName) (avg_over_time(AliyunFc_FunctionCPUPercent{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(functionName) (avg_over_time(AliyunFc_FunctionMemoryUsagePercent{}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(functionName) (ceil(sum_over_time(AliyunFc_FunctionTotalInvocations{}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ECS Resource Cell View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage%(Avg_Over_Time)",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "max(AliyunEcs_CPUUtilization{})by(nodeIp)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mem Usage% {Avg_Over_Time}",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "avg(avg_over_time(AliyunEcs_memory_usedutilization{}[$__range]))by(nodeIp)",
       "legendFormat": "{{instanceId}}"
      }
     ]
    },
    {
     "title": "Disk Usage% （Now）",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "max(AliyunEcs_diskusage_utilization{})by(nodeIp)",
       "legendFormat": "{{instanceId}}"
      }
     ]
    }
   ]
  }
 ]
}