{
 "title": "Interface",
 "tags": [
  "arms_app",
  "arms_metrics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Selecte Env", "query": "nonprod,uat,dev,sit" },
   {
    "name": "service",
    "label": "Services",
    "query": {
     "query": "label_values(arms_system_cpu_idle,service)"
    }
   },
   {
    "name": "rpc",
    "label": "Interface",
    "query": {
     "query": "label_values(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{service=\"$service\",callKind=~\"rpc|http|consumer|custom_entry|server\"},rpc)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(arms_system_cpu_idle{service=\"$service\"},host)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Indicator summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Machine Dimension-Indicator List (Selected Time Period)",
   "type": "table-old",
   "description": "Displays the machine indicators that carry the interface R in the selected time period.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",callKind=~\"http|rpc|custom_entry|consumer|server\"}[$__range]))",
     "legendFormat": "Number of requests"
    },
    {
     "expr": "sum by (host) (sum_over_time_lorc(arms_app_requests_error_count_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",callKind=~\"http|rpc|custom_entry|consumer|server\"}[$__range]))",
     "legendFormat": "Number of errors"
    },
    {
     "expr": "sum by (host) (sum_over_time_lorc(arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",callKind=~\"http|rpc|custom_entry|consumer|server\"}[$__range]))/sum by (host) (sum_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",callKind=~\"http|rpc|custom_entry|consumer|server\"}[$__range]))",
     "legendFormat": "Average time consumption"
    },
    {
     "expr": "sum by (host) (sum_over_time_lorc(arms_exception_requests_count_raw{service=\"$service\",rpc=\"$rpc\"}[$__range])) or on (host) (group by (host) (max_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",callKind=~\"http|rpc|custom_entry|consumer|server\"}[$__range]))-1)",
     "legendFormat": "Exception number"
    },
    {
     "expr": "max by (host) (max_over_time_lorc(arms_http_requests_latency_seconds{service=\"$service\",rpc=\"$rpc\",quantile=\"0.75\"}[$__range])) or on (host) (group by (host) (max_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",callKind=~\"http|rpc|custom_entry|consumer|server\"}[$__range]))-1)",
     "legendFormat": "70th perclarge"
    },
    {
     "expr": "max by (host) (max_over_time_lorc(arms_http_requests_latency_seconds{service=\"$service\",rpc=\"$rpc\",quantile=\"0.9\"}[$__range])) or on (host) (group by (host) (max_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",callKind=~\"http|rpc|custom_entry|consumer|server\"}[$__range]))-1)",
     "legendFormat": "90th perclarge"
    },
    {
     "expr": "max by (host) (max_over_time_lorc(arms_http_requests_latency_seconds{service=\"$service\",rpc=\"$rpc\",quantile=\"0.99\"}[$__range])) or on (host) (group by (host) (max_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",callKind=~\"http|rpc|custom_entry|consumer|server\"}[$__range]))-1)",
     "legendFormat": "99th perclarge"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Interface Time-consuming Stacking Chart",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum by (callType) (arms_app_requests_error_count_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",callKind=~\"rpc_client|http_client|db|sql|nosql|cache|producer|client\"}) or label_replace(sum(arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",callKind=~\"rpc|http|custom_entry|consumer|server\"})- sum(arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",callKind=~\"rpc_client|http_client|db|sql|nosql|cache|producer|client\"}),\"callType\",\"other\",\"callType\",\".*\"))/ on () group_left() sum(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",callKind=~\"rpc|http|custom_entry|consumer|server\"})",
     "legendFormat": "{{callType}}"
    }
   ]
  },
  {
   "title": "Response time/minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (callType) (sum_over_time_lorc(arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",host=~\"$host\",callKind=~\"rpc|http|custom_entry|consumer|server\"}[1m]))/sum by (callType) (sum_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",host=~\"$host\",callKind=~\"rpc|http|custom_entry|consumer|server\"}[1m]))",
     "legendFormat": "{{callType}} Entry"
    }
   ]
  },
  {
   "title": "Number of requests/minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (callType) (sum_over_time_lorc(arms_app_requests_count_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",host=~\"$host\",callKind=~\"rpc|http|custom_entry|consumer|server\"}[1m]))",
     "legendFormat": "{{callType}} Entry"
    }
   ]
  },
  {
   "title": "HTTP-status code statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (sum_over_time_lorc(arms_requests_by_status_count_raw{service=\"$service\",callKind=\"http\",rpc=\"$rpc\",host=~\"$host\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response time-score indicator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(arms_http_requests_latency_seconds{service=\"$service\",rpc=\"$rpc\",host=~\"$host\",quantile=\"0.75\"})",
     "legendFormat": "p75"
    },
    {
     "expr": "max(arms_http_requests_latency_seconds{service=\"$service\",rpc=\"$rpc\",host=~\"$host\",quantile=\"0.9\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "max(arms_http_requests_latency_seconds{service=\"$service\",rpc=\"$rpc\",host=~\"$host\",quantile=\"0.99\"})",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Number of errors/minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (callType) (sum_over_time_lorc(arms_app_requests_error_count_ign_destid_endpoint_ppid_prpc{service=\"$service\",rpc=\"$rpc\",host=~\"$host\",callKind=~\"rpc|http|custom_entry|consumer|server\"}[1m]))",
     "legendFormat": "{{callType}} Entry"
    }
   ]
  },
  { "title": "Link upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Link upstream",
   "type": "table-old",
   "description": "Displays the indicators related to the upstream service of the interface R deployed on machine N (default is All, which means all machines) in the selected time period.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "label_join(sum by (prpc,parent) (sum_over_time_lorc(arms_app_requests_count_raw{service=\"$service\",rpc=\"$rpc\",prpc!=\"nil\",prpc!=\"\",host=~\"$host\",parent!=\"\",parent!=\"nil\"}[$__range])),\"uniq\",\"-\",\"parent\",\"prpc\")"
    },
    {
     "expr": "sum by (uniq) (label_join(sum_over_time_lorc(arms_app_requests_seconds_raw{service=\"$service\",rpc=\"$rpc\",prpc!=\"nil\",prpc!=\"\",parent!=\"\",parent!=\"nil\",host=~\"$host\"}[$__range]),\"uniq\",\"-\",\"parent\",\"prpc\"))/sum by (uniq) (label_join(sum_over_time_lorc(arms_app_requests_count_raw{service=\"$service\",rpc=\"$rpc\",prpc!=\"nil\",prpc!=\"\",parent!=\"\",parent!=\"nil\",host=~\"$host\"}[$__range]),\"uniq\",\"-\",\"parent\",\"prpc\"))",
     "legendFormat": "Time-consuming"
    },
    {
     "expr": "sum by (uniq) (label_join(sum_over_time_lorc(arms_app_requests_error_count_raw{service=\"$service\",rpc=\"$rpc\",prpc!=\"nil\",prpc!=\"\",parent!=\"\",parent!=\"nil\",host=~\"$host\"}[$__range]),\"uniq\",\"-\",\"parent\",\"prpc\"))",
     "legendFormat": "Number of errors"
    }
   ]
  },
  {
   "title": "Number of requests/minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (parent,prpc) (sum_over_time_lorc(arms_app_requests_count_raw{service=\"$service\",rpc=\"$rpc\",prpc!=\"nil\",prpc!=\"\",parent!=\"\",parent!=\"nil\",host=~\"$host\"}[1m]))",
     "legendFormat": "{{parent}}:{{prpc}}"
    }
   ]
  },
  {
   "title": "Number of errors/minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (parent,prpc) (sum_over_time_lorc(arms_app_requests_error_count_raw{service=\"$service\",rpc=\"$rpc\",prpc!=\"nil\",prpc!=\"\",parent!=\"\",parent!=\"nil\",host=~\"$host\"}[1m]))",
     "legendFormat": "{{parent}}:{{prpc}}"
    }
   ]
  },
  {
   "title": "Time consuming/minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (parent,prpc) (sum_over_time_lorc(arms_app_requests_seconds_raw{service=\"$service\",rpc=\"$rpc\",prpc!=\"\",prpc!=\"nil\",parent!=\"\",parent!=\"nil\",host=~\"$host\"}[1m]))/sum by (parent,prpc) (sum_over_time_lorc(arms_app_requests_count_raw{service=\"$service\",rpc=\"$rpc\",prpc!=\"nil\",prpc!=\"\",parent!=\"\",parent!=\"nil\",host=~\"$host\"}[1m]))",
     "legendFormat": "{{parent}}=>{{prpc}}"
    }
   ]
  },
  { "title": "Link downstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Link downstream",
   "type": "table-old",
   "description": "Displays the relevant indicators of downstream services called by interface r deployed on machine n (default is All, indicating all machines) in the selected time period.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "label_join(sum by (service,rpc) (sum_over_time_lorc(arms_app_requests_count_raw{prpc=\"$rpc\",parent=\"$service\"}[$__range])),\"uniq\",\"-\",\"service\",\"rpc\")"
    },
    {
     "expr": "sum by (uniq) (label_join(sum_over_time_lorc(arms_app_requests_seconds_raw{parent=\"$service\",prpc=\"$rpc\"}[$__range]),\"uniq\",\"-\",\"service\",\"rpc\"))/sum by (uniq) (label_join(sum_over_time_lorc(arms_app_requests_count_raw{parent=\"$service\",prpc=\"$rpc\"}[$__range]),\"uniq\",\"-\",\"service\",\"rpc\"))",
     "legendFormat": "Time-consuming"
    },
    {
     "expr": "sum by (uniq) (label_join(sum_over_time_lorc(arms_app_requests_error_count_raw{parent=\"$service\",prpc=\"$rpc\"}[$__range]),\"uniq\",\"-\",\"service\",\"rpc\"))",
     "legendFormat": "Number of errors"
    }
   ]
  },
  {
   "title": "Number of requests/minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service,rpc) (sum_over_time_lorc(arms_app_requests_count_raw{prpc=\"$rpc\",parent=\"$service\"}[1m]))",
     "legendFormat": "{{service}}:{{rpc}}"
    }
   ]
  },
  {
   "title": "Time consuming/minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (service,rpc) (sum_over_time_lorc(arms_app_requests_seconds_raw{parent=\"$service\",prpc=\"$rpc\"}[1m]))/sum by (service,rpc) (sum_over_time_lorc(arms_app_requests_count_raw{parent=\"$service\",prpc=\"$rpc\"}[1m]))",
     "legendFormat": "{{service}}:{{rpc}}"
    }
   ]
  },
  {
   "title": "Number of errors/minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service,rpc) (sum_over_time_lorc(arms_app_requests_error_count_raw{parent=\"$service\",prpc=\"$rpc\"}[1m]))",
     "legendFormat": "{{service}}:{{rpc}}"
    }
   ]
  }
 ]
}