{
 "title": "KMS - Instance Details",
 "tags": [
  "scene:middleware",
  "addon:name:cloud-kms",
  "addon:version:0.0.2",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:kms-detail"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instanceId",
    "label": "InstanceId",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{product=\"kms\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "AliyunKms_code_5xx_1m",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "AliyunKms_code_5xx_1m{}", "legendFormat": "{{instanceId}}" }
   ]
  },
  {
   "title": "4xx Error Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKms_code_4xx_1m_shared {regionId=\"cn-hongkong\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Cpu utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKms_instance_cpu_utilization_1m{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Asymmetric_qps_utilization_1m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKms_instance_asymmetric_qps_utilization_1m{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Request Delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKms_latency_1m_shared{regionId=\"cn-hongkong\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Other Minute Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKms_request_other_1m_shared{regionId=\"cn-hongkong\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Instance Request Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKms_request_total_1m_shared{regionId=~\"cn-hongkong\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Symmetric_qps_utilization_1m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKms_instance_symmetric_qps_utilization_1m{id=~\"$instanceId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Request_symmetric_1m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKms_request_symmetric_1m_shared{regionId=\"cn-hongkong\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}