{
 "title": "Kubernetes Pod",
 "tags": [
  "Kubernetes",
  "Pod",
  "Workload",
  "scene:container",
  "addon:name:cs-default",
  "addon:version:0.0.11",
  "env:CS",
  "env:type:ManagedKubernetes",
  "env:profile:Default",
  "dashboard:name:k8s-pod"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Selecte Env", "query": "nprod,uat,dev,sit" },
   { "name": "datasource", "label": "Env( Datasource )", "query": "prometheus" },
   { "name": "kubeDatasource", "query": "aliyun-kubernetes-datasource" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_created, namespace)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, node)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\",node=~\"${node}.*\"}, pod)"
    }
   },
   { "name": "clusterUid", "query": "5328-18c04c" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_namespace_labels{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_pod_created{pod=~\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_status_ready{namespace=\"$namespace\", pod=~\"$pod\", condition=\"true\"}) or on() vector(0)",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "title": "Phase",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$pod\"}==1) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "group by (image, container,pod) (kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (container,pod)(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Restarts"
    },
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Memory Request"
    },
    {
     "expr": "max by (container,pod)(kube_pod_container_status_running{namespace=\"$namespace\", pod=~\"$pod\"})"
    },
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "Node Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{pod=~\"$pod\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restart Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum (increase(kube_pod_container_status_restarts_total{pod=~\"$pod\",namespace=\"$namespace\"}[1h])))",
     "legendFormat": "Last 1 Hour"
    },
    {
     "expr": "sum(max(kube_pod_container_status_restarts_total{pod=~\"$pod\",namespace=\"$namespace\"})by (pod))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\",namespace=~\"$namespace\",node=~\"$node\"}) or vector(0)",
     "legendFormat": "CPU (cores)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\",namespace=~\"$namespace\",node=~\"$node\"}) or vector(0)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\",namespace=~\"$namespace\",node=~\"$node\"}) or vector(0)",
     "legendFormat": "CPU (cores)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\",namespace=~\"$namespace\",node=~\"$node\"}) or vector(0)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Warning Events",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "ceil(increase(eventer_events_error_total{namespace=\"$namespace\", name=\"$pod\", kind=\"Pod\"}[1m]))>0 or ceil(increase(eventer_events_warning_total{namespace=\"$namespace\", name=\"$pod\", kind=\"Pod\"}[1m]))>0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Pod Status Phases",
   "type": "timeseries",
   "description": "Pod status phases",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\",phase=\"Pending\"} > 0 ) by (pod, phase) * 1",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{pod}} - {{phase}}",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "max(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\",phase=\"Unknown\"} > 0) by (pod, phase) * 2",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{pod}} - {{phase}}",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "max(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\",phase=\"Running\"} > 0) by (pod, phase) * 3",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{pod}} - {{phase}}",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "max(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\",phase=\"Succeeded\"} > 0) by (pod, phase) * 4",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{pod}} - {{phase}}",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "max(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\",phase=\"Failed\"} > 0) by (pod, phase) * 5",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{pod}} - {{phase}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Pod Status (Total Count)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(max(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"}) by(namespace, pod, phase)) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  { "title": "CPU Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "description": "容器 CPU 使用量相对于限制值的百分比。若没有数据需要检查相应容器是否进行了 CPU Limit 的配置。",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{pod=~\"$pod\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}[1m])) by (container,namespace,pod) / max(container_spec_cpu_quota{pod=~\"$pod\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}/100000) by (container,namespace,pod) or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage By Cores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{pod=~\"$pod\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}[1m])) by (pod,container,namespace)or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Load (10s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(container_cpu_load_average_10s{namespace=~\"${namespace}\", pod=~\"${pod}\", node=~\"${node}\", container!=\"\", container!=\"POD\"} / 1000)by(pod,container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Throttled Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max (rate (container_cpu_cfs_throttled_seconds_total{image!=\"\", container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\"}[1m])) by (container,pod) / max (rate (container_cpu_cfs_periods_total{image!=\"\", container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\"}[1m])) by (container,pod) or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  { "title": "Memory Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (pod,namespace,container)",
     "legendFormat": "{{pod}}/{{container}}(WSS)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (pod,namespace,container)",
     "legendFormat": "{{pod}}/{{container}}(Usage)"
    }
   ]
  },
  {
   "title": "Memory Usage (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_rss{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (pod,namespace,container) or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}(RSS)"
    }
   ]
  },
  {
   "title": "Memory Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_cache{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (pod,namespace,container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Usage WSS/Limit (%)",
   "type": "timeseries",
   "description": "容器 WSS 内存使用量相对于限制量的比例。若没有数据需要检查相应容器是否进行了 Memory Limit 的配置。",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(max(container_memory_working_set_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (pod,namespace,container)/ max(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (pod,namespace, container) * 100) <= 100 or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}(WSS/Limit)"
    }
   ]
  },
  {
   "title": "Usage/Limit (%)",
   "type": "timeseries",
   "description": "容器 Usage 内存使用量相对于限制量的比例。若没有数据需要检查相应容器是否进行了 Memory Limit 的配置。",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((max(container_memory_usage_bytes{container!=\"\",container!=\"POD\",namespace=~\"$namespace\",pod=~\"$pod\",node=~\"$node\"}) by(pod,container,namespace) / max(kube_pod_container_resource_limits_memory_bytes{container!=\"\",container!=\"POD\",namespace=~\"$namespace\",pod=~\"$pod\",node=~\"$node\"}) by(pod,container,namespace)) * 100) <= 100 or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}(Usage/Limit)"
    }
   ]
  },
  {
   "title": "Usage RSS/Limit (%)",
   "type": "timeseries",
   "description": "容器 RSS 内存使用量相对于限制量的比例。若没有数据需要检查相应容器是否进行了 Memory Limit 的配置。",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(max(container_memory_rss{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (pod,namespace,container)/ sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (pod,namespace, container) * 100) <= 100 or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}(RSS/Limit)"
    }
   ]
  },
  {
   "title": "Memory Failcnt",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max (increase(container_memory_failcnt{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", node=~\"$node\"}[1m])) by (pod,container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  { "title": "Network & Process Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Network Input",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max (rate (container_network_receive_bytes_total{image!=\"\",namespace=~\"$namespace\", pod_name=~\"$pod\",node=~\"$node\"}[1m])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Output",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max (rate (container_network_transmit_bytes_total{image!=\"\",namespace=~\"$namespace\", pod_name=~\"$pod\",node=~\"$node\"}[1m]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Input Error (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max (increase (container_network_receive_packets_dropped_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\"}[1m])) by (pod,interface) / max (increase (container_network_receive_packets_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\"}[1m])) by (pod,interface)",
     "legendFormat": "{{pod}}/{{interface}}(DroppedPacket-Input)"
    },
    {
     "expr": "max (increase (container_network_receive_errors_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\"}[1m])) by (pod,interface) / max (increase (container_network_receive_packets_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\"}[1m])) by (pod,interface)",
     "legendFormat": "{{pod}}/{{interface}}(Error-Input)"
    }
   ]
  },
  {
   "title": "Network Output Error (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max (increase (container_network_transmit_packets_dropped_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\"}[1m])) by (pod,interface) / max (increase (container_network_transmit_packets_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\"}[1m])) by (pod,interface)",
     "legendFormat": "{{pod}}/{{interface}}(DroppedPacket-Output)"
    },
    {
     "expr": "max (increase (container_network_transmit_errors_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\"}[1m])) by (pod,interface) / max (increase (container_network_receive_packets_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\"}[1m])) by (pod,interface)",
     "legendFormat": "{{pod}}/{{interface}}(Error-Output)"
    }
   ]
  },
  {
   "title": "Network Socket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(container_sockets{namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\", container!=\"\"}) by (container,pod)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Process Number",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_processes{namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\", container!=\"\"}) by (container,pod)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Pod File System Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "sum by (pod) (container_fs_usage_bytes{namespace=~\"$namespace\", node=~\"$node\", pod=~\"$pod\"})",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{pod}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Pod File System Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "(sum by (pod) (container_fs_usage_bytes{namespace=~\"$namespace\", node=~\"$node\", pod=~\"$pod\"})) /\n(avg by (pod) (container_fs_limit_bytes))",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{pod}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Pod File System Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "sum by (pod) (irate(container_fs_reads_bytes_total{namespace=~\"$namespace\", node=~\"$node\", pod=~\"$pod\", container!=\"\"}[1m]))",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{pod}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Pod File System Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "sum by (pod) (irate(container_fs_writes_bytes_total{namespace=~\"$namespace\", node=~\"$node\", pod=~\"$pod\", container!=\"\"}[1m]))",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{pod}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "ephemeral_storage_pod_usage_bytes{namespace=~\"$namespace\", node=~\"$node\", pod=~\"$pod\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{pod}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Usage(%)",
   "type": "timeseries",
   "description": "请确认Pod Yaml中设置了resources.limits.ephemeral-storage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "avg by (namespace, node, pod) (ephemeral_storage_pod_usage_bytes{namespace=~\"$namespace\", node=~\"$node\", pod=~\"$pod\"}) /\navg by (namespace, node, pod) (kube_pod_container_resource_limits{resource=\"ephemeral_storage\"})",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{pod}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Ephemeral Inode Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "ephemeral_storage_pod_inodes_used{namespace=~\"$namespace\", node=~\"$node\", pod=~\"$pod\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{pod}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Ephemeral Inode Usage(%)",
   "type": "timeseries",
   "description": "请确认Pod Yaml中设置了resources.limits.ephemeral-storage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "avg by (namespace, node, pod) (ephemeral_storage_pod_inodes_used{namespace=~\"$namespace\", node=~\"$node\", pod=~\"$pod\"}) /\navg by (namespace, node, pod) (ephemeral_storage_pod_inodes_total)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{pod}}",
     "method": "GET"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Pod Logs",
   "type": "aliyun-podlogs-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod_name=~\"$pod\",node=~\"$node\"}"
    }
   ]
  }
 ]
}