{
 "title": "Logical Architecture Version2",
 "tags": [
  "cmee",
  "alb",
  "scene:middleware",
  "addon:name:cloud-alb",
  "addon:version:0.0.3",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:cmee-alb-overview"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "regionId", "query": "cn-hongkong" },
   {
    "name": "NameSpace",
    "label": "ProjectName",
    "query": "Jarvis : ns-hkg-agent-system, ODS : ns-hkg-ods-system,ATAS : ns-gft-atas-system,DCS : ns-hkg-dcs-system,"
   },
   {
    "name": "Service",
    "label": "AppName",
    "query": {
     "query": "label_values(arms_app_requests_count_raw{namespace=\"$NameSpace\"},app)"
    }
   },
   {
    "name": "loadBalancerId",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_LoadBalancerQPS|AliyunAlb_LoadBalancerHealthyHostCount\", regionId=~\"$regionId\"},loadBalancerId)"
    }
   },
   {
    "name": "listenerProtocol",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_ListenerQPS|AliyunAlb_ListenerHealthyHostCount\",regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\"},listenerProtocol)"
    }
   },
   {
    "name": "listenerPort",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_ListenerQPS|AliyunAlb_ListenerHealthyHostCount\",regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\",listenerProtocol=~\"$listenerProtocol\"},listenerPort)"
    }
   },
   {
    "name": "ruleId",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_RuleQPS|AliyunAlb_RuleHealthyHostCount\",regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"},ruleId)"
    }
   },
   {
    "name": "serverGroupId",
    "query": {
     "query": "label_values({__name__=~\"AliyunAlb_ServerGroupQPS|AliyunAlb_ServerGroupHealthyHostCount\",regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"},serverGroupId)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   { "name": "asm_gateway_name", "label": "asm_gateway_name", "query": "istio-ingressgateway" },
   {
    "name": "Pid",
    "label": "pid",
    "query": {
     "query": "label_values(arms_app_requests_count_ign_destid_endpoint_parent_ppid_prpc{service=\"$Service\"},pid)"
    }
   },
   {
    "name": "ASMSVC",
    "label": "asmsvc",
    "query": {
     "query": "label_values(arms_app_requests_count_raw{namespace=\"$NameSpace\", service=\"$Service\"},app)"
    }
   },
   {
    "name": "GWSVC",
    "label": "asmavc",
    "query": {
     "query": "label_values(arms_app_requests_count_raw{namespace=\"$NameSpace\", service=\"$Service\"},app)"
    }
   },
   {
    "name": "incallKind",
    "label": "incallKind",
    "query": "http|rpc|consumer|custom_entry|server"
   },
   {
    "name": "outcallKind",
    "label": "outcallKind",
    "query": "rpc_client|http_client|db|sql|nosql|cache|producer|client"
   },
   {
    "name": "fullIncallKinds",
    "label": "fullIncallKinds",
    "query": "http|rpc|consumer|custom_entry|schedule|server"
   },
   {
    "name": "PromInstanceId",
    "label": "promInstanceId",
    "query": {
     "query": "label_values(AliyunAlb_ListenerQPS{loadBalancerId=\"$loadBalancerId\"},promInstanceId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ALB-->APIGW",
   "type": "canvas",
   "gridPos": { "h": 20, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round(avg_over_time(AliyunAlb_ListenerQPS{regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\"}[5m]))",
     "legendFormat": "alb-QPS"
    },
    {
     "expr": "round(avg_over_time(AliyunAlb_ListenerUpstreamResponseTime{loadBalancerId=~\"$loadBalancerId\"}[5m]))",
     "legendFormat": "Alb-Resp"
    },
    {
     "expr": "round(avg_over_time(AliyunCnapigateway_EnvoyClusterQps{promInstanceId=\"$PromInstanceId\"}[5m]))",
     "legendFormat": "apigw-qps"
    },
    {
     "expr": "round(avg_over_time(AliyunCnapigateway_EnvoyDownstreamSuccessRate{promInstanceId=~\"$PromInstanceId\"}[5m]))",
     "legendFormat": "apigwRate"
    },
    {
     "expr": "\r\nround(sum(AliyunAlb_LoadBalancerHTTPCodeUpstream2XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"})\r\n/\r\nsum(\r\n AliyunAlb_LoadBalancerHTTPCodeUpstream2XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream3XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream4XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream5XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\n))\r\n",
     "legendFormat": "alb-rate"
    },
    {
     "expr": "round(avg_over_time(AliyunCnapigateway_EnvoyApiRtAvg{promInstanceId=~\"$PromInstanceId\"}[5m]))",
     "legendFormat": "gw-resp"
    },
    {
     "expr": "round(sum by (istio)(rate(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\"}[5m])))",
     "legendFormat": "Asm QPS"
    },
    {
     "expr": "(sum(irate(istio_request_duration_milliseconds_bucket_delta{reporter=\"source\",source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[5m])) by (source_app, source_workload_namespace, le) / 1000) or sum(irate(istio_request_duration_seconds_bucket_delta{reporter=\"source\", source_workload_namespace=~\"istio-system\",source_app=\"$asm_gateway_name\"}[5m])) by (source_app, source_workload_namespace, le)",
     "legendFormat": "asm resp"
    },
    {
     "expr": "sum_over_time(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\",response_code=~\"2..\"}[5m])/sum_over_time(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\"}[5m])",
     "legendFormat": "asm rate"
    },
    {
     "expr": "round(sum(irate(apiserver_request_total{subresource !~ \".*/healthz$|/livez$|/readyz$\"}[5m])))",
     "legendFormat": "ack qps"
    },
    {
     "expr": "avg (sum by (verb) (irate(apiserver_request_duration_seconds_bucket{verb!~\"WATCH|CONNECT\",resource!=\"\",subresource!~\".*/healthz$|/livez$|/readyz$\"}[5m])))",
     "legendFormat": "ack resp"
    },
    {
     "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb!~\"GET|LIST|WATCH|CONNECT\"}[5m]))/sum(irate(apiserver_request_total{verb!~\"GET|LIST|WATCH|CONNECT\"}[5m]))",
     "legendFormat": "ack rate"
    },
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{service=~\"$Service\",rpc!~\".*/liveness$\",}[50m])) or vector(0)",
     "legendFormat": "app qps"
    },
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_seconds_raw{service=\"$Service\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",source=\"apm\",}[$__range]))/sum(sum_over_time_lorc(arms_app_requests_count_raw{service=\"$Service\",serverIp=~\".*\",callKind=~\"http|rpc|custom_entry|server\",rpc!~\".*/liveness$\",source=\"apm\"}[$__range])) or vector(0)",
     "legendFormat": "app resp"
    },
    {
     "expr": "sum(sum_over_time(arms_requests_by_status_count_raw{source=\"apm\",status=~\"2..\",app=\"$Service\",rpc!~\".*/liveness$\"}[$__range]) or vector(1))/sum(sum_over_time(arms_requests_by_status_count_raw{source=\"apm\",app=\"$Service\",rpc!~\".*/liveness$\"}[$__range]) or vector(1)) ",
     "legendFormat": "app rate"
    }
   ]
  },
  {
   "title": "ALB Req (Count/5m)",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(AliyunAlb_LoadBalancerQPS{regionId=~\"$regionId\",loadBalancerId=~\"$loadBalancerId\"}[5m])",
     "legendFormat": "alb qps"
    }
   ]
  },
  {
   "title": "ALB Suc rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(AliyunAlb_LoadBalancerHTTPCodeUpstream2XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"})\r\n/\r\nsum(\r\n AliyunAlb_LoadBalancerHTTPCodeUpstream2XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream3XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream4XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\nor AliyunAlb_LoadBalancerHTTPCodeUpstream5XX{regionId=~\"$regionId\", loadBalancerId=~\"$loadBalancerId\"}\r\n)\r\n",
     "legendFormat": "alb rate"
    }
   ]
  },
  {
   "title": "ALB Backend Resp",
   "type": "timeseries",
   "description": "负载均衡实例后端应答时间(ms)",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "AliyunAlb_LoadBalancerUpstreamResponseTime{loadBalancerId=~\"$loadBalancerId\"}",
     "legendFormat": "Alb resp"
    }
   ]
  },
  {
   "title": "GW Req (Count/5m)",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "AliyunCnapigateway_EnvoyApiQps{apiName=~\"$GWSVC\"}",
     "legendFormat": "gw qps"
    }
   ]
  },
  {
   "title": "GW Suc rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(AliyunCnapigateway_EnvoyDownstreamSuccessRate,0.01)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GW Resp",
   "type": "timeseries",
   "description": "网关Operation请求平均时延",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "AliyunCnapigateway_EnvoyApiRtAvg{apiName=~\"$GWSVC\"}",
     "legendFormat": "gw resp"
    }
   ]
  },
  {
   "title": "ASM Req (Count/5m)",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "sum by (istio)(rate(istio_requests_total{source_workload_namespace=\"istio-system\",reporter=\"source\",source_app=\"$asm_gateway_name\"}[5m]))",
     "legendFormat": "asm qps"
    }
   ]
  },
  {
   "title": "ASM Suc Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(istio_requests_total{destination_app=\"$ASMSVC\",response_code=~\"2..\"}[5m]))/sum(sum_over_time(istio_requests_total{destination_app=\"$ASMSVC\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ASM Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (callType) (arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc_rpc{namespace=\"$NameSpace\",callKind=~\"$incallKind\"})/sum by (callType) (arms_app_requests_count_ign_destid_endpoint_ppid_prpc_rpc{namespace=\"$NameSpace\",callKind=~\"$incallKind\"})",
     "legendFormat": "Asm resp"
    }
   ]
  },
  {
   "title": "APP Req (Count/5m)",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "sum(sum_over_time_lorc(arms_app_requests_count_raw{service=~\"$Service\",service!=\"\",rpc!~\".*/liveness$\",}[5m]) or vector(0)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Suc Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (sum_over_time_lorc(arms_requests_by_status_count_raw{source=\"apm\",status=~\"2..\",app=\"$Service\"}[5m]))/sum (sum_over_time_lorc(arms_requests_by_status_count_raw{source=\"apm\",app=\"$Service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (callType) (arms_app_requests_seconds_ign_destid_endpoint_ppid_prpc_rpc{service=\"$Service\",callKind=~\"$incallKind\",rpc!~\".*/liveness$\"})/sum by (callType) (arms_app_requests_count_ign_destid_endpoint_ppid_prpc_rpc{service=\"$Service\",callKind=~\"$incallKind\",rpc!~\".*/liveness$\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}