{
 "title": "Machine",
 "tags": [
  "arms_app",
  "arms_metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Application",
    "query": {
     "query": "label_values(arms_system_cpu_idle,service)"
    }
   },
   {
    "name": "host",
    "label": "Machine",
    "query": {
     "query": "label_values(arms_system_cpu_idle{service=\"$service\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(arms_system_cpu_system{host=~\"$host\"})",
     "legendFormat": "System CPU usage"
    },
    {
     "expr": "max(arms_system_cpu_io_wait{host=~\"$host\"})",
     "legendFormat": "CPU usage waiting for IO to complete"
    },
    {
     "expr": "max(arms_system_cpu_user{host=~\"$host\"})",
     "legendFormat": "User CPU usage"
    },
    {
     "expr": "max(arms_system_cpu_system{host=\"$host\"})+max(arms_system_cpu_io_wait{host=~\"$host\"})+max(arms_system_cpu_user{host=\"$host\"})",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(arms_system_mem_used_bytes{host=\"$host\"})",
     "legendFormat": "The system's used memory"
    },
    {
     "expr": "max(arms_system_mem_total_bytes{host=\"$host\"})",
     "legendFormat": "Sum"
    },
    {
     "expr": "max(arms_system_mem_buffers_bytes{host=\"$host\"})",
     "legendFormat": "The number of BufferCache memories of the system"
    },
    {
     "expr": "max(arms_system_mem_cached_bytes{host=\"$host\"})",
     "legendFormat": "The amount of memory in the PageCache of the system"
    },
    {
     "expr": "max(arms_system_mem_free_bytes{host=\"$host\"})",
     "legendFormat": "Free memory of the system"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(arms_system_load{host=\"$host\"})",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(arms_system_disk_free_bytes{host=\"$host\"})",
     "legendFormat": "Available disk capacity"
    },
    {
     "expr": "max(arms_system_disk_total_bytes{host=\"$host\"})",
     "legendFormat": "Total disk capacity"
    },
    {
     "expr": "max(arms_system_disk_total_bytes{host=~\"$host\"})-max(arms_system_disk_free_bytes{host=~\"$host\"})",
     "legendFormat": "Disk capacity used"
    }
   ]
  },
  {
   "title": "Network Traffic (Byte)/Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time_lorc(arms_system_net_in_bytes{host=~\"$host\"}[1m]))",
     "legendFormat": "Number of bytes received by the network"
    },
    {
     "expr": "max(max_over_time_lorc(arms_system_net_out_bytes{host=~\"$host\"}[1m]))",
     "legendFormat": "Number of bytes sent by the network"
    }
   ]
  },
  {
   "title": "Network packets (s)/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time_lorc(arms_system_net_in_packets{host=~\"$host\"}[1m]))",
     "legendFormat": "Number of messages received by the network"
    },
    {
     "expr": "max(max_over_time_lorc(arms_system_net_out_packets{host=~\"$host\"}[1m]))",
     "legendFormat": "Number of messages sent by the network"
    },
    {
     "expr": "max(max_over_time_lorc(arms_system_net_in_errs{host=~\"$host\"}[1m]))",
     "legendFormat": "Number of errors received by the network"
    },
    {
     "expr": "max(max_over_time_lorc(arms_system_net_out_errs{host=~\"$host\"}[1m]))",
     "legendFormat": "Number of network discarded messages"
    }
   ]
  }
 ]
}