{
 "title": "ManagedGrafanaDashboard",
 "tags": [
  "scene:middleware",
  "env:Cloud",
  "env:type:Cloud",
  "addon:version:0.0.1",
  "dashboard:name:grafana",
  "prometheus",
  "addon:name:cloud-grafana"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "uid",
    "label": "Workspace ID",
    "query": "label_values(grafana_stat_total_orgs{app=\"grafana\",job=\"kubernetes-pods\"}, uid)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total number of organizations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(grafana_stat_total_orgs{uid=\"$uid\",job=\"kubernetes-pods\"}) by (uid)"
    }
   ]
  },
  {
   "title": "Total number of accounts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(grafana_stat_total_users{uid=\"$uid\",job=\"kubernetes-pods\"})by (uid)"
    }
   ]
  },
  {
   "title": "Total number of dashboard panels",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(grafana_stat_totals_dashboard{uid=\"$uid\",job=\"kubernetes-pods\"}) by (uid)"
    }
   ]
  },
  {
   "title": "Total number of data sources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_totals_datasource{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)"
    }
   ]
  },
  {
   "title": "Total number of folders",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_totals_folder{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)"
    }
   ]
  },
  { "title": "Request Status Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "API request status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(increase(grafana_api_response_status_total{uid=\"$uid\",job=\"kubernetes-pods\"}[1m]))by (uid,code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Proxy interface request status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(increase(grafana_proxy_response_status_total{uid=\"$uid\",job=\"kubernetes-pods\"}[1m]))by (uid,code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Page Request Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(increase(grafana_page_response_status_total{uid=\"$uid\",job=\"kubernetes-pods\"}[1m]))by (uid,code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Request response latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Dashboard search latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(grafana_api_dashboard_search_milliseconds_sum{uid=\"$uid\",job=\"kubernetes-pods\"}[5m])/rate(grafana_api_dashboard_search_milliseconds_count{uid=\"$uid\",job=\"kubernetes-pods\"}[5m]))by(uid)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Dashboard read latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(grafana_api_dashboard_get_milliseconds_sum{uid=\"$uid\",job=\"kubernetes-pods\"}[5m])/rate(grafana_api_dashboard_get_milliseconds_count{uid=\"$uid\",job=\"kubernetes-pods\"}[5m]))by(uid)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Dashboard save delay",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(grafana_api_dashboard_save_milliseconds_sum{uid=\"$uid\",job=\"kubernetes-pods\"}[5m])/rate(grafana_api_dashboard_save_milliseconds_count{uid=\"$uid\",job=\"kubernetes-pods\"}[5m]))by(uid)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Data query latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(grafana_api_dataproxy_request_all_milliseconds_sum{uid=\"$uid\",job=\"kubernetes-pods\"}[5m])/rate(grafana_api_dataproxy_request_all_milliseconds_count{uid=\"$uid\",job=\"kubernetes-pods\"}[5m]))by(uid)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Dashboard search latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(grafana_api_dashboard_search_milliseconds{uid=\"$uid\",job=\"kubernetes-pods\",quantile=\"0.5\"})by(uid)",
     "legendFormat": " 0.5"
    },
    {
     "expr": "avg(grafana_api_dashboard_search_milliseconds{uid=\"$uid\",job=\"kubernetes-pods\",quantile=\"0.9\"})by(uid)",
     "legendFormat": " 0.9"
    },
    {
     "expr": "avg(grafana_api_dashboard_search_milliseconds{uid=\"$uid\",job=\"kubernetes-pods\",quantile=\"0.99\"})by(uid)",
     "legendFormat": " 0.99"
    }
   ]
  },
  {
   "title": "Dashboard read latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(grafana_api_dashboard_get_milliseconds{uid=\"$uid\",job=\"kubernetes-pods\",quantile=\"0.5\"})by(uid)",
     "legendFormat": " 0.5"
    },
    {
     "expr": "avg(grafana_api_dashboard_get_milliseconds{uid=\"$uid\",job=\"kubernetes-pods\",quantile=\"0.9\"})by(uid)",
     "legendFormat": " 0.9"
    },
    {
     "expr": "avg(grafana_api_dashboard_get_milliseconds{uid=\"$uid\",job=\"kubernetes-pods\",quantile=\"0.99\"})by(uid)",
     "legendFormat": " 0.99"
    }
   ]
  },
  {
   "title": "Dashboard save latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(grafana_api_dashboard_save_milliseconds{uid=\"$uid\",job=\"kubernetes-pods\",quantile=\"0.5\"})by(uid)",
     "legendFormat": " 0.5"
    },
    {
     "expr": "avg(grafana_api_dashboard_save_milliseconds{uid=\"$uid\",job=\"kubernetes-pods\",quantile=\"0.9\"})by(uid)",
     "legendFormat": " 0.9"
    },
    {
     "expr": "avg(grafana_api_dashboard_save_milliseconds{uid=\"$uid\",job=\"kubernetes-pods\",quantile=\"0.99\"})by(uid)",
     "legendFormat": " 0.99"
    }
   ]
  },
  {
   "title": "Data query latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(grafana_api_dataproxy_request_all_milliseconds{uid=\"$uid\",job=\"kubernetes-pods\",quantile=\"0.5\"})by(uid)",
     "legendFormat": " 0.5"
    },
    {
     "expr": "avg(grafana_api_dataproxy_request_all_milliseconds{uid=\"$uid\",job=\"kubernetes-pods\",quantile=\"0.9\"})by(uid)",
     "legendFormat": " 0.9"
    },
    {
     "expr": "avg(grafana_api_dataproxy_request_all_milliseconds{uid=\"$uid\",job=\"kubernetes-pods\",quantile=\"0.99\"})by(uid)",
     "legendFormat": " 0.99"
    }
   ]
  },
  { "title": "Information Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "User",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(grafana_stat_totals_viewers{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of Viewer Users"
    },
    {
     "expr": "avg(grafana_stat_totals_editors{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of Editor Users"
    },
    {
     "expr": "avg(grafana_stat_totals_admins{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of admin users"
    },
    {
     "expr": "avg(grafana_stat_totals_active_editors{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Editor active user count"
    },
    {
     "expr": "avg(grafana_stat_totals_active_viewers{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of active viewers"
    },
    {
     "expr": "avg(grafana_stat_totals_active_admins{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of active admin users"
    },
    {
     "expr": "avg(grafana_stat_total_users{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Total number of users"
    },
    {
     "expr": "avg(grafana_stat_active_users{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of active users"
    }
   ]
  },
  {
   "title": "Organization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(grafana_stat_total_orgs{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of organizations"
    }
   ]
  },
  {
   "title": "Log in",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(grafana_api_login_post_total{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of logged-in users"
    },
    {
     "expr": "avg(grafana_api_login_oauth_total{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of OAuth logged-in users"
    },
    {
     "expr": "avg(grafana_api_arms_login_oauth_total{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of Alibaba Cloud logged-in users"
    },
    {
     "expr": "avg(grafana_api_login_saml_total{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of SMAL logged-in users"
    }
   ]
  },
  {
   "title": "Folder",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(grafana_stat_totals_folder{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of folders"
    }
   ]
  },
  {
   "title": "Dashboard panel",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(grafana_stat_totals_dashboard_versions{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of大盘 versions"
    },
    {
     "expr": "avg(grafana_stat_totals_dashboard{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Market-wide quantity"
    }
   ]
  },
  {
   "title": "Data Source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(grafana_stat_totals_datasource{uid=\"$uid\",job=\"kubernetes-pods\"})by(uid)",
     "legendFormat": "Number of data sources"
    }
   ]
  }
 ]
}