{
 "title": "MongoDB Overview",
 "tags": [
  "scene:database",
  "env:Cloud",
  "env:type:Cloud",
  "addon:version:0.0.3",
  "prometheus",
  "dashboard:name:cloud-mongodb-overview",
  "addon:name:cloud-mongodb"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "arch",
    "label": "Instance Architecture",
    "query": "label_values(cpu_usage{product=\"mongodb\"}, arch)"
   },
   {
    "name": "logicInstance",
    "label": "Logical Instance",
    "query": "label_values(cpu_usage{product=\"mongodb\", arch=\"$arch\"}, logicIns)"
   },
   {
    "name": "character",
    "label": "Component Type",
    "query": "label_values(cpu_usage{product=\"mongodb\", arch=\"$arch\", logicIns=\"$logicInstance\"}, character)"
   },
   {
    "name": "instance",
    "label": "Component ID",
    "query": "label_values(cpu_usage{product=\"mongodb\", arch=\"$arch\", logicIns=\"$logicInstance\",character=\"$character\"}, instance)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(cpu_usage{product=\"mongodb\", arch=\"$arch\", logicIns=\"$logicInstance\",character=\"$character\", instance=\"$instance\"}, role)"
   },
   {
    "name": "nodeId",
    "label": "Node ID",
    "query": "label_values(cpu_usage{product=\"mongodb\", arch=\"$arch\", logicIns=\"$logicInstance\",character=\"$character\", instance=\"$instance\", role=\"$role\"}, rdsIns)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Advanced Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total QPS of Shard Component Operations in Sharded Clusters (by Role)",
   "type": "graph",
   "description": "This panel shows the sum of the QPS of the operations of all Shard nodes and certain roles (primary/secondary/hidden) in the sharded cluster instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(insert{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"primary\"})",
     "legendFormat": "insert_primary"
    },
    {
     "expr": "sum(query{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"primary\"})",
     "legendFormat": "query_primary"
    },
    {
     "expr": "sum(update{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"primary\"})",
     "legendFormat": "update_primary"
    },
    {
     "expr": "sum(delete{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"primary\"})",
     "legendFormat": "delete_primary"
    },
    {
     "expr": "sum(getmore{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"primary\"})",
     "legendFormat": "getmore_primary"
    },
    {
     "expr": "sum(command{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"primary\"})",
     "legendFormat": "command_primary"
    },
    {
     "expr": "sum(insert{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"secondary\"})",
     "legendFormat": "insert_secondary"
    },
    {
     "expr": "sum(query{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"secondary\"})",
     "legendFormat": "query_secondary"
    },
    {
     "expr": "sum(update{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"secondary\"})",
     "legendFormat": "update_secondary"
    },
    {
     "expr": "sum(delete{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"secondary\"})",
     "legendFormat": "delete_secondary"
    },
    {
     "expr": "sum(getmore{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"secondary\"})",
     "legendFormat": "getmore_secondary"
    },
    {
     "expr": "sum(command{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"secondary\"})",
     "legendFormat": "command_secondary"
    },
    {
     "expr": "sum(insert{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"hidden\"})",
     "legendFormat": "insert_hidden"
    },
    {
     "expr": "sum(query{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"hidden\"})",
     "legendFormat": "query_hidden"
    },
    {
     "expr": "sum(update{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"hidden\"})",
     "legendFormat": "update_hidden"
    },
    {
     "expr": "sum(delete{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"hidden\"})",
     "legendFormat": "delete_hidden"
    },
    {
     "expr": "sum(getmore{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"hidden\"})",
     "legendFormat": "getmore_hidden"
    },
    {
     "expr": "sum(command{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Shard\", role=\"hidden\"})",
     "legendFormat": "command_hidden"
    }
   ]
  },
  {
   "title": "Total QPS of Mongos Component Operations in Sharded Clusters",
   "type": "graph",
   "description": "This panel shows the sum of the QPS of the operations of all Mongos nodes in the sharded cluster instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(insert{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Mongos\", role=\"primary\"})",
     "legendFormat": "insert"
    },
    {
     "expr": "sum(query{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Mongos\", role=\"primary\"})",
     "legendFormat": "query"
    },
    {
     "expr": "sum(update{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Mongos\", role=\"primary\"})",
     "legendFormat": "update"
    },
    {
     "expr": "sum(delete{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Mongos\", role=\"primary\"})",
     "legendFormat": "delete"
    },
    {
     "expr": "sum(getmore{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Mongos\", role=\"primary\"})",
     "legendFormat": "getmore"
    },
    {
     "expr": "sum(command{product=\"mongodb\",logicIns=\"$logicInstance\", character=\"Mongos\", role=\"primary\"})",
     "legendFormat": "command"
    }
   ]
  },
  { "title": "Basic Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "cpu_usage"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mem_usage{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "mem_usage"
    }
   ]
  },
  {
   "title": "IOPS Usage (Times/Second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "data_iops{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "data_iops"
    },
    {
     "expr": "log_iops{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "log_iops"
    }
   ]
  },
  {
   "title": "IOPS Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iops_usage{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "iops_usage"
    }
   ]
  },
  {
   "title": "Disk Space Usage (Byte)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "ins_size{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "ins_size"
    },
    {
     "expr": "data_size{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "data_size"
    },
    {
     "expr": "log_size{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "log_size"
    }
   ]
  },
  {
   "title": "Disk Space Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "disk_usage{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "disk_usage"
    }
   ]
  },
  {
   "title": "Number of Connections (pcs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "current_conn{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "current_conn"
    },
    {
     "expr": "connections_active{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "active_conn"
    }
   ]
  },
  {
   "title": "Number of Connections Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "conn_usage{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "conn_usage"
    }
   ]
  },
  {
   "title": "Network Traffic (Byte)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "bytes_in{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "bytes_in"
    },
    {
     "expr": "bytes_out{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "bytes_out"
    }
   ]
  },
  {
   "title": "WiR edTigerCache usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "wt_cache_usage{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "wt_cache_usage"
    },
    {
     "expr": "wt_cache_dirty_usage{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "wt_cache_dirty_usage"
    }
   ]
  },
  {
   "title": "IO latency (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "iocheck_cost{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "iocheck_cost"
    }
   ]
  },
  {
   "title": "Master-slave latency (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "repl_lag{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "repl_lag"
    }
   ]
  },
  {
   "title": "Operation QPS (pcs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "insert{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "insert"
    },
    {
     "expr": "query{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "query"
    },
    {
     "expr": "update{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "update"
    },
    {
     "expr": "delete{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "delete"
    },
    {
     "expr": "getmore{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "getmore"
    },
    {
     "expr": "command{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "command"
    }
   ]
  },
  {
   "title": "Read and write queues (pcs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "gl_cq_total{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "currentQueue_total"
    },
    {
     "expr": "gl_cq_readers{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "currentQueue_readers"
    },
    {
     "expr": "gl_cq_writers{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "currentQueue_writers"
    },
    {
     "expr": "gl_ac_readers{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "active_readers"
    },
    {
     "expr": "gl_ac_writers{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "active_writers"
    }
   ]
  },
  {
   "title": "WiredTiger request queues (pcs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "write_concurrent_trans_out{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "write_concurrent_trans_out"
    },
    {
     "expr": "write_concurrent_trans_available{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "write_concurrent_trans_available"
    },
    {
     "expr": "read_concurrent_trans_out{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "read_concurrent_trans_out"
    },
    {
     "expr": "read_concurrent_trans_available{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "read_concurrent_trans_available"
    }
   ]
  },
  {
   "title": "Cursors (pcs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "noTimeout_open{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "open_no_timedout"
    },
    {
     "expr": "pinned_open{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "open_with_timedout"
    },
    {
     "expr": "total_open{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "open_total"
    },
    {
     "expr": "timed_out{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "closed_by_timeout"
    },
    {
     "expr": "job_cursors_closed{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "closed_by_session"
    }
   ]
  },
  {
   "title": "Operation details (pcs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "operation_scanAndOrder_ps{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "scanAndOrder"
    },
    {
     "expr": "operation_writeConflicts_ps{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "writeConflicts"
    },
    {
     "expr": "operation_exactIDCount_ps{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "exactIDCount"
    }
   ]
  },
  {
   "title": "Number of affected documents (pcs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "document_deleted_ps{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "deletedDocuments"
    },
    {
     "expr": "document_inserted_ps{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "insertedDocuments"
    },
    {
     "expr": "document_returned_ps{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "returnDocuments"
    },
    {
     "expr": "document_updated_ps{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "updatedDocuments"
    }
   ]
  },
  {
   "title": "Number of query scan indexes and documents (pcs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "queryExecutor_scanned_ps{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "scannedKeys"
    },
    {
     "expr": "queryExecutor_scannedObject_ps{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "scannedDocs"
    }
   ]
  },
  {
   "title": "TTL (pcs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "ttl_deletedDocuments_ps{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "ttlDeletedDocuments"
    },
    {
     "expr": "ttl_passes_ps{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "ttlPasses"
    }
   ]
  },
  {
   "title": "Average response time (microseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "avg_rt{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "avg_rt"
    }
   ]
  },
  {
   "title": "moveChunk (pcs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "moveChunk_donor_started_ps{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "donorCount"
    },
    {
     "expr": "moveChunk_recip_stared_ps{product=\"mongodb\",instance=\"$instance\", role=\"$role\", rdsIns=\"$nodeId\"}",
     "legendFormat": "recipientCount"
    }
   ]
  }
 ]
}