{
 "title": "MongoDB Replica Set",
 "tags": [
  "dashboard:name:cloud-mongodb-replica-set",
  "scene:database",
  "env:Cloud",
  "env:type:Cloud",
  "addon:version:0.0.3",
  "prometheus",
  "addon:name:cloud-mongodb"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(cpu_usage{product=\"mongodb\",arch=\"副本集实例\"}, instance)"
    }
   },
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(cpu_usage{product=\"mongodb\",instance=~\"$instance\"}, role)"
    }
   },
   {
    "name": "nodeId",
    "label": "Node ID",
    "query": {
     "query": "label_values(cpu_usage{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\"},rdsIns)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_usage{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "{{logicIns}}/{{role}}"
    }
   ]
  },
  {
   "title": "Memory usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mem_usage{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "{{logicIns}}/{{role}}"
    }
   ]
  },
  {
   "title": "IOPS usage (times/second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "data_iops{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "data_iops/{{logicIns}}/{{role}}"
    },
    {
     "expr": "log_iops{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "log_iops/{{logicIns}}/{{role}}"
    }
   ]
  },
  {
   "title": "IOPS usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "iops_usage{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "{{logicIns}}/{{role}}"
    }
   ]
  },
  {
   "title": "Disk space usage (Byte)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{product=\"mongodb\",__name__=~\"ins_size|data_size|log_size\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "{{logicIns}}/{{role}}/{{__name__}}"
    }
   ]
  },
  {
   "title": "Disk space usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_usage{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "{{logicIns}}/{{role}}"
    }
   ]
  },
  {
   "title": "Operation QPS (pcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{product=\"mongodb\",__name__=~\"insert|query|update|delete|getmore|command\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "{{logicIns}}/{{role}}/{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of connections (pcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{product=\"mongodb\",__name__=~\"current_conn|connections_active\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "{{logicIns}}/{{role}}/{{__name__}}"
    }
   ]
  },
  {
   "title": "Cursors (pcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "noTimeout_open{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "open_no_timedout/{{logicIns}}/{{role}}"
    },
    {
     "expr": "pinned_open{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "open_with_timedout/{{logicIns}}/{{role}}"
    },
    {
     "expr": "total_open{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "open_total/{{logicIns}}/{{role}}"
    },
    {
     "expr": "timed_out{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "closed_by_timeout/{{logicIns}}/{{role}}"
    },
    {
     "expr": "job_cursors_closed{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "closed_by_session/{{logicIns}}/{{role}}"
    }
   ]
  },
  {
   "title": "Network traffic (Byte)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{product=\"mongodb\",__name__=~\"bytes_in|bytes_out\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "{{logicIns}}/{{role}}/{{__name__}}"
    }
   ]
  },
  {
   "title": "Read and write queues (pcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gl_cq_total{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "currentQueue_total/{{logicIns}}/{{role}}"
    },
    {
     "expr": "gl_cq_readers{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "currentQueue_readers/{{logicIns}}/{{role}}"
    },
    {
     "expr": "gl_cq_writers{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "currentQueue_writers/{{logicIns}}/{{role}}"
    },
    {
     "expr": "gl_ac_readers{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "active_readers/{{logicIns}}/{{role}}"
    },
    {
     "expr": "gl_ac_writers{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "active_writers/{{logicIns}}/{{role}}"
    }
   ]
  },
  {
   "title": "WiredTiger request queues (pcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace({product=\"mongodb\",__name__=~\"write_concurrent_trans_out|write_concurrent_trans_available|read_concurrent_trans_out|read_concurrent_trans_available\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"},\"name\",\"${1}_${2}\",\"__name__\",\"(.+)_concurrent_trans_(.+)\")",
     "legendFormat": "{{logicIns}}/{{role}}/{{name}}"
    }
   ]
  },
  {
   "title": "Master-slave delay (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "repl_lag{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "{{logicIns}}/{{role}}"
    }
   ]
  },
  {
   "title": "IO delay (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "iocheck_cost{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "{{logicIns}}/{{role}}"
    }
   ]
  },
  {
   "title": "Number of connections usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "conn_usage{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "{{logicIns}}/{{role}}"
    }
   ]
  },
  {
   "title": "Operation details (pcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace({product=\"mongodb\",__name__=~\"operation_scanAndOrder_ps|operation_writeConflicts_ps|operation_exactIDCount_ps\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"},\"name\",\"$1\",\"__name__\",\"operation_(.+)_ps\")",
     "legendFormat": "{{logicIns}}/{{role}}/{{name}}"
    }
   ]
  },
  {
   "title": "WiredTigerCache usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "{product=\"mongodb\",__name__=~\"wt_cache_usage|wt_cache_dirty_usage\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "{{logicIns}}/{{role}}/{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of affected documents (pcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace({product=\"mongodb\",__name__=~\"document_deleted_ps|document_inserted_ps|document_returned_ps|\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"},\"name\",\"$1\",\"__name__\",\"document_(.+)_ps\")",
     "legendFormat": "{{logicIns}}/{{role}}/{{name}}"
    }
   ]
  },
  {
   "title": "Number of query scan indexes and documents (pcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace({product=\"mongodb\",__name__=~\"queryExecutor_scanned_ps|queryExecutor_scannedObject_ps\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"},\"name\",\"$1\",\"__name__\",\"queryExecutor_(.+)_ps\")",
     "legendFormat": "{{logicIns}}/{{role}}/{{name}}"
    }
   ]
  },
  {
   "title": "TTL (pcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace({product=\"mongodb\",__name__=~\"ttl_deletedDocuments_ps|ttl_passes_ps\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"},\"name\",\"$1\",\"__name__\",\"ttl_(.+)_ps\")",
     "legendFormat": "{{logicIns}}/{{role}}/{{name}}"
    }
   ]
  },
  {
   "title": "Average response time (microseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_rt{product=\"mongodb\",logicIns=~\"$instance\",role=~\"$role\",rdsIns=~\"$nodeId\"}",
     "legendFormat": "{{logicIns}}/{{role}}"
    }
   ]
  }
 ]
}