{
 "title": "MongoDB version of cloud database - replica set - instance details",
 "tags": [
  "scene:database",
  "dashboard:name:mongodb_replicaset-detail",
  "env:Cloud",
  "env:type:Cloud",
  "prometheus",
  "addon:name:cloud-mongodb_replicaset",
  "addon:version:0.0.4"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instanceId",
    "label": "InstanceId",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"mongodb_replicaset\"}, id)"
    }
   },
   {
    "name": "instanceName",
    "label": "InstanceName",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"mongodb_replicaset\",id=\"$instanceId\"}, instanceName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Example List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "cloud_monitor_instance_info{service=\"mongodb_replicaset\",instanceId=~\"$instanceId\",instanceName=~\"$instanceName\"}"
    }
   ]
  },
  {
   "title": "CPU usage rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_CPUUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of connections usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_ConnectionAmount{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Connection usage rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_ConnectionUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "The amount of disk space occupied by data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_DataDiskAmount{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Disk utilization rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_DiskUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Application grouping CPU usage rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_GroupCPUUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Application group connection usage rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_GroupConnectionUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Application group disk usage rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_GroupDiskUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Application grouping IOPS usage rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_GroupIOPSUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Application group memory usage rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_GroupMemoryUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "IOPS usage rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_IOPSUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "The amount of disk space occupied by the instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_InstanceDiskAmount{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Network incoming traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_IntranetIn{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Network traffic output",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_IntranetOut{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "The amount of disk space occupied by logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_LogDiskAmount{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Memory usage rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_MemoryUtilization{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_NumberRequests{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Command operation times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_OpCommand{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Delete operation times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_OpDelete{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Getmore operation times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_OpGetmore{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Insert operation times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_OpInsert{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Query operation times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_OpQuery{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Update operation frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_OpUpdate{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "OPLog retention duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "hour" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_OplogTimeInterval{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average number of SQL queries per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_QPS{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Copy delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_ReplicationLag{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average response time for writing operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_WriteAvgRt{id=~\"$instanceId\",instanceName=~\"$instanceName\"} / 1000000",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average response time for read operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunMongodb_replicaset_ReadAvgRt{id=~\"$instanceId\",instanceName=~\"$instanceName\"} / 1000000",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  }
 ]
}