{
 "title": "NAS-CPFS monitoring",
 "tags": [
  "nas",
  "addon:name:cloud-nas",
  "scene:middleware",
  "cmee",
  "cpfs",
  "env:Cloud",
  "env:type:Cloud",
  "addon:version:0.0.2",
  "prometheus",
  "dashboard:name:nas-cpfs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Data volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNas_CPFSCapacityUsed{}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{description}}/{{fileSystemId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Storage utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNas_CPFSCapacityUsed{} / on(fileSystemId) group_left() AliyunNas_CPFSCapacity{}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{description}}/{{fileSystemId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cn-short" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNas_CPFSInodeLimit{}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Limit:{{description}}/{{fileSystemId}}",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNas_CPFSInodeAlloc{}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Alloc:{{description}}/{{fileSystemId}}",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNas_CPFSInodeUsed{}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Used:{{description}}/{{fileSystemId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of files in Fileset",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cn-short" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNas_FsetInodeAlloc{}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Alloc:{{description}}/{{fileSystemId}}",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNas_FsetInodeUsed{}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Used:{{description}}/{{fileSystemId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "NFS IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNas_IopsRead{}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Read:{{description}}/{{fileSystemId}}",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNas_IopsWrite{}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Write:{{description}}/{{fileSystemId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "NFS Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNas_ThruputRead{}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Read:{{description}}/{{fileSystemId}}",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNas_ThruputWrite{}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Write:{{description}}/{{fileSystemId}}",
     "method": "GET"
    }
   ]
  }
 ]
}