{
 "title": "OSS monitoring dashboard",
 "tags": [
  "addon:name:cloud-oss",
  "dashboard:name:cmee-oss-overview",
  "scene:middleware",
  "cmee",
  "env:Cloud",
  "env:type:Cloud",
  "prometheus",
  "oss",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "query": {
     "query": "label_values({__name__=~\"AliyunOss_InternetRecvBandwidth|AliyunOss_IntranetRecvBandwidth|AliyunOss_InternetRecv|AliyunOss_IntranetRecv\"}, regionId)"
    }
   },
   {
    "name": "VarBucketName",
    "query": {
     "query": "label_values({__name__=~\"AliyunOss_InternetRecvBandwidth|AliyunOss_IntranetRecvBandwidth|AliyunOss_InternetRecv|AliyunOss_IntranetRecv\",regionId=~\"$regionId\"}, BucketName)"
    }
   },
   {
    "name": "VarUserId",
    "query": {
     "query": "label_values({__name__=~\"AliyunOss_InternetRecvBandwidth|AliyunOss_IntranetRecvBandwidth|AliyunOss_InternetRecv|AliyunOss_IntranetRecv\"}, userId)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User availability and success rate (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunOss_UserAvailability{userId=~\"$VarUserId\"}",
     "legendFormat": "Availability-{{userId}}"
    },
    {
     "expr": "AliyunOss_UserSuccessRate{userId=~\"$VarUserId\"}",
     "legendFormat": "Success rate-{{userId}}"
    }
   ]
  },
  {
   "title": "User request status (number)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunOss_UserTotalRequestCount{userId=~\"$VarUserId\"}",
     "legendFormat": "Total number of requests-{{userId}}"
    },
    {
     "expr": "AliyunOss_UserSuccessCount{userId=~\"$VarUserId\"}",
     "legendFormat": "Number of successful requests-{{userId}}"
    },
    {
     "expr": "AliyunOss_UserValidRequestCount{userId=~\"$VarUserId\"}",
     "legendFormat": "Number of valid requests-{{userId}}"
    }
   ]
  },
  {
   "title": "User public network bandwidth (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(AliyunOss_InternetRecvBandwidth{userId=~\"$VarUserId\"}) / 8 / 1024 / 1024",
     "legendFormat": "Public network inbound bandwidth-$VarUserId"
    },
    {
     "expr": "sum(AliyunOss_InternetSendBandwidth{userId=~\"$VarUserId\"}) / 8 / 1024 / 1024",
     "legendFormat": "Public network outbound bandwidth-$VarUserId"
    }
   ]
  },
  {
   "title": "User intranet bandwidth (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(AliyunOss_IntranetRecvBandwidth{userId=~\"$VarUserId\"}) / 8 / 1024 / 1024",
     "legendFormat": "Intranet inbound bandwidth-$VarUserId"
    },
    {
     "expr": "sum(AliyunOss_IntranetRecvBandwidth{userId=~\"$VarUserId\"}) / 8 / 1024 / 1024",
     "legendFormat": "Intranet outbound bandwidth-$VarUserId"
    }
   ]
  },
  {
   "title": "User CDN traffic (Byte)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "AliyunOss_UserCdnRecv", "legendFormat": "C DN inflow-{{userId}}" },
    { "expr": "AliyunOss_UserCdnSend", "legendFormat": "Cdn outflow-{{userId}}" }
   ]
  },
  {
   "title": "User cross-region replication traffic (Byte)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunOss_UserSyncRecv",
     "legendFormat": "Regional replication inflow-{{userId}}"
    },
    {
     "expr": "AliyunOss_UserSyncSend",
     "legendFormat": "Regional replication outflow-{{userId}}"
    }
   ]
  },
  {
   "title": "User public network traffic (Byte)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunOss_UserInternetRecv",
     "legendFormat": "Public network inflow-{{userId}}"
    },
    {
     "expr": "AliyunOss_UserInternetSend",
     "legendFormat": "Public network outflow-{{userId}}"
    }
   ]
  },
  {
   "title": "User intranet traffic (Byte)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "AliyunOss_UserIntranetRecv", "legendFormat": "Intranet inflow-{{userId}}" },
    { "expr": "AliyunOss_UserIntranetSend", "legendFormat": "Intranet outflow-{{userId}}" }
   ]
  },
  {
   "title": "Traffic monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Public network traffic (Byte)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "AliyunOss_InternetRecv{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Public network inflow-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_InternetSend{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Public network outflow-{{BucketName}}"
      }
     ]
    },
    {
     "title": "Intranet traffic (Byte)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "targets": [
      {
       "expr": "AliyunOss_IntranetRecv{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Intranet inflow-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_IntranetSend{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Intranet outflow-{{BucketName}}"
      }
     ]
    },
    {
     "title": "Cross-region replication traffic (Byte)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "AliyunOss_SyncRecv{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Cross-region replication inflow-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_SyncSend{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Cross-region replication outflow-{{BucketName}}"
      }
     ]
    },
    {
     "title": "CDN traffic (Byte)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
     "targets": [
      {
       "expr": "AliyunOss_CdnRecv{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Cdn inflow-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_CdnSend{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Cdn outflow-{{BucketName}}"
      }
     ]
    },
    {
     "title": "Public network bandwidth (KB/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "AliyunOss_InternetRecvBandwidth{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"} / 8 / 1024",
       "legendFormat": "Public network inflow-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_InternetSendBandwidth{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"} / 8 / 1024",
       "legendFormat": "Public network outflow-{{BucketName}}"
      }
     ]
    },
    {
     "title": "Intranet traffic (Byte) Network bandwidth (KB/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "AliyunOss_IntranetRecvBandwidth{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"} / 8 / 1024",
       "legendFormat": "Intranet inflow-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_IntranetSendBandwidth{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"} / 8 / 1024",
       "legendFormat": "Intranet outflow-{{BucketName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "HeadObject request delay (ms)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "AliyunOss_HeadObjectE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-end-to-end-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_HeadObjectServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxHeadObjectE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-end-to-end-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxHeadObjectServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-end-to-end-{{Bucket Name}}"
      }
     ]
    },
    {
     "title": "GetObject request delay (ms)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 35 },
     "targets": [
      {
       "expr": "AliyunOss_GetObjectE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-end-to-end-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_GetObjectServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxGetObjectE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-end-to-end-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxGetObjectServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-end-to-end-{{BucketName}}"
      }
     ]
    },
    {
     "title": "PutObject request delay (ms)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "AliyunOss_PutObjectE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_PutObjectServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-end-to-end-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxPutObjectE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxPutObjectServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-end-to-end-{{BucketName}}"
      }
     ]
    },
    {
     "title": "PostObject request delay (ms)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 35 },
     "targets": [
      {
       "expr": "AliyunOss_PostObjectE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_PostObjectServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-end-to-end-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxPostObjectE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxPostObjectServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-end-to-end-{{BucketName}}"
      }
     ]
    },
    {
     "title": "AppendObject request delay (ms)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "AliyunOss_AppendObjectE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_AppendObjectServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-end-to-end-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxAppendObjectE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxAppendObjectServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-end-to-end-{{BucketName}}"
      }
     ]
    },
    {
     "title": "CopyObject request delay (ms)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 44 },
     "targets": [
      {
       "expr": "AliyunOss_CopyObjectE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_CopyObjectServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxCopyObjectE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxCopyObjectServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-end-to-end-{{BucketName}}"
      }
     ]
    },
    {
     "title": "UploadPart request delay (ms)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "AliyunOss_UploadPartE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_UploadPartServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-end-to-end-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxUploadPartE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxUploadPartServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-end-to-end-{{BucketName}}"
      }
     ]
    },
    {
     "title": "UploadPartCopy request delay (ms)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 44 },
     "targets": [
      {
       "expr": "AliyunOss_UploadPartCopyE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_UploadPartCopyServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-end-to-end-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxUploadPartCopyE2eLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Average-server-{{BucketName}}"
      },
      {
       "expr": "AliyunOss_MaxUploadPartCopyServerLatency{userId=~\"$VarUserId\", BucketName=~\"$VarBucketName\"}",
       "legendFormat": "Maximum-end-to-end-{{BucketName}}"
      }
     ]
    }
   ]
  }
 ]
}