{
 "title": "PolarDB Global AWR_A",
 "tags": [
  "PolarDB",
  "GAWR"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "grafana-postgresql-datasource" },
   {
    "name": "LogicInstanceShow",
    "label": "Logical Instance ID",
    "query": "SELECT logical_ins_name FROM $LogicInstance.dim_ins_info WHERE logical_ins_name != 'others'"
   },
   {
    "name": "PhysicalInstance",
    "label": "Physical Instance ID",
    "query": "SELECT physical_ins_name FROM $LogicInstance.dim_ins_info WHERE physical_ins_name != 'others'"
   },
   { "name": "LogicInstance", "label": "逻辑实例id", "query": "SELECT 'polar_gawr_collection'" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Role",
   "type": "state-timeline",
   "description": "Metric Description: \n- Database compute nodes are categorized as read-write (RW) nodes or read-only (RO) nodes.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n time - time % ((($__interval_ms / 1000)::INTEGER)::integer) AS time,\n MAX(role) AS Role\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Version",
   "type": "state-timeline",
   "description": "Metric Description: \n- Version details of the database instance include the release date and version number.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n MAX(version) AS Version\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Metric Description: \n- CPU usage status of the database instance.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n (AVG(cpu_user_usage) + AVG(pfsd_cpu_user / cpu_cores) + AVG(cpu_sys_usage) + AVG(pfsd_cpu_sys / cpu_cores))\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Metric Description: \n- Memory usage status of the database instance.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(mem_total_usage)\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "IO",
   "type": "stat",
   "description": "Metric Description: \n- The current I/O throughput of the database instance indicates how busy the I/O is.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(pls_throughput_read + pls_throughput_write)\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk Space Usage Rate",
   "type": "stat",
   "description": "Metric Description: \n- Disk space usage rate of the database instance.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(fs_blocks_usage)\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "description": "Metric Description: \n- Average TPS during the current time interval.\n\nMetric Source & Collection Method: \n- The metric is obtained from the pg_stat_database view as `SUM(xact_commit) + SUM(xact_rollback)`, and a delta is calculated during collection.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(commits_delta+rollbacks_delta) AS TPS\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "Metric Description: \n- Current active connections, indicating the database workload during the time window.\n\nMetric Source & Collection Method: \n- Source: pg_stat_activity view. The metric is calculated as `SUM(CASE WHEN state IN ('active') THEN 1 ELSE 0 END)` to count active backend sessions.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(active_connections) AS active_connections\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "stat",
   "description": "Metric Description: \n- The average buffer hit rate of database block reads within the time window.\n\nMetric Source & Collection Method: \n- From the pg_stat_database view. blks_hit: Number of blocks hit in the buffer cache (no disk read required). blks_read: Number of blocks read from disk. Hit ratio: blks_hit / (blks_hit + blks_read).",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(blks_hit_delta / (blks_hit_delta + blks_read_delta + 1))\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "RO Synchronization Delay",
   "type": "stat",
   "description": "Metric Description: \n- Current delay of the slowest RO instance attached to the RW instance.\n- This panel is displayed only for RW nodes.\n\nMetric Source & Collection Method: \n- Metric source: replay_lag in the pg_stat_replication view. The maximum value is selected for entries where application_name matches replica%, indicating the current maximum delay of RO nodes.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n MAX(replay_lag_in_ms) AS replay\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_pg_stat_replication, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND application_name like 'replica%'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Active Session",
   "type": "timeseries",
   "description": "Metric Description: \n- This histogram shows the average number of sessions per second waiting on each event. If a session is not waiting, it is considered to be using CPU. The concept aligns with Oracle ASH.\n\nMetric Source & Collection Method: \n- Wait events are collected from the pg_stat_activity view at a one-second interval, using the fields wait_event_type and wait_event. A session with a NULL value in wait_event is considered to be using CPU.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n wait_event_type::text || ':' || wait_event AS metric,\n CASE WHEN ($__interval_ms / 1000) >= 3600 THEN ROUND(CAST(SUM(wait_count) AS NUMERIC) / (($__interval_ms / 3600 / 1000)::INTEGER), 2)::FLOAT\n WHEN ($__interval_ms / 1000) >= 60 THEN ROUND(CAST(SUM(wait_count) AS NUMERIC) / (($__interval_ms / 60 / 1000)::INTEGER), 2)::FLOAT\n ELSE ROUND(CAST(SUM(wait_count) AS NUMERIC) / (($__interval_ms / 1000)::INTEGER), 2)::FLOAT END AS wait_count\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_aas_history, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), metric\nORDER BY 1"
    }
   ]
  },
  { "title": "Resource - CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "title": "CPU", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "options": { "content": " " } },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "description": "Metric Description: \n- Database User Mode: CPU usage in user mode\n- Database System Mode: CPU usage in system mode\n",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(cpu_user_usage) + AVG(pfsd_cpu_user / cpu_cores) AS database_user_mode,\n AVG(cpu_sys_usage) + AVG(pfsd_cpu_sys / cpu_cores) AS database_system_mode\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU Usage by Process Type (stacked)",
   "type": "timeseries",
   "description": "Metric Description: \n- Stacked view of CPU usage by process type over the selected time window, including both user and system mode.\n- Since client backend processes represent database sessions that can fluctuate over time, precise measurement of incremental CPU usage is challenging. This may lead to some *estimation error* in the reported values.\n\nMetric Source & Collection Method: \n- CPU usage is collected via the polar_stat_process view by reading /proc/<pid>/stat. The values are cumulative and have been differenced over the specified time window for display.",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT time, metric, cpu FROM (\nSELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n backend_type AS metric,\n AVG(cpu_user+cpu_sys) / (SELECT cpu_cores FROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER) ORDER BY time DESC LIMIT 1) AS cpu\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_process, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND\n $__unixEpochFilter(time)\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), backend_type\nUNION ALL\nSELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n 'postmaster' AS metric,\n AVG(postmaster_cpu) AS cpu\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND\n $__unixEpochFilter(time)\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nUNION ALL\nSELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n 'logger' AS metric,\n AVG(logger_cpu) AS cpu\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND\n $__unixEpochFilter(time)\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nUNION ALL\nSELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n 'pgstat' AS metric,\n AVG(pgstat_cpu) AS cpu\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND\n $__unixEpochFilter(time)\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\n) a ORDER BY time"
    }
   ]
  },
  { "title": "Resource - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  { "title": "Memory", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }, "options": { "content": " " } },
  {
   "title": "Memory Usage (%)",
   "type": "graph",
   "description": "Metric Description: \n- Memory usage of the database instance over the specified time window.",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 35 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n MAX(mem_total_usage) AS memory_usage_rate\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Memory: Stacked by Process Type",
   "type": "timeseries",
   "description": "Metric Description: \n- Summary of private memory usage by process type within the specified time window.\n\nMetric Source & Collection Method: \n- From the rss column in the polar_stat_process view, obtain the Rss and Share values by reading the /proc/%pid/statm file corresponding to each process, and finally output the calculated `Rss - Share` as the process's private memory consumption.",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT time, metric, rss FROM (\nSELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n backend_type AS metric,\n AVG(rss) AS rss\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_process, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), backend_type\nUNION ALL\nSELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n 'postmaster' AS metric,\n AVG(postmaster_mem) AS rss\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nUNION ALL\nSELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n 'pgstat' AS metric,\n AVG(pgstat_mem) AS rss\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nUNION ALL\nSELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n 'logger' AS metric,\n AVG(logger_mem) AS rss\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\n) a ORDER BY time"
    }
   ]
  },
  {
   "title": "Top Memory-Consuming Sessions (Over 200MB)",
   "type": "table",
   "description": "Metric Description: \n- Top processes by private memory usage within the specified time window, including the collection timestamp, RSS values, and query information.\n\nMetric Source & Collection Method: \n- polar_stat_process view, filtered by RSS usage.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": " SELECT pid AS pid, rss_mb AS \"RSS(MB)\", TO_CHAR(TO_TIMESTAMP(time), 'YYYY-MM-DD HH24:MI:SS') AS timepoint, query AS query\n FROM ${LogicInstance}.view_fact_polar_stat_max_memory_sql \n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n ORDER BY rss_mb DESC, time DESC LIMIT 10\n\n"
    }
   ]
  },
  {
   "title": "Top Memory Context",
   "type": "table",
   "description": "Metric Description: \n- List the Memory Context information of the process that consumes the most memory within the current time window, to gain a more granular view of its memory usage.\n\nMetric Source & Collection Method: \n- The process with the highest RSS is identified from the polar_stat_process view. Its memory contexts are then fetched using `polar_get_mcxt()`, and the top few largest memory contexts are returned as the final result.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": " SELECT pid AS \"pid\", name AS \"Memory Context\", totalspace / 1024 / 1024 AS \"MB\", TO_CHAR(TO_TIMESTAMP(time), 'YYYY-MM-DD HH24:MI:SS') AS \"timepoint\"\n FROM ${LogicInstance}.view_fact_polar_max_memory_backend_memory_context\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n ORDER BY totalspace DESC, time DESC LIMIT 10\n\n"
    }
   ]
  },
  { "title": "Resource - IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  { "title": "Shared Storage I/O", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }, "options": { "content": " " } },
  {
   "title": "IOPS",
   "type": "timeseries",
   "description": "Metric Description: \n- Display the disk read and write IOPS of the shared storage medium for the database instance within the current time window.\n",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(pls_iops_read) AS read,\n AVG(pls_iops_write) AS write\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "description": "Metric Description: \n- Display the disk read and write throughput of the shared storage medium for the database instance within the current time window.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(pls_throughput_read) AS read,\n AVG(pls_throughput_write) AS write\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "description": "Metric Description: \n- Display the disk read and write latency of the shared storage medium for the database instance within the current time window.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(pls_latency_read) AS read,\n AVG(pls_latency_write) AS write\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  { "title": "Database I/O by File Type", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 }, "options": { "content": " " } },
  {
   "title": "PFS read iops",
   "type": "graph",
   "description": "Metric Description: \n- Display the IOPS distribution of read operations across different file types on the shared storage medium within the current time window.\n\nMetric Source & Collection Method: \n- Aggregated I/O statistics from `polar_stat_io_info()` grouped by process type.\n- Detailed I/O information for each process is displayed using the polar_stat_io_info function, showing which types of files (e.g., WAL, data, log, index) the process accessed and what operations (e.g., seek, read, write, fsync, falloc) were performed.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 71 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n filetype AS metric,\n AVG(read_count) AS read_iops\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_info, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND fileloc='pfs'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), filetype\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PFS write iops",
   "type": "graph",
   "description": "Metric Description: \n- Display the IOPS distribution of write operations across different file types on the shared storage medium within the current time window.\n\nMetric Source & Collection Method: \n- Aggregated I/O statistics from `polar_stat_io_info()` grouped by process type.\n- Detailed I/O information for each process is displayed using the polar_stat_io_info function, showing which types of files (e.g., WAL, data, log, index) the process accessed and what operations (e.g., seek, read, write, fsync, falloc) were performed.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 71 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n filetype AS metric,\n AVG(write_count) AS write_iops\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_info, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND fileloc='pfs'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), filetype\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PFS seek iops",
   "type": "graph",
   "description": "Metric Description: \n- Display the IOPS distribution of seek operations across different file types on the shared storage medium within the current time window.\n\nMetric Source & Collection Method: \n- Aggregated I/O statistics from `polar_stat_io_info()` grouped by process type.\n- Detailed I/O information for each process is displayed using the polar_stat_io_info function, showing which types of files (e.g., WAL, data, log, index) the process accessed and what operations (e.g., seek, read, write, fsync, falloc) were performed.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 71 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n filetype AS metric,\n AVG(seek_count) AS seek_iops\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_info, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND fileloc='pfs'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), filetype\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PFS open iops",
   "type": "graph",
   "description": "Metric Description: \n- Display the IOPS distribution of open operations across different file types on the shared storage medium within the current time window.\n\nMetric Source & Collection Method: \n- Aggregated I/O statistics from `polar_stat_io_info()` grouped by process type.\n- Detailed I/O information for each process is displayed using the polar_stat_io_info function, showing which types of files (e.g., WAL, data, log, index) the process accessed and what operations (e.g., seek, read, write, fsync, falloc) were performed.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 71 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n filetype AS metric,\n AVG(open_count) AS open_iops\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_info, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND fileloc='pfs'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), filetype\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PFS read bps",
   "type": "graph",
   "description": "Metric Description: \n- Display the I/O bandwidth distribution of read operations across different file types on the shared storage medium within the current time window.\n\n\nMetric Source & Collection Method: \n- Aggregating I/O information across each process type dimension via the polar_stat_io_info function.\n- I/O activity per process is visualized using polar_stat_io_info including file type (WAL, data, log, index) and operation type (read, write).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n filetype AS metric,\n AVG(read_throughput) AS read_throughput\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_info, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND fileloc='pfs'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), filetype\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PFS write bps",
   "type": "graph",
   "description": "Metric Description: \n- Display the I/O bandwidth distribution of write operations across different file types on the shared storage medium within the current time window.\n\nMetric Source & Collection Method: \n- Aggregating I/O information across each process type dimension via the polar_stat_io_info function.\n- I/O activity per process is visualized using polar_stat_io_info including file type (WAL, data, log, index) and operation type (read, write).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n filetype AS metric,\n AVG(write_throughput) AS write_throughput\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_info, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND fileloc='pfs'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), filetype\nORDER BY 1"
    }
   ]
  },
  { "title": "Database I/O: Latency", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 }, "options": { "content": " " } },
  {
   "title": "Read Latency Distribution",
   "type": "timeseries",
   "description": "Metric Description: \n- Display the read operation latency within the current time window, including both the shared storage medium and local directories.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG((num_lessthan200us+0.00001) / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"[0, 200us]\",\n AVG(num_lessthan400us / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(200us, 400us]\",\n AVG(num_lessthan1ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(400us, 1ms]\",\n AVG(num_lessthan10ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(1ms, 10ms]\",\n AVG(num_lessthan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(10ms, 100ms]\",\n AVG(num_morethan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(100ms, )\"\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_latency, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND iotype='read'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Write Latency Distribution",
   "type": "timeseries",
   "description": "Metric Description: \n- Display the read latency within the current time window, covering both the shared storage medium and local directories.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG((num_lessthan200us+0.00001) / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"[0, 200us]\",\n AVG(num_lessthan400us / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(200us, 400us]\",\n AVG(num_lessthan1ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(400us, 1ms]\",\n AVG(num_lessthan10ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(1ms, 10ms]\",\n AVG(num_lessthan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(10ms, 100ms]\",\n AVG(num_morethan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(100ms, )\"\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_latency, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND iotype='write'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Seek Latency Distribution",
   "type": "timeseries",
   "description": "Metric Description: \n- Display the seek operation latency within the current time window, covering both the shared storage medium and local directories.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG((num_lessthan200us+0.00001) / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"[0, 200us]\",\n AVG(num_lessthan400us / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(200us, 400us]\",\n AVG(num_lessthan1ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(400us, 1ms]\",\n AVG(num_lessthan10ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(1ms, 10ms]\",\n AVG(num_lessthan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(10ms, 100ms]\",\n AVG(num_morethan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(100ms, )\"\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_latency, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND iotype='seek'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Open Latency Distribution",
   "type": "timeseries",
   "description": "Metric Description: \n- Display the open operation latency within the current time window, covering both the shared storage medium and local directories.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG((num_lessthan200us+0.00001) / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"[0, 200us]\",\n AVG(num_lessthan400us / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(200us, 400us]\",\n AVG(num_lessthan1ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(400us, 1ms]\",\n AVG(num_lessthan10ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(1ms, 10ms]\",\n AVG(num_lessthan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(10ms, 100ms]\",\n AVG(num_morethan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+0.00001)) AS \"(100ms, )\"\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_latency, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND iotype='open'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  { "title": "Resource - Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  { "title": "Disk Space", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }, "options": { "content": " " } },
  {
   "title": "Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(fs_blocks_usage) AS block_usage_rate,\n AVG(fs_inodes_usage) AS inode_usage_rate\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Space Distribution",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(polar_base_dir_size) AS data_dir_size,\n AVG(polar_wal_dir_size) AS WAL_dir_size\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  { "title": "DB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Connection",
   "type": "graph",
   "description": "Metric Description: \n- Display the total, active, and idle connection counts of the database instance within the current time window.\n\nMetric Source & Collection Method: \n- From the pg_stat_activity view.\n- Active connections count entries with `state = 'active'`, idle connections count entries with `state = 'idle'`, and total connections equal the total rows in pg_stat_activity.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(connections) AS total,\n AVG(active_connections) AS active,\n AVG(idle_connections) AS idle\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "graph",
   "description": "Metric Description: \n- Display the active and idle transaction counts of the database instance within the current time window.\n\nMetric Source & Collection Method: \n- From the pg_stat_activity view\n- Number of active transactions refers to entries with `state = 'active'`, and number of idle transactions refers to entries with state in `['idle in transaction', 'idle in transaction (aborted)']`.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(active_transactions) AS active,\n AVG(idle_transactions) AS idle\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "description": "Metric Description: \n- Display the total number of commits, total number of rollbacks, and TPS within the current time window. TPS is the sum of commit and rollback counts. These metrics reflect the operational status of the database instance.\n\nMetric Source & Collection Method: \n- Calculate based on the total commit and rollback counts from the pg_stat_database view.\n- Commit count: xact_commit; rollback count: xact_rollback; TPS is the sum of the two.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(commits_delta) AS commits,\n AVG(rollbacks_delta) AS rollbacks,\n AVG(commits_delta+rollbacks_delta) AS TPS\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "graph",
   "description": "Metric Description: \n- Display the read, update, and delete operations on tuples within the current time window for the database instance. These metrics reflect the operational status and help assess the performance of the database.\n\nMetric Source & Collection Method: \n- Calculate the tuple-related metrics by using the pg_stat_database view. Since the corresponding fields in this view are cumulative values, the difference per second is computed during collection.\n- The corresponding fields in the pg_stat_database view are as follows, all of which are cumulative values: tup_returned: Number of tuples (rows) returned by queries since the database was started. tup_fetched: Number of tuples physically fetched from disk by queries since the database was started. tup_inserted: Number of tuples inserted since the database was started. tup_updated: Number of tuples updated since the database was started. tup_deleted: Number of tuples deleted since the database was started.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(tup_returned_delta) AS tup_returned,\n AVG(tup_fetched_delta) AS tup_fetched,\n AVG(tup_inserted_delta) AS tup_inserted,\n AVG(tup_updated_delta) AS tup_updated,\n AVG(tup_deleted_delta) AS tup_deleted\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DB Age",
   "type": "graph",
   "description": "Metric Description: \n- This reflects the current age of the database, which is related to the oldest frozen transaction ID. A high database age typically indicates long-running transactions or infrequent VACUUM operations. When the database age becomes very large (e.g., over 1.2 billion), it can impact performance and increase the risk of transaction ID wraparound (which occurs at over 2.1 billion).\n\nMetric Source & Collection Method: \n- Calculate the `AGE(datfrozenxid)` field for each database from the pg_database view, and return the maximum value.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 129 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(db_age) AS db_age\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Longest Transaction Duration",
   "type": "timeseries",
   "description": "Metric Description: \n- Display the longest transaction duration within the current time window, where the transaction is still active (not yet committed or rolled back). This helps assess long-running transactions, which can lead to increased database age, WAL log bloat, and inability to vacuum outdated tuples.\n\nMetric Source & Collection Method: \n- From the pg_stat_activity view.\n- Calculate the duration since the earliest active transaction started, or the duration since the earliest prepared transaction was prepared. The resulting time interval is referred to as swell_time.\n- The earliest active transaction refers to the one that has actually started a transaction session. A prepared transaction refers to a transaction in the two-phase commit (2PC) protocol — that is, a transaction that has been prepared for commit but has not yet been finalized (committed or rolled back).\n- Collection sql：WITH a AS (SELECT MIN(xact_start) m FROM pg_stat_activity WHERE backend_type='client backend' AND (backend_xid IS NOT NULL OR backend_xmin IS NOT NULL)), b AS (SELECT MIN(prepared) m FROM pg_prepared_xacts) SELECT EXTRACT(EPOCH FROM NOW()-LEAST(a.m,b.m))::BIGINT FROM a,b",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(swell_time) AS longest_transaction_duration\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Longest SQL Duration",
   "type": "graph",
   "description": "Metric Description: \n- Display the duration of the slowest ongoing SQL query within the current time window to help evaluate SQL execution performance in the database.\n\nMetric Source & Collection Method: \n- The metric is derived from the pg_stat_activity view, filtered with the conditions `backend_type = 'client backend'` and `state = 'active'`.\n- Return the record with the maximum value of `now() - query_start`",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 129 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(longest_sql_running_time) AS longest_sql_running_time\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Replication Lag(bytes)",
   "type": "timeseries",
   "description": "Metric Description: \n- Display the replication lag (including send, write, flush, and replay delays) in MB between the primary database and each standby instance or connection that has established streaming replication, within the current time window. The name of each streaming replication connection is also included. This metric is collected only from the read-write (RW) node.\n\nMetric Source & Collection Method: \n- From the pg_stat_replication view.\n- Data is collected by grouping records in pg_stat_replication by application_name, and calculating the difference between sent_lsn, write_lsn, flush_lsn, and replay_lsn for each replication stream and the current_lsn on the read-write (RW) node. These differences represent send lag, write lag, flush lag, and replay lag, respectively.\n- sent_lsn: The last WAL log position (LSN) sent from the read-write (RW) node to the replication receiver. write_lsn: The last WAL position confirmed to have been written to disk by the replication receiver. flush_lsn: The last WAL position confirmed to have been flushed (fsync) by the replication receiver. In PolarDB, which uses direct I/O, all WAL logs up to write_lsn are effectively already flushed. replay_lsn: The last WAL position confirmed to have been replayed by the replication receiver.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n application_name AS metric,\n AVG(sent_latency_in_bytes) AS sent,\n AVG(write_latency_in_bytes) AS write,\n AVG(flush_latency_in_bytes) AS flush,\n AVG(replay_latency_in_bytes) AS replay\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_pg_stat_replication, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND application_name NOT LIKE 'standby%'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), application_name\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Replication Lag(time)",
   "type": "graph",
   "description": "Metric Description: \n- Display the replication lag (including write lag, flush lag, and replay lag) in milliseconds between the primary database and each instance or connection that has established streaming replication, within the current time window. The name of each streaming replication connection is also included. This metric is collected only from the read-write (RW) node.\n\nMetric Source & Collection Method: \n- From the pg_stat_replication view.\n- Data is collected by grouping entries in the pg_stat_replication view by application_name, and retrieving the write_lag, flush_lag, and replay_lag fields as write lag, flush lag, and replay lag, respectively.\n- write_lag: The delay between the time a WAL log is received by the replication receiver and the time it is written to the operating system. flush_lag: The delay between the time a WAL log is received by the replication receiver and the time it is flushed (fsync) to disk. replay_lag: The delay between the time a WAL log is received by the replication receiver and the time it is successfully replayed.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 138 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n application_name AS metric,\n AVG(replay_lag_in_ms) AS replay,\n AVG(write_lag_in_ms) AS write,\n AVG(flush_lag_in_ms) AS flush\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_pg_stat_replication, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}' AND application_name NOT LIKE 'standby%'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), application_name\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DB Read",
   "type": "timeseries",
   "description": "Metric Description: \n- Display the number of block reads from cache and disk for the database instance within the current time window, which can reflect the block read status and cache hit ratio to a certain extent.\n- blks_read：The number of blocks read from disk within the current time window.\n- blks_hit：The number of blocks that were found in the buffer cache (i.e., cache hits) within the current time window, avoiding disk I/O.\n\nMetric Source & Collection Method: \n- The data is obtained from the pg_stat_database view. Since the blks_read and blks_hit fields in this view are cumulative, the difference between their values over the specified time window is calculated to obtain the data for the current period.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(blks_read_delta) AS blks_read,\n AVG(blks_hit_delta) AS blks_hit\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DB Write",
   "type": "timeseries",
   "description": "Metric Description: \n- Display the number of dirty page writes from buffer to disk by each process (bg_writer, backend, checkpoint) within the current time window. In PolarDB, the dirty page writes from backend processes include all activity excluding bgwriter and checkpoint processes, such as parallel writes and IOWorker operations. This metric reflects the distribution of dirty page writes across different processes in the database instance.\n\nMetric Source & Collection Method: \n- The data comes from the pg_stat_bgwriter view, a PostgreSQL system view that provides statistics on the background writer process.\n- checkpoint: Corresponds to the buffers_checkpoint column in the view, representing the number of buffer blocks written to disk during checkpoint operations.\n- bgwriter: Corresponds to the buffers_clean column in the view, representing the number of dirty pages cleaned by the background writer process during its normal operation.\n- backend: Corresponds to the buffers_backend column in the view, representing the number of buffer blocks written to disk by other processes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(buffers_checkpoint_delta) AS checkpoint,\n AVG(buffers_backend_delta) AS backend,\n AVG(buffers_clean_delta) AS bgwriter\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PolarDB LSN Positions",
   "type": "timeseries",
   "description": "Metric Description: \n- Terminology Explanation: WP (Write LSN): Represents the current WAL write position on the primary node. It can be queried using `select pg_current_wal_insert_lsn();`. CP (Consistent LSN): Indicates the consistency point, meaning all data up to this LSN has been written to disk. It can be queried using `select polar_consistent_lsn();`. AP (Apply LSN): Represents the replay position on the read-only (RO) nodes. In monitoring, it refers to the minimum replay LSN among all RO nodes. It can be queried using `select polar_oldest_apply_lsn();`. \n- wp_cp_latency_mb: The gap between the latest LSN and the Consistent LSN. A large value may indicate high RW write pressure or a recent checkpoint failure. You can combine the current pressure status of RW with the command `grep -nr 'Checkpoint approved' *error.log` to search for relevant records of ’Checkpoint approved‘ in the error logs. This will help determine whether the Checkpoint was executed properly within the time period, thus aiding in the root cause analysis.\n- ap_cp_latency_mb: The gap between the consistency checkpoint position and the RO replay position.\n- wp_ap_latency_mb: The gap between the current latest LSN and the RO replay position. A large value indicates significant RO replay delay; you can investigate whether there are inactive replication slots present.\n\nMetric Source & Collection Method: \n- wp_cp_latency_mb: pg_current_wal_insert_lsn(), polar_consistent_lsn())。\n- ap_cp_latency_mb: pg_wal_lsn_diff(polar_oldest_apply_lsn(), polar_consistent_lsn())。\n- wp_ap_latency_mb: pg_wal_lsn_diff(pg_current_wal_lsn(), polar_oldest_apply_lsn())。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(wp_cp_latency_mb) AS wp_cp_latency_mb,\n AVG(ap_cp_latency_mb) AS ap_cp_latency_mb,\n AVG(wp_ap_latency_mb) AS wp_ap_latency_mb\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Checkpoint Delay",
   "type": "graph",
   "description": "Metric Description: \n- Relevant terminology explanation: The Checkpoint position refers to the Checkpoint.redo point. In the native logic checkpoint mechanism, Checkpoint.redo is set to the current Write LSN, requiring all data up to that point to be flushed to disk. When PolarDB's lazy checkpoint feature is enabled, Checkpoint.redo is set to the current consistency position, allowing the checkpoint to complete quickly and non-blockingly.\n- When the checkpoint position experiences significant latency, it directly affects the amount of log that needs to be replayed during cluster crash recovery. The larger the volume of logs to be replayed, the longer the recovery time, and the greater the potential impact on cluster availability.\n\nThe following scenarios may lead to checkpoint position latency:\n- Consistency position latency can lead to checkpoint position latency. The cause of consistency position latency should be prioritized for investigation.\n- Any factors that cause consistency position latency can also lead to checkpoint position latency. For example, bulk data modifications in the workload or delayed dirty page flushing may contribute to such delays.\n- The checkpoint execution cycle is long, and a significant amount of data modifications occur within each cycle.\n\nMetric Source & Collection Method: \n- select redo_lsn from pg_control_checkpoint();。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 160 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(checkpoint_latency_mb) AS checkpoint延迟\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "dirty page",
   "type": "graph",
   "description": "Metric Description: \n- The metric displays the number of dirty pages in the current time window, reflecting the current update and write pressure on the database instance.\n\nMetric Source & Collection Method: \n- From the polar_flushlist() function.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 169 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(polar_dirtypage_size) AS polar_dirtypage_size\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Inactive Slots",
   "type": "timeseries",
   "description": "Metric Description: \n- Inactive replication slots should be closely monitored when their count is greater than zero, as they may lead to the risk of WAL log accumulation.\n\nMetric Source & Collection Method: \n- `select count(*) AS inactive_slots from pg_replication_slots where restart_lsn is not null and active = 'f';`",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n AVG(inactive_slots) AS inactive_slots\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  { "title": "SQL & Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 178 } },
  {
   "title": "Top Slow Queries",
   "type": "table",
   "description": "Metric Description: \n- Displays SQL statements that have been executing for more than 5 seconds and are still in progress within the current time window. The information shown includes the process PID, the database name of the query, the type and count of wait events, execution time, and the specific SQL text.\n\nMetric Source & Collection Method: \n- Collected based on views such as polar_stat_process.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 179 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n pid AS pid, \n dbname AS dbname, \n string_agg(wait_event || ':' || wait_event_count, ', ') AS wait_event_and_event_count, \n MAX(executing_time) / 60 AS max_sample_execution_time_min, \n query AS query \nFROM (\n SELECT\n pid AS pid,\n dbname AS dbname,\n CASE WHEN wait_event_type = '' THEN 'CPU:CPU' ELSE wait_event_type || ':' || wait_event END AS wait_event,\n query AS query,\n COUNT(*) AS wait_event_count,\n MAX(executing_time) AS executing_time\n FROM ${LogicInstance}.view_fact_polar_stat_slow_query\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() \n AND physical_ins_name='${PhysicalInstance}'\n GROUP BY pid, dbname, CASE WHEN wait_event_type = '' THEN 'CPU:CPU' ELSE wait_event_type || ':' || wait_event END, query\n) a \nGROUP BY pid, dbname, query \nORDER BY 3 DESC;"
    }
   ]
  },
  {
   "title": "Top Lock Contentions",
   "type": "table",
   "description": "Metric Description: \n- Displays the lock contention situation within the current time window. It lists the database, table, lock type, lock level, and the total number of other sessions that were blocked during the period this lock was held.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 191 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n datname AS database,\n relation AS relation,\n locktype AS lock_type,\n mode AS lock_mode,\n query AS query,\n SUM(total_num)::BIGINT AS total_blocked_sessions\n FROM ${LogicInstance}.view_fact_polar_lock_contention_history\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n GROUP BY 数据库, 表, 锁类型, 锁级别, query\n ORDER BY 累计阻塞采样会话数 DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Top Long-Running Transactions (>5s)",
   "type": "table",
   "description": "Metric Description: \n- Displays the top 10 longest-running transactions (>5s) within the current time window, along with detailed information such as application, client, database, user, process, query, status, and wait events.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 203 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "WITH x AS (\nSELECT\n time,\n application_name,\n client,\n dbname,\n username,\n pid,\n query,\n state,\n CASE WHEN wait_event_type='' THEN 'CPU:CPU' ELSE wait_event_type || ':' || wait_event END AS wait_event_union,\n transaction_time AS transaction_time\n FROM ${LogicInstance}.view_fact_polar_stat_long_transaction\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n ) \nSELECT \n TO_TIMESTAMP(time)::TEXT AS \"last_sample_time\",\n x.application_name AS \"application_name\",\n x.client AS \"client\",\n x.dbname AS \"dbname\",\n x.username AS \"username\",\n x.pid AS \"pid\",\n x.query AS \"last_query\",\n x.state AS \"state\",\n x.wait_event_union AS \"wait_event\",\n x.transaction_time AS \"transaction_time\"\n FROM x\n \n JOIN (\nSELECT\n application_name,\n client,\n dbname,\n username,\n pid,\n query,\n state,\n wait_event_union,\n MAX(transaction_time) AS max_transaction_time\n FROM x\n \n GROUP BY application_name, client, dbname, username, pid, query, state, wait_event_union\n ORDER BY max_transaction_time DESC LIMIT 10\n ) b ON x.application_name=b.application_name AND x.client=b.client AND x.dbname=b.dbname AND x.username=b.username AND x.pid=b.pid AND x.transaction_time=b.max_transaction_time"
    }
   ]
  },
  {
   "title": "The following data requires the pg_stat_statements extension to be enabled.",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 215 },
   "options": { "content": " " }
  },
  {
   "title": "Top Total Execution Time",
   "type": "table",
   "description": "Metric Description: \n- Displays detailed information about SQL statements with the longest total execution time within the current time window. This includes total execution time, average execution time, IO ratio, physical and logical read/write operations, number of rows processed, and more.\n- Physical & Logical Explanation: Logical Read indicates the number of times a page read operation is invoked, including both reading from the buffer (cache hit) and reading from disk (cache miss). Physical read refers to the number of times data is read directly from disk. Logical write and physical write are similar in concept to logical and physical read, respectively. The ratio between physical I/O and logical I/O reflects the cache hit rate during the execution of the SQL statement to some extent.\n\nMetric Source & Collection Method: \n- Obtained by processing the pg_stat_statements, pg_user, and pg_database views.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 216 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "\n\n\n WITH x AS (\n SELECT * FROM ${LogicInstance}.view_fact_polar_stat_top_sql\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n )\n SELECT queryid AS queryid, query AS query,\n \n ROUND(SUM(total_time)::NUMERIC, 2) AS \"total_time(ms)\",\n SUM(calls)::BIGINT AS total_calls,\n ROUND((SUM(total_time) / SUM(calls))::NUMERIC, 2) AS \"avg_time(ms)\",\n ROUND((SUM(blk_iotime) / SUM(total_time) * 100)::NUMERIC, 2) AS \"IO_time(%)\",\n SUM(logical_read)::BIGINT AS logical_read,\n SUM(blks_read)::BIGINT AS blks_read,\n SUM(logical_write)::BIGINT AS logical_write,\n SUM(blks_written)::BIGINT AS blks_write,\n SUM(rows)::BIGINT AS rows\n FROM x\n GROUP BY queryid, query\n ORDER BY SUM(total_time) DESC LIMIT 40"
    }
   ]
  },
  {
   "title": "Top Average Execution Time",
   "type": "table",
   "description": "Metric Description: \n- Displays detailed information about SQL statements with the longest average execution time within the current time window. This includes total execution time, average execution time, IO ratio, physical and logical read/write operations, number of rows processed, and more.\n- Physical & Logical Explanation: Logical read indicates the number of times a page read operation is invoked, including both reads from the buffer (cache hit) and reads from disk (cache miss). Physical read refers to the number of times data is read directly from disk. Logical write and physical write are similar to the former. The ratio between physical I/O and logical I/O provides an indication of the cache hit rate during the execution of the SQL statement.\n\nMetric Source & Collection Method: \n- Obtained by processing the pg_stat_statements, pg_user, and pg_database system views.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 228 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "\n\n\n WITH x AS (\n SELECT * FROM ${LogicInstance}.view_fact_polar_stat_top_sql\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n )\n SELECT queryid, query,\n ROUND(SUM(total_time)::NUMERIC, 2) AS \"total_time(ms)\",\n SUM(calls)::BIGINT AS calls,\n ROUND((SUM(total_time) / SUM(calls))::NUMERIC, 2) AS \"avg_time(ms)\",\n ROUND((SUM(blk_iotime) / SUM(total_time) * 100)::NUMERIC, 2) AS \"IO_time(%)\",\n SUM(logical_read)::BIGINT AS logical_read,\n SUM(blks_read)::BIGINT AS blks_read,\n SUM(logical_write)::BIGINT AS logical_write,\n SUM(blks_written)::BIGINT AS blks_write,\n SUM(rows)::BIGINT AS rows\n FROM x\n GROUP BY queryid, query\n ORDER BY \"avg_time(ms)\" DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Top Read I/O",
   "type": "table",
   "description": "Metric Description: \n- Displays detailed information about SQL statements with the longest total read I/O time within the current time window. This includes total read I/O time, average read I/O time, read cache hit ratio, and more.\n\nMetric Source & Collection Method: \n- Obtained by processing the pg_stat_statements, pg_user, pg_database views.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 240 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "\n\n\n WITH x AS (\n SELECT * FROM ${LogicInstance}.view_fact_polar_stat_top_sql\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n )\n SELECT queryid, query,\n ROUND(SUM(blk_read_time)::NUMERIC, 2) AS \"blk_read_time(ms)\",\n SUM(calls)::BIGINT AS calls,\n ROUND((SUM(total_time) / SUM(calls))::NUMERIC, 2) AS \"avg_time(ms)\",\n ROUND((SUM(blk_read_time) / SUM(calls))::NUMERIC, 2) AS \"avg_blk_read_time(ms)\",\n ROUND((SUM(blk_read_time) / SUM(total_time) * 100)::NUMERIC, 2) AS \"blk_read_time(%)\",\n ROUND((SUM(logical_read) / SUM(calls))::NUMERIC, 2) AS avg_logical_read,\n ROUND((SUM(blks_read) / SUM(calls))::NUMERIC, 2) AS avg_blks_read,\n CASE WHEN SUM(logical_read) < 1 THEN 100 ELSE ROUND((SUM(blks_hit) / SUM(logical_read) * 100)::NUMERIC, 2) END AS \"read_cache_hit(%)\",\n ROUND((SUM(rows) / SUM(calls))::NUMERIC, 2) AS avg_rows\n FROM x\n GROUP BY queryid, query\n ORDER BY SUM(blk_read_time) DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Top Write I/O",
   "type": "table",
   "description": "Metric Description: \n- Displays detailed information about SQL statements with the longest total write I/O time within the current time window. This includes total write I/O time, average write I/O time, write cache hit ratio, and more.\n\nMetric Source & Collection Method: \n- Obtained by processing the pg_stat_statements, pg_user, and pg_database views.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 252 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "\n\n\n WITH x AS (\n SELECT * FROM ${LogicInstance}.view_fact_polar_stat_top_sql\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n )\n SELECT queryid, query,\n ROUND(SUM(blk_write_time)::NUMERIC, 2) AS \"total_blk_write_time(ms)\",\n SUM(calls)::BIGINT AS calls,\n ROUND((SUM(total_time) / SUM(calls))::NUMERIC, 2) AS \"avg_calls(ms)\",\n ROUND((SUM(blk_write_time) / SUM(calls))::NUMERIC, 2) AS \"avg_blk_write_time(ms)\",\n ROUND((SUM(blk_write_time) / SUM(total_time) * 100)::NUMERIC, 2) AS \"blk_write_time(%)\",\n ROUND((SUM(logical_write) / SUM(calls))::NUMERIC, 2) AS avg_logical_write,\n ROUND((SUM(blks_written) / SUM(calls))::NUMERIC, 2) AS avg_blks_write,\n CASE WHEN SUM(logical_write) < 1 THEN 100 ELSE ROUND((SUM(blks_hit) / SUM(logical_write) * 100)::NUMERIC, 2) END AS \"write_cache_hit(%)\",\n ROUND((SUM(rows) / SUM(calls))::NUMERIC, 2) AS avg_rows\n FROM x\n GROUP BY queryid, query\n ORDER BY SUM(blk_write_time) DESC LIMIT 10"
    }
   ]
  },
  { "title": "Table & Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 264 } },
  {
   "title": "The following data is recommended to be queried with an interval of at least one hour.",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 265 },
   "options": { "content": " " }
  },
  {
   "title": "Top Table-Level Sequential Scans",
   "type": "table",
   "description": "Metric Description: \n- Displays tables that have undergone a high number of sequential scans within the current time window.\n\nMetric Source & Collection Method: \n- Collect data from the pg_stat_user_tables view and filter based on the seq_tup_read column.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 266 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "\n WITH x AS (\n SELECT *\n FROM ${LogicInstance}.view_fact_polar_stat_user_tables\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n )\n SELECT\n dbname AS dbname,\n schemaname AS schema,\n relname AS relname,\n SUM(seq_scan)::BIGINT AS seq_scan,\n SUM(seq_tup_read)::BIGINT AS seq_tup_read\n FROM x\n GROUP BY dbname, schemaname, relname HAVING SUM(seq_tup_read) > 0.1\n ORDER BY seq_tup_read DESC LIMIT 10\n \n"
    }
   ]
  },
  {
   "title": "Top Table-Level Index Scans",
   "type": "table",
   "description": "Metric Description: \n- Displays tables that have undergone a high number of index scans within the current time window.\n\nMetric Source & Collection Method: \n- Collect data from the pg_stat_user_tables view and filter based on the idx_tup_fetch column.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 278 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": " SELECT\n dbname AS dbname,\n schemaname AS schema,\n relname AS relname,\n SUM(idx_scan)::BIGINT AS idx_scan,\n SUM(idx_tup_fetch)::BIGINT AS idx_tup_fetch\n FROM ${LogicInstance}.view_fact_polar_stat_user_tables\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n GROUP BY dbname, schemaname, relname HAVING SUM(idx_tup_fetch) > 0.1\n ORDER BY idx_tup_fetch DESC LIMIT 10\n"
    }
   ]
  },
  {
   "title": "Top Table-Level Row Changes",
   "type": "table",
   "description": "Metric Description: \n- Displays tables with the highest total number of modified rows within the current time window.\n\nMetric Source & Collection Method: \n- Collect data from the pg_stat_user_tables view and filter based on `n_tup_ins + n_tup_upd + n_tup_del + n_tup_hot_upd`.\n- n_tup_ins: The number of tuples inserted into the table.\n- n_tup_upd: The number of tuples updated in the table.\n- n_tup_hot_upd: The number of tuples updated using HOT.\n- n_tup_del: The number of tuples deleted from the table.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 290 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n dbname AS dbname,\n schemaname AS schema,\n relname AS relname,\n SUM(n_tup_ins)::BIGINT AS insert_rows,\n SUM(n_tup_upd)::BIGINT AS update_rows,\n SUM(n_tup_hot_upd)::BIGINT AS HOT_update_rows,\n SUM(n_tup_del)::BIGINT AS delete_rows,\n SUM(n_tup_modified)::BIGINT AS total_modified_rows\n FROM ${LogicInstance}.view_fact_polar_stat_user_tables\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n GROUP BY dbname, schemaname, relname HAVING SUM(n_tup_modified) > 0.1\n ORDER BY total_modified_rows DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Top Index Scans",
   "type": "table",
   "description": "Metric Description: \n- Displays indexes that have undergone a high number of index scans within the current time window.\n\nMetric Source & Collection Method: \n- Collect data from the pg_stat_user_indexes view and filter based on the idx_tup_read column.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 302 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n dbname AS dbname,\n schemaname AS schema,\n relname AS relname,\n indexrelname AS index,\n SUM(idx_scan)::BIGINT AS idx_scan,\n SUM(idx_tup_fetch)::BIGINT AS idx_tup_fetch,\n SUM(idx_tup_read)::BIGINT AS idx_tup_read\n FROM ${LogicInstance}.view_fact_polar_stat_user_indexes\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n GROUP BY dbname, schema, relname, index HAVING SUM(idx_tup_read) > 0.1\n ORDER BY idx_scan DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Top Table-Level Read I/O",
   "type": "table",
   "description": "Metric Description: \n- Displays tables with a high number of logical reads within the current time window. Logical reads: `heap_blks_read+heap_blks_hit`.\n\nMetric Source & Collection Method: \n- Collect data from the pg_statio_user_tables view and filter based on the `heap_blks_read+heap_blks_hit`.\n- heap_blks_read: The number of table data pages (heap blocks) read from disk.\n- heap_blks_hit: The number of table data pages found in cache, avoiding disk reads.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 314 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n dbname AS dbname,\n schemaname AS schema,\n relname AS relname,\n SUM(heap_logical_read)::BIGINT AS logical_read,\n SUM(heap_blks_read)::BIGINT AS heap_blks_read,\n ROUND((SUM(heap_blks_hit) / SUM(heap_logical_read) * 100)::NUMERIC, 2) AS \"cache_hit(%)\"\n FROM ${LogicInstance}.view_fact_polar_statio_user_tables\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n GROUP BY dbname, schema, relname HAVING SUM(heap_logical_read) > 0.1\n ORDER BY logical_read DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Top Table-Level Index Read I/O",
   "type": "table",
   "description": "Metric Description: \n- Displays tables with a high number of logical reads via index usage within the current time window. Logical reads: idx_blks_read + idx_blks_hit.\n\nMetric Source & Collection Method: \n- Collect data from the pg_statio_user_tables view and filter based on `idx_blks_read + idx_blks_hit`.\n- heap_blks_read: The number of table data pages (heap blocks) read from disk.\n- heap_blks_hit: The number of table data pages found in the cache, thus avoiding a read from disk.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 326 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n dbname AS dbname,\n schemaname AS schema,\n relname AS relname,\n SUM(idx_logical_read)::BIGINT AS logical_read,\n SUM(idx_blks_read)::BIGINT AS blks_read,\n ROUND((SUM(idx_blks_hit) / (SUM(idx_logical_read)+1) * 100)::NUMERIC, 2) AS \"cache_hit(%)\"\n FROM ${LogicInstance}.view_fact_polar_statio_user_tables\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n GROUP BY dbname, schema, relname HAVING SUM(heap_logical_read) > 0.1\n ORDER BY logical_read DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Top Index-Level Read I/O",
   "type": "table",
   "description": "Metric Description: \n- Display the indexes with the highest number of logical reads on index pages within the current time window. Logical Reads: idx_blks_read+idx_blks_hit。\n\nMetric Source & Collection Method: \n- Collect the data from the pg_statio_user_tables view, filtering by the sum of idx_blks_read+idx_blks_hitt.\n- idx_blks_read: The number of index pages read from disk.\n- idx_blks_hit: The number of index pages found in the cache.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 338 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n dbname AS dbname,\n schemaname AS schema,\n relname AS relname,\n indexrelname AS index,\n SUM(idx_logical_read)::BIGINT AS logical_read,\n SUM(idx_blks_read)::BIGINT AS blks_read,\n ROUND((SUM(idx_blks_hit) / SUM(idx_logical_read) * 100)::NUMERIC, 2) AS \"cache_hit(%)\"\n FROM ${LogicInstance}.view_fact_polar_statio_user_indexes\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n GROUP BY dbname, schema, relname, index HAVING SUM(idx_logical_read) > 0.1\n ORDER BY logical_read DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Top Space Consumption",
   "type": "table",
   "description": "Metric Description: \n- Display the ordinary tables and TOAST tables with the highest space consumption in the current database instance.\n\nMetric Source & Collection Method: \n- Calculate table size using the pg_class view with the formula: relpages * current_setting('block_size')::BIGINT / 1024 / 1024",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 350 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n dbname AS dbname,\n schemaname AS schema,\n relname AS relname,\n CASE WHEN relkind='r' THEN 'relname'\n WHEN relkind='i' THEN 'index'\n WHEN relkind='S' THEN 'seq'\n WHEN relkind='t' THEN 'TOAST_rel'\n ELSE 'other' END AS type,\n ROUND(relsize_total::NUMERIC / 1024, 2) AS \"space_usage(GB)\"\n FROM ${LogicInstance}.view_fact_polar_stat_relation_size\n WHERE time = (SELECT MAX(time) FROM ${LogicInstance}.view_fact_polar_stat_relation_size WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}')\n AND physical_ins_name='${PhysicalInstance}' AND relsize_total > 0.01\n ORDER BY relsize_total DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Top Table Age",
   "type": "table",
   "description": "Metric Description: \n- Assess tables where age consistently exceeds $1.2$ billion, as this hits the autovacuum freeze threshold. This condition suggests autovacuum is failing to complete operations on the table. Execute a manual VACUUM FREEZE command to lower the table's age.\n\nMetric Source & Collection Method: \n- Calculate table age using the pg_class view by applying the function AGE(relfrozenxid)。",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 362 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": " SELECT\n dbname AS dbname,\n schemaname AS schema,\n relname AS relname,\n CASE WHEN relkind='r' THEN 'relname'\n WHEN relkind='i' THEN 'index'\n WHEN relkind='S' THEN 'seq'\n WHEN relkind='t' THEN 'TOAST_rel'\n ELSE 'other' END AS type,\n table_age::BIGINT AS value_age,\n ROUND((table_age / 2147483647 * 100)::NUMERIC, 2) AS \"wraparound_ratio(%)\"\n FROM ${LogicInstance}.view_fact_polar_stat_table_age\n WHERE time = (SELECT MAX(time) FROM ${LogicInstance}.view_fact_polar_stat_table_age WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}')\n ORDER BY table_age DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Top Bloat Ratio",
   "type": "table",
   "description": "Metric Description: \n- Display tables with a high proportion of dead tuples, as this suggests delayed or insufficient VACUUM processes. Analyze the last VACUUM and AUTOVACUUM times for supplementary diagnosis. Perform a manual VACUUM operation if necessary.\n\nMetric Source & Collection Method: \n- From the pg_stat_user_tables view, which provides statistics to determine the necessity of index optimization, VACUUM, or ANALYZE maintenance tasks.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 374 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n dbname AS dbname,\n schemaname AS schema,\n relname AS relname,\n n_live_tup::BIGINT AS live_tup,\n n_dead_tup::BIGINT AS dead_tup,\n ROUND(dead_tup_ratio::NUMERIC, 2) AS dead_tup_ratio_percent,\n CASE WHEN last_vacuum < 0.1 THEN 'Not performed'\n ELSE ROUND(((time - last_vacuum) / 60)::NUMERIC, 1)::TEXT END AS since_last_vacuum_min,\n CASE WHEN last_autovacuum < 0.1 THEN 'Not performed'\n ELSE ROUND(((time - last_autovacuum) / 60)::NUMERIC, 1)::TEXT END AS since_last_autovacuum_min\nFROM ${LogicInstance}.view_fact_polar_stat_user_tables\nWHERE time = (\n SELECT MAX(time)\n FROM ${LogicInstance}.view_fact_polar_stat_user_tables\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\n AND physical_ins_name='${PhysicalInstance}'\n)\nAND physical_ins_name='${PhysicalInstance}'\nORDER BY dead_tup_ratio DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top Analyze Row Update Counts",
   "type": "table",
   "description": "Metric Description: \n- Display tables with a high number of updated rows following ANALYZE execution. Note that excessive row updates after ANALYZE can result in stale statistics, potentially impairing the selection of the optimal SQL execution plan.\n\nMetric Source & Collection Method: \n- From the pg_stat_user_tables view, which provides statistics to determine the necessity of index optimization, VACUUM, or ANALYZE maintenance tasks.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 386 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": " SELECT\n dbname AS dbname,\n schemaname AS schema,\n relname AS relname,\n n_mod_since_analyze::BIGINT AS since_analyze_update_rows,\n CASE WHEN last_analyze<0.1 THEN 'Not performed' ELSE ROUND(((time - last_analyze) / 60)::NUMERIC, 1)::TEXT END AS \"since_last_analyze(min)\",\n CASE WHEN last_autoanalyze<0.1 THEN 'Not performed' ELSE ROUND(((time - last_autoanalyze) / 60)::NUMERIC, 1)::TEXT END AS \"since_last_autoanalyze(min)\"\n FROM ${LogicInstance}.view_fact_polar_stat_user_tables\n WHERE time = (SELECT MAX(time) FROM ${LogicInstance}.view_fact_polar_stat_user_tables WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}')\n ORDER BY n_mod_since_analyze DESC LIMIT 10"
    }
   ]
  },
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 398 } },
  {
   "title": "Database Configuration",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 399 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT name AS name, source AS source, MAX(setting) AS value, (TO_TIMESTAMP(MAX(time)))::TEXT AS sample_time\n FROM ${LogicInstance}.view_fact_polar_settings\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}' AND source NOT IN ('client', 'session')\n GROUP BY name, source\n ORDER BY\n CASE source\n WHEN 'configuration file' THEN 1\n WHEN 'override' THEN 2\n WHEN 'default' THEN 3\n ELSE 4 END"
    }
   ]
  },
  {
   "title": "Database Configuration Changes",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 413 },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT name AS name, source AS source, MAX(setting) AS value1, MIN(setting) AS value2 \n FROM ${LogicInstance}.view_fact_polar_settings\n WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}' AND source NOT IN ('client', 'session')\n GROUP BY name, source\n HAVING MAX(setting) != MIN(setting)\n ORDER BY\n CASE source\n WHEN 'configuration file' THEN 1\n WHEN 'override' THEN 2\n WHEN 'default' THEN 3\n ELSE 4 END"
    }
   ]
  }
 ]
}