{
 "title": "PolarDB MySQL cluster version disk",
 "tags": [
  "dashboard:name:cmee-polardb-mysql-overview",
  "addon:name:cloud-polardb",
  "scene:database",
  "env:Cloud",
  "env:type:Cloud",
  "prometheus",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "clusterDesc",
    "query": {
     "query": "label_values(AliyunPolardb_cluster_cpu_utilization, desc)"
    }
   },
   {
    "name": "clusterId",
    "label": "clusterId",
    "query": {
     "query": "label_values(AliyunPolardb_cluster_active_sessions{desc=~\"$clusterDesc\"}, clusterId)"
    }
   },
   {
    "name": "nodeId",
    "query": {
     "query": "label_values(AliyunPolardb_cluster_cpu_utilization{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}, nodeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of active connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_active_sessions{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "blktag usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_blktag_utilization{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{clusterId}}"
    }
   ]
  },
  {
   "title": "Number of Delete statements executed per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_com_delete{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Number of Multi-Delete statements executed per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_com_delete_multi{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Number of Insert statements executed per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_com_insert{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Number of Insert-Select statements executed per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_com_insert_select{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Number of Replace statements executed per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_com_replace{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Number of Replace-Select statements executed per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_com_replace_select{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Number of Select statements executed per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_com_select{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Number of Update statements executed per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_com_update{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Number of Multi-Update statements executed per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_com_update_multi{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Number of connections used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_connection_utilization{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_cpu_utilization{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Storage engine IO throughput per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_data_io{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Storage engine IO throughput per second times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_data_iops{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "direntry usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_direntry_utilization{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "disk usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_disk_utilization{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "IMCI node column index storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_imci_datasize{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "IMCI executor memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_imci_exememusage{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "IMCI query SQL number per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_imci_stmtsexepersec{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "IMCI SQL number in the scheduling queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_imci_stmtsinqueue{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "IMCI executor temporary table size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_imci_tmpfileusedsize{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "buffer pool dirty block rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_innodb_buffer_dirty_ratio{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "buffer pool read hit rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_innodb_buffer_read_hit_rate{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "inode usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_inode_utilization{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "network input traffic per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_input_traffic{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "IO times per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_iops{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "IOPS usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_iops_usage{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "MDL lock blocked connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_mdl_lock_session{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "memory hit rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_mem_hit_ratio{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_memory_utilization{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "data operations per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 90 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_mps{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "other lock blocked connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 90 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_other_lock_session{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "network output traffic per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 99 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_output_traffic{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "PolarDB The management unit for resource elasticity in Serverless clusters. The minimum PCU unit for a single elasticity is 0.5 PCU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 99 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_pcu_by_cpu_cores{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Number of Prepared Statements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 99 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_prepared_stmt_count{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Usage of Prepared Statements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_prepared_stmt_utilization{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Usage of ProxyCPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_proxy_cpu_utilization{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Number of queries per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 108 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_qps{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Redo log write rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 117 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_redo_write_rate{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Read-only node replication delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 117 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_replica_lag{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of slow queries per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 117 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_slow_queries_ps{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Current total number of connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 126 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_total_session{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  },
  {
   "title": "Number of transactions per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 126 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunPolardb_cluster_tps{clusterId=~\"$clusterId\",nodeId=~\"$nodeId\"}",
     "legendFormat": "{{clusterId}}/{{nodeId}}"
    }
   ]
  }
 ]
}