{
 "title": "PolarDB Oracle disk",
 "tags": [
  "addon:name:cloud-polardb",
  "scene:database",
  "oracle",
  "cmee",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:cmee-polardb-oracle-overview",
  "prometheus",
  "polardb",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "label": "Region",
    "query": "label_values(AliyunPolardb_cpu_total, regionId)"
   },
   {
    "name": "clusterDesc",
    "query": "label_values(AliyunPolardb_cpu_total{regionId=~\"$regionId\"}, desc)"
   },
   {
    "name": "clusterId",
    "query": "label_values(AliyunPolardb_cpu_total{regionId=~\"$regionId\", desc=\"$clusterDesc\"}, clusterId)"
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "AliyunPolardb_cpu_total{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "AliyunPolardb_mem_usage{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    }
   ]
  },
  {
   "title": "Number of active connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunPolardb_active_connections{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    }
   ]
  },
  {
   "title": "Connection usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "AliyunPolardb_conn_usage{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunPolardb_pls_iops{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    },
    {
     "expr": "AliyunPolardb_pls_iops_read{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}/read"
    },
    {
     "expr": "AliyunPolardb_pls_iops_write{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}/write"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "AliyunPolardb_pls_throughput{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    },
    {
     "expr": "AliyunPolardb_pls_throughput_read{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    },
    {
     "expr": "AliyunPolardb_pls_throughput_write{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    }
   ]
  },
  {
   "title": "TPS (transactions per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunPolardb_tps{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    }
   ]
  },
  {
   "title": "Number of data blocks read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunPolardb_blks_read_delta{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    }
   ]
  },
  {
   "title": "Data disk size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunPolardb_pls_data_size{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    }
   ]
  },
  {
   "title": "WAL log size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunPolardb_pls_pg_wal_dir_size{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    }
   ]
  },
  {
   "title": "Transaction rollback rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunPolardb_rollback_ratio{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    }
   ]
  },
  {
   "title": "Expansion point",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunPolardb_swell_time{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    }
   ]
  },
  {
   "title": "Maximum database age",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunPolardb_db_age{clusterId=~\"$clusterId\"}",
     "legendFormat": "{{desc}}#{{clusterId}}"
    }
   ]
  }
 ]
}