{
 "title": "RabbitMQ Expert Edition - Instance Details",
 "tags": [
  "scene:middleware",
  "addon:name:cloud-amqp_instance",
  "addon:version:0.0.4",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:amqp_instance-detail"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Selecte Env", "query": "dev,uat" },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instanceId",
    "label": "InstanceId",
    "query": {
     "query": "label_values(AliyunAmqp_instance_ExchangeTPSIn{}, id)"
    }
   },
   {
    "name": "instanceName",
    "label": "instanceName",
    "query": {
     "query": "label_values(AliyunAmqp_instance_ExchangeTPSIn{id=~\"$instanceId\"}, instanceName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Exchange Message Inflow Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_ExchangeTPSIn{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}/{{exchangeName}}"
    }
   ]
  },
  {
   "title": "Exchange Message Outflow Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_ExchangeTPSOut{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}/{{exchangeName}}"
    }
   ]
  },
  {
   "title": "Instance Channel Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceChannels{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Channel Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceChannelsNew{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Connection Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceConnections{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Consumer Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceConsumers{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Instance API TPS Peak (Times/Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceMaxTpsInMinute{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Instance Message Production Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceMessageInput{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Instance Message Consumption Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceMessageOutput{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Queue Message Accumulation Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceQueueMessageAccumulation{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostQueue}}"
    }
   ]
  },
  {
   "title": "Queue Message Production Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceQueueMessageInput{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostQueue}}"
    }
   ]
  },
  {
   "title": "Queue Message Consumption Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceQueueMessageOutput{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostQueue}}"
    }
   ]
  },
  {
   "title": "Instance Message Inflow Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceTPSIn{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Instance Message Outflow Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceTPSOut{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "VHost Channel Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceVhostChannels{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}"
    }
   ]
  },
  {
   "title": "VHost Consumer Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceVhostConsumers{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}"
    }
   ]
  },
  {
   "title": "VHost Message Production Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceVhostMessageInput{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}"
    }
   ]
  },
  {
   "title": "VHost Message Consumption Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceVhostMessageOutput{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}"
    }
   ]
  },
  {
   "title": "Queue Consumer Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceVhostQueueConsumers{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}/{{queueName}}"
    }
   ]
  },
  {
   "title": "Queue Message Accumulation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceVhostQueueMessageAccum{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}/{{queueName}}"
    }
   ]
  },
  {
   "title": "Queue Message Production Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceVhostQueueMessageInput{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}/{{queueName}}"
    }
   ]
  },
  {
   "title": "Queue Message Consumption Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_InstanceVhostQueueMessageOutput{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}/{{queueName}}"
    }
   ]
  },
  {
   "title": "Queue Message Inflow Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_QueueTPSIn{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}/{{queueName}}"
    }
   ]
  },
  {
   "title": "Queue Message Outflow Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_QueueTPSOut{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}/{{queueName}}"
    }
   ]
  },
  {
   "title": "VHost Number of incoming messages per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_VHostTPSIn{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}"
    }
   ]
  },
  {
   "title": "Number of outgoing messages per second for VHost",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_VHostTPSOut{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}"
    }
   ]
  },
  {
   "title": "Number of VHost channels",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_VhostChannels{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}"
    }
   ]
  },
  {
   "title": "Number of VHost connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunAmqp_instance_VhostConnections{id=~\"$instanceId\", instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}/{{vhostName}}"
    }
   ]
  }
 ]
}