{
 "title": "RDS-MySQL-Global Overview",
 "tags": [
  "scene:database",
  "env:Cloud",
  "env:type:Cloud",
  "addon:name:cloud-rds-mysql",
  "dashboard:name:cmee-rds-mysql-overview",
  "prometheus",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region Name",
    "query": {
     "query": "label_values(AliyunRds_CpuUsage{ engine=\"MySQL\"},regionId)"
    }
   },
   {
    "name": "instanceName",
    "label": "Instance Name",
    "query": {
     "query": "label_values(AliyunRds_CpuUsage{regionId=~\"$region\", engine=\"MySQL\"},instanceName)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   { "name": "clusterUid", "query": "5952-055230" }
  ]
 },
 "panels": [
  {
   "title": "Top 10 CPU usage of cloud database RDS in $region",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk (10,AliyunRds_CpuUsage{regionId=~\"$region\",instanceName=~\"$instanceName\",engine=\"MySQL\"})",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Top 10 memory usage of cloud database RDS in $region",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10,AliyunRds_MemoryUsage{regionId=~\"$region\",instanceName=~\"$instanceName\",engine=\"MySQL\"})",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Top 10 disk usage of cloud database RDS in $region",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10,AliyunRds_DiskUsage{regionId=~\"$region\",instanceName=~\"$instanceName\",engine=\"MySQL\"})",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Top 10 IOPS usage of cloud database RDS in $region",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10,AliyunRds_IOPSUsage{regionId=~\"$region\",instanceName=~\"$instanceName\",engine=\"MySQL\"})",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Resource usage of cloud database RDS in $region",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "AliyunRds_CpuUsage{regionId=~\"$region\",instanceName=~\"$instanceName\",engine=\"MySQL\"}"
    },
    {
     "expr": "AliyunRds_MemoryUsage{regionId=~\"$region\",instanceName=~\"$instanceName\",engine=\"MySQL\"}"
    },
    {
     "expr": "AliyunRds_DiskUsage{regionId=~\"$region\",instanceName=~\"$instanceName\",engine=\"MySQL\"}"
    },
    {
     "expr": "AliyunRds_IOPSUsage{regionId=~\"$region\",instanceName=~\"$instanceName\",engine=\"MySQL\"}"
    }
   ]
  }
 ]
}