{
 "title": "RDS-PostgreSQL-Single Instance Monitoring",
 "description": "PostgreSQL",
 "tags": [
  "RDS",
  "dashboard:name:cmee-postgresql-instance",
  "scene:database",
  "addon:name:cloud-postgresql",
  "env:Cloud",
  "CMEE",
  "PostgreSQL",
  "env:type:Cloud",
  "addon:version:0.0.3",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "query": {
     "query": "label_values(AliyunRds_PG_DBAge, regionId)"
    }
   },
   {
    "name": "instanceName",
    "query": {
     "query": "label_values(AliyunRds_PG_DBAge{regionId=~\"$regionId\"}, instanceName)"
    }
   },
   {
    "name": "instanceId",
    "query": {
     "query": "label_values(AliyunRds_PG_DBAge{regionId=~\"$regionId\" ,instanceName=~\"$instanceName\"},instanceId)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(AliyunRds_pg_cpu_usage{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId,instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(AliyunRds_pg_mem_usage{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of active connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_ConnectionActive{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of idle connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_ConnectionIdle{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of waiting connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_ConnectionWaiting{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of connection utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(AliyunRds_pg_conn_usage{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average number of active connections per CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(AliyunRds_pg_active_connections_per_cpu{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Inbound traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_NetworkRx{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Outbound traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_NetworkTx{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Maximum replication slot latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_MaxSlotWalDelay{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "SharedBuffer hit count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_SharedBufferHitCount{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "SharedBuffer hit rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_SharedBufferHitRate{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "SharedBuffer memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_SharedBufferUsage{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of write transaction commits per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_TransactionCommit{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of write transaction rollbacks per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_TransactionRollback{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Longest transaction execution time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_SwellTime{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "IOPS Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(AliyunRds_pg_iops_usage{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Slowest SQL execution time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_MaxExecutingSQLTime{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "One second slow SQL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(AliyunRds_pg_one_second_executing_sqls{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Three seconds slow SQL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(AliyunRds_pg_three_seconds_executing_sqls{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Five seconds slow SQL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(AliyunRds_pg_five_seconds_executing_sqls{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Read-only synchronization delay",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_RO_ReadLag{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Read-only synchronization delay",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_RO_ReadLag{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Read-only streaming replication status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(AliyunRds_PG_RO_StreamingStatus{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"})by(instanceId, instanceName)",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Local disk throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "targets": [
    {
     "expr": "AliyunRds_PG_LocalThroughput{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Local disk read throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "targets": [
    {
     "expr": "AliyunRds_PG_LocalThroughputRead{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Local disk write throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "targets": [
    {
     "expr": "AliyunRds_PG_LocalThroughputWrite{instanceId=~\"$instanceId\",instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  }
 ]
}