{
 "title": "RDS-SQLServer-Single Instance Monitoring",
 "description": "Alibaba Cloud SQLServer Dashboard",
 "tags": [
  "RDS",
  "scene:database",
  "env:Cloud",
  "CMEE",
  "env:type:Cloud",
  "addon:version:0.0.2",
  "prometheus",
  "addon:name:cloud-sqlserver",
  "dashboard:name:cmee-sqlserver-instance",
  "SQLServer"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "query": {
     "query": "label_values(AliyunRds_SQLServer_CpuUsage, regionId)"
    }
   },
   {
    "name": "instanceName",
    "query": {
     "query": "label_values(AliyunRds_SQLServer_CpuUsage{regionId=~\"$regionId\"}, instanceName)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "AliyunRds_SQLServer_CpuUsage{instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "AliyunRds_SQLServer_DiskUsage{instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "AliyunRds_SQLServer_QPS{instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "AliyunRds_SQLServer_TPS{instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "NetworkRead",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "AliyunRds_SQLServer_NetworkRead{instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "NetworkWrite",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "AliyunRds_SQLServer_NetworkWrite{instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "AliyunRds_SQLServer_IOPS{instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "TotalConnections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "AliyunRds_SQLServer_TotaConn{instanceName=~\"$instanceName\",regionId=~\"$regionId\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  }
 ]
}