{
 "title": "RDS-MySQL-single instance monitoring",
 "tags": [
  "scene:database",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:cmee-rds-mysql-instance",
  "addon:name:cloud-rds-mysql",
  "prometheus",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(AliyunRds_CpuUsage{engine=\"MySQL\"}, regionId)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(AliyunRds_CpuUsage{regionId=\"$region\",engine=\"MySQL\"},instanceId)"
    }
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(AliyunRds_CpuUsage{regionId=\"$region\",instanceId=~\"$instance\", engine=\"MySQL\"},desc)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "RDS monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "AliyunRds_CpuUsage{instanceId=\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Query QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AliyunRds_MySQL_QPS{instanceId=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Number of connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "AliyunRds_MySQL_ThreadsConnected{instanceId=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "ThreadsConnected"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "AliyunRds_IOPSUsage{instanceId=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "IOPSUsage"
    }
   ]
  },
  {
   "title": "Slow query QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AliyunRds_MySQL_SlowQueries{instanceId=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "SlowQueries"
    }
   ]
  },
  {
   "title": "Number of threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "AliyunRds_MySQL_ThreadsRunning{instanceId=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "running"
    },
    {
     "expr": "AliyunRds_MySQL_ThreadsConnected{instanceId=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "connected"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "AliyunRds_MemoryUsage{instanceId=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "expr": "AliyunRds_MySQL_NetworkInNew{instanceId=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "Inflow"
    },
    {
     "expr": "AliyunRds_MySQL_NetworkOutNew{instanceId=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "outgoing flow"
    }
   ]
  },
  {
   "title": "bin log usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_BinLogSize{id=~\"$instance\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Regular log usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_GeneralLogSize{id=~\"$instance\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Instance space usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_InsSize{id=~\"$instance\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "redo log usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_RedoLogSize{id=~\"$instance\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "relay log usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_RelayLogSize{id=~\"$instance\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Temporary file usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_TempFileSize{id=~\"$instance\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "MySQL slow queries per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_SlowQueries{id=~\"$instance\",engine=\"MySQL\",regionId=\"cn-hangzhou\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "MySQL temporary tables created per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_TempDiskTableCreates{id=~\"$instance\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "MySQL physical reads per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_ibufPoolReads{id=~\"$instance\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "undo log usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_UndoLogSize{id=~\"$instance\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "User data usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_UserDataSize{id=~\"$instance\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Slow log usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_SlowLogSize{id=~\"$instance\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "MySQL transactions per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_TPS{id=~\"$instance\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Master instance standby synchronization delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_StandbySyncLag{id=~\"$instance\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "System data usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRds_MySQL_SysDataSize{id=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  { "title": "InnoDB monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "MySQL_DML",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "AliyunRds_MySQL_ComDelete{instanceId=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "Delete"
    },
    {
     "expr": "AliyunRds_MySQL_ComInsert{instanceId=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "Insert"
    },
    {
     "expr": "AliyunRds_MySQL_ComUpdate{instanceId=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "Update"
    },
    {
     "expr": "AliyunRds_MySQL_ComSelect{instanceId=~\"$instance\",engine=\"MySQL\"}",
     "legendFormat": "Select"
    }
   ]
  }
 ]
}