{
 "title": "Redis/Tair memory-based (standard version) instance details dashboard",
 "tags": [
  "scene:database",
  "env:Cloud",
  "dashboard:name:cmee-redis-standard",
  "env:type:Cloud",
  "prometheus",
  "addon:name:cloud-redis",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instanceName",
    "label": "instanceName",
    "query": {
     "query": "label_values(AliyunKvstore_StandardAvgRt{}, instanceName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardAvgRt{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of blocked client connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardBlockedClients{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of Lua script caches",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardCachedScriptsNumber{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "DB connection usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardConnectionUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardCpuUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys evicted in history",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardEvictedKeys{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys evicted per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardEvictedKeysPerSecond{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys eliminated in history",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardExpiredKeys{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys eliminated per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardExpiredKeysPerSecond{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys with expiration time set",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardExpires{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Read QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardGetQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardHitRate{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of keys hit per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardHits{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Inbound bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardIntranetIn{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Inbound bandwidth usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardIntranetInRatio{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Outbound bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardIntranetOut{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Outbound bandwidth usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardIntranetOutRatio{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardKeys{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardMemoryUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of keys not hit per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardMisses{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Other QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardOtherOps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Write QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardPutQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Maximum number of instances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardQuotaConnection{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of slow queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardSlowlogCount{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Multi-active synchronization delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardSyncDelayTime{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of processed commands",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardTotalCommandsProcessed{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of used DB connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardUsedConnection{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardUsedMemory{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Memory used by Lua scripts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_StandardUsedMemoryLua{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average number of visits per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 81 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_StandardUsedQPS{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  }
 ]
}