{
 "title": "Redis community edition-monitoring dashboard-cluster edition",
 "tags": [
  "scene:database",
  "env:Cloud",
  "CMEE",
  "env:type:Cloud",
  "Redis",
  "prometheus",
  "dashboard:name:cmee-redis-community-cluster",
  "addon:name:cloud-redis",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Top_Number", "query": "5,10,20,30" },
   {
    "name": "RegionID",
    "query": {
     "query": "label_values(AliyunKvstore_ShardingCpuUsage, regionId)"
    }
   },
   {
    "name": "Proxy_InstanceID",
    "query": {
     "query": "label_values(AliyunKvstore_ShardingProxyCpuUsage{regionId=~\"$RegionID\"}, instanceId)"
    }
   },
   {
    "name": "Proxy_NodeID",
    "query": {
     "query": "label_values(AliyunKvstore_ShardingProxyCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$Proxy_InstanceID\"}, nodeId)"
    }
   },
   {
    "name": "Node_InstanceID",
    "query": {
     "query": "label_values(AliyunKvstore_ShardingCpuUsage{regionId=~\"$RegionID\"}, instanceId)"
    }
   },
   {
    "name": "Node_NodeID",
    "query": {
     "query": "label_values(AliyunKvstore_ShardingCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"}, nodeId)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node resource allocation overview",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (instanceId) (AliyunKvstore_ShardingProxyCpuUsage))",
     "legendFormat": "Number of Proxy instances "
    },
    {
     "expr": "count by (userId) (AliyunKvstore_ShardingProxyCpuUsage)",
     "legendFormat": "Number of Proxy nodes "
    },
    {
     "expr": "count(count by (instanceId) (AliyunKvstore_ShardingCpuUsage))",
     "legendFormat": "Number of Node instances"
    },
    {
     "expr": "count by (userId) (AliyunKvstore_ShardingProxyCpuUsage)",
     "legendFormat": "Node Number of nodes "
    }
   ]
  },
  {
   "title": "Proxy monitoring indicators-Top$Top_Number",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Proxy-CPU usage (%)-Top$Top_Number",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingProxyCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$Proxy_InstanceID\"})"
    }
   ]
  },
  {
   "title": "Proxy-Total QPS (pcs)-Top$Top_Number",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingProxyTotalQps{regionId=~\"$RegionID\", instanceId=~\"$Proxy_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  {
   "title": "Proxy-Average response time (us)-Top$Top_Number",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingProxyAvgRt{regionId=~\"$RegionID\", instanceId=~\"$Proxy_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  {
   "title": "Proxy-Inbound traffic rate (bits/s)-Top$Top_Number",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingProxyIntranetIn{regionId=~\"$RegionID\", instanceId=~\"$Proxy_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  {
   "title": "Proxy-Outbound traffic rate (bits/s)-Top$Top_Number",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingProxyIntranetOut{regionId=~\"$RegionID\", instanceId=~\"$Proxy_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  {
   "title": "Node monitoring indicators-Top$Top_Number",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "Node-CPU usage (%)-Top$Top_Number",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})"
    }
   ]
  },
  {
   "title": "Node-Memory usage (%)-Top$Top_Number",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingMemoryUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  {
   "title": " Node-Average response time (us)-Top$Top_Number",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingAvgRt{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  {
   "title": "Node-Maximum response time (us)-Top$Top_Number",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingMaxRt{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  {
   "title": "node-QPS usage (%)-Top$Top_Number",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingQPSUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  {
   "title": "Node-Data node inflow bandwidth-Top$Top_Number",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingIntranetIn{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    },
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingIntranetInRatio{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  {
   "title": "Node-Data node outflow bandwidth-Top$Top_Number",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingIntranetOut{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    },
    {
     "expr": "topk($Top_Number, AliyunKvstore_ShardingIntranetOutRatio{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  { "title": "Detailed monitoring indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "AliyunKvstore_ShardingCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
    }
   ]
  },
  {
   "title": "Memory usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "targets": [
    {
     "expr": "AliyunKvstore_ShardingMemoryUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
    }
   ]
  },
  {
   "title": "Response time (us)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "AliyunKvstore_ShardingAvgRt{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
    }
   ]
  },
  {
   "title": "QPS (pcs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "targets": [
    {
     "expr": "AliyunKvstore_ShardingUsedQPS{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
    }
   ]
  },
  {
   "title": "Hit rate (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "AliyunKvstore_ShardingHitRate{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
    }
   ]
  },
  {
   "title": "Number of connections usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
   "targets": [
    {
     "expr": "AliyunKvstore_ShardingConnectionUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
    }
   ]
  },
  {
   "title": "Inflow bandwidth (KByte/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "AliyunKvstore_ShardingIntranetIn{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
    }
   ]
  },
  {
   "title": "Outflow bandwidth (KByte/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "targets": [
    {
     "expr": "AliyunKvstore_ShardingIntranetOut{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
    }
   ]
  },
  {
   "title": "Node details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "AliyunKvstore_ShardingCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
    },
    {
     "expr": "AliyunKvstore_ShardingMemoryUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
    },
    {
     "expr": "AliyunKvstore_ShardingAvgRt{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
    },
    {
     "expr": "AliyunKvstore_ShardingIntranetIn{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
    },
    {
     "expr": "AliyunKvstore_ShardingIntranetOut{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
    }
   ]
  }
 ]
}