{
 "title": "Redis Community Edition-Monitoring Dashboard-Standard Edition",
 "tags": [
  "scene:database",
  "cmee",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:cmee-redis-community-standard",
  "prometheus",
  "redis",
  "addon:name:cloud-redis",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Top_Number", "query": "5,10,20,30" },
   {
    "name": "RegionID",
    "query": {
     "query": "label_values(AliyunKvstore_StandardCpuUsage, regionId)"
    }
   },
   {
    "name": "InstanceID",
    "query": {
     "query": "label_values(AliyunKvstore_StandardCpuUsage{regionId=~\"$RegionID\"}, instanceId)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node resource allocation list",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (instanceId) (AliyunKvstore_StandardCpuUsage))",
     "legendFormat": "Total number of instances"
    },
    {
     "expr": "count by (regionId) (AliyunKvstore_StandardCpuUsage)",
     "legendFormat": "{{regionId}} Instances"
    }
   ]
  },
  {
   "title": "Utilization monitoring metrics sort-Top$Top_Number",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage (%)-Top$Top_Number",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_StandardCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"})"
    }
   ]
  },
  {
   "title": "QPS usage (%)-Top$Top_Number",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_StandardQPSUsage{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"})",
     "legendFormat": "{{desc}}.{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average Response Time (us)-Top$Top_Number",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_StandardAvgRt{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"})",
     "legendFormat": "{{desc}}.{{instanceId}}"
    }
   ]
  },
  {
   "title": "Inflow Rate (bits/s)-Top$Top_Number",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_StandardIntranetIn{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"})",
     "legendFormat": "{{desc}}.{{instanceId}}"
    }
   ]
  },
  {
   "title": "Flow rate (bits/s)-Top$Top_Number",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_StandardIntranetOut{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"})",
     "legendFormat": "{{desc}}.{{instanceId}}"
    }
   ]
  },
  {
   "title": "Detailed monitoring indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunKvstore_StandardCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"}"
    }
   ]
  },
  {
   "title": "Memory usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunKvstore_StandardMemoryUsage{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"}"
    }
   ]
  },
  {
   "title": "Response Time (us)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunKvstore_StandardAvgRt{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"}"
    }
   ]
  },
  {
   "title": "QPS (unit)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunKvstore_StandardUsedQPS{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"}"
    }
   ]
  },
  {
   "title": "Hit Rate (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunKvstore_StandardHitRate{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"}"
    }
   ]
  },
  {
   "title": "Connection usage rate (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunKvstore_StandardConnectionUsage{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"}"
    }
   ]
  },
  {
   "title": "Incoming bandwidth (KByte/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunKvstore_StandardIntranetIn{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"}"
    }
   ]
  },
  {
   "title": "Outgoing bandwidth (KByte/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AliyunKvstore_StandardIntranetOut{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"}"
    }
   ]
  },
  {
   "title": "Node Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "AliyunKvstore_StandardCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"}"
    },
    {
     "expr": "AliyunKvstore_StandardMemoryUsage{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"}"
    },
    {
     "expr": "AliyunKvstore_StandardAvgRt{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"}"
    },
    {
     "expr": "AliyunKvstore_StandardIntranetIn{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"}"
    },
    {
     "expr": "AliyunKvstore_StandardIntranetOut{regionId=~\"$RegionID\", instanceId=~\"$InstanceID\"}"
    }
   ]
  }
 ]
}