{
 "title": "Redis instance utilization ranking - Standard Edition",
 "tags": [
  "scene:database",
  "dashboard:name:cmee-redis-utili-standard",
  "cmee",
  "env:Cloud",
  "env:type:Cloud",
  "prometheus",
  "redis",
  "addon:name:cloud-redis",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "label": "Region",
    "query": {
     "query": "label_values(AliyunKvstore_StandardCpuUsage, regionId)"
    }
   },
   {
    "name": "rmgroup_name",
    "label": "Resource Group",
    "query": {
     "query": "label_values(AliyunKvstore_StandardCpuUsage, rmgroup_name)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(AliyunKvstore_StandardCpuUsage{regionId=~\"$regionId\"})"
    }
   ]
  },
  {
   "title": "Total memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(AliyunKvstore_StandardMemoryUsage{regionId=~\"$regionId\"})"
    }
   ]
  },
  {
   "title": "Total QPS usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(AliyunKvstore_StandardQPSUsage{regionId=~\"$regionId\"})"
    }
   ]
  },
  {
   "title": "Total connection usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(AliyunKvstore_StandardConnectionUsage{regionId=~\"$regionId\"})"
    }
   ]
  },
  {
   "title": "Top 30 memory usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk(30,AliyunKvstore_StandardMemoryUsage{regionId=~\"$regionId\",rmgroup_name=~\"$rmgroup_name\"})"
    }
   ]
  },
  {
   "title": "Top 30 CPU usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "topk(30,AliyunKvstore_StandardCpuUsage{regionId=~\"$regionId\",rmgroup_name=~\"$rmgroup_name\"})"
    }
   ]
  },
  {
   "title": "Top 30 QPS usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(30,AliyunKvstore_StandardQPSUsage{regionId=~\"$regionId\",rmgroup_name=~\"$rmgroup_name\"})"
    }
   ]
  },
  {
   "title": "Top 30 connection usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "topk(30,AliyunKvstore_StandardConnectionUsage{regionId=~\"$regionId\",rmgroup_name=~\"$rmgroup_name\"})"
    }
   ]
  }
 ]
}