{
 "title": "Redis/Tair memory type (read-write separation version/cluster class) instance details dashboard",
 "tags": [
  "scene:database",
  "env:Cloud",
  "env:type:Cloud",
  "dashboard:name:cmee-redis-non-standard",
  "prometheus",
  "addon:name:cloud-redis",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instanceName",
    "label": "instanceName",
    "query": {
     "query": "label_values(AliyunRedis_ShardingAdminClients{}, instanceName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Proxy to DB connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingAdminClients{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average response time of data nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingAvgRt{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of blocked client connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingBlockedClients{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of Lua script caches",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingCachedScriptsNumber{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "DB connection usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingConnectionUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingCpuUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys evicted in history",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingEvictedKeys{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys evicted per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingEvictedKeysPerSecond{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys eliminated in history",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingExpiredKeys{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys eliminated per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingExpiredKeysPerSecond{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys with expiration time set",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingExpires{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Read QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingGetQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node hit rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingHitRate{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of keys hit per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingHits{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy instance inbound bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingInstProxyIntranetIn{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy instance outbound bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingInstProxyIntranetOut{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of requests per second for Proxy instances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingInstProxyTotalQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of used connections for Proxy instances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingInstProxyUsedConnection{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node inbound bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingIntranetIn{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node inbound bandwidth usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingIntranetInRatio{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node outbound bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingIntranetOut{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node outbound bandwidth usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingIntranetOutRatio{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingKeys{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingMemoryUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of keys missed per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingMisses{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Other QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingOtherOps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average number of bytes per Proxy request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingProxyAvgRequestSize{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average number of bytes per Proxy response",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingProxyAvgResponseSize{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average latency for Proxy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingProxyAvgRt{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy connection usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingProxyConnectionUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingProxyCpuUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "proxy read QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 90 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingProxyGetQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy inbound traffic rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 90 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingProxyIntranetIn{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy outbound traffic rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 99 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingProxyIntranetOut{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy single request maximum bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 99 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingProxyMaxRequestSize{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy single response maximum bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 99 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingProxyMaxResponseSize{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "proxy write QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 108 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingProxyPutQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy total requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 108 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingProxyTotalQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy used connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 108 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingProxyUsedConnection{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Write QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 117 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingPutQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Instance maximum connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 117 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingQuotaConnection{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of slow queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 117 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingSlowlogCount{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Multi-active synchronization delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 126 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingSyncDelayTime{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of processed commands",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 126 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingTotalCommandsProcessed{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "DB used connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 126 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingUsedConnection{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 135 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingUsedMemory{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Lua script memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 135 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_ShardingUsedMemoryLua{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node average number of visits per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 135 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_ShardingUsedQPS{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy to DB connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 144 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwAdminClients{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node average response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 144 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwAvgRt{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of blocked client connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 144 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwBlockedClients{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Lua script cache number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 153 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwCachedScriptsNumber{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "DB connection usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwConnectionUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node CPU Utilization rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwCpuUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys evicted in history",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 162 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwEvictedKeys{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys evicted per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 162 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwEvictedKeysPerSecond{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys eliminated in history",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 162 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwExpiredKeys{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys eliminated per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 171 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwExpiredKeysPerSecond{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys with set expiration time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 171 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwExpires{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Read QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 171 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwGetQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node hit rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwHitRate{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of keys hit per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 180 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwHits{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node inbound bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 180 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwIntranetIn{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node inbound bandwidth utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwIntranetInRatio{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node outbound bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 189 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwIntranetOut{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node outbound bandwidth utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwIntranetOutRatio{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of keys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 198 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwKeys{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwMemoryUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of keys missed per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 198 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwMisses{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of connections from Proxy to DB node (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 207 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeAdminClients{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average response time (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 207 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeAvgRt{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of clients temporarily suspended after executing block command (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 207 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeBlockedClients{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of Lua script caches",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 216 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeCachedScriptsNumber{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of connections utilization (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeConnectionUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "CPU Utilization rate (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeCpuUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "The total number of keys evicted in history (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 225 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeEvictedKeys{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "The number of keys evicted per second (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 225 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeEvictedKeysPerSecond{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "The total number of keys eliminated in history (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 225 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeExpiredKeys{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "The number of keys eliminated per second (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 234 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeExpiredKeysPerSecond{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "The number of keys with expiration time set in the instance, showing the instantaneous value when collecting data (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 234 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeExpires{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Read QPS (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 234 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeGetQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Hit rate (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 243 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeHitRate{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "The number of keys hit per second. (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 243 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeHits{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Inbound bandwidth (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 243 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeIntranetIn{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Inbound bandwidth utilization rate (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 252 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeIntranetInRatio{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Outbound bandwidth (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 252 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeIntranetOut{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Outbound bandwidth utilization rate (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 252 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeIntranetOutRatio{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "The number of keys in the cache (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 261 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeKeys{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Memory utilization rate (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 261 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeMemoryUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "The number of keys missed per second. (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 261 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeMisses{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Other QPS (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 270 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeOtherOps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average bytes per proxy request (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 270 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeProxyAvgRequestSize{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average bytes per proxy response (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 270 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeProxyAvgResponseSize{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average latency of proxy (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 279 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeProxyAvgRt{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Use of proxy connections (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 279 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeProxyConnectionUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy CPU usage (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 279 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeProxyCpuUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy read QPS (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 288 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeProxyGetQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy inbound traffic rate (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 288 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeProxyIntranetIn{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy outbound traffic rate (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 288 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeProxyIntranetOut{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Maximum bytes per proxy request (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 297 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeProxyMaxRequestSize{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Maximum bytes per proxy response (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 297 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeProxyMaxResponseSize{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy write QPS (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 297 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeProxyPutQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of proxy requests per second (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 306 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeProxyTotalQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of used connections of proxy (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 306 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeProxyUsedConnection{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Write QPS (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 306 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodePutQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Maximum number of connections of instance (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 315 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeQuotaConnection{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of slow queries (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 315 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeSlowlogCount{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Delay of synchronizing current Binlog to the latest Binlog (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 315 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeSyncDelayTime{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of processed commands (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 324 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeTotalCommandsProcessed{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of used connections (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 324 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeUsedConnection{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Memory usage (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 324 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeUsedMemory{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Memory usage of Lua script (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 333 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeUsedMemoryLua{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average number of visits per second (node dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 333 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwNodeUsedQPS{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Other QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 333 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwOtherOps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average number of bytes per proxy request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 342 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwProxyAvgRequestSize{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average number of bytes per proxy response",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 342 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwProxyAvgResponseSize{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Average latency of proxy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 342 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwProxyAvgRt{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Use rate of proxy connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 351 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwProxyConnectionUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 351 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwProxyCpuUsage{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy read QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 351 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwProxyGetQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy inbound traffic rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 360 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwProxyIntranetIn{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy outbound traffic rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 360 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwProxyIntranetOut{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy single request maximum bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 360 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwProxyMaxRequestSize{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy single response maximum bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 369 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwProxyMaxResponseSize{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy write QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 369 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwProxyPutQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy total requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 369 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwProxyTotalQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Proxy used connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 378 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwProxyUsedConnection{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Write QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 378 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwPutQps{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Instance maximum connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 378 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwQuotaConnection{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of slow queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 387 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwSlowlogCount{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Multi-active synchronization delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 387 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwSyncDelayTime{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Total number of processed commands",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 387 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwTotalCommandsProcessed{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "DB used connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 396 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwUsedConnection{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 396 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwUsedMemory{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Lua script memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 396 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRedis_SplitrwUsedMemoryLua{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Data node average number of visits per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 405 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunKvstore_SplitrwUsedQPS{instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  }
 ]
}