{
 "title": "Redis community version-monitoring disk-read-write separation version",
 "tags": [
  "scene:database",
  "dashboard:name:cmee-redis-community-separate",
  "cmee",
  "env:Cloud",
  "env:type:Cloud",
  "prometheus",
  "redis",
  "addon:name:cloud-redis",
  "addon:version:0.0.6"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Top_Number", "query": "5,10,20,30" },
   {
    "name": "RegionID",
    "query": {
     "query": "label_values(AliyunKvstore_SplitrwCpuUsage, regionId)"
    }
   },
   {
    "name": "Proxy_InstanceID",
    "query": {
     "query": "label_values(AliyunKvstore_SplitrwProxyCpuUsage{regionId=~\"$RegionID\"}, instanceId)"
    }
   },
   {
    "name": "Proxy_NodeID",
    "query": {
     "query": "label_values(AliyunKvstore_SplitrwProxyCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$Proxy_InstanceID\"}, nodeId)"
    }
   },
   {
    "name": "Node_InstanceID",
    "query": {
     "query": "label_values(AliyunKvstore_SplitrwCpuUsage{regionId=~\"$RegionID\"}, instanceId)"
    }
   },
   {
    "name": "Node_NodeID",
    "query": {
     "query": "label_values(AliyunKvstore_SplitrwCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"}, nodeId)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node resource allocation overview",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (instanceId) (AliyunKvstore_SplitrwProxyCpuUsage))",
     "legendFormat": "Number of Proxy instances"
    },
    {
     "expr": "count by (userId) (AliyunKvstore_SplitrwProxyCpuUsage)",
     "legendFormat": "Number of Proxy Nodes"
    },
    {
     "expr": "count(count by (instanceId) (AliyunKvstore_SplitrwCpuUsage))",
     "legendFormat": "Number of Node instances"
    },
    {
     "expr": "count by (userId) (AliyunKvstore_SplitrwProxyCpuUsage)",
     "legendFormat": "Node number"
    }
   ]
  },
  {
   "title": "Proxy monitoring indicators-Top$Top_Number",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "proxy-CPU usage (%)-Top$Top_Number",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_SplitrwProxyCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$Proxy_InstanceID\"})"
    }
   ]
  },
  {
   "title": "proxy-total QPS (pcs)-Top$Top_Number",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_SplitrwProxyTotalQps{regionId=~\"$RegionID\", instanceId=~\"$Proxy_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  {
   "title": "proxy-average response time (us)-Top$Top_Number",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_SplitrwProxyAvgRt{regionId=~\"$RegionID\", instanceId=~\"$Proxy_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  {
   "title": "proxy-inbound traffic rate (bits/s)-Top$Top_Number",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_SplitrwProxyIntranetIn{regionId=~\"$RegionID\", instanceId=~\"$Proxy_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  {
   "title": "proxy-outbound traffic rate (bits/s)-Top$Top_Number",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk($Top_Number, AliyunKvstore_SplitrwProxyIntranetOut{regionId=~\"$RegionID\", instanceId=~\"$Proxy_InstanceID\"})",
     "legendFormat": "{{desc}}.{{nodeId}}"
    }
   ]
  },
  {
   "title": "Node monitoring indicators-Top$Top_Number",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "node-CPU usage (%)-Top$Top_Number",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk($Top_Number, AliyunKvstore_SplitrwCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})"
      }
     ]
    },
    {
     "title": "node-memory usage (%)-Top$Top_Number",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk($Top_Number, AliyunKvstore_SplitrwMemoryUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
       "legendFormat": "{{desc}}.{{nodeId}}"
      }
     ]
    },
    {
     "title": "node-average response time (us)-Top$Top_Numb er",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk($Top_Number, AliyunKvstore_SplitrwAvgRt{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
       "legendFormat": "{{desc}}.{{nodeId}}"
      }
     ]
    },
    {
     "title": "node-Maximum response time (us)-Top$Top_Number",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk($Top_Number, AliyunKvstore_SplitrwMaxRt{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
       "legendFormat": "{{desc}}.{{nodeId}}"
      }
     ]
    },
    {
     "title": "node-QPS usage (%)-Top$Top_Number",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk($Top_Number, AliyunKvstore_SplitrwQPSUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
       "legendFormat": "{{desc}}.{{nodeId}}"
      }
     ]
    },
    {
     "title": "node-Data node inflow bandwidth-Top$Top_Number",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "topk($Top_Number, AliyunKvstore_SplitrwIntranetIn{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
       "legendFormat": "{{desc}}.{{nodeId}}"
      },
      {
       "expr": "topk($Top_Number, AliyunKvstore_SplitrwIntranetInRatio{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
       "legendFormat": "{{desc}}.{{nodeId}}"
      }
     ]
    },
    {
     "title": "node-Data node outflow bandwidth-Top$Top_Number",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "topk($Top_Number, AliyunKvstore_SplitrwIntranetOut{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
       "legendFormat": "{{desc}}.{{nodeId}}"
      },
      {
       "expr": "topk($Top_Number, AliyunKvstore_SplitrwIntranetOutRatio{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\"})",
       "legendFormat": "{{desc}}.{{nodeId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed monitoring indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "AliyunKvstore_SplitrwCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
      }
     ]
    },
    {
     "title": "Memory usage (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "expr": "AliyunKvstore_SplitrwMemoryUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
      }
     ]
    },
    {
     "title": "Response time (us)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "AliyunKvstore_SplitrwAvgRt{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
      }
     ]
    },
    {
     "title": "QPS (pcs)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "targets": [
      {
       "expr": "AliyunKvstore_SplitrwUsedQPS{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
      }
     ]
    },
    {
     "title": "Hit rate (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "AliyunKvstore_SplitrwHitRate{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
      }
     ]
    },
    {
     "title": "Connection usage (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "targets": [
      {
       "expr": "AliyunKvstore_SplitrwConnectionUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
      }
     ]
    },
    {
     "title": "Inflow bandwidth (KByte/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "AliyunKvstore_SplitrwIntranetIn{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
      }
     ]
    },
    {
     "title": "Outflow bandwidth (KByte/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
     "targets": [
      {
       "expr": "AliyunKvstore_SplitrwIntranetOut{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
      }
     ]
    },
    {
     "title": "Node details",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "AliyunKvstore_SplitrwCpuUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
      },
      {
       "expr": "AliyunKvstore_SplitrwMemoryUsage{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
      },
      {
       "expr": "AliyunKvstore_SplitrwAvgRt{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
      },
      {
       "expr": "AliyunKvstore_SplitrwIntranetIn{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
      },
      {
       "expr": "AliyunKvstore_SplitrwIntranetOut{regionId=~\"$RegionID\", instanceId=~\"$Node_InstanceID\", nodeId=~\"$Node_NodeID\"}"
      }
     ]
    }
   ]
  }
 ]
}