{
 "title": "RocketMQ-InstanceDashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instanceId",
    "label": "InstanceId",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"rocketmq5\",instanceName!=\"\"}, id)"
    }
   },
   {
    "name": "instanceName",
    "label": "InstanceName",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"rocketmq5\",id=~\"$instanceId\"}, instanceName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Over View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Instance ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cloud_monitor_instance_info{service=\"rocketmq5\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance list",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 5, "y": 1 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "cloud_monitor_instance_info{service=\"rocketmq5\"}\r\n* on(id)\r\ngroup_left(key,value)\r\ncloud_monitor_instance_tag{service=\"rocketmq5\", key=\"AppCode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message accumulation (Group)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ConsumerLag{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{groupId}}"
    }
   ]
  },
  {
   "title": "Message processing delay (GroupId)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ConsumerLagLatencyPerGid{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{groupId}}"
    }
   ]
  },
  {
   "title": "Message processing delay (GroupId&Topic)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ConsumerLagLatencyPerGidTopic{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{groupId}}{{topic}}"
    }
   ]
  },
  {
   "title": "Message accumulation (Group&Topic)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ConsumerLagPerGidTopic{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{groupId}}{{topic}}"
    }
   ]
  },
  {
   "title": "Instance API call frequency (Instance)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_InstanceApiCallTps{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "5.0 series instance public network downlink traffic bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_InstanceInternetFlowoutBandwidth{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "5.0 series instance consumption API call TPS peak",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_InstanceReceiveApiCallTps{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "5.0 series instance sending API call TPS peak",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_InstanceSendApiCallTps{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "5.0 Series instance storage size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_InstanceStorageSize{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Ready message queue time (Group)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ReadyMessageQueueTime{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{groupId}}"
    }
   ]
  },
  {
   "title": "Ready message queue time (Group&Topic)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ReadyMessageQueueTimePerGidTopic{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{groupId}}{{topic}}"
    }
   ]
  },
  {
   "title": "Ready message volume (Group)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ReadyMessages{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{groupId}}"
    }
   ]
  },
  {
   "title": "Ready message volume (Group&Topic)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ReadyMessagesPerGidTopic{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{groupId}}{{topic}}"
    }
   ]
  },
  {
   "title": "Number of messages received by consumers per minute (Group)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ReceiveMessageCountPerGid{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{groupId}}"
    }
   ]
  },
  {
   "title": "Number of messages received by consumers per minute (Group&Topic)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ReceiveMessageCountPerGidTopic{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{groupId}}{{topic}}"
    }
   ]
  },
  {
   "title": "Number of messages received by consumers per minute (Instance)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ReceiveMessageCountPerInstance{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of messages received by consumers per minute (Topic)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ReceiveMessageCountPerTopic{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{topic}}"
    }
   ]
  },
  {
   "title": "Number of dead-letter messages generated per minute (Group)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_SendDLQMessageCountPerGid{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{groupId}}"
    }
   ]
  },
  {
   "title": "Number of dead-letter messages generated per minute (Group&Topic)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_SendDLQMessageCountPerGidTopic{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{groupId}}{{topic}}"
    }
   ]
  },
  {
   "title": "Number of messages sent by producers per minute (Instance)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_SendMessageCountPerInstance{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of messages sent by producers per minute (Topic)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_SendMessageCountPerTopic{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{topic}}"
    }
   ]
  },
  {
   "title": "Number of consumption throttling per minute (GroupId)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ThrottledReceiveRequestsPerGid{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of consumption throttling per minute (GroupId&Topic)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ThrottledReceiveRequestsPerGidTopic{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{groupId}}{{topic}}"
    }
   ]
  },
  {
   "title": "Number of consumption throttling per minute (Instance)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ThrottledReceiveRequestsPerInstance{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of sending throttling per minute (Instance)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ThrottledSendRequestsPerInstance{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}"
    }
   ]
  },
  {
   "title": "Number of sending throttling per minute (Topic)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunRocketmq5_ThrottledSendRequestsPerTopic{id=~\"$instanceId\",instanceName=~\"$instanceName\"}",
     "legendFormat": "{{instanceName}}/{{instanceId}}{{topic}}"
    }
   ]
  }
 ]
}