{
 "title": "SLB instance-Dashbord",
 "tags": [ "slb" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "query": {
     "query": "label_values(AliyunSlb_ActiveConnection{}, regionId)"
    }
   },
   {
    "name": "instanceName",
    "query": {
     "query": "label_values(AliyunSlb_ActiveConnection{regionId=~\"$regionId\"}, instanceName)"
    }
   },
   {
    "name": "instanceId",
    "query": {
     "query": "query_result(AliyunSlb_ActiveConnection{regionId=~\"$regionId\", instanceName=~\"$instanceName\" })"
    }
   },
   {
    "name": "vip",
    "query": {
     "query": "label_values(AliyunSlb_ActiveConnection{regionId=~\"$regionId\",instanceName=~\"$instanceName\"},vip)"
    }
   },
   { "name": "ConnectionStatus", "label": "Connection Status", "query": "Active,Inactive,Drop,Max" },
   {
    "name": "RT",
    "label": "RT Options",
    "query": "Listen RT : Rt,Instance RT : InstanceRt,Listen Upstream RT : UpstreamRt,Instance Upstream RT : UpstreamInstanceRt"
   },
   {
    "name": "StatusCode",
    "label": "Status Code",
    "query": "Listen 2XX : StatusCode2xx,Listen 3XX : StatusCode3xx,Listen 4XX : StatusCode4xx,Listen 5XX : StatusCode5xx,Listen Other : StatusCodeOther,Listen Upstream 4XX : UpstreamCode4xx,Listen Upstream 5XX : UpstreamCode5xx,Instance 2XX : InstanceStatusCode2xx,Instance 3XX : InstanceStatusCode3xx,Instance 4XX : InstanceStatusCode4xx,Instance 5XX : InstanceStatusCode5xx,Instance Other : StatusCodeOther"
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Healthy Server Count",
   "type": "graph",
   "description": "Number of healthy backend ECS instances",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(AliyunSlb_HeathyServerCount{instanceId=~\"$instanceId\",vip=~\"$vip\"}) by (instanceName,vip)",
     "legendFormat": "{{instanceName}}/{{vip}}"
    }
   ]
  },
  { "title": "RX/TX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Instance TrafficRX/TX",
   "type": "graph",
   "description": "Number of inbound/outbound bits per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "AliyunSlb_InstanceTrafficTX{regionId=~\"$regionId\",instanceId=~\"$instanceId\",vip=~\"$vip\"}",
     "legendFormat": "{{instanceName}}/{{vip}}"
    },
    {
     "expr": "-AliyunSlb_InstanceTrafficRX{regionId=~\"$regionId\",instanceId=~\"$instanceId\",vip=~\"$vip\"}",
     "legendFormat": "{{instanceName}}/{{vip}}"
    }
   ]
  },
  {
   "title": "TrafficRX/TX",
   "type": "graph",
   "description": "Inbound/outbound bandwidth",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "AliyunSlb_TrafficTXNew{regionId=~\"$regionId\",instanceId=~\"$instanceId\",vip=~\"$vip\"}",
     "legendFormat": "{{instanceName}}:{{port}}/{{vip}}"
    },
    {
     "expr": "-AliyunSlb_TrafficRXNew{regionId=~\"$regionId\",instanceId=~\"$instanceId\",vip=~\"$vip\"}",
     "legendFormat": "{{instanceName}}:{{port}}/{{vip}}"
    }
   ]
  },
  {
   "title": "Package RX/TX",
   "type": "graph",
   "description": "Number of outbound/inbound packets per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": " AliyunSlb_PacketTX{regionId=~\"$regionId\",instanceId=~\"$instanceId\",vip=~\"$vip\"}",
     "legendFormat": "{{instanceName}}:{{port}}/{{vip}}"
    },
    {
     "expr": " -AliyunSlb_PacketRX{regionId=~\"$regionId\",instanceId=~\"$instanceId\",vip=~\"$vip\"}",
     "legendFormat": "{{instanceName}}:{{port}}/{{vip}}"
    }
   ]
  },
  { "title": "Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "$ConnectionStatus Connection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "repeat": "ConnectionStatus",
   "targets": [
    {
     "expr": "AliyunSlb_${ConnectionStatus}Connection{regionId=~\"$regionId\",instanceId=~\"$instanceId\",vip=~\"$vip\"}",
     "legendFormat": "{{instanceName}}:{{port}}/{{vip}}"
    }
   ]
  },
  {
   "title": "Instance Connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instance ${ConnectionStatus} Connection",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "repeat": "ConnectionStatus",
     "targets": [
      {
       "expr": "AliyunSlb_Instance${ConnectionStatus}Connection{regionId=~\"$regionId\",instanceId=~\"$instanceId\",regionId=~\"$regionId\"}",
       "legendFormat": "${ConnectionStatus}#{{instanceName}}/{{vip}}"
      }
     ]
    }
   ]
  },
  {
   "title": "QPS(Layer 7)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instance QPS",
     "type": "graph",
     "description": "Layer 7 protocol instance QPS",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "AliyunSlb_InstanceQps{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
       "legendFormat": "{{instanceName}}/{{vip}}"
      }
     ]
    },
    {
     "title": "Instance Qps Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "AliyunSlb_InstanceQpsUtilization{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
       "legendFormat": "{{instanceName}}/{{vip}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "description": "Layer 7 protocol port QPS",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(AliyunSlb_Qps{instanceId=~\"$instanceId\"}) by (instanceId,vip)",
       "legendFormat": "{{instanceName}}/{{vip}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RT(Layer 7)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "${RT}",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "repeat": "RT",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "AliyunSlb_${RT}{regionId=~\"$regionId\",instanceId=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{instanceName}}/{{vip}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Status Code(Layer 7)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "$StatusCode",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
     "repeat": "StatusCode",
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "AliyunSlb_$StatusCode{instanceId=~\"$instanceId\"}",
       "legendFormat": "{{instanceName}}:{{port}}/{{vip}}"
      }
     ]
    }
   ]
  }
 ]
}