{
 "title": "SLS",
 "description": "Alibaba Cloud SLS Dashboard",
 "tags": [
  "scene:middleware",
  "dashboard:name:sls-overview",
  "cmee",
  "env:Cloud",
  "env:type:Cloud",
  "sls",
  "addon:version:0.0.2",
  "prometheus",
  "addon:name:cloud-sls"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "query": "label_values(AliyunSls_SumQPS, regionId)"
   },
   {
    "name": "project",
    "query": "label_values(AliyunSls_SumQPS{regionId=~\"$regionId\"}, project)"
   },
   {
    "name": "logstore",
    "query": "label_values(AliyunSls_SumQPS{regionId=~\"$regionId\" ,project=~\"$project\"},logstore)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Write traffic (incoming traffic)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_LogInflow{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  },
  {
   "title": "Original data size (network incoming traffic)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_NetFlow{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  },
  {
   "title": "Write lines (Lines/Minute)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_InflowLine{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  },
  {
   "title": "Read traffic (outgoing traffic)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_LogOutflow{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  },
  {
   "title": "Client parsing successful traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_SuccessdByte{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  },
  {
   "title": "Client parsing successful lines (Lines/Minute)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_SuccessdLines{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  },
  {
   "title": "Client parsing failed lines (Lines)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_FailedLines{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  },
  {
   "title": "Client error number (Frequency)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_AlarmPV{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  },
  {
   "title": "Client error machine number (Frequency)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_AlarmUV{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  },
  {
   "title": "Error IP statistics (Frequency)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_AlarmIPCount{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  },
  {
   "title": "Total QPS (pcs)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_SumQPS{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  },
  {
   "title": "Number of operations (pcs)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_LogMethodQPS{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  },
  {
   "title": "Consumption delay time (Second)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_ConsumerGroupFallBehind{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  },
  {
   "title": "Service status (pcs)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AliyunSls_LogCodeQPS{regionId=~\"$regionId\",project=~\"$project\",logstore=~\"$logstore\"}",
     "legendFormat": "{{project}}/{{logstore}}"
    }
   ]
  }
 ]
}