{
 "title": "Vip new connections per second",
 "tags": [
  "scene:middleware",
  "env:Cloud",
  "addon:name:cloud-nlb",
  "env:type:Cloud",
  "addon:version:0.0.3",
  "prometheus",
  "dashboard:name:nlb-detail"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "regionId",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"nlb\"},regionId)"
    }
   },
   {
    "name": "instanceId",
    "query": {
     "query": "label_values(cloud_monitor_instance_info{service=\"nlb\",regionId=~\"$regionId\"},id)"
    }
   },
   {
    "name": "listenerProtocol",
    "query": {
     "query": "label_values(AliyunNlb_ActiveConnection{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}, listenerProtocol)"
    }
   },
   {
    "name": "listenerPort",
    "query": {
     "query": "label_values(AliyunNlb_ActiveConnection{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\"}, listenerPort)"
    }
   },
   {
    "name": "vip",
    "query": {
     "query": "label_values(AliyunNlb_VipTrafficTX{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}, vip)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of new connections per second for the instance",
   "type": "timeseries",
   "description": "Count/s",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNlb_InstanceNewConnection{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{instanceId}}:{{loadBalancerName}}/{{regionId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of dropped connections per second for the instance",
   "type": "timeseries",
   "description": "Count/s",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNlb_InstanceDropConnection{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{instanceId}}:{{loadBalancerName}}/{{regionId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of active connections per second for the instance",
   "type": "timeseries",
   "description": "Count/s",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNlb_InstanceActiveConnection{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{instanceId}}:{{loadBalancerName}}/{{regionId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of inactive connections per second for the instance",
   "type": "timeseries",
   "description": "Count/s",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNlb_InstanceInactiveConnection{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{instanceId}}:{{loadBalancerName}}/{{regionId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of maximum concurrent connections per second for the instance",
   "type": "timeseries",
   "description": "Count/s",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNlb_InstanceMaxConnection{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{instanceId}}:{{loadBalancerName}}/{{regionId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of dropped incoming packets per second for the instance",
   "type": "timeseries",
   "description": "Count/s",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNlb_InstanceDropPacketRX{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{instanceId}}:{{loadBalancerName}}/{{regionId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of dropped outgoing packets per second for the instance",
   "type": "timeseries",
   "description": "Count/s",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNlb_InstanceDropPacketTX{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{instanceId}}:{{loadBalancerName}}/{{regionId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of dropped incoming bits per second for the instance",
   "type": "timeseries",
   "description": "bits/s",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNlb_InstanceDropTrafficRX{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{instanceId}}:{{loadBalancerName}}/{{regionId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of dropped outgoing bits per second for the instance",
   "type": "timeseries",
   "description": "bits/s",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNlb_InstanceDropTrafficTX{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{instanceId}}:{{loadBalancerName}}/{{regionId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of incoming packets per second for the instance",
   "type": "timeseries",
   "description": "Count/s",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNlb_InstancePacketRX{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{instanceId}}:{{loadBalancerName}}/{{regionId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of outgoing packets per second for the instance",
   "type": "timeseries",
   "description": "Count/s",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNlb_InstancePacketTX{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{instanceId}}:{{loadBalancerName}}/{{regionId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of incoming packets per second for the instance",
   "type": "timeseries",
   "description": "bits/s",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNlb_InstanceTrafficRX{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{instanceId}}:{{loadBalancerName}}/{{regionId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Number of outgoing packets per second for the instance",
   "type": "timeseries",
   "description": "bits/s",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "AliyunNlb_InstanceTrafficTX{regionId=~\"$regionId\",instanceId=~\"$instanceId\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{instanceId}}:{{loadBalancerName}}/{{regionId}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Monitor incoming bits per second",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of incoming bits per second for the instance",
     "type": "timeseries",
     "description": "Count",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_ActiveConnection{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "fields": [
        { "jsonPath": "" }
       ],
       "legendFormat": "{{instanceId}}:{{loadBalancerName}}:{{listenerProtocol}}:{{listenerPort}}/{{regionId}}",
       "method": "GET"
      }
     ]
    },
    {
     "title": "Number of outgoing bits per second for the instance",
     "type": "timeseries",
     "description": "Count",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_InactiveConnection{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "fields": [
        { "jsonPath": "" }
       ],
       "legendFormat": "{{instanceId}}:{{loadBalancerName}}:{{listenerProtocol}}:{{listenerPort}}/{{regionId}}",
       "method": "GET"
      }
     ]
    },
    {
     "title": "Number of active connections per second for the listener",
     "type": "timeseries",
     "description": "Count/s",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_DropConnection{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "fields": [
        { "jsonPath": "" }
       ],
       "legendFormat": "{{instanceId}}:{{loadBalancerName}}:{{listenerProtocol}}:{{listenerPort}}/{{regionId}}",
       "method": "GET"
      }
     ]
    },
    {
     "title": "Number of inactive connections for the listener",
     "type": "timeseries",
     "description": "Count/s",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_NewConnection{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "fields": [
        { "jsonPath": "" }
       ],
       "legendFormat": "{{instanceId}}:{{loadBalancerName}}:{{listenerProtocol}}:{{listenerPort}}/{{regionId}}",
       "method": "GET"
      }
     ]
    },
    {
     "title": "Number of dropped connections per second for the listener",
     "type": "timeseries",
     "description": "Count/s",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_DropPacketTX{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "fields": [
        { "jsonPath": "" }
       ],
       "legendFormat": "{{instanceId}}:{{loadBalancerName}}:{{listenerProtocol}}:{{listenerPort}}/{{regionId}}",
       "method": "GET"
      }
     ]
    },
    {
     "title": "Number of new connections for the listener",
     "type": "timeseries",
     "description": "Count/s",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_DropPacketRX{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "fields": [
        { "jsonPath": "" }
       ],
       "legendFormat": "{{instanceId}}:{{loadBalancerName}}:{{listenerProtocol}}:{{listenerPort}}/{{regionId}}",
       "method": "GET"
      }
     ]
    },
    {
     "title": "Number of dropped outgoing packets per second for the listener",
     "type": "timeseries",
     "description": "bits/s",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_DropTrafficTX{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "fields": [
        { "jsonPath": "" }
       ],
       "legendFormat": "{{instanceId}}:{{loadBalancerName}}:{{listenerProtocol}}:{{listenerPort}}/{{regionId}}",
       "method": "GET"
      }
     ]
    },
    {
     "title": "Number of dropped incoming packets per second for the listener",
     "type": "timeseries",
     "description": "bits/s",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_DropTrafficRX{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "fields": [
        { "jsonPath": "" }
       ],
       "legendFormat": "{{instanceId}}:{{loadBalancerName}}:{{listenerProtocol}}:{{listenerPort}}/{{regionId}}",
       "method": "GET"
      }
     ]
    },
    {
     "title": "Number of dropped outgoing bits per second for the listener",
     "type": "timeseries",
     "description": "Count/s",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_ListenerPacketTX{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "fields": [
        { "jsonPath": "" }
       ],
       "legendFormat": "{{instanceId}}:{{loadBalancerName}}:{{listenerProtocol}}:{{listenerPort}}/{{regionId}}",
       "method": "GET"
      }
     ]
    },
    {
     "title": "Number of dropped incoming bits per second for the listener",
     "type": "timeseries",
     "description": "Count/s",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_ListenerPacketRX{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "fields": [
        { "jsonPath": "" }
       ],
       "legendFormat": "{{instanceId}}:{{loadBalancerName}}:{{listenerProtocol}}:{{listenerPort}}/{{regionId}}",
       "method": "GET"
      }
     ]
    },
    {
     "title": "Monitor outgoing packets per second",
     "type": "timeseries",
     "description": "bits/s",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_TrafficTXNew{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "fields": [
        { "jsonPath": "" }
       ],
       "legendFormat": "{{instanceId}}:{{loadBalancerName}}:{{listenerProtocol}}:{{listenerPort}}/{{regionId}}",
       "method": "GET"
      }
     ]
    },
    {
     "title": "Monitor incoming packets per second",
     "type": "timeseries",
     "description": "bits/s",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_TrafficRXNew{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "fields": [
        { "jsonPath": "" }
       ],
       "legendFormat": "{{instanceId}}:{{loadBalancerName}}:{{listenerProtocol}}:{{listenerPort}}/{{regionId}}",
       "method": "GET"
      }
     ]
    },
    {
     "title": "Monitor outgoing bits per second",
     "type": "timeseries",
     "description": "Count",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_ListenerHeathyServerCount{regionId=~\"$regionId\",instanceId=~\"$instanceId\",listenerProtocol=~\"$listenerProtocol\",listenerPort=~\"$listenerPort\"}",
       "fields": [
        { "jsonPath": "" }
       ],
       "legendFormat": "{{instanceId}}:{{loadBalancerName}}:{{listenerProtocol}}:{{listenerPort}}/{{regionId}}",
       "method": "GET"
      }
     ]
    }
   ]
  },
  {
   "title": "Vip discarded connections per second",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Monitor number of healthy ECS instances in health check backend",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_VipTrafficTX{id=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{loadBalancerName}}/{{instanceId}}/{{vip}}"
      }
     ]
    },
    {
     "title": "Monitor",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_VipDropTrafficTX{id=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{loadBalancerName}}/{{instanceId}}/{{vip}}"
      }
     ]
    },
    {
     "title": "Vip outgoing bits per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_VipDropPacketTX{id=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{loadBalancerName}}/{{instanceId}}/{{vip}}"
      }
     ]
    },
    {
     "title": "Vip discarded outgoing bits per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_VipTrafficRX{id=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{loadBalancerName}}/{{instanceId}}/{{vip}}"
      }
     ]
    },
    {
     "title": "Vip discarded outgoing packets per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_VipDropTrafficRX{id=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{loadBalancerName}}/{{instanceId}}/{{vip}}"
      }
     ]
    },
    {
     "title": "Vip incoming bits per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 57 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_VipDropPacketRX{id=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{loadBalancerName}}/{{instanceId}}/{{vip}}"
      }
     ]
    },
    {
     "title": "Vip discarded ingoing bits per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 66 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_VipActiveConnection{id=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{loadBalancerName}}/{{instanceId}}/{{vip}}"
      }
     ]
    },
    {
     "title": "Vip discarded incoming packets per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 66 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_VipPacketTX{id=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{loadBalancerName}}/{{instanceId}}/{{vip}}"
      }
     ]
    },
    {
     "title": "Vip active connections per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 66 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_VipMaxConnection{id=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{loadBalancerName}}/{{instanceId}}/{{vip}}"
      }
     ]
    },
    {
     "title": "Vip outgoing packets per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 75 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_VipInactiveConnection{id=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{loadBalancerName}}/{{instanceId}}/{{vip}}"
      }
     ]
    },
    {
     "title": "Vip maximum concurrent connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 75 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_VipPacketRX{id=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{loadBalancerName}}/{{instanceId}}/{{vip}}"
      }
     ]
    },
    {
     "title": "Vip inactive connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 75 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_VipDropConnection{id=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{loadBalancerName}}/{{instanceId}}/{{vip}}"
      }
     ]
    },
    {
     "title": "Vip incoming packets per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 84 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "expr": "AliyunNlb_VipNewConnection{id=~\"$instanceId\",vip=~\"$vip\"}",
       "legendFormat": "{{loadBalancerName}}/{{instanceId}}/{{vip}}"
      }
     ]
    }
   ]
  }
 ]
}